"""Expanded aesthetic atlas: earlydigital.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-four-color-research-monitor-1983",
    name="Four Color Research Monitor",
    family="digital",
    era="1983",
    tagline="Cyan-magenta blocks, hard edges",
    desc="Cyan-magenta blocks, hard edges: a four-color computer-video interpretation.",
    tags=('digital', 'atlas', 'archival', 'computer', 'pixel', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'computer',
     'pixel',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('pixel_era', {'res_h': 200, 'palette': 'cga_cyan', 'dither': 'bayer2', 'contrast_snap': 0.4}),
     ('crt', {'scan_strength': 0.1, 'bloom': 0.03})],
    audio=[('a_bitcrush', {'bits': 8, 'sr_hz': 11025, 'antialias': True}),
     ('a_speaker', {'device': 'pc_speaker_1992', 'strength': 0.35})],
))

register_preset(Preset(
    id="atlas-sixteen-color-demo-capture-1987",
    name="Sixteen Color Demo Capture",
    family="digital",
    era="1987",
    tagline="Limited primaries, ordered dither",
    desc="Limited primaries, ordered dither: a sixteen-color demo-screen impression.",
    tags=('digital', 'atlas', 'archival', 'computer', 'demo', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'computer',
     'demo',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('pixel_era', {'res_h': 240, 'palette': 'ega16', 'dither': 'bayer4', 'contrast_snap': 0.25})],
    audio=[('a_bitcrush', {'bits': 10, 'sr_hz': 16000, 'antialias': True})],
))

register_preset(Preset(
    id="atlas-desktop-video-digitizer-1990",
    name="Desktop Video Digitizer",
    family="digital",
    era="1990",
    tagline="Soft capture, coarse levels",
    desc="Soft capture, coarse levels: an early desktop video digitizer interpretation.",
    tags=('digital', 'atlas', 'archival', 'computer', 'capture', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'computer',
     'capture',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('pixel_era', {'res_h': 240, 'palette': 'vga256', 'dither': 'bayer2'}),
     ('chroma_dv', {'ratio': '4:1:0', 'edge_sharpen': 0.2})],
    audio=[('a_bitcrush', {'bits': 8, 'sr_hz': 22050, 'dither': True, 'antialias': True})],
))

register_preset(Preset(
    id="atlas-multimedia-encyclopedia-window-1993",
    name="Multimedia Encyclopedia Window",
    family="digital",
    era="1993",
    tagline="Small frame, soft blocks",
    desc="Small frame, soft blocks: a CD-ROM encyclopedia movie-window encode.",
    tags=('digital', 'atlas', 'archival', 'cdrom', 'educational', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'cdrom',
     'educational',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('codec_era', {'codec': 'msmpeg4', 'kbps': 450, 'res': '240p', 'gop': 12})],
    audio=[('a_bitcrush', {'bits': 8, 'sr_hz': 11025, 'antialias': True}), ('a_mono', {'amount': 1})],
))

register_preset(Preset(
    id="atlas-museum-kiosk-mjpeg-1995",
    name="Museum Kiosk MJPEG",
    family="digital",
    era="1995",
    tagline="Fine JPEG texture, clear edges",
    desc="Fine JPEG texture, clear edges: a looping multimedia-kiosk movie encode.",
    tags=('digital', 'atlas', 'archival', 'kiosk', 'documentary', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'kiosk',
     'documentary',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.13}),
     ('codec_era', {'codec': 'mjpeg', 'kbps': 3500, 'res': '480p', 'qscale': 7})],
    audio=[('a_bandlimit', {'low_hz': 70, 'high_hz': 14000}),
     ('a_speaker', {'device': 'pc_speaker_1992', 'strength': 0.3})],
))

register_preset(Preset(
    id="atlas-camcorder-dv-first-generation-1997",
    name="Camcorder DV First Generation",
    family="digital",
    era="1997",
    tagline="Crisp luma, broad chroma steps",
    desc="Crisp luma, broad chroma steps: a clean first-generation digital camcorder treatment.",
    tags=('digital', 'atlas', 'archival', 'minidv', 'home-video', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'minidv',
     'home-video',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('chroma_dv', {'ratio': '4:1:1', 'edge_sharpen': 0.5}),
     ('tone', {'contrast': 1.08, 'knee': 0.81}),
     ('codec_era', {'codec': 'mjpeg', 'kbps': 7500, 'res': 'native', 'qscale': 3})],
    audio=[('a_historical_mic', {'profile': 'camcorder_1994', 'amount': 0.45, 'self_noise_db': -69})],
))

register_preset(Preset(
    id="atlas-pocket-multimedia-transcode-2000",
    name="Pocket Multimedia Transcode",
    family="digital",
    era="2000",
    tagline="Soft video, compact sound",
    desc="Soft video, compact sound: a small-screen MPEG-4 transfer.",
    tags=('digital', 'atlas', 'archival', 'handheld', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'handheld',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('codec_era', {'codec': 'mpeg4', 'kbps': 620, 'res': '240p', 'gop': 24}),
     ('lcd_screen', {'grid': 0.07, 'response_smear': 0.09, 'backlight_bleed': 0.03})],
    audio=[('a_codec_mp3', {'kbps': '48', 'mono': False})],
))

register_preset(Preset(
    id="atlas-field-laptop-review-proxy-2003",
    name="Field Laptop Review Proxy",
    family="digital",
    era="2003",
    tagline="Muted color, practical compression",
    desc="Muted color, practical compression: a lightweight field-review movie proxy.",
    tags=('digital', 'atlas', 'archival', 'documentary', 'proxy', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'documentary',
     'proxy',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 0.87}),
     ('codec_era', {'codec': 'mpeg4', 'kbps': 1200, 'res': '360p', 'gop': 15})],
    audio=[('a_codec_mp3', {'kbps': '96', 'mono': False})],
))

register_preset(Preset(
    id="atlas-early-digital-cinema-dailies-2006",
    name="Early Digital Cinema Dailies",
    family="digital",
    era="2006",
    tagline="Neutral mids, clean detail",
    desc="Neutral mids, clean detail: an early digital-cinema dailies interpretation.",
    tags=('digital', 'atlas', 'archival', 'cinema', 'dailies', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'cinema',
     'dailies',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.04, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.02, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.94, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.4}),
     ('codec_era', {'codec': 'h264', 'kbps': 8000, 'res': 'native', 'crf': 19})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.1, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-pocket-raw-indie-grade-2014",
    name="Pocket Raw Indie Grade",
    family="digital",
    era="2014",
    tagline="Open shadows, gentle color density",
    desc="Open shadows, gentle color density: a small digital-cinema camera finishing impression.",
    tags=('digital', 'atlas', 'archival', 'independent', 'cinema', 'digital-cinema'),
    keywords=('digital',
     'archival',
     'independent',
     'cinema',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.07, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.05, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.91, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.3, 'highlight_desat': 0.65}),
     ('grain', {'amount': 0.075, 'size': 0.9, 'chroma_grain': 0.015})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.25, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.96, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
