"""Expanded aesthetic atlas: color.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-additive-screen-travel-color-1932",
    name="Additive Screen Travel Color",
    family="film",
    era="1932",
    tagline="Muted primaries, screen texture",
    desc="Muted primaries, screen texture: an additive-color travel-film impression.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'technicolor2', 'strength': 0.65}),
     ('tone', {'contrast': 1.06, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.12}),
     ('saturation', {'amount': 0.68}),
     ('grain', {'amount': 0.31, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('grain', {'amount': 0.13, 'size': 0.9, 'chroma_grain': 0.04})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-dye-matrix-botanical-reel-1937",
    name="Dye Matrix Botanical Reel",
    family="film",
    era="1937",
    tagline="Dense green, crimson separation",
    desc="Dense green, crimson separation: botanical dye-transfer color with a clean print surface.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'technicolor3', 'strength': 0.65}),
     ('tone', {'contrast': 1.22, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.06}),
     ('saturation', {'amount': 1.27}),
     ('grain', {'amount': 0.17, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.65})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-daylight-reversal-survey-1948",
    name="Daylight Reversal Survey",
    family="film",
    era="1948",
    tagline="Brilliant whites, crisp red",
    desc="Brilliant whites, crisp red: a daylight reversal documentary master.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.18, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.1}),
     ('saturation', {'amount': 1.18}),
     ('grain', {'amount': 0.22, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('print_char', {'acutance': 0.36})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-warm-negative-answer-print-1957",
    name="Warm Negative Answer Print",
    family="film",
    era="1957",
    tagline="Warm skin, cyan shadows",
    desc="Warm skin, cyan shadows: an early color-negative studio answer print.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.07, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.22}),
     ('saturation', {'amount': 0.94}),
     ('grain', {'amount': 0.27, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'teal', 'shadow_amt': 0.33})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-cool-reversal-laboratory-1962",
    name="Cool Reversal Laboratory",
    family="film",
    era="1962",
    tagline="Cool whites, blue-green density",
    desc="Cool whites, blue-green density: a reversal record under laboratory lighting.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.25, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.24}),
     ('saturation', {'amount': 0.9}),
     ('grain', {'amount': 0.29, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.3})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-mauve-safety-dupe-1969",
    name="Mauve Safety Dupe",
    family="film",
    era="1969",
    tagline="Mauve dye drift, milky blacks",
    desc="Mauve dye drift, milky blacks: a gently aged color duplicate.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.08, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.02}),
     ('saturation', {'amount': 0.78}),
     ('grain', {'amount': 0.39, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('fade', {'profile': 'eastman_pink', 'amount': 0.22})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-olive-release-positive-1976",
    name="Olive Release Positive",
    family="film",
    era="1976",
    tagline="Olive neutrals, hard red",
    desc="Olive neutrals, hard red: a dense release positive with slight green bias.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'orwo_east', 'strength': 0.65}),
     ('tone', {'contrast': 1.27, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.05}),
     ('saturation', {'amount': 0.86}),
     ('grain', {'amount': 0.32, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'tint': -0.19})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-cool-eighties-interpositive-1984",
    name="Cool Eighties Interpositive",
    family="film",
    era="1984",
    tagline="Cool shadow detail, tight grain",
    desc="Cool shadow detail, tight grain: an interpositive generation before the release-print contrast.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodak_80s', 'strength': 0.65}),
     ('tone', {'contrast': 0.96, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.1}),
     ('saturation', {'amount': 0.88}),
     ('grain',
      {'amount': 0.2,
       'size': 1.2,
       'chroma_grain': 0.08,
       'layers': 'print_from_neg',
       'stock': 'print_dupe'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optical_composite', {'softness': 0.15, 'layer_haze': 0.06})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-night-negative-silver-retain-1998",
    name="Night Negative Silver Retain",
    family="film",
    era="1998",
    tagline="Silver blacks, quiet color",
    desc="Silver blacks, quiet color: a partial bleach-bypass night-negative interpretation.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.12, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.12}),
     ('saturation', {'amount': 0.9}),
     ('grain',
      {'amount': 0.24,
       'size': 1.45,
       'chroma_grain': 0.08,
       'layers': 'color_neg',
       'stock': 'push_process'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.62, 'density': 0.25})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-modern-reversal-gallery-scan-2025",
    name="Modern Reversal Gallery Scan",
    family="film",
    era="2025",
    tagline="Vivid dyes, fine texture",
    desc="Vivid dyes, fine texture: a clean contemporary gallery scan of reversal film.",
    tags=('film', 'atlas', 'color', 'documentary', 'travel', 'print', 'process'),
    keywords=('color',
     'film',
     'documentary',
     'travel',
     'print',
     'process',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.1, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.04}),
     ('saturation', {'amount': 1.12}),
     ('grain', {'amount': 0.12, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'highlight_desat': 0.55, 'local_contrast': 0.21})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.82, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))
