"""Expanded aesthetic atlas: silver.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-soundstage-ribbon-silver-1930",
    name="Soundstage Ribbon Silver",
    family="film",
    era="1930",
    tagline="Dense silver, ribbon warmth",
    desc="Dense silver, ribbon warmth: early studio sound photographed through soft incandescent light.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.12, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.3, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.24, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'diffusion': 0.2})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 4200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 4200,
       'cell_noise': -51,
       'flutter': 0.28,
       'academy_rolloff': 'newsreel_1930s',
       'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-tabloid-flashbulb-print-1933",
    name="Tabloid Flashbulb Print",
    family="film",
    era="1933",
    tagline="Chalk whites, inky contours",
    desc="Chalk whites, inky contours: hard news-photography contrast on a release print.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.6, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.37, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.05, 'tint': 'neutral', 'threshold': 0.78}),
     ('print_char', {'acutance': 0.55})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500,
       'cell_noise': -53,
       'flutter': 0.16,
       'academy_rolloff': 'newsreel_1930s',
       'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-backlot-rain-duplicate-1935",
    name="Backlot Rain Duplicate",
    family="film",
    era="1935",
    tagline="Wet highlights, coarse silver",
    desc="Wet highlights, coarse silver: a high-contrast studio-rain print with neutral lamp glow.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.38, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.46, 'size': 1.5, 'chroma_grain': 0, 'stock': 'print_dupe'}),
     ('halation', {'strength': 0.3, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'veiling_flare': 0.09})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6400}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6400,
       'cell_noise': -55,
       'flutter': 0.18,
       'academy_rolloff': 'feature_1940s',
       'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-housing-survey-16-1936",
    name="Housing Survey 16",
    family="film",
    era="1936",
    tagline="Open gray, clear speech",
    desc="Open gray, clear speech: a modest monochrome municipal documentary record.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.98, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.36, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.08, 'tint': 'neutral', 'threshold': 0.78}),
     ('sharpen', {'amount': 0.14})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 4800}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 4800,
       'cell_noise': -52,
       'flutter': 0.22,
       'academy_rolloff': 'classroom_16mm',
       'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-carbon-arc-costume-print-1938",
    name="Carbon Arc Costume Print",
    family="film",
    era="1938",
    tagline="Radiant whites, soft faces",
    desc="Radiant whites, soft faces: costume-drama silver with restrained edge glow.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.21, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.22, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.4, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'soft_focus': 0.13})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6800}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6800,
       'cell_noise': -56,
       'flutter': 0.1,
       'academy_rolloff': 'feature_1940s',
       'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-factory-shift-safety-reel-1941",
    name="Factory Shift Safety Reel",
    family="film",
    era="1941",
    tagline="Steel grays, dry grain",
    desc="Steel grays, dry grain: an industrial optical-sound training print.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.28, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.43, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.04, 'tint': 'neutral', 'threshold': 0.78}),
     ('print_char', {'contrast_buildup': 1, 'acutance': 0.18})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 4400}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 4400,
       'cell_noise': -49,
       'flutter': 0.3,
       'academy_rolloff': 'classroom_16mm',
       'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-pool-camera-press-negative-1946",
    name="Pool Camera Press Negative",
    family="film",
    era="1946",
    tagline="Fine grain, clipped flash edges",
    desc="Fine grain, clipped flash edges: a press-pool negative with direct mono sound.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.16, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.18, 'size': 1.2, 'chroma_grain': 0, 'stock': 'newsreel_35'}),
     ('halation', {'strength': 0.12, 'tint': 'neutral', 'threshold': 0.78}),
     ('cinema_finish', {'local_contrast': 0.32})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7400}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7400, 'cell_noise': -60, 'flutter': 0.06, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-silver-fog-chamber-film-1949",
    name="Silver Fog Chamber Film",
    family="film",
    era="1949",
    tagline="Pale mids, blooming lamps",
    desc="Pale mids, blooming lamps: a low-contrast chamber-drama positive.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.86, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.25, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.38, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'diffusion': 0.32})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7200, 'cell_noise': -59, 'flutter': 0.12, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-television-silver-reduction-1951",
    name="Television Silver Reduction",
    family="film",
    era="1951",
    tagline="Soft contours, duplicate grain",
    desc="Soft contours, duplicate grain: a monochrome feature reduced for television exhibition.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.31, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.5, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.11, 'tint': 'neutral', 'threshold': 0.78}),
     ('sharpen', {'amount': -0.35}),
     ('print_char', {'contrast_buildup': 1})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5200, 'cell_noise': -51, 'flutter': 0.26, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-fine-grain-academy-master-1954",
    name="Fine Grain Academy Master",
    family="film",
    era="1954",
    tagline="Deep silver, stable detail",
    desc="Deep silver, stable detail: a well-kept fine-grain theatrical master.",
    tags=('film', 'atlas', 'bw', 'studio', 'drama', 'documentary', '35mm', 'optical'),
    keywords=('bw',
     'studio',
     'drama',
     'documentary',
     '35mm',
     'optical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.23, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.13, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.06, 'tint': 'neutral', 'threshold': 0.78}),
     ('cinema_finish', {'local_contrast': 0.2, 'highlight_desat': 0.8}),
     ('print_char', {'acutance': 0.3})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 8500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 8500, 'cell_noise': -67, 'flutter': 0.04, 'academy_rolloff': 'none', 'drive': 1.12})],
))
