"""Expanded aesthetic atlas: early.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-paper-positive-reconstruction-1894",
    name="Paper Positive Reconstruction",
    family="film",
    era="1894",
    tagline="Paper fibers, ivory whites",
    desc="Paper fibers, ivory whites: a moving photographic record rebuilt with subdued silver and soft print edges.",
    tags=('film', 'atlas', 'actuality', 'paper', 'archive', 'documentary', 'silent'),
    keywords=('actuality',
     'paper',
     'archive',
     'documentary',
     'silent',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'blue_sensitive', 'tint': 'sepia', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.28, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.31, 'size': 1.6, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.02, 'tint': 'neutral', 'threshold': 0.78}),
     ('paper_texture', {'amount': 0.035}),
     ('sharpen', {'amount': -0.25})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 0,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -78}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-peep-show-contact-print-1895",
    name="Peep Show Contact Print",
    family="film",
    era="1895",
    tagline="Dense silver, intimate falloff",
    desc="Dense silver, intimate falloff: a contact-print impression with bright centers and dark edge illumination.",
    tags=('film', 'atlas', 'silent', 'actuality', 'documentary', 'kinetoscope'),
    keywords=('silent',
     'actuality',
     'documentary',
     'kinetoscope',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'nitrate_warm', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.42, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.3, 'size': 1.05, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.04, 'tint': 'neutral', 'threshold': 0.78}),
     ('vignette', {'amount': 0.5, 'radius': 0.65}),
     ('flicker', {'amount': 0.08})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 0,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -78}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-glass-lantern-dissolve-study-1898",
    name="Glass Lantern Dissolve Study",
    family="film",
    era="1898",
    tagline="Blue silver, frosted glass",
    desc="Blue silver, frosted glass: a lantern-slide impression applied continuously to the supplied moving picture.",
    tags=('film', 'atlas', 'experimental', 'lantern', 'documentary', 'silent'),
    keywords=('experimental',
     'lantern',
     'documentary',
     'silent',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'blue_sensitive', 'tint': 'cyanotype', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.08, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.15, 'size': 1, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.19, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'diffusion': 0.22}),
     ('screen', {'surface': 'glass_beaded', 'hotspot': 0.16, 'room_spill': 0.04, 'shake_event': 0})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 0,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -78}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-fairground-hand-crank-1901",
    name="Fairground Hand Crank",
    family="film",
    era="1901",
    tagline="Uneven density, warm silver",
    desc="Uneven density, warm silver: restrained hand-cranked exposure breathing across a coarse traveling print.",
    tags=('film', 'atlas', 'silent', 'fairground', 'actuality', 'documentary'),
    keywords=('silent',
     'fairground',
     'actuality',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'nitrate_warm', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.18, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.46, 'size': 1.6, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.12, 'tint': 'neutral', 'threshold': 0.78}),
     ('flicker', {'character': 'hand_cranked', 'amount': 0.3}),
     ('gate_weave', {'amount': 0.45, 'rotation': 0.02, 'splice_bump': 0})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -61}),
     ('a_channel_aging',
      {'width': 0.1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-expedition-glass-negative-1903",
    name="Expedition Glass Negative",
    family="film",
    era="1903",
    tagline="Cool whites, open shadows",
    desc="Cool whites, open shadows: blue-sensitive documentary silver with gentle lens haze and no invented title cards.",
    tags=('film', 'atlas', 'expedition', 'documentary', 'travel', 'archive'),
    keywords=('expedition',
     'documentary',
     'travel',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'blue_sensitive', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.95, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.32, 'size': 1.35, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.2, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'veiling_flare': 0.16})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 0,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -76}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-trick-film-magenta-bath-1906",
    name="Trick Film Magenta Bath",
    family="film",
    era="1906",
    tagline="Rose tint, dense highlights",
    desc="Rose tint, dense highlights: a theatrical color-bath impression over early monochrome emulsion.",
    tags=('film', 'atlas', 'silent', 'fantasy', 'experimental', 'trick-film'),
    keywords=('silent',
     'fantasy',
     'experimental',
     'trick-film',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'neutral', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.31, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.24, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.16, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'tint': 0.38, 'shadow_tint': 'magenta', 'shadow_amt': 0.65}),
     ('print_char', {'acutance': 0.3})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5000}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5000, 'cell_noise': -60, 'flutter': 0.12, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-railway-survey-positive-1909",
    name="Railway Survey Positive",
    family="film",
    era="1909",
    tagline="Hard edges, graphite blacks",
    desc="Hard edges, graphite blacks: fine monochrome duplication with a restrained mechanical weave.",
    tags=('film', 'atlas', 'railway', 'industrial', 'documentary', 'archive'),
    keywords=('railway',
     'industrial',
     'documentary',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'neutral', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.35, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.21, 'size': 1.1, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.03, 'tint': 'neutral', 'threshold': 0.78}),
     ('print_char', {'acutance': 0.5, 'contrast_buildup': 1}),
     ('gate_weave', {'amount': 0.22, 'rotation': 0.01, 'splice_bump': 0})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 0,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -78}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-polar-field-reel-1911",
    name="Polar Field Reel",
    family="film",
    era="1911",
    tagline="Cold silver, milk-glass haze",
    desc="Cold silver, milk-glass haze: a pale blue-sensitive field record that keeps snow highlights open.",
    tags=('film', 'atlas', 'polar', 'expedition', 'documentary', 'silent'),
    keywords=('polar',
     'expedition',
     'documentary',
     'silent',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'blue_sensitive', 'tint': 'cyanotype', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.9, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.39, 'size': 1.5, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.27, 'tint': 'neutral', 'threshold': 0.78}),
     ('tone', {'gamma': 1.1, 'knee': 0.75}),
     ('optics', {'corner_softness': 0.25})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 0.3, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-amber-storefront-reel-1913",
    name="Amber Storefront Reel",
    family="film",
    era="1913",
    tagline="Amber whites, velvety black",
    desc="Amber whites, velvety black: a warm tinted small-theater print with soft central illumination.",
    tags=('film', 'atlas', 'silent', 'melodrama', 'storefront', 'archive'),
    keywords=('silent',
     'melodrama',
     'storefront',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'nitrate_warm', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.21, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.28, 'size': 1.4, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.22, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'warmth': 0.2}),
     ('vignette', {'amount': 0.28, 'hot_center': 0.12})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 4500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 4500, 'cell_noise': -63, 'flutter': 0.2, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-museum-separation-master-1920",
    name="Museum Separation Master",
    family="film",
    era="1920",
    tagline="Neutral silver, fine detail",
    desc="Neutral silver, fine detail: a calm preservation-master interpretation of an early monochrome source.",
    tags=('film', 'atlas', 'restored', 'documentary', 'silent', 'preservation'),
    keywords=('restored',
     'documentary',
     'silent',
     'preservation',
     'carrier',
     'transfer',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'neutral', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.06, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.16, 'size': 0.9, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.02, 'tint': 'neutral', 'threshold': 0.78}),
     ('telecine_scan', {'pin_stability': 'pin_registered', 'hop_px': 0.2, 'scanner_stripe': 0})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.1, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
