"""Expanded aesthetic atlas: cinema2026.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-large-format-daylight-epic-2026",
    name="Large Format Daylight Epic",
    family="modern",
    era="2026",
    tagline="Fine texture, deep color",
    desc="Fine texture, deep color: expansive daylight finishing with neutral highlight color.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'epic',
     'adventure',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'epic',
     'adventure',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.13, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.05, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.06, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.42, 'highlight_desat': 0.85, 'local_contrast': 0.24}),
     ('optics', {'corner_softness': 0.12, 'chromatic_aberration': 0.12}),
     ('grain', {'amount': 0.055, 'size': 0.85, 'chroma_grain': 0.015, 'layers': 'print_from_neg'})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.6, 'attack_ms': 35, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.18, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-desert-action-silver-finish-2026",
    name="Desert Action Silver Finish",
    family="modern",
    era="2026",
    tagline="Sand gold, silver black",
    desc="Sand gold, silver black: dense action finishing with strong neutral contrast.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'action',
     'desert',
     'blockbuster',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'action',
     'desert',
     'blockbuster',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.27, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.27, 'shadow_tint': 'teal', 'shadow_amt': 0.27}),
     ('saturation', {'amount': 0.82, 'vibrance': 0.08}),
     ('cinema_finish', {'silver': 0.58, 'density': 0.32, 'highlight_desat': 0.65}),
     ('sharpen', {'amount': 0.15})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.8, 'attack_ms': 18, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.12, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-rain-city-blue-hour-thriller-2026",
    name="Rain City Blue Hour Thriller",
    family="modern",
    era="2026",
    tagline="Blue shade, warm practicals",
    desc="Blue shade, warm practicals: a nocturnal thriller grade with fine shadow texture.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'crime',
     'thriller',
     'night',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'crime',
     'thriller',
     'night',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.19, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.16, 'shadow_tint': 'blue', 'shadow_amt': 0.7}),
     ('saturation', {'amount': 0.9, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.35, 'density': 0.12, 'local_contrast': 0.12}),
     ('halation', {'strength': 0.12, 'tint': 'warm_white'}),
     ('grain', {'amount': 0.08, 'size': 0.9, 'chroma_grain': 0.025})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.2, 'attack_ms': 22, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.08, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-orbital-clean-science-fiction-2026",
    name="Orbital Clean Science Fiction",
    family="modern",
    era="2026",
    tagline="Steel neutral, clean whites",
    desc="Steel neutral, clean whites: a precise science-fiction finish with cool deep shadows.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'scifi',
     'space',
     'blockbuster',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'scifi',
     'space',
     'blockbuster',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.16, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.1, 'shadow_tint': 'teal', 'shadow_amt': 0.5}),
     ('saturation', {'amount': 0.76, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 1, 'local_contrast': 0.42, 'density': 0.2})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.8, 'attack_ms': 32, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.22, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-summer-tentpole-color-2026",
    name="Summer Tentpole Color",
    family="modern",
    era="2026",
    tagline="Bright primaries, clear skin",
    desc="Bright primaries, clear skin: a buoyant contemporary adventure finish with rich color density.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'adventure',
     'family',
     'blockbuster',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'adventure',
     'family',
     'blockbuster',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.08, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.1, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.23, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.6, 'highlight_desat': 0.65, 'local_contrast': 0.18}),
     ('optics', {'diffusion': 0.05})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2, 'attack_ms': 26, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.12, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-candlelit-historical-drama-2026",
    name="Candlelit Historical Drama",
    family="modern",
    era="2026",
    tagline="Amber light, pearl skin",
    desc="Amber light, pearl skin: a modern period-drama finish with soft diffusion.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'period',
     'drama',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'period',
     'drama',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.05, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.3, 'shadow_tint': 'brown', 'shadow_amt': 0.35}),
     ('saturation', {'amount': 0.89, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.8, 'local_contrast': -0.2}),
     ('optics', {'diffusion': 0.24}),
     ('grain', {'amount': 0.12, 'size': 1.1, 'chroma_grain': 0.02})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.4, 'attack_ms': 35, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.98, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-prestige-horror-mineral-green-2026",
    name="Prestige Horror Mineral Green",
    family="modern",
    era="2026",
    tagline="Mineral green, dense shadow",
    desc="Mineral green, dense shadow: restrained horror color with dry fine-grain texture.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'horror',
     'suspense',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'horror',
     'suspense',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.3, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.04, 'shadow_tint': 'green', 'shadow_amt': 0.72}),
     ('saturation', {'amount': 0.58, 'vibrance': 0.08}),
     ('cinema_finish', {'silver': 0.25, 'density': 0.3, 'highlight_desat': 0.8}),
     ('grain', {'amount': 0.14, 'size': 1.3, 'chroma_grain': 0.01})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.6, 'attack_ms': 42, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.95, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-romantic-comedy-pearl-finish-2026",
    name="Romantic Comedy Pearl Finish",
    family="modern",
    era="2026",
    tagline="Cream whites, rosy mids",
    desc="Cream whites, rosy mids: luminous romantic-comedy color with soft highlight separation.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'romance',
     'comedy',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'romance',
     'comedy',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 0.96, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.12, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.03, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.7, 'local_contrast': -0.3, 'density': 0.18}),
     ('balance', {'high_tint': 'pink', 'high_amt': 0.2}),
     ('optics', {'soft_focus': 0.065})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.8, 'attack_ms': 20, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.03, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-concert-feature-chrome-night-2026",
    name="Concert Feature Chrome Night",
    family="modern",
    era="2026",
    tagline="Electric color, silver glints",
    desc="Electric color, silver glints: concert-film finishing with dense blue-magenta separation.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'concert',
     'music-video',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'concert',
     'music-video',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.24, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.06, 'shadow_tint': 'magenta', 'shadow_amt': 0.58}),
     ('saturation', {'amount': 1.17, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.52, 'highlight_desat': 0.35, 'local_contrast': 0.3}),
     ('halation', {'strength': 0.18, 'tint': 'neutral', 'edge_only': 0.65})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.4, 'attack_ms': 28, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.25, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-contemporary-documentary-neutral-2026",
    name="Contemporary Documentary Neutral",
    family="modern",
    era="2026",
    tagline="Neutral skin, open detail",
    desc="Neutral skin, open detail: restrained observational finishing with gentle audio dynamics.",
    tags=('modern',
     'atlas',
     '2026',
     'contemporary',
     'digital',
     'cinema',
     'documentary',
     'nonfiction',
     'digital-cinema'),
    keywords=('2026',
     'contemporary',
     'digital',
     'cinema',
     'documentary',
     'nonfiction',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.02, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.015, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.98, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.5, 'local_contrast': 0.12}),
     ('sharpen', {'amount': 0.055})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.25, 'attack_ms': 40, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-hollywood-blockbuster-2026",
    name="Hollywood Blockbuster",
    family="modern",
    era="2026",
    tagline="Rich color, polished highlights",
    desc="Rich color, polished highlights: a contemporary tentpole finish with warm faces, cool shadow separation and controlled stereo dynamics.",
    tags=('modern',
     'atlas',
     '2026',
     'hollywood',
     'blockbuster',
     'action',
     'adventure',
     'digital',
     'cinema',
     'tentpole',
     'digital-cinema'),
    keywords=('2026',
     'hollywood',
     'blockbuster',
     'action',
     'adventure',
     'digital',
     'cinema',
     'tentpole',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.18, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.09, 'shadow_tint': 'teal', 'shadow_amt': 0.42}),
     ('saturation', {'amount': 1.12, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.38, 'highlight_desat': 0.78, 'local_contrast': 0.2}),
     ('optics', {'diffusion': 0.08, 'chromatic_aberration': 0.16}),
     ('grain', {'amount': 0.065, 'size': 0.85, 'chroma_grain': 0.025}),
     ('halation', {'strength': 0.09, 'threshold': 0.84, 'tint': 'warm_white'})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.1, 'attack_ms': 30, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.16, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
