"""Expanded aesthetic atlas: opticallab.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-soft-matte-composite-print-1940",
    name="Soft Matte Composite Print",
    family="film",
    era="1940",
    tagline="Soft matte edges, silver glow",
    desc="Soft matte edges, silver glow: a restrained optical-composite generation.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.19, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.24, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.18, 'tint': 'neutral', 'threshold': 0.78}),
     ('optical_composite', {'softness': 0.26, 'matte_line': 0.21, 'registration': 0.3})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5800}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5800, 'cell_noise': -56, 'flutter': 0.18, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-color-separation-misregister-1955",
    name="Color Separation Misregister",
    family="film",
    era="1955",
    tagline="Fine colored contours, dense dye",
    desc="Fine colored contours, dense dye: a slightly misregistered separation-print impression.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'technicolor3', 'strength': 0.65}),
     ('tone', {'contrast': 1.17, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.06}),
     ('saturation', {'amount': 1.15}),
     ('grain', {'amount': 0.2, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optical_composite', {'registration': 0.8, 'matte_line': 0.1})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7200, 'cell_noise': -59, 'flutter': 0.1, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-rephotographed-glass-screen-1961",
    name="Rephotographed Glass Screen",
    family="film",
    era="1961",
    tagline="Beaded highlights, soft detail",
    desc="Beaded highlights, soft detail: a projected color print photographed from a glass screen.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.1, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.12}),
     ('saturation', {'amount': 0.96}),
     ('grain', {'amount': 0.24, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('screen', {'surface': 'glass_beaded', 'hotspot': 0.28, 'room_spill': 0.08, 'shake_event': 0}),
     ('optics', {'diffusion': 0.1})],
    audio=[('a_room', {'mix': 0.18, 'decay_s': 0.8}), ('a_bandlimit', {'low_hz': 100, 'high_hz': 10000})],
))

register_preset(Preset(
    id="atlas-optical-zoom-generation-1967",
    name="Optical Zoom Generation",
    family="film",
    era="1967",
    tagline="Enlarged grain, printer haze",
    desc="Enlarged grain, printer haze: an optically enlarged intermediate with softened edge detail.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.19, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.04}),
     ('saturation', {'amount': 0.83}),
     ('grain', {'amount': 0.43, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optical_composite', {'softness': 0.4, 'layer_haze': 0.16, 'density_breath': 0.05})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -61}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-bleach-laboratory-workprint-1972",
    name="Bleach Laboratory Workprint",
    family="film",
    era="1972",
    tagline="Heavy silver, muted dyes",
    desc="Heavy silver, muted dyes: a dense bleach-bypass workprint interpretation.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.12, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.02}),
     ('saturation', {'amount': 0.78}),
     ('grain', {'amount': 0.37, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.8, 'density': 0.3})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -59}),
     ('a_channel_aging',
      {'width': 0.6, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-cinema-wall-preview-1978",
    name="Cinema Wall Preview",
    family="film",
    era="1978",
    tagline="Warm wall, dimmed whites",
    desc="Warm wall, dimmed whites: an intimate projected print on a painted room wall.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodak_80s', 'strength': 0.65}),
     ('tone', {'contrast': 1.05, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.13}),
     ('saturation', {'amount': 0.94}),
     ('grain', {'amount': 0.26, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('screen', {'surface': 'wall_paint', 'hotspot': 0.12, 'room_spill': 0.21, 'shake_event': 0})],
    audio=[('a_room', {'size': 1.4, 'decay_s': 0.65, 'mix': 0.2})],
))

register_preset(Preset(
    id="atlas-printer-haze-festival-dupe-1986",
    name="Printer Haze Festival Dupe",
    family="film",
    era="1986",
    tagline="Pale blacks, soft color",
    desc="Pale blacks, soft color: a festival duplicate with optical haze and mild density breathing.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodak_80s', 'strength': 0.65}),
     ('tone', {'contrast': 1.04, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.03}),
     ('saturation', {'amount': 0.83}),
     ('grain', {'amount': 0.31, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optical_composite', {'layer_haze': 0.24, 'density_breath': 0.16, 'softness': 0.2})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-fine-grain-laser-filmout-2002",
    name="Fine Grain Laser Filmout",
    family="film",
    era="2002",
    tagline="Tight grain, firm dye contrast",
    desc="Tight grain, firm dye contrast: a digital-to-film theatrical print interpretation.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.16, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.04, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.02, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.38, 'highlight_desat': 0.62}),
     ('grain', {'amount': 0.17, 'size': 0.9, 'chroma_grain': 0.04}),
     ('print_char', {'acutance': 0.2})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.6, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.12, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-wet-gate-preservation-scan-2018",
    name="Wet Gate Preservation Scan",
    family="film",
    era="2018",
    tagline="Stable color, open shadows",
    desc="Stable color, open shadows: a clean archive-scan impression with restrained surface texture.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.01, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.01}),
     ('saturation', {'amount': 0.91}),
     ('grain', {'amount': 0.14, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('telecine_scan', {'pin_stability': 'pin_registered', 'hop_px': 0.2}),
     ('cinema_finish', {'local_contrast': 0.16})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-photochemical-gallery-filmout-2026",
    name="Photochemical Gallery Filmout",
    family="film",
    era="2026",
    tagline="Subtractive color, fine silver",
    desc="Subtractive color, fine silver: a contemporary filmout finish for gallery presentation.",
    tags=('film', 'atlas', 'experimental', 'cinema', 'optical', 'print', 'projection'),
    keywords=('experimental',
     'cinema',
     'film',
     'optical',
     'print',
     'projection',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.08, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.055, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.04, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.6, 'silver': 0.12, 'highlight_desat': 0.7}),
     ('grain', {'amount': 0.19, 'size': 1.05, 'chroma_grain': 0.065})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -71}),
     ('a_channel_aging',
      {'width': 1.05, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))
