"""Expanded aesthetic atlas: videoart.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-electronic-amber-sculpture-1970",
    name="Electronic Amber Sculpture",
    family="stylized",
    era="1970",
    tagline="Amber phosphor, luminous trails",
    desc="Amber phosphor, luminous trails: monochrome video shaped as an electronic sculpture.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'tint': 'amber_crt', 'tint_amt': 0.65}),
     ('phosphor_decay', {'mode': 'amber_mono', 'decay': 0.55}),
     ('crt', {'scan_strength': 0.16, 'bloom': 0.28})],
    audio=[('a_tube_amp', {'drive': 1.5, 'sag': 0.2}), ('a_room', {'mode': 'spring_amp', 'mix': 0.16})],
))

register_preset(Preset(
    id="atlas-studio-chroma-phase-painting-1973",
    name="Studio Chroma Phase Painting",
    family="stylized",
    era="1973",
    tagline="Rotated hue, soft scan texture",
    desc="Rotated hue, soft scan texture: an analog color-phase study.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('ntsc',
      {'system': 'ntsc',
       'luma_bw': 4.5,
       'chroma_bw': 0.8,
       'phase_error': 25,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('saturation', {'amount': 1.35}),
     ('crt', {'scan_strength': 0.1, 'bloom': 0.12})],
    audio=[('a_tape_sat', {'drive': 2.7, 'hf_loss': 0.28}), ('a_channel_aging', {'width': 1.3})],
))

register_preset(Preset(
    id="atlas-green-monitor-video-poem-1976",
    name="Green Monitor Video Poem",
    family="stylized",
    era="1976",
    tagline="Green afterglow, deep black",
    desc="Green afterglow, deep black: a phosphor video poem with long luminous memory.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'tint': 'phosphor_green', 'tint_amt': 0.8}),
     ('tone', {'contrast': 1.3}),
     ('phosphor_decay', {'mode': 'green_mono', 'decay': 0.7})],
    audio=[('a_bandlimit', {'low_hz': 130, 'high_hz': 6000}),
     ('a_room', {'mode': 'chamber', 'mix': 0.2, 'decay_s': 1.6})],
))

register_preset(Preset(
    id="atlas-magnetic-color-field-study-1979",
    name="Magnetic Color Field Study",
    family="stylized",
    era="1979",
    tagline="Soft chroma, wandering edges",
    desc="Soft chroma, wandering edges: a color-field video treatment with gentle time-base motion.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 1.45}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.18,
       'chroma_delay': 3.8,
       'luma_noise': 0.16,
       'chroma_noise': 0.112,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.32,
       'jitter_v': 0.015,
       'dropout_burst': 0}),
     ('phosphor_decay', {'decay': 0.3})],
    audio=[('a_analog_dub',
      {'format': 'cassette', 'generations': 3, 'alignment': 0.08, 'compression': 0.18, 'hiss_db': -52}),
     ('a_channel_aging',
      {'width': 1.2, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-scanline-performance-master-1982",
    name="Scanline Performance Master",
    family="stylized",
    era="1982",
    tagline="Hard white, delicate scan grid",
    desc="Hard white, delicate scan grid: a graphic monochrome performance-video finish.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {}),
     ('tone', {'contrast': 1.6, 'knee': 0.76}),
     ('crt', {'scan_strength': 0.27, 'phosphor_mask': 'grille', 'mask_strength': 0.12, 'bloom': 0.1})],
    audio=[('a_compressor', {'ratio': 4.5}), ('a_tape_sat', {'drive': 2.2})],
))

register_preset(Preset(
    id="atlas-cyan-red-signal-essay-1985",
    name="Cyan Red Signal Essay",
    family="stylized",
    era="1985",
    tagline="Cyan-red edges, bright mids",
    desc="Cyan-red edges, bright mids: a split-chroma signal treatment with dry tape sound.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('ntsc',
      {'system': 'ntsc',
       'luma_bw': 3.8,
       'chroma_bw': 0.5,
       'phase_error': -18,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('crt', {'misconvergence': 1.8, 'scan_strength': 0.07, 'bloom': 0.08})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -56}),
     ('a_channel_aging',
      {'width': 0.5, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-pastel-tube-installation-1988",
    name="Pastel Tube Installation",
    family="stylized",
    era="1988",
    tagline="Pastel video, soft afterglow",
    desc="Pastel video, soft afterglow: an open-toned installation loop with restrained tube texture.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 0.86, 'lift': 0.04}),
     ('saturation', {'amount': 0.69}),
     ('phosphor_decay', {'decay': 0.24}),
     ('crt', {'bloom': 0.26, 'glass_glow': 0.14})],
    audio=[('a_room', {'mode': 'plate1960', 'mix': 0.16, 'decay_s': 1.8}), ('a_tape_hiss', {'level_db': -65})],
))

register_preset(Preset(
    id="atlas-video-sculpture-pixel-veil-1992",
    name="Video Sculpture Pixel Veil",
    family="stylized",
    era="1992",
    tagline="Coarse grid, amber color",
    desc="Coarse grid, amber color: a hybrid low-resolution monitor treatment.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('pixel_era', {'res_h': 180, 'palette': 'none', 'dither': 'none'}),
     ('balance', {'warmth': 0.3}),
     ('crt', {'scan_strength': 0.15, 'curvature': 0.035, 'bloom': 0.18})],
    audio=[('a_bitcrush', {'bits': 12, 'sr_hz': 22050, 'mix': 0.5}), ('a_room', {'mix': 0.1})],
))

register_preset(Preset(
    id="atlas-purple-analog-gallery-loop-1996",
    name="Purple Analog Gallery Loop",
    family="stylized",
    era="1996",
    tagline="Violet shadow, broad color bleed",
    desc="Violet shadow, broad color bleed: a gallery-loop transfer in saturated tape color.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('balance', {'tint': 0.3, 'shadow_tint': 'magenta', 'shadow_amt': 0.5}),
     ('vhs',
      {'mode': 'lp',
       'luma_bw': 2.5,
       'chroma_bw': 0.3,
       'chroma_delay': 2.6,
       'luma_noise': 0.1,
       'chroma_noise': 0.07,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.16,
       'jitter_v': 0.015,
       'dropout_burst': 0}),
     ('saturation', {'amount': 1.2})],
    audio=[('a_analog_dub',
      {'format': 'cassette', 'generations': 2, 'alignment': 0.08, 'compression': 0.18, 'hiss_db': -59}),
     ('a_channel_aging',
      {'width': 1.15, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-contemporary-crt-installation-2026",
    name="Contemporary CRT Installation",
    family="stylized",
    era="2026",
    tagline="Clean color, fine phosphor",
    desc="Clean color, fine phosphor: a present-day gallery master displayed through subtle CRT texture.",
    tags=('stylized', 'atlas', 'experimental', 'video-art', 'gallery', 'video', 'television'),
    keywords=('experimental',
     'video-art',
     'gallery',
     'video',
     'television',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.06, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.05, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.35, 'density': 0.12, 'local_contrast': 0.12}),
     ('crt', {'phosphor_mask': 'dots', 'mask_strength': 0.13, 'scan_strength': 0.06, 'bloom': 0.1})],
    audio=[('a_room', {'mix': 0.12, 'decay_s': 1.3}),
     ('a_channel_aging', {'width': 1.15, 'imbalance_db': 0, 'skew_us': 0, 'phase_wander': 0})],
))
