"""Expanded aesthetic atlas: printanimation.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-graphite-animation-test-1934",
    name="Graphite Animation Test",
    family="cartoon",
    era="1934",
    tagline="Graphite lines, ivory paper",
    desc="Graphite lines, ivory paper: an animation-test surface over monochrome footage.",
    tags=('cartoon', 'atlas', 'animation', 'pencil'),
    keywords=('cartoon', 'animation', 'pencil', 'mixed-media', 'handmade', 'ink', 'paper', 'experimental'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {}),
     ('cel_flatten', {'smooth': 0.4, 'levels': 16, 'flatness': 0.35}),
     ('ink_line', {'weight': 0.25, 'xerox_grit': 0.15}),
     ('paper_texture', {'amount': 0.035})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5300}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5300, 'cell_noise': -60, 'flutter': 0.1, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-woodcut-motion-study-1943",
    name="Woodcut Motion Study",
    family="cartoon",
    era="1943",
    tagline="Black ink, rough edges",
    desc="Black ink, rough edges: a graphic moving woodcut interpretation.",
    tags=('cartoon', 'atlas', 'experimental', 'print'),
    keywords=('cartoon', 'experimental', 'print', 'mixed-media', 'handmade', 'ink', 'paper', 'animation'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {}),
     ('tone', {'contrast': 1.6}),
     ('halftone', {'process': 'newspaper_bw', 'lpi': 36, 'paper': 0.2, 'ink_tone': 1.3}),
     ('ink_line', {'weight': 0.65})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 4800}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 4800, 'cell_noise': -57, 'flutter': 0.16, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-screenprint-travel-poster-1956",
    name="Screenprint Travel Poster",
    family="cartoon",
    era="1956",
    tagline="Flat primaries, warm paper",
    desc="Flat primaries, warm paper: travel-poster color applied to a moving image.",
    tags=('cartoon', 'atlas', 'animation', 'travel', 'print'),
    keywords=('cartoon',
     'animation',
     'travel',
     'print',
     'mixed-media',
     'handmade',
     'ink',
     'paper',
     'experimental'),
    proc_height=None,
    upscale="auto",
    video=[('cel_flatten', {'levels': 8, 'smooth': 0.7, 'flatness': 0.8}),
     ('stock', {'profile': 'technicolor3', 'strength': 0.65}),
     ('halftone', {'process': 'magazine_fine', 'lpi': 95, 'paper': 0.23, 'misregister': 0.2})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.5, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-ink-wash-television-cel-1965",
    name="Ink Wash Television Cel",
    family="cartoon",
    era="1965",
    tagline="Soft gray wash, fine ink",
    desc="Soft gray wash, fine ink: a restrained cel-and-paper television surface.",
    tags=('cartoon', 'atlas', 'television'),
    keywords=('cartoon', 'television', 'mixed-media', 'handmade', 'ink', 'paper', 'experimental', 'animation'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'tint': 'silver'}),
     ('cel_flatten', {'levels': 18, 'flatness': 0.4}),
     ('ink_line', {'weight': 0.18, 'line_color': 'sepia'}),
     ('paper_texture', {'amount': 0.045})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6500, 'cell_noise': -59, 'flutter': 0.15, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-xerographic-festival-animation-1974",
    name="Xerographic Festival Animation",
    family="cartoon",
    era="1974",
    tagline="Dry toner, rough outlines",
    desc="Dry toner, rough outlines: a xerographic animation surface with slight registration movement.",
    tags=('cartoon', 'atlas', 'animation', 'xerox'),
    keywords=('cartoon', 'animation', 'xerox', 'mixed-media', 'handmade', 'ink', 'paper', 'experimental'),
    proc_height=None,
    upscale="auto",
    video=[('cel_flatten', {'levels': 10, 'flatness': 0.65}),
     ('ink_line', {'weight': 0.5, 'xerox_grit': 0.6}),
     ('cel_wobble', {'amount': 0.3, 'rot': 0.015, 'rot_p': 0.03}),
     ('paper_texture', {'amount': 0.03})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 0.6, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-comic-insert-motion-plate-1982",
    name="Comic Insert Motion Plate",
    family="cartoon",
    era="1982",
    tagline="Bold CMYK, visible dots",
    desc="Bold CMYK, visible dots: a printed-comic insert look with deliberate ink misregistration.",
    tags=('cartoon', 'atlas', 'comic', 'animation', 'print'),
    keywords=('cartoon',
     'comic',
     'animation',
     'print',
     'mixed-media',
     'handmade',
     'ink',
     'paper',
     'experimental'),
    proc_height=None,
    upscale="auto",
    video=[('cel_flatten', {'levels': 9, 'flatness': 0.6}),
     ('halftone', {'process': 'comic_cmyk', 'lpi': 42, 'misregister': 1.1, 'paper': 0.32}),
     ('ink_line', {'weight': 0.43})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.9, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-photocopied-music-zine-1991",
    name="Photocopied Music Zine",
    family="cartoon",
    era="1991",
    tagline="Crushed toner, paper streaks",
    desc="Crushed toner, paper streaks: a moving photocopied music-zine surface.",
    tags=('cartoon', 'atlas', 'music-video', 'experimental', 'print'),
    keywords=('cartoon',
     'music-video',
     'experimental',
     'print',
     'mixed-media',
     'handmade',
     'ink',
     'paper',
     'animation'),
    proc_height=None,
    upscale="auto",
    video=[('photocopy', {'generations': 3, 'toner': 0.45, 'roller_marks': 0.18, 'skew': 0.05}),
     ('paper_texture', {'amount': 0.05})],
    audio=[('a_tape_sat', {'drive': 3.1, 'hf_loss': 0.4}), ('a_compressor', {'ratio': 4})],
))

register_preset(Preset(
    id="atlas-early-digital-ink-paint-2001",
    name="Early Digital Ink Paint",
    family="cartoon",
    era="2001",
    tagline="Clean flats, fine outlines",
    desc="Clean flats, fine outlines: an early digital-paint animation finish.",
    tags=('cartoon', 'atlas', 'digital', 'digital-cinema'),
    keywords=('cartoon',
     'digital',
     'digital-cinema',
     'mixed-media',
     'handmade',
     'ink',
     'paper',
     'experimental',
     'animation'),
    proc_height=None,
    upscale="auto",
    video=[('cel_flatten', {'levels': 18, 'flatness': 0.7, 'smooth': 0.5}),
     ('ink_line', {'weight': 0.22, 'xerox_grit': 0}),
     ('color_era', {'profile': 'cable_90s', 'strength': 0.55})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.7, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-teal-orange-riso-animation-2017",
    name="Teal Orange Riso Animation",
    family="cartoon",
    era="2017",
    tagline="Two drums, soft paper grain",
    desc="Two drums, soft paper grain: a moving risograph interpretation with teal and orange ink.",
    tags=('cartoon', 'atlas', 'animation', 'riso', 'print'),
    keywords=('cartoon', 'animation', 'riso', 'print', 'mixed-media', 'handmade', 'ink', 'paper', 'experimental'),
    proc_height=None,
    upscale="auto",
    video=[('cel_flatten', {'levels': 12, 'flatness': 0.4}),
     ('riso_print', {'inks': 'teal_orange', 'misregister': 0.8, 'grain_ink': 0.3, 'paper': 0.35})],
    audio=[('a_tape_sat', {'drive': 1.6, 'hf_loss': 0.15}), ('a_room', {'mix': 0.08})],
))

register_preset(Preset(
    id="atlas-contemporary-mixed-media-feature-2026",
    name="Contemporary Mixed Media Feature",
    family="cartoon",
    era="2026",
    tagline="Layered ink, rich flat color",
    desc="Layered ink, rich flat color: a contemporary hybrid animation surface over supplied footage.",
    tags=('cartoon', 'atlas', 'animation', 'hybrid', 'digital', 'digital-cinema'),
    keywords=('cartoon',
     'animation',
     'hybrid',
     'digital',
     'digital-cinema',
     'mixed-media',
     'handmade',
     'ink',
     'paper',
     'experimental'),
    proc_height=None,
    upscale="auto",
    video=[('cel_flatten', {'levels': 20, 'flatness': 0.32, 'smooth': 0.25}),
     ('cinema_finish', {'density': 0.45, 'local_contrast': 0.2}),
     ('ink_line', {'weight': 0.18, 'xerox_grit': 0.12}),
     ('paper_texture', {'amount': 0.022})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.5, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
