"""Expanded aesthetic atlas: smallgauge.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-nine-five-garden-positive-1931",
    name="Nine Five Garden Positive",
    family="film",
    era="1931",
    tagline="Soft green, modest grain",
    desc="Soft green, modest grain: a small-gauge garden diary with gentle warm highlights.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=520,
    upscale="soft",
    video=[('stock', {'profile': 'technicolor2', 'strength': 0.65}),
     ('tone', {'contrast': 1.05, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.19}),
     ('saturation', {'amount': 0.74}),
     ('grain', {'amount': 0.32, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'corner_softness': 0.24})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 0.15, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-sixteen-millimeter-alpine-survey-1949",
    name="Sixteen Millimeter Alpine Survey",
    family="film",
    era="1949",
    tagline="Blue air, sharp reversal",
    desc="Blue air, sharp reversal: a mountain-field record with cool shadow separation.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=640,
    upscale="soft",
    video=[('stock', {'profile': 'kodachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.23, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.19}),
     ('saturation', {'amount': 1.08}),
     ('grain', {'amount': 0.3, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'blue', 'shadow_amt': 0.24})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 0.45, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-regular-eight-indoor-tungsten-1958",
    name="Regular Eight Indoor Tungsten",
    family="film",
    era="1958",
    tagline="Amber interiors, soft grain",
    desc="Amber interiors, soft grain: a home-reel impression under uncorrected warm light.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=520,
    upscale="soft",
    video=[('stock', {'profile': 'kodachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.12, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.38}),
     ('saturation', {'amount': 0.92}),
     ('grain', {'amount': 0.39, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'diffusion': 0.12})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -56}),
     ('a_channel_aging',
      {'width': 0.2, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-single-eight-coastal-reversal-1966",
    name="Single Eight Coastal Reversal",
    family="film",
    era="1966",
    tagline="Cyan sea, bright sand",
    desc="Cyan sea, bright sand: compact reversal color with firm whites and delicate texture.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=540,
    upscale="soft",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.17, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.13}),
     ('saturation', {'amount': 1.21}),
     ('grain', {'amount': 0.28, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.2})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-super-eight-tungsten-night-1971",
    name="Super Eight Tungsten Night",
    family="film",
    era="1971",
    tagline="Warm lamps, heavy shadow grain",
    desc="Warm lamps, heavy shadow grain: available-light cartridge footage without added light leaks.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=520,
    upscale="soft",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.19, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.28}),
     ('saturation', {'amount': 0.85}),
     ('grain', {'amount': 0.49, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('grain', {'amount': 0.14, 'size': 1, 'chroma_grain': 0.04, 'shadow_boost': 0.8})],
    audio=[('a_analog_dub',
      {'format': 'cassette', 'generations': 1, 'alignment': 0.08, 'compression': 0.18, 'hiss_db': -56}),
     ('a_channel_aging',
      {'width': 0.6, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-reversal-roadside-diary-1977",
    name="Reversal Roadside Diary",
    family="film",
    era="1977",
    tagline="Yellow-green mids, soft blacks",
    desc="Yellow-green mids, soft blacks: a travel diary on weathered reversal stock.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.02, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.2}),
     ('saturation', {'amount': 0.98}),
     ('grain', {'amount': 0.4, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('fade', {'profile': 'cyan_loss', 'amount': 0.18})],
    audio=[('a_analog_dub',
      {'format': 'cassette', 'generations': 2, 'alignment': 0.08, 'compression': 0.18, 'hiss_db': -55}),
     ('a_channel_aging',
      {'width': 0.7, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-community-darkroom-sixteen-1982",
    name="Community Darkroom Sixteen",
    family="film",
    era="1982",
    tagline="Cool silver, coarse emulsion",
    desc="Cool silver, coarse emulsion: a handmade black-and-white community-film print.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=640,
    upscale="soft",
    video=[('stock', {'profile': 'none', 'strength': 0.65}),
     ('tone', {'contrast': 1.26, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.1}),
     ('saturation', {'amount': 0.0}),
     ('grain', {'amount': 0.46, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('mono', {'tint': 'silver'}),
     ('print_char', {'acutance': 0.21})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5900}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5900, 'cell_noise': -54, 'flutter': 0.22, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-super-sixteen-winter-diary-1993",
    name="Super Sixteen Winter Diary",
    family="film",
    era="1993",
    tagline="Pale daylight, fine color grain",
    desc="Pale daylight, fine color grain: winter naturalism on a small negative.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=640,
    upscale="soft",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.04, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.2}),
     ('saturation', {'amount': 0.73}),
     ('grain', {'amount': 0.28, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'veiling_flare': 0.11})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -66}),
     ('a_channel_aging',
      {'width': 0.92, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-hand-processed-copper-eight-2016",
    name="Hand Processed Copper Eight",
    family="film",
    era="2016",
    tagline="Copper mids, uneven dye",
    desc="Copper mids, uneven dye: a handmade modern Super 8 process interpretation.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=540,
    upscale="soft",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.3, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.3}),
     ('saturation', {'amount': 0.69}),
     ('grain', {'amount': 0.43, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'brown', 'shadow_amt': 0.6}),
     ('flicker', {'amount': 0.08, 'color_flicker': 0.24})],
    audio=[('a_analog_dub',
      {'format': 'cassette', 'generations': 1, 'alignment': 0.08, 'compression': 0.18, 'hiss_db': -61}),
     ('a_channel_aging',
      {'width': 0.9, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-fresh-cartridge-wedding-film-2026",
    name="Fresh Cartridge Wedding Film",
    family="film",
    era="2026",
    tagline="Cream highlights, clear color",
    desc="Cream highlights, clear color: contemporary fine-texture Super 8 with intimate supplied sound.",
    tags=('film', 'atlas', 'small-gauge', '16mm', 'super8', 'home-movie', 'documentary', 'travel'),
    keywords=('small-gauge',
     '16mm',
     'super8',
     'home-movie',
     'documentary',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.06, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.13}),
     ('saturation', {'amount': 1.05}),
     ('grain', {'amount': 0.23, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'highlight_desat': 0.62})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.35, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.92, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
