"""Expanded aesthetic atlas: institution.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-training-room-open-reel-video-1967",
    name="Training Room Open Reel Video",
    family="broadcast",
    era="1967",
    tagline="Soft gray, tube glow",
    desc="Soft gray, tube glow: a monochrome industrial camera record.",
    tags=('broadcast', 'atlas', 'archive', 'training', 'industrial'),
    keywords=('archive',
     'training',
     'industrial',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.18, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.1, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.12, 'tint': 'neutral', 'threshold': 0.78}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.35,
       'chroma_delay': 0.4,
       'luma_noise': 0.09,
       'chroma_noise': 0.063,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.08,
       'jitter_v': 0.015,
       'dropout_burst': 0}),
     ('crt', {'bloom': 0.07, 'scan_strength': 0.06})],
    audio=[('a_historical_mic', {'profile': 'broadcast_dynamic_1955', 'self_noise_db': -60}),
     ('a_mono', {'amount': 1})],
))

register_preset(Preset(
    id="atlas-university-portapak-interview-1972",
    name="University Portapak Interview",
    family="broadcast",
    era="1972",
    tagline="Open silver, soft edges",
    desc="Open silver, soft edges: a portable monochrome interview record.",
    tags=('broadcast', 'atlas', 'archive', 'documentary', 'interview'),
    keywords=('archive',
     'documentary',
     'interview',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.97, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.16, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.06, 'tint': 'neutral', 'threshold': 0.78}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.4,
       'chroma_delay': 0.4,
       'luma_noise': 0.12,
       'chroma_noise': 0.084,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.1,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_historical_mic', {'profile': 'lavalier_1972', 'handling': 0.03}),
     ('a_analog_dub', {'format': 'reel_375ips', 'hiss_db': -58})],
))

register_preset(Preset(
    id="atlas-hospital-teaching-camera-1978",
    name="Hospital Teaching Camera",
    family="broadcast",
    era="1978",
    tagline="Cool whites, narrow chroma",
    desc="Cool whites, narrow chroma: clinical teaching-video color with modest tape noise.",
    tags=('broadcast', 'atlas', 'archive', 'educational', 'clinical'),
    keywords=('archive',
     'educational',
     'clinical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('balance', {'warmth': -0.18, 'tint': -0.04}),
     ('saturation', {'amount': 0.8}),
     ('ntsc',
      {'system': 'pal',
       'luma_bw': 4,
       'chroma_bw': 0.9,
       'phase_error': 0,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.75,
       'chroma_delay': 0.4,
       'luma_noise': 0.06,
       'chroma_noise': 0.042,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.08,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_bandlimit', {'low_hz': 110, 'high_hz': 9000}), ('a_room', {'mix': 0.08, 'decay_s': 0.4})],
))

register_preset(Preset(
    id="atlas-museum-oral-history-tape-1983",
    name="Museum Oral History Tape",
    family="broadcast",
    era="1983",
    tagline="Warm skin, soft mids",
    desc="Warm skin, soft mids: a carefully recorded seated interview on institutional tape.",
    tags=('broadcast', 'atlas', 'archive', 'documentary', 'interview'),
    keywords=('archive',
     'documentary',
     'interview',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('stock', {'profile': 'tube_80s', 'strength': 0.35}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.8,
       'chroma_delay': 0.4,
       'luma_noise': 0.045,
       'chroma_noise': 0.032,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.02,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'umatic_linear', 'tracking': 0.02, 'dropout_rate': 0, 'noise_db': -63})],
))

register_preset(Preset(
    id="atlas-industrial-inspection-color-1986",
    name="Industrial Inspection Color",
    family="broadcast",
    era="1986",
    tagline="Hard luma, muted color",
    desc="Hard luma, muted color: an inspection-camera feed with firm electronic edges.",
    tags=('broadcast', 'atlas', 'archive', 'industrial', 'documentary'),
    keywords=('archive',
     'industrial',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('tone', {'contrast': 1.25, 'knee': 0.82}),
     ('saturation', {'amount': 0.62}),
     ('sharpen', {'amount': 0.35}),
     ('ntsc',
      {'system': 'ntsc',
       'luma_bw': 3.8,
       'chroma_bw': 0.6,
       'phase_error': 0,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'})],
    audio=[('a_bandlimit', {'low_hz': 180, 'high_hz': 6200}), ('a_mono', {'amount': 1})],
))

register_preset(Preset(
    id="atlas-lecture-hall-tape-master-1991",
    name="Lecture Hall Tape Master",
    family="broadcast",
    era="1991",
    tagline="Pale tungsten, steady picture",
    desc="Pale tungsten, steady picture: an institutional lecture master with roomy speech.",
    tags=('broadcast', 'atlas', 'archive', 'educational', 'lecture'),
    keywords=('archive',
     'educational',
     'lecture',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('balance', {'warmth': 0.15}),
     ('tone', {'contrast': 1.03, 'knee': 0.88}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.9,
       'chroma_delay': 0.4,
       'luma_noise': 0.05,
       'chroma_noise': 0.035,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.015,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_historical_mic', {'profile': 'electret_1985'}), ('a_room', {'decay_s': 0.8, 'mix': 0.14})],
))

register_preset(Preset(
    id="atlas-courtroom-digital-record-1998",
    name="Courtroom Digital Record",
    family="broadcast",
    era="1998",
    tagline="Neutral gray, sharp edges",
    desc="Neutral gray, sharp edges: a standard-definition evidence record without added words.",
    tags=('broadcast', 'atlas', 'archive', 'documentary', 'evidence'),
    keywords=('archive',
     'documentary',
     'evidence',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 0.78}),
     ('chroma_dv', {'ratio': '4:1:1', 'edge_sharpen': 0.18}),
     ('codec_era', {'codec': 'mjpeg', 'kbps': 6000, 'res': '480p', 'qscale': 4})],
    audio=[('a_bandlimit', {'low_hz': 120, 'high_hz': 11000}), ('a_compressor', {'ratio': 2.3})],
))

register_preset(Preset(
    id="atlas-field-research-minidv-2004",
    name="Field Research MiniDV",
    family="broadcast",
    era="2004",
    tagline="Natural mids, crisp chroma edges",
    desc="Natural mids, crisp chroma edges: a field-research camera recording.",
    tags=('broadcast', 'atlas', 'archive', 'research', 'documentary'),
    keywords=('archive',
     'research',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.08}),
     ('chroma_dv', {'ratio': '4:2:0', 'edge_sharpen': 0.38}),
     ('codec_era', {'codec': 'mpeg2video', 'kbps': 6800, 'res': 'native'})],
    audio=[('a_historical_mic', {'profile': 'camcorder_1994', 'self_noise_db': -65, 'handling': 0.02})],
))

register_preset(Preset(
    id="atlas-municipal-archive-h264-2013",
    name="Municipal Archive H264",
    family="broadcast",
    era="2013",
    tagline="Flat daylight, modest bitrate",
    desc="Flat daylight, modest bitrate: a city-archive documentary encode.",
    tags=('broadcast', 'atlas', 'archive', 'documentary', 'civic'),
    keywords=('archive',
     'documentary',
     'civic',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 0.96, 'knee': 0.92}),
     ('saturation', {'amount': 0.87}),
     ('codec_era', {'codec': 'h264', 'kbps': 2200, 'res': '480p'})],
    audio=[('a_codec_aac', {'kbps': 96, 'mono': True})],
))

register_preset(Preset(
    id="atlas-contemporary-oral-history-master-2026",
    name="Contemporary Oral History Master",
    family="broadcast",
    era="2026",
    tagline="True neutrals, gentle dynamics",
    desc="True neutrals, gentle dynamics: a restrained contemporary archival interview finish.",
    tags=('broadcast', 'atlas', 'archive', 'documentary', 'interview'),
    keywords=('archive',
     'documentary',
     'interview',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.02, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.02, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.96, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.48, 'local_contrast': 0.08})],
    audio=[('a_bandlimit', {'low_hz': 65, 'high_hz': 18000}),
     ('a_compressor', {'ratio': 1.6, 'attack_ms': 18, 'release_ms': 350})],
))
