"""Expanded aesthetic atlas: webarchive.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-dialup-science-lecture-1996",
    name="Dialup Science Lecture",
    family="digital",
    era="1996",
    tagline="Postage-stamp detail, narrow speech",
    desc="Postage-stamp detail, narrow speech: a low-bandwidth lecture stream.",
    tags=('digital', 'atlas', 'web-video', 'educational', 'lecture', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'educational',
     'lecture',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 0.72}), ('codec_era', {'codec': 'h263p', 'kbps': 96, 'res': '144p'})],
    audio=[('a_codec_speech', {'codec': 'mulaw_8k'})],
))

register_preset(Preset(
    id="atlas-fan-site-trailer-download-1999",
    name="Fan Site Trailer Download",
    family="digital",
    era="1999",
    tagline="Dense blocks, small stereo",
    desc="Dense blocks, small stereo: a downloadable movie trailer transfer.",
    tags=('digital', 'atlas', 'web-video', 'trailer', 'cinema', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'trailer',
     'cinema',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.2}), ('codec_era', {'codec': 'mpeg1video', 'kbps': 420, 'res': '240p'})],
    audio=[('a_codec_mp3', {'kbps': '48', 'mono': False})],
))

register_preset(Preset(
    id="atlas-web-art-quicktime-era-2001",
    name="Web Art Quicktime Era",
    family="digital",
    era="2001",
    tagline="Soft gradients, compact color",
    desc="Soft gradients, compact color: an early web-art movie transfer using a comparable period codec.",
    tags=('digital', 'atlas', 'web-video', 'experimental', 'web-art', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'experimental',
     'web-art',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 0.9}), ('codec_era', {'codec': 'mjpeg', 'kbps': 1200, 'res': '240p'})],
    audio=[('a_bandlimit', {'low_hz': 50, 'high_hz': 11000})],
))

register_preset(Preset(
    id="atlas-flash-interview-embed-2004",
    name="Flash Interview Embed",
    family="digital",
    era="2004",
    tagline="Soft skin, block edges",
    desc="Soft skin, block edges: a low-bandwidth embedded interview.",
    tags=('digital', 'atlas', 'web-video', 'interview', 'documentary', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'interview',
     'documentary',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('sharpen', {'amount': 0.17}), ('codec_era', {'codec': 'flv1', 'kbps': 280, 'res': '240p'})],
    audio=[('a_codec_mp3', {'kbps': '32', 'mono': True})],
))

register_preset(Preset(
    id="atlas-broadband-festival-screener-2007",
    name="Broadband Festival Screener",
    family="digital",
    era="2007",
    tagline="Clean mids, visible compression",
    desc="Clean mids, visible compression: a private web-era festival screener.",
    tags=('digital', 'atlas', 'web-video', 'cinema', 'independent', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'cinema',
     'independent',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.06, 'knee': 0.87}),
     ('codec_era', {'codec': 'h264', 'kbps': 850, 'res': '360p'})],
    audio=[('a_codec_aac', {'kbps': 96})],
))

register_preset(Preset(
    id="atlas-forum-reposted-concert-2009",
    name="Forum Reposted Concert",
    family="digital",
    era="2009",
    tagline="Hot color, repeated compression",
    desc="Hot color, repeated compression: a concert clip passed through several web uploads.",
    tags=('digital', 'atlas', 'web-video', 'concert', 'music-video', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'concert',
     'music-video',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 1.18}),
     ('upload_gen', {'gens': 2, 'qscale': 8, 'deband_loss': 0.16}),
     ('codec_era', {'codec': 'mpeg4', 'kbps': 650, 'res': '360p'})],
    audio=[('a_codec_mp3', {'kbps': '64', 'mono': False})],
))

register_preset(Preset(
    id="atlas-early-hd-vlog-upload-2011",
    name="Early HD Vlog Upload",
    family="digital",
    era="2011",
    tagline="Crisp face detail, modest bitrate",
    desc="Crisp face detail, modest bitrate: an early HD vlog distribution encode.",
    tags=('digital', 'atlas', 'web-video', 'home-video', 'vlog', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'home-video',
     'vlog',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('sharpen', {'amount': 0.24}), ('codec_era', {'codec': 'h264', 'kbps': 1800, 'res': 'native'})],
    audio=[('a_codec_aac', {'kbps': 112})],
))

register_preset(Preset(
    id="atlas-vertical-message-forward-2015",
    name="Vertical Message Forward",
    family="digital",
    era="2015",
    tagline="Soft detail, lean mono sound",
    desc="Soft detail, lean mono sound: a compact mobile-message transfer that keeps source framing.",
    tags=('digital', 'atlas', 'web-video', 'mobile', 'social', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'mobile',
     'social',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('chroma_dv', {'ratio': '4:2:0', 'edge_sharpen': 0.1}),
     ('codec_era', {'codec': 'h264', 'kbps': 480, 'res': '360p'})],
    audio=[('a_codec_aac', {'kbps': 48, 'mono': True})],
))

register_preset(Preset(
    id="atlas-conference-archive-upload-2020",
    name="Conference Archive Upload",
    family="digital",
    era="2020",
    tagline="Neutral video, clear speech",
    desc="Neutral video, clear speech: a practical conference-recording distribution copy.",
    tags=('digital', 'atlas', 'web-video', 'educational', 'conference', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'educational',
     'conference',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.02}),
     ('saturation', {'amount': 0.92}),
     ('codec_era', {'codec': 'h264', 'kbps': 1600, 'res': '480p'})],
    audio=[('a_compressor', {'ratio': 2.5}), ('a_codec_aac', {'kbps': 80, 'mono': True})],
))

register_preset(Preset(
    id="atlas-modern-social-archive-copy-2026",
    name="Modern Social Archive Copy",
    family="digital",
    era="2026",
    tagline="Bright color, smooth detail",
    desc="Bright color, smooth detail: a contemporary social-video archive encode.",
    tags=('digital', 'atlas', 'web-video', 'social', 'archive', 'digital-cinema'),
    keywords=('digital',
     'web-video',
     'social',
     'archive',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 1.09}),
     ('cinema_finish', {'highlight_desat': 0.28}),
     ('codec_era', {'codec': 'h264', 'kbps': 4000, 'res': 'native'})],
    audio=[('a_codec_aac', {'kbps': 192})],
))
