"""Expanded aesthetic atlas: artnow.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-digital-dusk-contemplation-2003",
    name="Digital Dusk Contemplation",
    family="arthouse",
    era="2003",
    tagline="Cobalt dusk, soft low lights",
    desc="Cobalt dusk, soft low lights: an early digital slow-film interpretation.",
    tags=('arthouse', 'atlas', 'slow-cinema', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'slow-cinema',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 0.96, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.24, 'shadow_tint': 'blue', 'shadow_amt': 0.4}),
     ('saturation', {'amount': 0.7, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.35, 'density': 0.12, 'local_contrast': 0.12}),
     ('codec_era', {'codec': 'mpeg2video', 'kbps': 6500, 'res': 'native', 'field_mode': 'progressive'})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.95, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-bleached-festival-debut-2006",
    name="Bleached Festival Debut",
    family="arthouse",
    era="2006",
    tagline="Silver mids, chalky highlights",
    desc="Silver mids, chalky highlights: a restrained debut-film digital intermediate.",
    tags=('arthouse', 'atlas', 'independent', 'film'),
    keywords=('arthouse',
     'independent',
     'film',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.2, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.06}),
     ('saturation', {'amount': 0.72}),
     ('grain', {'amount': 0.26, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.48})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.5, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.88, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-pastel-apartment-naturalism-2009",
    name="Pastel Apartment Naturalism",
    family="arthouse",
    era="2009",
    tagline="Pastel walls, creamy daylight",
    desc="Pastel walls, creamy daylight: delicate domestic color with soft local contrast.",
    tags=('arthouse', 'atlas', 'domestic', 'drama', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'domestic',
     'drama',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 0.94, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.1, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.8, 'vibrance': 0.08}),
     ('cinema_finish', {'local_contrast': -0.25, 'highlight_desat': 0.6, 'density': 0.12})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.3, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.9, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-coastal-slow-cinema-2012",
    name="Coastal Slow Cinema",
    family="arthouse",
    era="2012",
    tagline="Sea-gray blues, open shadow",
    desc="Sea-gray blues, open shadow: a muted coastal master with minimal processing grain.",
    tags=('arthouse', 'atlas', 'slow-cinema', 'coastal', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'slow-cinema',
     'coastal',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.03, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.12, 'shadow_tint': 'teal', 'shadow_amt': 0.18}),
     ('saturation', {'amount': 0.58, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.35, 'density': 0.12, 'local_contrast': 0.12}),
     ('grain', {'amount': 0.07, 'size': 0.85, 'chroma_grain': 0.02})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.1, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-museum-white-cube-film-2014",
    name="Museum White Cube Film",
    family="arthouse",
    era="2014",
    tagline="Neutral white, precise texture",
    desc="Neutral white, precise texture: clean gallery presentation with firm midtone detail.",
    tags=('arthouse', 'atlas', 'gallery', 'experimental', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'gallery',
     'experimental',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.04, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.92, 'vibrance': 0.08}),
     ('cinema_finish', {'local_contrast': 0.32, 'highlight_desat': 0.85})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.05, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0}),
     ('a_room', {'size': 1.8, 'decay_s': 1.1, 'mix': 0.18})],
))

register_preset(Preset(
    id="atlas-summer-memory-sixteen-2016",
    name="Summer Memory Sixteen",
    family="arthouse",
    era="2016",
    tagline="Honey highlights, soft foliage",
    desc="Honey highlights, soft foliage: a contemporary memory-film print with tactile color grain.",
    tags=('arthouse', 'atlas', 'memory', '16mm', 'pastoral'),
    keywords=('arthouse',
     'memory',
     '16mm',
     'pastoral',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.04, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.2}),
     ('saturation', {'amount': 0.92}),
     ('grain', {'amount': 0.32, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'diffusion': 0.2})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 0.95, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-night-bus-available-light-2018",
    name="Night Bus Available Light",
    family="arthouse",
    era="2018",
    tagline="Green lamps, cobalt black",
    desc="Green lamps, cobalt black: a low-light city-film grade with restrained noise.",
    tags=('arthouse', 'atlas', 'urban', 'night', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'urban',
     'night',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.17, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.13, 'shadow_tint': 'green', 'shadow_amt': 0.35}),
     ('saturation', {'amount': 0.72, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.35, 'density': 0.12, 'local_contrast': 0.12}),
     ('grain', {'amount': 0.12, 'size': 0.9, 'chroma_grain': 0.05, 'shadow_boost': 0.6})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.7, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.95, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-monochrome-festival-master-2021",
    name="Monochrome Festival Master",
    family="arthouse",
    era="2021",
    tagline="Graphite black, pearl whites",
    desc="Graphite black, pearl whites: modern monochrome with gentle density and fine silver texture.",
    tags=('arthouse', 'atlas', 'bw', 'digital', 'drama', 'digital-cinema'),
    keywords=('arthouse',
     'bw',
     'digital',
     'drama',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.24, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.09, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.055, 'tint': 'neutral', 'threshold': 0.78}),
     ('cinema_finish', {'local_contrast': 0.22, 'highlight_desat': 1})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.25, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.05, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-rose-gray-memory-film-2024",
    name="Rose Gray Memory Film",
    family="arthouse",
    era="2024",
    tagline="Rose skin, gray-green shade",
    desc="Rose skin, gray-green shade: restrained memory cinema with color-density separation.",
    tags=('arthouse', 'atlas', 'memory', 'drama', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'memory',
     'drama',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 0.99, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.08, 'shadow_tint': 'green', 'shadow_amt': 0.25}),
     ('saturation', {'amount': 0.76, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.45, 'highlight_desat': 0.6}),
     ('optics', {'diffusion': 0.09})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.4, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.92, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-mineral-daylight-art-film-2026",
    name="Mineral Daylight Art Film",
    family="arthouse",
    era="2026",
    tagline="Mineral blue, neutral whites",
    desc="Mineral blue, neutral whites: crisp contemporary daylight with subtle color density.",
    tags=('arthouse', 'atlas', 'contemporary', 'drama', 'digital', 'digital-cinema'),
    keywords=('arthouse',
     'contemporary',
     'drama',
     'digital',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.1, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.11, 'shadow_tint': 'blue', 'shadow_amt': 0.2}),
     ('saturation', {'amount': 0.87, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.32, 'local_contrast': 0.27, 'highlight_desat': 0.7})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.35, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.08, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
