"""Expanded aesthetic atlas: broadcast.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-monochrome-studio-line-feed-1956",
    name="Monochrome Studio Line Feed",
    family="broadcast",
    era="1956",
    tagline="Soft silver, fine line texture",
    desc="Soft silver, fine line texture: a monochrome studio feed with a narrow mono track.",
    tags=('broadcast', 'atlas', 'television', 'bw', 'studio'),
    keywords=('broadcast',
     'television',
     'bw',
     'studio',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=576,
    upscale="soft",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.17, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.12, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.14, 'tint': 'neutral', 'threshold': 0.78}),
     ('ntsc',
      {'system': 'ntsc',
       'luma_bw': 3.5,
       'chroma_bw': 0.7,
       'phase_error': 0,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('crt', {'scan_strength': 0.09, 'bloom': 0.06})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6000}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6000, 'cell_noise': -58, 'flutter': 0.07, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-color-outside-broadcast-truck-1968",
    name="Color Outside Broadcast Truck",
    family="broadcast",
    era="1968",
    tagline="Warm tube color, soft chroma",
    desc="Warm tube color, soft chroma: an early outside-broadcast signal with restrained phase noise.",
    tags=('broadcast', 'atlas', 'television', 'sport', 'live'),
    keywords=('broadcast',
     'television',
     'sport',
     'live',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=576,
    upscale="soft",
    video=[('stock', {'profile': 'tube_70s', 'strength': 0.6}),
     ('ntsc',
      {'system': 'ntsc',
       'luma_bw': 4,
       'chroma_bw': 0.8,
       'phase_error': 2.5,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'})],
    audio=[('a_tv_sound', {'comp': 0.42, 'buzz_db': -62, 'hum_db': -67})],
))

register_preset(Preset(
    id="atlas-pal-studio-master-feed-1974",
    name="PAL Studio Master Feed",
    family="broadcast",
    era="1974",
    tagline="Stable hue, clear luma",
    desc="Stable hue, clear luma: a color-studio PAL feed with broad midtone detail.",
    tags=('broadcast', 'atlas', 'television', 'pal', 'studio'),
    keywords=('broadcast',
     'television',
     'pal',
     'studio',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=576,
    upscale="soft",
    video=[('stock', {'profile': 'tube_70s', 'strength': 0.4}),
     ('ntsc',
      {'system': 'pal',
       'luma_bw': 5.2,
       'chroma_bw': 1.5,
       'phase_error': 0,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('sharpen', {'amount': 0.12})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.3, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.2, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-c-band-satellite-return-1982",
    name="C Band Satellite Return",
    family="broadcast",
    era="1982",
    tagline="Soft chroma, faint RF grain",
    desc="Soft chroma, faint RF grain: a satellite return with modest noise and no invented outages.",
    tags=('broadcast', 'atlas', 'television', 'satellite', 'news'),
    keywords=('broadcast',
     'television',
     'satellite',
     'news',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=576,
    upscale="soft",
    video=[('stock', {'profile': 'tube_80s', 'strength': 0.5}),
     ('ntsc',
      {'system': 'ntsc',
       'luma_bw': 4.5,
       'chroma_bw': 1.1,
       'phase_error': 0,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('signal_rf', {'snow': 0.035, 'ghost_n': 0, 'impulse_noise': 0})],
    audio=[('a_fm_radio', {'hiss_db': -62, 'comp': 0.35})],
))

register_preset(Preset(
    id="atlas-component-newsroom-tape-1988",
    name="Component Newsroom Tape",
    family="broadcast",
    era="1988",
    tagline="Clear luma, restrained edges",
    desc="Clear luma, restrained edges: a component newsroom master with modest chroma loss.",
    tags=('broadcast', 'atlas', 'television', 'news', 'component'),
    keywords=('broadcast',
     'television',
     'news',
     'component',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=576,
    upscale="soft",
    video=[('tone', {'contrast': 1.1, 'knee': 0.87}),
     ('chroma_dv', {'ratio': '4:2:0', 'edge_sharpen': 0.2}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 1.1,
       'chroma_delay': 0.1,
       'luma_noise': 0.04,
       'chroma_noise': 0.028,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.015,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'betahifi', 'tracking': 0.02, 'dropout_rate': 0, 'noise_db': -68})],
))

register_preset(Preset(
    id="atlas-regional-cable-headend-1993",
    name="Regional Cable Headend",
    family="broadcast",
    era="1993",
    tagline="Warm video, soft detail",
    desc="Warm video, soft detail: a regional cable feed with faint interference texture.",
    tags=('broadcast', 'atlas', 'television', 'cable', 'news'),
    keywords=('broadcast',
     'television',
     'cable',
     'news',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=576,
    upscale="soft",
    video=[('ntsc',
      {'system': 'ntsc',
       'luma_bw': 3.6,
       'chroma_bw': 0.75,
       'phase_error': -2,
       'phase_noise': 1.2,
       'rainbow': 0.08,
       'dot_crawl': 0.06,
       'fringing': 0.3,
       'comb_mode': 'comb_2d_adaptive'}),
     ('herringbone', {'amount': 0.035, 'pattern': 'diagonal_bars'})],
    audio=[('a_tv_sound', {'comp': 0.6, 'buzz_db': -57, 'hum_db': -63})],
))

register_preset(Preset(
    id="atlas-digital-studio-sd-feed-1999",
    name="Digital Studio SD Feed",
    family="broadcast",
    era="1999",
    tagline="Firm edges, clean color",
    desc="Firm edges, clean color: a standard-definition digital studio chain.",
    tags=('broadcast', 'atlas', 'television', 'digital', 'studio', 'digital-cinema'),
    keywords=('broadcast',
     'television',
     'digital',
     'studio',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('chroma_dv', {'ratio': '4:2:0', 'edge_sharpen': 0.45}),
     ('codec_era', {'codec': 'mpeg2video', 'kbps': 6000, 'res': '480p'})],
    audio=[('a_codec_mp3', {'kbps': '128', 'mono': False})],
))

register_preset(Preset(
    id="atlas-field-hdv-news-master-2005",
    name="Field HDV News Master",
    family="broadcast",
    era="2005",
    tagline="Sharp luma, modest codec texture",
    desc="Sharp luma, modest codec texture: a field-news HDV-like MPEG-2 master.",
    tags=('broadcast', 'atlas', 'television', 'hdv', 'news', 'digital', 'digital-cinema'),
    keywords=('broadcast',
     'television',
     'hdv',
     'news',
     'digital',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.13, 'knee': 0.85}),
     ('chroma_dv', {'ratio': '4:2:0', 'edge_sharpen': 0.35}),
     ('codec_era', {'codec': 'mpeg2video', 'kbps': 7800, 'res': 'native', 'gop': 15})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.4, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.9, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-early-hd-sports-replay-2009",
    name="Early HD Sports Replay",
    family="broadcast",
    era="2009",
    tagline="Bright color, brisk edges",
    desc="Bright color, brisk edges: an early HD broadcast replay treatment.",
    tags=('broadcast', 'atlas', 'television', 'sport', 'hd', 'digital', 'digital-cinema'),
    keywords=('broadcast',
     'television',
     'sport',
     'hd',
     'digital',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('saturation', {'amount': 1.16}),
     ('sharpen', {'amount': 0.28}),
     ('codec_era', {'codec': 'h264', 'kbps': 7000, 'res': 'native', 'crf': 20})],
    audio=[('a_compressor', {'ratio': 3, 'threshold_db': -21}), ('a_codec_aac', {'kbps': 192})],
))

register_preset(Preset(
    id="atlas-live-cinema-broadcast-2026",
    name="Live Cinema Broadcast",
    family="broadcast",
    era="2026",
    tagline="Natural color, smooth whites",
    desc="Natural color, smooth whites: a contemporary cinema-style live broadcast finish.",
    tags=('broadcast', 'atlas', 'television', 'live', 'concert', 'digital', 'digital-cinema'),
    keywords=('broadcast',
     'television',
     'live',
     'concert',
     'digital',
     'digital-cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.06, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.025, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.04, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.6, 'local_contrast': 0.18}),
     ('codec_era', {'codec': 'h264', 'kbps': 8000, 'res': 'native', 'crf': 18})],
    audio=[('a_agc', {'amount': 0.38, 'target_db': -18, 'max_gain_db': 6}),
     ('a_compressor',
      {'threshold_db': -18, 'ratio': 2.1, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.08, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
