"""Expanded aesthetic atlas: soundfinish.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-oral-history-cylinder-transfer-1908",
    name="Oral History Cylinder Transfer",
    family="audio",
    era="1908",
    tagline="Narrow speech, soft surface",
    desc="Narrow speech, soft surface: a gently worn cylinder-transfer interpretation.",
    tags=('audio', 'atlas', 'sound', 'cylinder', 'archive'),
    keywords=('audio',
     'sound',
     'cylinder',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_mono', {'amount': 1}),
     ('a_disc_medium',
      {'medium': 'wax_cylinder_1905', 'wear': 0.2, 'surface_db': -53, 'impacts': 2, 'wow_cents': 7}),
     ('a_speaker', {'device': 'gramophone_horn_1915', 'strength': 0.32})],
))

register_preset(Preset(
    id="atlas-electrical-disc-library-copy-1932",
    name="Electrical Disc Library Copy",
    family="audio",
    era="1932",
    tagline="Clear mids, restrained surface",
    desc="Clear mids, restrained surface: an electrical-era disc library transfer.",
    tags=('audio', 'atlas', 'sound', 'disc', 'archive'),
    keywords=('audio',
     'sound',
     'disc',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_historical_mic', {'profile': 'ribbon_1938', 'amount': 0.35}),
     ('a_transcription_disc', {'band': 0.65, 'swish': 0.15, 'crackle': 1, 'wear': 0.12}),
     ('a_mono', {'amount': 1})],
))

register_preset(Preset(
    id="atlas-field-wire-clean-transfer-1948",
    name="Field Wire Clean Transfer",
    family="audio",
    era="1948",
    tagline="Thin highs, gentle flutter",
    desc="Thin highs, gentle flutter: a carefully recovered field-wire recording.",
    tags=('audio', 'atlas', 'sound', 'wire', 'documentary'),
    keywords=('audio',
     'sound',
     'wire',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_bandlimit', {'low_hz': 140, 'high_hz': 6800}),
     ('a_wire_recorder',
      {'flutter': 0.15, 'watery': 0.13, 'twang': 0.05, 'dropout_rate': 0, 'hiss_db': -58})],
))

register_preset(Preset(
    id="atlas-quarter-inch-essay-master-1963",
    name="Quarter Inch Essay Master",
    family="audio",
    era="1963",
    tagline="Warm tape, steady center",
    desc="Warm tape, steady center: a documentary essay master with broad midrange.",
    tags=('audio', 'atlas', 'sound', 'reel', 'tape', 'documentary'),
    keywords=('audio',
     'sound',
     'reel',
     'tape',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_historical_mic', {'profile': 'broadcast_dynamic_1955', 'amount': 0.45}),
     ('a_analog_dub', {'format': 'reel_75ips', 'generations': 1, 'alignment': 0.035, 'hiss_db': -68}),
     ('a_mono', {'amount': 0.75})],
))

register_preset(Preset(
    id="atlas-small-theater-magnetic-mix-1976",
    name="Small Theater Magnetic Mix",
    family="audio",
    era="1976",
    tagline="Warm low end, soft room",
    desc="Warm low end, soft room: a magnetic-film screening interpretation.",
    tags=('audio', 'atlas', 'sound', 'cinema', 'magnetic', 'tape'),
    keywords=('audio',
     'sound',
     'cinema',
     'magnetic',
     'tape',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_tape_sat', {'drive': 1.4, 'bump_db': 1.8, 'hf_loss': 0.12}),
     ('a_channel_aging', {'width': 1.1, 'imbalance_db': 0, 'skew_us': 12, 'phase_wander': 0.03}),
     ('a_room', {'size': 2.2, 'decay_s': 0.9, 'mix': 0.12})],
))

register_preset(Preset(
    id="atlas-indie-cassette-location-stem-1988",
    name="Indie Cassette Location Stem",
    family="audio",
    era="1988",
    tagline="Dry speech, fine cassette hiss",
    desc="Dry speech, fine cassette hiss: an intimate cassette location recording.",
    tags=('audio', 'atlas', 'sound', 'cassette', 'location'),
    keywords=('audio',
     'sound',
     'cassette',
     'location',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_historical_mic', {'profile': 'electret_1985', 'amount': 0.6, 'handling': 0.025}),
     ('a_noise_reduction', {'system': 'dolby_c', 'decode_error': -0.1, 'pumping': 0.1, 'hiss_db': -64}),
     ('a_tape_sat', {'drive': 1.3, 'hf_loss': 0.2})],
))

register_preset(Preset(
    id="atlas-dat-festival-dialogue-master-1995",
    name="DAT Festival Dialogue Master",
    family="audio",
    era="1995",
    tagline="Clean speech, tight dynamics",
    desc="Clean speech, tight dynamics: a digital festival dialogue-master finish.",
    tags=('audio', 'atlas', 'sound', 'digital', 'dat', 'cinema'),
    keywords=('audio',
     'sound',
     'digital',
     'dat',
     'cinema',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_bandlimit', {'low_hz': 55, 'high_hz': 20000}),
     ('a_compressor', {'ratio': 1.6, 'attack_ms': 17, 'release_ms': 330}),
     ('a_channel_aging',
      {'width': 0.72, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-broadband-documentary-sound-2008",
    name="Broadband Documentary Sound",
    family="audio",
    era="2008",
    tagline="Clear voice, compact stereo",
    desc="Clear voice, compact stereo: a web-era documentary audio encode.",
    tags=('audio', 'atlas', 'sound', 'digital', 'web', 'documentary'),
    keywords=('audio',
     'sound',
     'digital',
     'web',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_bandlimit', {'low_hz': 75, 'high_hz': 16500}),
     ('a_compressor', {'ratio': 2.1, 'attack_ms': 12}),
     ('a_codec_aac', {'kbps': 112})],
))

register_preset(Preset(
    id="atlas-intimate-contemporary-art-mix-2026",
    name="Intimate Contemporary Art Mix",
    family="audio",
    era="2026",
    tagline="Soft dynamics, close detail",
    desc="Soft dynamics, close detail: a quiet art-film finishing pass on the supplied soundtrack.",
    tags=('audio', 'atlas', 'sound', 'digital', 'cinema', 'arthouse'),
    keywords=('audio',
     'sound',
     'digital',
     'cinema',
     'arthouse',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_bandlimit', {'low_hz': 32, 'high_hz': 20000}),
     ('a_compressor', {'ratio': 1.18, 'attack_ms': 45, 'release_ms': 550}),
     ('a_room', {'mix': 0.035, 'decay_s': 0.35})],
))

register_preset(Preset(
    id="atlas-contemporary-tentpole-stereo-mix-2026",
    name="Contemporary Tentpole Stereo Mix",
    family="audio",
    era="2026",
    tagline="Wide field, controlled peaks",
    desc="Wide field, controlled peaks: a contemporary cinema-style stereo finishing pass.",
    tags=('audio', 'atlas', 'sound', 'digital', 'cinema', 'blockbuster'),
    keywords=('audio',
     'sound',
     'digital',
     'cinema',
     'blockbuster',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[],
    audio=[('a_compressor',
      {'ratio': 2.4, 'threshold_db': -17, 'attack_ms': 32, 'release_ms': 280, 'knee_db': 8}),
     ('a_channel_aging',
      {'width': 1.22,
       'imbalance_db': 0,
       'crosstalk_db': -80,
       'skew_us': 0,
       'phase_wander': 0,
       'mono_bass_hz': 130}),
     ('a_tape_sat', {'drive': 1.08, 'bump_db': 0.8, 'hf_loss': 0})],
))
