"""Expanded aesthetic atlas: moderncapture.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-travel-drone-overcast-2016",
    name="Travel Drone Overcast",
    family="modern",
    era="2016",
    tagline="Cool sky, crisp terrain",
    desc="Cool sky, crisp terrain: a neutral overcast drone-camera finish.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'travel', 'drone', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'travel',
     'drone',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.1, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.08, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.9, 'vibrance': 0.08}),
     ('cinema_finish', {'local_contrast': 0.35, 'highlight_desat': 0.6}),
     ('optics', {'distortion': -0.025, 'chromatic_aberration': 0.3}),
     ('codec_era', {'codec': 'h264', 'kbps': 6500, 'res': 'native', 'crf': 20})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-mirrorless-natural-light-diary-2018",
    name="Mirrorless Natural Light Diary",
    family="modern",
    era="2018",
    tagline="Warm skin, soft shoulder",
    desc="Warm skin, soft shoulder: a mirrorless-camera diary grade.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'home-video', 'mirrorless', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'home-video',
     'mirrorless',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.03, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.075, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.97, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.6, 'density': 0.2}),
     ('optics', {'diffusion': 0.05}),
     ('grain', {'amount': 0.11, 'size': 0.9, 'chroma_grain': 0.06})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.4, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.95, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-phone-night-computational-2020",
    name="Phone Night Computational",
    family="modern",
    era="2020",
    tagline="Lifted lows, smoothed noise",
    desc="Lifted lows, smoothed noise: a computational night-camera finishing impression.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'mobile', 'night', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'mobile',
     'night',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'gamma': 1.17, 'contrast': 1.11, 'knee': 0.84}),
     ('dvnr', {'strength': 0.2, 'wax': 0.08}),
     ('sharpen', {'amount': 0.28}),
     ('codec_era', {'codec': 'h264', 'kbps': 4800, 'res': 'native', 'crf': 21})],
    audio=[('a_agc', {'amount': 0.35}), ('a_codec_aac', {'kbps': 128})],
))

register_preset(Preset(
    id="atlas-daylight-creator-studio-2022",
    name="Daylight Creator Studio",
    family="modern",
    era="2022",
    tagline="Clean whites, bright color",
    desc="Clean whites, bright color: a well-lit creator-studio distribution finish.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'vlog', 'studio', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'vlog',
     'studio',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.1, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.03, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.1, 'vibrance': 0.08}),
     ('cinema_finish', {'local_contrast': 0.23, 'highlight_desat': 0.42}),
     ('codec_era', {'codec': 'h264', 'kbps': 6000, 'res': 'native', 'crf': 19})],
    audio=[('a_compressor', {'ratio': 2.6, 'threshold_db': -22}), ('a_codec_aac', {'kbps': 192})],
))

register_preset(Preset(
    id="atlas-luxury-product-soft-light-2024",
    name="Luxury Product Soft Light",
    family="modern",
    era="2024",
    tagline="Pearl highlights, dense color",
    desc="Pearl highlights, dense color: a soft-lit contemporary product-film finish.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'commercial', 'product', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'commercial',
     'product',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.06, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.04, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.07, 'vibrance': 0.08}),
     ('cinema_finish', {'highlight_desat': 0.9, 'density': 0.54, 'local_contrast': -0.1}),
     ('optics', {'diffusion': 0.08}),
     ('halation', {'strength': 0.17, 'tint': 'warm_white', 'threshold': 0.75})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.7, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-fashion-silver-chrome-2025",
    name="Fashion Silver Chrome",
    family="modern",
    era="2025",
    tagline="Silver contrast, restrained color",
    desc="Silver contrast, restrained color: a hard-edged fashion-film finishing pass.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'fashion', 'commercial', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'fashion',
     'commercial',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.3, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.07, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.83, 'vibrance': 0.08}),
     ('cinema_finish', {'silver': 0.55, 'density': 0.35, 'local_contrast': 0.4})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.2, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-sports-campaign-sunlit-2026",
    name="Sports Campaign Sunlit",
    family="modern",
    era="2026",
    tagline="Bold color, crisp mids",
    desc="Bold color, crisp mids: a punchy daylight sports-commercial grade.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'sport', 'commercial', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'sport',
     'commercial',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.23, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': 0.11, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 1.16, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.47, 'highlight_desat': 0.55, 'local_contrast': 0.45}),
     ('sharpen', {'amount': 0.12})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2.8, 'attack_ms': 15, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.12, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-nightclub-phone-wide-color-2026",
    name="Nightclub Phone Wide Color",
    family="modern",
    era="2026",
    tagline="Purple spill, dense blue",
    desc="Purple spill, dense blue: a contemporary nightlife phone-camera interpretation.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'mobile', 'concert', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'mobile',
     'concert',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.18, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.045, 'shadow_tint': 'magenta', 'shadow_amt': 0.65}),
     ('saturation', {'amount': 1.2, 'vibrance': 0.08}),
     ('cinema_finish', {'density': 0.35, 'highlight_desat': 0.2}),
     ('dvnr', {'strength': 0.14, 'wax': 0.08}),
     ('codec_era', {'codec': 'h264', 'kbps': 3200, 'res': 'native', 'crf': 23})],
    audio=[('a_compressor', {'ratio': 4, 'attack_ms': 5}), ('a_codec_aac', {'kbps': 128})],
))

register_preset(Preset(
    id="atlas-architecture-daylight-neutral-2026",
    name="Architecture Daylight Neutral",
    family="modern",
    era="2026",
    tagline="Neutral stone, clean glass",
    desc="Neutral stone, clean glass: a precise architecture-film grade with broad local detail.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'architecture', 'documentary', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'architecture',
     'documentary',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('tone', {'contrast': 1.08, 'lift': 0.005, 'knee': 0.87}),
     ('balance', {'warmth': -0.025, 'shadow_tint': 'none', 'shadow_amt': 0}),
     ('saturation', {'amount': 0.88, 'vibrance': 0.08}),
     ('cinema_finish', {'local_contrast': 0.38, 'radius': 0.06, 'highlight_desat': 0.78}),
     ('sharpen', {'amount': 0.18, 'radius': 1.4})],
    audio=[('a_bandlimit', {'low_hz': 90, 'high_hz': 17000}),
     ('a_compressor',
      {'threshold_db': -18, 'ratio': 1.2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-digital-silver-portrait-2026",
    name="Digital Silver Portrait",
    family="modern",
    era="2026",
    tagline="Soft silver, clear eyes",
    desc="Soft silver, clear eyes: a modern monochrome portrait finish with gentle diffusion.",
    tags=('modern', 'atlas', 'digital', 'contemporary', 'portrait', 'bw', 'digital-cinema'),
    keywords=('digital',
     'contemporary',
     'portrait',
     'bw',
     'digital-cinema',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.16, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.055, 'size': 0.85, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.075, 'tint': 'neutral', 'threshold': 0.78}),
     ('cinema_finish', {'local_contrast': 0.2}),
     ('optics', {'soft_focus': 0.045})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 1.5, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.92, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
