"""Expanded aesthetic atlas: hometape.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-first-home-deck-color-1977",
    name="First Home Deck Color",
    family="vhs",
    era="1977",
    tagline="Muted chroma, warm video",
    desc="Muted chroma, warm video: a carefully kept first-generation home recording.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('balance', {'warmth': 0.12}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.6,
       'chroma_delay': 1.1,
       'luma_noise': 0.09,
       'chroma_noise': 0.063,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.08,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'vhs_linear',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-kitchen-tungsten-betatape-1980",
    name="Kitchen Tungsten Betatape",
    family="vhs",
    era="1980",
    tagline="Amber rooms, clear luma",
    desc="Amber rooms, clear luma: a compact home-video recording under warm lamps.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('balance', {'warmth': 0.32}),
     ('tone', {'contrast': 1.08, 'knee': 0.83}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.95,
       'chroma_delay': 0.2,
       'luma_noise': 0.07,
       'chroma_noise': 0.049,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.04,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'betamax_linear',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-six-hour-family-archive-1984",
    name="Six Hour Family Archive",
    family="vhs",
    era="1984",
    tagline="Soft chroma, gentle hiss",
    desc="Soft chroma, gentle hiss: a long-play home archive without tracking storms.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=520,
    upscale="soft",
    video=[('saturation', {'amount': 0.83}),
     ('vhs',
      {'mode': 'ep',
       'luma_bw': 2.5,
       'chroma_bw': 0.25,
       'chroma_delay': 1.8,
       'luma_noise': 0.11,
       'chroma_noise': 0.077,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.14,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'vhs_linear',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -58,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-holiday-shoulder-camcorder-1987",
    name="Holiday Shoulder Camcorder",
    family="vhs",
    era="1987",
    tagline="Hot red, broad daylight",
    desc="Hot red, broad daylight: shoulder-camera color with mild exposure hunting.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('exposure_auto', {'target': 0.44, 'wb_amount': 0.2, 'agc_gain_noise': 0.12}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.45,
       'chroma_delay': 0.9,
       'luma_noise': 0.13,
       'chroma_noise': 0.091,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.07,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'vhs_linear',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-compact-camcorder-indoor-eight-1990",
    name="Compact Camcorder Indoor Eight",
    family="vhs",
    era="1990",
    tagline="Cool shadows, thin detail",
    desc="Cool shadows, thin detail: a compact video camera record under mixed interior light.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('balance', {'warmth': -0.1, 'tint': -0.08}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.65,
       'chroma_delay': 0.3,
       'luma_noise': 0.16,
       'chroma_noise': 0.112,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.03,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'video8_afm',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-clean-hi-fi-home-dub-1992",
    name="Clean Hi Fi Home Dub",
    family="vhs",
    era="1992",
    tagline="Steady video, wide sound",
    desc="Steady video, wide sound: a clean home-deck dub with little transport instability.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('tone', {'contrast': 1.06, 'knee': 0.9}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.85,
       'chroma_delay': 0.2,
       'luma_noise': 0.045,
       'chroma_noise': 0.032,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.015,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'vhs_hifi',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-concert-balcony-hi-eight-1995",
    name="Concert Balcony Hi Eight",
    family="vhs",
    era="1995",
    tagline="Bright lamps, shadow hiss",
    desc="Bright lamps, shadow hiss: a balcony camcorder recording with dense stage color.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('saturation', {'amount': 1.21}),
     ('tone', {'contrast': 1.24, 'knee': 0.77}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 0.9,
       'chroma_delay': 0.15,
       'luma_noise': 0.17,
       'chroma_noise': 0.119,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.04,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'hi8_afm',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-school-play-extended-tape-1997",
    name="School Play Extended Tape",
    family="vhs",
    era="1997",
    tagline="Warm stage, soft color edges",
    desc="Warm stage, soft color edges: an extended-play recording with gentle low-light noise.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=520,
    upscale="soft",
    video=[('balance', {'warmth': 0.25}),
     ('sharpen', {'amount': -0.12}),
     ('vhs',
      {'mode': 'ep',
       'luma_bw': 2.5,
       'chroma_bw': 0.3,
       'chroma_delay': 2.2,
       'luma_noise': 0.09,
       'chroma_noise': 0.063,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.1,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'vhs_linear',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -58,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-wedding-svhs-master-1999",
    name="Wedding SVHS Master",
    family="vhs",
    era="1999",
    tagline="Clear whites, fine tape texture",
    desc="Clear whites, fine tape texture: a carefully exposed high-band home master.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('tone', {'contrast': 1.04, 'knee': 0.81}),
     ('sharpen', {'amount': 0.13}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 1.16,
       'chroma_delay': 0.1,
       'luma_noise': 0.035,
       'chroma_noise': 0.025,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.01,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'vhs_hifi',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))

register_preset(Preset(
    id="atlas-last-analog-travel-camera-2002",
    name="Last Analog Travel Camera",
    family="vhs",
    era="2002",
    tagline="Natural color, mild softness",
    desc="Natural color, mild softness: a late analog travel recording with clean stereo sound.",
    tags=('vhs', 'atlas', 'videotape', 'home-video', 'camcorder', 'archival'),
    keywords=('videotape',
     'home-video',
     'camcorder',
     'archival',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=560,
    upscale="soft",
    video=[('balance', {'warmth': 0.04}),
     ('saturation', {'amount': 0.96}),
     ('vhs',
      {'mode': 'sp',
       'luma_bw': 3.8,
       'chroma_bw': 1,
       'chroma_delay': 0.25,
       'luma_noise': 0.065,
       'chroma_noise': 0.045,
       'head_switch': 0.12,
       'dropouts': 0,
       'tracking_error': 0,
       'flagging': 0.02,
       'time_base_error': 0.025,
       'jitter_v': 0.015,
       'dropout_burst': 0})],
    audio=[('a_video_tape_audio',
      {'format': 'hi8_afm',
       'tracking': 0.04,
       'dropout_rate': 0,
       'noise_db': -65,
       'head_switch_db': -70})],
))
