"""Expanded aesthetic atlas: art90.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-midnight-metro-reversal-1981",
    name="Midnight Metro Reversal",
    family="arthouse",
    era="1981",
    tagline="Cyan lamps, crimson accents",
    desc="Cyan lamps, crimson accents: a dense urban-night reversal impression.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.28, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.18}),
     ('saturation', {'amount': 1.11}),
     ('grain', {'amount': 0.35, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'teal', 'shadow_amt': 0.48})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -64}),
     ('a_channel_aging',
      {'width': 1.05, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-kitchen-sink-color-sixteen-1983",
    name="Kitchen Sink Color Sixteen",
    family="arthouse",
    era="1983",
    tagline="Drab green, coarse grain",
    desc="Drab green, coarse grain: available-light domestic realism on small negative.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=640,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.12, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.06}),
     ('saturation', {'amount': 0.64}),
     ('grain',
      {'amount': 0.43, 'size': 1.4, 'chroma_grain': 0.08, 'layers': 'color_neg', 'stock': 'doc_16'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'corner_softness': 0.12})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -61}),
     ('a_channel_aging',
      {'width': 0.7, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-cobalt-velvet-art-film-1985",
    name="Cobalt Velvet Art Film",
    family="arthouse",
    era="1985",
    tagline="Cobalt shadows, warm faces",
    desc="Cobalt shadows, warm faces: a polished nocturnal art-film positive.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodak_80s', 'strength': 0.65}),
     ('tone', {'contrast': 1.22, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.14}),
     ('saturation', {'amount': 1.03}),
     ('grain', {'amount': 0.18, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'blue', 'shadow_amt': 0.86})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -66}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-sun-bleached-road-diary-1987",
    name="Sun Bleached Road Diary",
    family="arthouse",
    era="1987",
    tagline="Washed yellow, soft black",
    desc="Washed yellow, soft black: an arid roadside diary with restrained highlight color.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 0.94, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.26}),
     ('saturation', {'amount': 0.68}),
     ('grain', {'amount': 0.26, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'highlight_desat': 0.82}),
     ('optics', {'veiling_flare': 0.13})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 0.85, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-black-velvet-silver-feature-1989",
    name="Black Velvet Silver Feature",
    family="arthouse",
    era="1989",
    tagline="Deep silver, clean contours",
    desc="Deep silver, clean contours: sculptural monochrome on a fine theatrical print.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'none', 'strength': 0.65}),
     ('tone', {'contrast': 1.42, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0}),
     ('saturation', {'amount': 0}),
     ('grain', {'amount': 0.2, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('mono', {'tint': 'neutral'}),
     ('print_char', {'acutance': 0.44})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 8200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 8200, 'cell_noise': -65, 'flutter': 0.06, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-lavender-neon-dupe-1991",
    name="Lavender Neon Dupe",
    family="arthouse",
    era="1991",
    tagline="Lavender spill, soft color edges",
    desc="Lavender spill, soft color edges: an optically duplicated night-scene print.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.13, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.1}),
     ('saturation', {'amount': 0.95}),
     ('grain', {'amount': 0.28, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'tint': 0.25}),
     ('optical_composite', {'registration': 0.55, 'softness': 0.2})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-peripheral-city-negative-1993",
    name="Peripheral City Negative",
    family="arthouse",
    era="1993",
    tagline="Green-gray mids, dry texture",
    desc="Green-gray mids, dry texture: a distant city-drama print with quiet wide sound.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'orwo_east', 'strength': 0.65}),
     ('tone', {'contrast': 1.07, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.12}),
     ('saturation', {'amount': 0.56}),
     ('grain', {'amount': 0.24, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.33})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -68}),
     ('a_channel_aging',
      {'width': 1.15, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-rose-motel-reversal-1995",
    name="Rose Motel Reversal",
    family="arthouse",
    era="1995",
    tagline="Rose highlights, cyan shade",
    desc="Rose highlights, cyan shade: saturated roadside color with reversal density.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.3, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.05}),
     ('saturation', {'amount': 1.22}),
     ('grain', {'amount': 0.29, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'high_tint': 'pink', 'high_amt': 0.6, 'shadow_tint': 'teal', 'shadow_amt': 0.4})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 0.9, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-handheld-manifesto-video-1998",
    name="Handheld Manifesto Video",
    family="arthouse",
    era="1998",
    tagline="Thin whites, sharp video edges",
    desc="Thin whites, sharp video edges: an unpolished digital art-film carrier.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'none', 'strength': 0.65}),
     ('tone', {'contrast': 1.18, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.04}),
     ('saturation', {'amount': 0.8}),
     ('grain', {'amount': 0.08, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('chroma_dv', {'ratio': '4:2:0', 'edge_sharpen': 0.55}),
     ('sharpen', {'amount': 0.3})],
    audio=[('a_compressor',
      {'threshold_db': -18, 'ratio': 2, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.85, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))

register_preset(Preset(
    id="atlas-millennium-silver-diary-1999",
    name="Millennium Silver Diary",
    family="arthouse",
    era="1999",
    tagline="Soft silver, fine grain",
    desc="Soft silver, fine grain: a restrained monochrome diary with open mids.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'urban', 'independent'),
    keywords=('arthouse',
     'drama',
     'film',
     'urban',
     'independent',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'none', 'strength': 0.65}),
     ('tone', {'contrast': 0.95, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0}),
     ('saturation', {'amount': 0}),
     ('grain', {'amount': 0.32, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('mono', {'tint': 'silver'}),
     ('optics', {'diffusion': 0.16})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -68}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))
