"""Expanded aesthetic atlas: worldarchive.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-mediterranean-harbor-reversal-1959",
    name="Mediterranean Harbor Reversal",
    family="world",
    era="1959",
    tagline="Blue water, ochre walls",
    desc="Blue water, ochre walls: a daylight harbor documentary on warm reversal.",
    tags=('world', 'atlas', 'film', 'archival', 'italy', 'travel'),
    keywords=('film',
     'archival',
     'italy',
     'travel',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.16, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.13}),
     ('saturation', {'amount': 1.19}),
     ('grain', {'amount': 0.24, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.23})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 0.6, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-andean-field-sixteen-1964",
    name="Andean Field Sixteen",
    family="world",
    era="1964",
    tagline="Cool sky, red earth",
    desc="Cool sky, red earth: a highland documentary print with dry color grain.",
    tags=('world', 'atlas', 'film', 'archival', 'latin-america', 'documentary'),
    keywords=('film',
     'archival',
     'latin-america',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.2, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.13}),
     ('saturation', {'amount': 0.94}),
     ('grain', {'amount': 0.37, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('print_char', {'acutance': 0.26})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6200, 'cell_noise': -55, 'flutter': 0.19, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-west-african-news-positive-1968",
    name="West African News Positive",
    family="world",
    era="1968",
    tagline="Warm skin, dense green",
    desc="Warm skin, dense green: a touring color-news positive with restrained dye fade.",
    tags=('world', 'atlas', 'film', 'archival', 'africa', 'news'),
    keywords=('film',
     'archival',
     'africa',
     'news',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.18, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.2}),
     ('saturation', {'amount': 0.94}),
     ('grain', {'amount': 0.34, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('fade', {'profile': 'cyan_loss', 'amount': 0.1})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6500, 'cell_noise': -54, 'flutter': 0.2, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-baltic-winter-reversal-1972",
    name="Baltic Winter Reversal",
    family="world",
    era="1972",
    tagline="Cold gray, muted red",
    desc="Cold gray, muted red: a winter documentary carrier with subdued dye separation.",
    tags=('world', 'atlas', 'film', 'archival', 'eastern-europe', 'documentary'),
    keywords=('film',
     'archival',
     'eastern-europe',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'orwo_east', 'strength': 0.65}),
     ('tone', {'contrast': 1.06, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.25}),
     ('saturation', {'amount': 0.62}),
     ('grain', {'amount': 0.32, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'blue', 'shadow_amt': 0.32})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 0.35, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-pacific-community-film-1975",
    name="Pacific Community Film",
    family="world",
    era="1975",
    tagline="Sea green, amber light",
    desc="Sea green, amber light: a community-film color negative with gentle print texture.",
    tags=('world', 'atlas', 'film', 'archival', 'pacific', 'documentary'),
    keywords=('film',
     'archival',
     'pacific',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.02, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.15}),
     ('saturation', {'amount': 1.07}),
     ('grain', {'amount': 0.31, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'veiling_flare': 0.08})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -60}),
     ('a_channel_aging',
      {'width': 0.6, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-south-asian-dance-print-1979",
    name="South Asian Dance Print",
    family="world",
    era="1979",
    tagline="Scarlet dyes, gold highlights",
    desc="Scarlet dyes, gold highlights: a color performance print with rich subtractive primaries.",
    tags=('world', 'atlas', 'film', 'archival', 'india', 'musical'),
    keywords=('film',
     'archival',
     'india',
     'musical',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodak_80s', 'strength': 0.65}),
     ('tone', {'contrast': 1.25, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.22}),
     ('saturation', {'amount': 1.28}),
     ('grain', {'amount': 0.29, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.68})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7900}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7900, 'cell_noise': -59, 'flutter': 0.16, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-nordic-public-archive-scan-1985",
    name="Nordic Public Archive Scan",
    family="world",
    era="1985",
    tagline="Pale color, fine grain",
    desc="Pale color, fine grain: a stable public-archive scan of a restrained documentary print.",
    tags=('world', 'atlas', 'film', 'archival', 'sweden', 'documentary'),
    keywords=('film',
     'archival',
     'sweden',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.03, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.15}),
     ('saturation', {'amount': 0.73}),
     ('grain', {'amount': 0.18, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('telecine_scan', {'pin_stability': 'pin_registered', 'hop_px': 0.2})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -69}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-hong-kong-festival-interpositive-1992",
    name="Hong Kong Festival Interpositive",
    family="world",
    era="1992",
    tagline="Cyan night, red light",
    desc="Cyan night, red light: a theatrical festival-copy impression before final release contrast.",
    tags=('world', 'atlas', 'film', 'archival', 'hong-kong', 'drama'),
    keywords=('film',
     'archival',
     'hong-kong',
     'drama',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.13, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.08}),
     ('saturation', {'amount': 1.08}),
     ('grain', {'amount': 0.23, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'teal', 'shadow_amt': 0.6})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -64}),
     ('a_channel_aging',
      {'width': 1.1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-iranian-daylight-location-print-1997",
    name="Iranian Daylight Location Print",
    family="world",
    era="1997",
    tagline="Dust green, clean skin",
    desc="Dust green, clean skin: a restrained daylight-location color print.",
    tags=('world', 'atlas', 'film', 'archival', 'iran', 'drama'),
    keywords=('film',
     'archival',
     'iran',
     'drama',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.01, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.1}),
     ('saturation', {'amount': 0.74}),
     ('grain', {'amount': 0.19, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'highlight_desat': 0.66})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -66}),
     ('a_channel_aging',
      {'width': 0.85, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-australasian-oral-history-scan-2010",
    name="Australasian Oral History Scan",
    family="world",
    era="2010",
    tagline="Natural color, gentle silver",
    desc="Natural color, gentle silver: a clean documentary scan with close, steady speech.",
    tags=('world', 'atlas', 'film', 'archival', 'australia', 'documentary'),
    keywords=('film',
     'archival',
     'australia',
     'documentary',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'vision_90s', 'strength': 0.65}),
     ('tone', {'contrast': 1.07, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.03}),
     ('saturation', {'amount': 0.91}),
     ('grain', {'amount': 0.14, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.18, 'local_contrast': 0.16})],
    audio=[('a_bandlimit', {'low_hz': 65, 'high_hz': 18000}),
     ('a_compressor',
      {'threshold_db': -18, 'ratio': 1.8, 'attack_ms': 24, 'release_ms': 240, 'makeup_db': 0}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -80, 'skew_us': 0, 'phase_wander': 0})],
))
