"""Expanded aesthetic atlas: art70.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-desert-modernist-bleach-1970",
    name="Desert Modernist Bleach",
    family="arthouse",
    era="1970",
    tagline="Parchment sand, silver shadows",
    desc="Parchment sand, silver shadows: a sun-struck art-film print with restrained color.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'modernist', 'desert'),
    keywords=('arthouse',
     'drama',
     'film',
     'modernist',
     'desert',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.22, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.23}),
     ('saturation', {'amount': 0.7}),
     ('grain', {'amount': 0.26, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.45, 'highlight_desat': 0.6})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.7, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-urban-alienation-green-1971",
    name="Urban Alienation Green",
    family="arthouse",
    era="1971",
    tagline="Green glass, cool gray",
    desc="Green glass, cool gray: an austere city-film negative with dense shadow color.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'italy', 'modernist'),
    keywords=('arthouse',
     'drama',
     'film',
     'italy',
     'modernist',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.12, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.13}),
     ('saturation', {'amount': 0.63}),
     ('grain', {'amount': 0.22, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'tint': -0.2, 'shadow_tint': 'green', 'shadow_amt': 0.55})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -62}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-harvest-pastoral-negative-1972",
    name="Harvest Pastoral Negative",
    family="arthouse",
    era="1972",
    tagline="Ochre mids, soft green",
    desc="Ochre mids, soft green: rural lyricism with open highlights and gently worn dye.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'pastoral', 'rural'),
    keywords=('arthouse',
     'drama',
     'film',
     'pastoral',
     'rural',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 0.97, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.24}),
     ('saturation', {'amount': 0.92}),
     ('grain', {'amount': 0.3, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'diffusion': 0.17}),
     ('flicker', {'amount': 0.09, 'character': 'slow_drift', 'color_flicker': 0.04})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -60}),
     ('a_channel_aging',
      {'width': 0.9, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-concrete-essay-sixteen-1973",
    name="Concrete Essay Sixteen",
    family="arthouse",
    era="1973",
    tagline="Dry grain, pale concrete",
    desc="Dry grain, pale concrete: an essay-film reduction with little highlight bloom.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'essay-film', 'documentary'),
    keywords=('arthouse',
     'drama',
     'film',
     'essay-film',
     'documentary',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.16, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.38, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.025, 'tint': 'neutral', 'threshold': 0.78}),
     ('print_char', {'acutance': 0.38})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -58}),
     ('a_channel_aging',
      {'width': 0.15, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-jewel-box-chamber-color-1974",
    name="Jewel Box Chamber Color",
    family="arthouse",
    era="1974",
    tagline="Jewel red, dark velvet",
    desc="Jewel red, dark velvet: a chamber-drama dye print with rich subtractive color.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'chamber-drama', 'theater'),
    keywords=('arthouse',
     'drama',
     'film',
     'chamber-drama',
     'theater',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'technicolor3', 'strength': 0.65}),
     ('tone', {'contrast': 1.28, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.08}),
     ('saturation', {'amount': 1.26}),
     ('grain', {'amount': 0.16, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.72})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7600}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7600, 'cell_noise': -62, 'flutter': 0.07, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-rain-forest-dream-negative-1975",
    name="Rain Forest Dream Negative",
    family="arthouse",
    era="1975",
    tagline="Humid green, veiled light",
    desc="Humid green, veiled light: dreamlike location photography with lifted deep foliage.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'dream', 'surreal', 'forest'),
    keywords=('arthouse',
     'drama',
     'film',
     'dream',
     'surreal',
     'forest',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'orwo_east', 'strength': 0.65}),
     ('tone', {'contrast': 0.92, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.05}),
     ('saturation', {'amount': 0.89}),
     ('grain', {'amount': 0.31, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'veiling_flare': 0.22}),
     ('balance', {'tint': -0.12})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-factory-district-color-diary-1976",
    name="Factory District Color Diary",
    family="arthouse",
    era="1976",
    tagline="Brick red, lead sky",
    desc="Brick red, lead sky: an industrial-city diary in restrained color negative.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'industrial', 'documentary', 'essay-film'),
    keywords=('arthouse',
     'drama',
     'film',
     'industrial',
     'documentary',
     'essay-film',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.2, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.04}),
     ('saturation', {'amount': 0.67}),
     ('grain', {'amount': 0.35, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.25, 'local_contrast': 0.24})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -61}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-candlelit-chamber-positive-1977",
    name="Candlelit Chamber Positive",
    family="arthouse",
    era="1977",
    tagline="Amber light, velvet shadows",
    desc="Amber light, velvet shadows: warm studio interiors with soft optical diffusion.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'period', 'chamber-drama'),
    keywords=('arthouse',
     'drama',
     'film',
     'period',
     'chamber-drama',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'kodak_80s', 'strength': 0.65}),
     ('tone', {'contrast': 1.08, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.32}),
     ('saturation', {'amount': 0.87}),
     ('grain', {'amount': 0.21, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('optics', {'soft_focus': 0.19, 'bloom_mids': 0.12})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 8000}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 8000, 'cell_noise': -64, 'flutter': 0.04, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-winter-road-slow-print-1978",
    name="Winter Road Slow Print",
    family="arthouse",
    era="1978",
    tagline="Blue snow, gray skin",
    desc="Blue snow, gray skin: patient winter naturalism with cool lifted shadows.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'slow-cinema', 'winter'),
    keywords=('arthouse',
     'drama',
     'film',
     'slow-cinema',
     'winter',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.02, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.3}),
     ('saturation', {'amount': 0.58}),
     ('grain', {'amount': 0.28, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'blue', 'shadow_amt': 0.28})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -65}),
     ('a_channel_aging',
      {'width': 0.65, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-copper-surrealist-positive-1979",
    name="Copper Surrealist Positive",
    family="arthouse",
    era="1979",
    tagline="Copper haze, red-brown blacks",
    desc="Copper haze, red-brown blacks: a deliberately feverish color-print interpretation.",
    tags=('arthouse', 'atlas', 'drama', 'film', 'surreal', 'experimental'),
    keywords=('arthouse',
     'drama',
     'film',
     'surreal',
     'experimental',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_70s', 'strength': 0.65}),
     ('tone', {'contrast': 1.31, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.29}),
     ('saturation', {'amount': 1.07}),
     ('grain', {'amount': 0.33, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'brown', 'shadow_amt': 0.73}),
     ('optical_composite', {'layer_haze': 0.13, 'softness': 0.08})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -59}),
     ('a_channel_aging',
      {'width': 0.8, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))
