"""Expanded aesthetic atlas: silent.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-moonlit-cyan-reel-1917",
    name="Moonlit Cyan Reel",
    family="film",
    era="1917",
    tagline="Cyan night bath, silver grain",
    desc="Cyan night bath, silver grain: a nocturnal silent-drama print.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'cyanotype', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.24, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.26, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'warmth': -0.28})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-firelight-vermilion-reel-1919",
    name="Firelight Vermilion Reel",
    family="film",
    era="1919",
    tagline="Red-orange bath, hard blacks",
    desc="Red-orange bath, hard blacks: a fire-scene tint impression.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'blue_sensitive', 'tint': 'nitrate_warm', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.42, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.38, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'warmth': 0.55, 'tint': 0.1})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-lavender-interior-reel-1921",
    name="Lavender Interior Reel",
    family="film",
    era="1921",
    tagline="Lavender shadows, pearl whites",
    desc="Lavender shadows, pearl whites: a delicate interior-scene tint.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.99, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.19, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'shadow_tint': 'magenta', 'shadow_amt': 0.7, 'high_tint': 'pink', 'high_amt': 0.32})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-viridian-garden-reel-1922",
    name="Viridian Garden Reel",
    family="film",
    era="1922",
    tagline="Green dye, warm silver",
    desc="Green dye, warm silver: a garden-sequence color-bath impression.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'neutral', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.13, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.33, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'tint': -0.38, 'shadow_tint': 'green', 'shadow_amt': 0.5})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-ochre-desert-reel-1923",
    name="Ochre Desert Reel",
    family="film",
    era="1923",
    tagline="Ochre haze, dense midtones",
    desc="Ochre haze, dense midtones: a tinted expedition-release print.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'blue_sensitive', 'tint': 'sepia', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.3, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.44, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('fade', {'profile': 'nitrate_amber', 'amount': 0.16})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-pearl-portrait-positive-1924",
    name="Pearl Portrait Positive",
    family="film",
    era="1924",
    tagline="Pearl highlights, velvet grain",
    desc="Pearl highlights, velvet grain: a studio close-up diffusion pass.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 0.94, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.22, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'soft_focus': 0.22, 'bloom_mids': 0.13}),
     ('vignette', {'amount': 0.3, 'radius': 0.9, 'softness': 0.75})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-silver-sulfide-duplicate-1925",
    name="Silver Sulfide Duplicate",
    family="film",
    era="1925",
    tagline="Brown silver, crisp contours",
    desc="Brown silver, crisp contours: a toned duplicate-print interpretation.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'sepia', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.45, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.41, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('print_char', {'acutance': 0.48, 'contrast_buildup': 1})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-blue-hour-melodrama-1926",
    name="Blue Hour Melodrama",
    family="film",
    era="1926",
    tagline="Blue shadows, neutral faces",
    desc="Blue shadows, neutral faces: a split-toned silent chamber drama.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'neutral', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.17, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.27, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'shadow_tint': 'blue', 'shadow_amt': 0.9, 'high_tint': 'cream', 'high_amt': 0.25})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-amber-dupe-release-1927",
    name="Amber Dupe Release",
    family="film",
    era="1927",
    tagline="Honey fog, coarse print grain",
    desc="Honey fog, coarse print grain: a surviving tinted distribution copy.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'orthochromatic', 'tint': 'nitrate_warm', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.33, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.51, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('fade', {'profile': 'nitrate_amber', 'amount': 0.24}),
     ('sharpen', {'amount': -0.2})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-silver-festival-scan-1928",
    name="Silver Festival Scan",
    family="film",
    era="1928",
    tagline="Clean whites, lively fine grain",
    desc="Clean whites, lively fine grain: a modern neutral scan of a silent-era print.",
    tags=('film', 'atlas', 'silent', 'drama', 'tint', 'toned', '35mm', 'archive'),
    keywords=('silent',
     'drama',
     'tint',
     'toned',
     '35mm',
     'archive',
     'carrier',
     'transfer',
     'preservation',
     'recording',
     'legacy',
     'texture'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.09, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.18, 'size': 1.25, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.09, 'tint': 'neutral', 'threshold': 0.78}),
     ('cinema_finish', {'highlight_desat': 0.65, 'local_contrast': 0.28})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5500}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5500, 'cell_noise': -64, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))
