"""Expanded aesthetic atlas: postwar.

Creative carrier and finishing interpretations; supplied picture and sound remain the source.
Source framing is inherited. No fabricated captions, dialogue or music.
See docs/expanded-atlas.md for scope, design references and verification.
"""

from ..engine.presets import Preset, register_preset

register_preset(Preset(
    id="atlas-postwar-apartment-silver-1947",
    name="Postwar Apartment Silver",
    family="arthouse",
    era="1947",
    tagline="Gray daylight, open grain",
    desc="Gray daylight, open grain: intimate rooms held in a gentle monochrome print.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'italy', 'neorealism'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'italy',
     'neorealism',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.02, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.34, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.11, 'tint': 'neutral', 'threshold': 0.78}),
     ('optics', {'corner_softness': 0.16})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 5700}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 5700, 'cell_noise': -55, 'flutter': 0.15, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-waterfront-poetic-negative-1950",
    name="Waterfront Poetic Negative",
    family="arthouse",
    era="1950",
    tagline="Pearl fog, dark wet stone",
    desc="Pearl fog, dark wet stone: soft halation over restrained silver detail.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'france', 'poetic-realism'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'france',
     'poetic-realism',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.19, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.21, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.33, 'tint': 'neutral', 'threshold': 0.78}),
     ('cinema_finish', {'local_contrast': -0.28})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 6700}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 6700, 'cell_noise': -60, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-summer-chamber-pastel-1953",
    name="Summer Chamber Pastel",
    family="arthouse",
    era="1953",
    tagline="Cream whites, quiet greens",
    desc="Cream whites, quiet greens: a restrained color chamber film with soft dye density.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'sweden', 'chamber-drama'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'sweden',
     'chamber-drama',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'agfa_60s', 'strength': 0.65}),
     ('tone', {'contrast': 0.98, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.12}),
     ('saturation', {'amount': 0.78}),
     ('grain', {'amount': 0.21, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'density': 0.22})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7200}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7200, 'cell_noise': -62, 'flutter': 0.08, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-modernist-concrete-positive-1958",
    name="Modernist Concrete Positive",
    family="arthouse",
    era="1958",
    tagline="Hard gray planes, dry silver",
    desc="Hard gray planes, dry silver: architecture-led art cinema with direct monochrome contrast.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'italy', 'modernist'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'italy',
     'modernist',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.48, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.17, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.02, 'tint': 'neutral', 'threshold': 0.78}),
     ('print_char', {'acutance': 0.6})],
    audio=[('a_analog_dub',
      {'format': 'reel_15ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -66}),
     ('a_channel_aging',
      {'width': 0.1, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-left-bank-essay-reversal-1960",
    name="Left Bank Essay Reversal",
    family="arthouse",
    era="1960",
    tagline="Cool dyes, bright edges",
    desc="Cool dyes, bright edges: an essay-film reversal print with crisp documentary texture.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'france', 'essay-film'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'france',
     'essay-film',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'ektachrome', 'strength': 0.65}),
     ('tone', {'contrast': 1.23, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.14}),
     ('saturation', {'amount': 0.84}),
     ('grain', {'amount': 0.3, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('sharpen', {'amount': 0.18})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -60}),
     ('a_channel_aging',
      {'width': 0.2, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-new-wave-push-negative-1962",
    name="New Wave Push Negative",
    family="arthouse",
    era="1962",
    tagline="Pushed silver, hot windows",
    desc="Pushed silver, hot windows: available-light monochrome with energetic grain.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'france', 'new-wave'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'france',
     'new-wave',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.32, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.48, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.19, 'tint': 'neutral', 'threshold': 0.78}),
     ('grain', {'amount': 0.12, 'size': 0.85, 'stock': 'push_process', 'chroma_grain': 0})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 2,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -58}),
     ('a_channel_aging',
      {'width': 0.15, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-minimal-domestic-color-1963",
    name="Minimal Domestic Color",
    family="arthouse",
    era="1963",
    tagline="Ochre rooms, softened green",
    desc="Ochre rooms, softened green: a modest domestic color print with precise midtones.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'japan'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'japan',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'eastman_60s', 'strength': 0.65}),
     ('tone', {'contrast': 1.08, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': 0.16}),
     ('saturation', {'amount': 0.74}),
     ('grain', {'amount': 0.19, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('balance', {'shadow_tint': 'brown', 'shadow_amt': 0.3})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7400}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7400, 'cell_noise': -61, 'flutter': 0.1, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-winter-island-silver-1965",
    name="Winter Island Silver",
    family="arthouse",
    era="1965",
    tagline="Cold whites, stern blacks",
    desc="Cold whites, stern blacks: a fine-grain monochrome chamber-study positive.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'sweden', 'chamber-drama'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'sweden',
     'chamber-drama',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.36, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.23, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.08, 'tint': 'neutral', 'threshold': 0.78}),
     ('balance', {'warmth': -0.15}),
     ('cinema_finish', {'local_contrast': 0.18})],
    audio=[('a_bandlimit', {'low_hz': 80, 'high_hz': 7900}),
     ('a_mono', {'amount': 1}),
     ('a_optical_track',
      {'high_hz': 7900, 'cell_noise': -65, 'flutter': 0.05, 'academy_rolloff': 'none', 'drive': 1.12})],
))

register_preset(Preset(
    id="atlas-coffeehouse-sixteen-print-1967",
    name="Coffeehouse Sixteen Print",
    family="arthouse",
    era="1967",
    tagline="Soft black, restless grain",
    desc="Soft black, restless grain: a small-format urban art-film print with close location sound.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'czechoslovakia', 'new-wave'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'czechoslovakia',
     'new-wave',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('mono', {'response': 'panchromatic', 'tint': 'silver', 'tint_amt': 0.25}),
     ('tone', {'contrast': 1.08, 'lift': 0.02, 'knee': 0.88}),
     ('grain', {'amount': 0.42, 'size': 1.2, 'chroma_grain': 0, 'stock': 'fine_35'}),
     ('halation', {'strength': 0.17, 'tint': 'neutral', 'threshold': 0.78}),
     ('sharpen', {'amount': -0.15})],
    audio=[('a_analog_dub',
      {'format': 'reel_375ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -60}),
     ('a_channel_aging',
      {'width': 0.35, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))

register_preset(Preset(
    id="atlas-desaturated-political-negative-1969",
    name="Desaturated Political Negative",
    family="arthouse",
    era="1969",
    tagline="Olive mids, bright gray sky",
    desc="Olive mids, bright gray sky: political art cinema on restrained color negative.",
    tags=('arthouse', 'atlas', 'drama', '35mm', 'political', 'new-wave'),
    keywords=('arthouse',
     'drama',
     '35mm',
     'political',
     'new-wave',
     'finishing',
     'color-grading',
     'stereo',
     'cinematography',
     'independent',
     'film-look'),
    proc_height=None,
    upscale="auto",
    video=[('stock', {'profile': 'orwo_east', 'strength': 0.65}),
     ('tone', {'contrast': 1.2, 'lift': 0.008, 'knee': 0.86}),
     ('balance', {'warmth': -0.04}),
     ('saturation', {'amount': 0.55}),
     ('grain', {'amount': 0.32, 'size': 1.2, 'chroma_grain': 0.08, 'layers': 'color_neg'}),
     ('halation', {'strength': 0.12, 'threshold': 0.8, 'tint': 'red_orange'}),
     ('cinema_finish', {'silver': 0.28})],
    audio=[('a_analog_dub',
      {'format': 'reel_75ips',
       'generations': 1,
       'alignment': 0.08,
       'compression': 0.18,
       'hiss_db': -63}),
     ('a_channel_aging',
      {'width': 0.5, 'imbalance_db': 0, 'crosstalk_db': -60, 'skew_us': 0, 'phase_wander': 0.03})],
))
