"""Audiovisual presets, third collection: theatrical capture and release formats."""

from ..engine.presets import Preset, Variant, register_preset


register_preset(Preset(
    id="vitaphone-palace-1929",
    name="Vitaphone Palace Run",
    family="film",
    era="1929",
    desc="A late nitrate feature synchronized to a 16-inch sound disc: square panchromatic frames, projection flicker, lacquer swish, tube-stage sag and auditorium reflections.",
    tagline="Nitrate frame, lacquer swish, palace room",
    tags=("20s", "early-sound", "sound-on-disc", "nitrate"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.18}),
        ("tone", {"contrast": 1.2, "lift": 0.055, "knee": 0.76, "gamma": 0.94}),
        ("optics", {"soft_focus": 0.2, "corner_softness": 0.26, "focus_drift": 0.08}),
        ("grain", {"amount": 0.5, "size": 2.0, "chroma_grain": 0.0,
                   "stock": "print_dupe", "layers": "mono", "mottle": 0.18}),
        ("halation", {"strength": 0.24, "tint": "neutral", "threshold": 0.72}),
        ("print_char", {"contrast_buildup": 2, "dmax_breath": 0.32, "acutance": 0.15}),
        ("cadence", {"pattern": "projector_flutter", "field_blend": 0.08}),
        ("flicker", {"amount": 0.3, "character": "projector", "spatial": 0.25}),
        ("gate_weave", {"amount": 1.65, "splice_bump": 1.1}),
        ("dust", {"density": 0.65, "hairs": 0.32}),
        ("scratches", {"count": 2, "transient_rate": 0.8}),
        ("vignette", {"amount": 0.38, "softness": 0.58, "roundness": 0.86}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.008}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_transcription_disc", {"band": 0.92, "swish": 0.72, "crackle": 3.8, "wear": 0.38}),
        ("a_vinyl_wow", {"rpm": "33", "depth_cents": 6.0}),
        ("a_tube_amp", {"drive": 2.0, "sag": 0.48, "microphonics": 0.08, "hum_db": -52.0}),
        ("a_compressor", {"threshold_db": -23.0, "ratio": 4.5, "attack_ms": 5.0, "release_ms": 220.0}),
        ("a_room", {"mode": "chamber", "size": 1.5, "decay_s": 1.25, "mix": 0.22,
                    "damp": 0.74, "predelay_ms": 18.0}),
    ],
    variants=[
        Variant("premiere-disc", "Premiere Disc", "The synchronized disc is fresh and the nitrate print has only crossed the projector once.",
                video={"dust.density": 0.18, "scratches.count": 0, "gate_weave.amount": 0.7},
                audio={"a_transcription_disc.wear": 0.08, "a_transcription_disc.crackle": 1.0,
                       "a_transcription_disc.swish": 0.38}),
        Variant("roadshow-sync", "Roadshow Sync", "A touring disc and print pair with more surface wear, gate motion and room around the screen.",
                video={"gate_weave.amount": 2.8, "dust.density": 0.9, "flicker.amount": 0.44},
                audio={"a_transcription_disc.wear": 0.82, "a_transcription_disc.crackle": 9.0,
                       "a_room.mix": 0.34}),
    ],
))


register_preset(Preset(
    id="precode-studio-print-1932",
    name="Pre-Code Studio Print",
    family="film",
    era="1932",
    desc="An early sound-stage release print: silver-rich panchromatic faces, soft Cooke edges, hot optical density, narrow variable-area mono and fine nitrate wear.",
    tagline="Silver faces, Cooke edge, hot optical mono",
    tags=("30s", "early-sound", "nitrate", "studio"),
    proc_height=700,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.24}),
        ("tone", {"contrast": 1.32, "lift": 0.035, "knee": 0.72, "pivot": 0.43}),
        ("optics", {"soft_focus": 0.16, "diffusion": 0.12, "corner_softness": 0.32,
                    "veiling_flare": 0.12}),
        ("grain", {"amount": 0.46, "size": 1.8, "chroma_grain": 0.0,
                   "stock": "fine_35", "layers": "mono", "shadow_boost": 0.12}),
        ("halation", {"strength": 0.34, "tint": "neutral", "threshold": 0.68}),
        ("print_char", {"contrast_buildup": 2, "dmax_breath": 0.28, "acutance": 0.2}),
        ("flicker", {"amount": 0.16, "character": "projector", "spatial": 0.16}),
        ("gate_weave", {"amount": 0.95, "splice_bump": 0.75}),
        ("dust", {"density": 0.42, "hairs": 0.18}),
        ("scratches", {"count": 1, "transient_rate": 0.45}),
        ("vignette", {"amount": 0.3, "softness": 0.7}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "ribbon_1938", "amount": 0.5,
                              "proximity": 0.18, "overload": 0.18, "self_noise_db": -60.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 120.0, "high_hz": 5200.0,
                             "academy_rolloff": "newsreel_1930s", "cell_noise": -43.0,
                             "flutter": 0.62, "drive": 2.1}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 5.0, "attack_ms": 5.0, "release_ms": 190.0}),
        ("a_tube_amp", {"drive": 1.85, "sag": 0.42, "hum_db": -56.0}),
    ],
    variants=[
        Variant("camera-negative", "Camera-Negative Print", "A careful first-generation print with steadier density and a quieter track.",
                video={"grain.amount": 0.34, "print_char.dmax_breath": 0.12, "dust.density": 0.16},
                audio={"a_optical_track.cell_noise": -51.0, "a_optical_track.flutter": 0.25}),
        Variant("exchange-copy", "Exchange Copy", "A busy theater copy with stronger density buildup, splices and optical grit.",
                video={"print_char.contrast_buildup": 3, "gate_weave.splice_bump": 1.8,
                       "dust.density": 0.78, "scratches.count": 4},
                audio={"a_optical_track.cell_noise": -37.0, "a_optical_track.drive": 2.8}),
    ],
))


register_preset(Preset(
    id="cinecolor-travel-print-1948",
    name="Cinecolor Travel Print",
    family="world",
    era="1948",
    desc="A two-color travel short on duplitized stock: brick reds, cyan-green skies, restrained yellow, soft emulsion registration and a compressed mono optical stripe.",
    tagline="Brick red, cyan-green sky, duplitized grain",
    tags=("40s", "cinecolor", "travel", "two-color"),
    proc_height=680,
    upscale="soft",
    video=[
        ("stock", {"profile": "technicolor2", "strength": 0.82}),
        ("balance", {"warmth": 0.18, "tint": -0.05, "shadow_tint": "teal", "shadow_amt": 0.16,
                     "high_tint": "pink", "high_amt": 0.12}),
        ("tone", {"contrast": 1.16, "lift": 0.035, "knee": 0.78}),
        ("saturation", {"amount": 1.12, "vibrance": 0.12}),
        ("optics", {"soft_focus": 0.12, "corner_softness": 0.14}),
        ("optical_composite", {"softness": 0.12, "matte_line": 0.0, "registration": 0.28,
                               "layer_haze": 0.06, "density_breath": 0.16}),
        ("grain", {"amount": 0.4, "size": 1.85, "chroma_grain": 0.12,
                   "stock": "fine_35", "layers": "print_from_neg", "mottle": 0.12}),
        ("halation", {"strength": 0.28, "tint": "orange", "threshold": 0.72}),
        ("fade", {"amount": 0.08, "profile": "eastman_pink", "bloom_whites": 0.08}),
        ("gate_weave", {"amount": 0.82, "splice_bump": 0.55}),
        ("flicker", {"amount": 0.11, "color_flicker": 0.09}),
        ("dust", {"density": 0.36, "hairs": 0.16}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 100.0, "high_hz": 6500.0,
                             "academy_rolloff": "feature_1940s", "cell_noise": -49.0,
                             "flutter": 0.42, "drive": 1.55}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.5, "attack_ms": 8.0, "release_ms": 240.0}),
        ("a_room", {"mode": "room", "size": 0.8, "decay_s": 0.4, "mix": 0.1}),
    ],
    variants=[
        Variant("fresh-dye", "Fresh Dye Print", "The red and cyan records sit almost together on a low-mileage print.",
                video={"optical_composite.registration": 0.08, "fade.amount": 0.0,
                       "dust.density": 0.12, "grain.amount": 0.32}),
        Variant("library-copy", "Traveling Library Copy", "Repeated projection leaves faded reds, wandering records and a noisier stripe.",
                video={"optical_composite.registration": 0.72, "fade.amount": 0.2,
                       "dust.density": 0.72, "gate_weave.amount": 1.35},
                audio={"a_optical_track.cell_noise": -42.0, "a_optical_track.flutter": 0.72}),
    ],
))


register_preset(Preset(
    id="anscochrome-pageant-1954",
    name="Anscochrome Pageant Reel",
    family="film",
    era="1954",
    desc="A community pageant on 16 mm reversal: cool blue highlights, russet skin, dense dye grain, soft projection focus and a crystal microphone copied to a narrow magnetic stripe.",
    tagline="Cool reversal dye, russet skin, stripe hiss",
    tags=("50s", "16mm", "reversal", "pageant"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.72}),
        ("balance", {"warmth": -0.06, "tint": 0.04, "shadow_tint": "blue", "shadow_amt": 0.18,
                     "high_tint": "cream", "high_amt": 0.1}),
        ("tone", {"contrast": 1.18, "lift": 0.028, "knee": 0.76}),
        ("saturation", {"amount": 1.04, "vibrance": 0.08}),
        ("optics", {"soft_focus": 0.18, "corner_softness": 0.24, "focus_drift": 0.12}),
        ("grain", {"amount": 0.48, "size": 1.95, "chroma_grain": 0.2,
                   "stock": "doc_16", "layers": "reversal", "mottle": 0.22}),
        ("halation", {"strength": 0.3, "tint": "orange", "threshold": 0.7}),
        ("fade", {"amount": 0.1, "profile": "cyan_loss", "bloom_whites": 0.08}),
        ("gate_weave", {"amount": 1.4, "splice_bump": 1.0}),
        ("flicker", {"amount": 0.18, "character": "projector", "color_flicker": 0.1}),
        ("dust", {"density": 0.54, "hairs": 0.25}),
        ("scratches", {"count": 1, "transient_rate": 0.6}),
        ("vignette", {"amount": 0.32, "softness": 0.66}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "crystal_1940", "amount": 0.66,
                              "overload": 0.28, "self_noise_db": -57.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_analog_dub", {"format": "reel_375ips", "generations": 2,
                          "alignment": 0.28, "compression": 0.34, "hiss_db": -53.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -49.0, "distance": 0.68}),
    ],
    variants=[
        Variant("indoor-stage", "Indoor Stage", "Tungsten lamps warm the reversal stock while the microphone moves closer to the platform.",
                video={"balance.warmth": 0.16, "tone.exposure": -0.12, "saturation.amount": 0.96},
                audio={"a_historical_mic.proximity": 0.38, "a_historical_mic.overload": 0.4}),
        Variant("projector-copy", "Projector Copy", "A faded duplicate with a louder machine, softer focus and more stripe hiss.",
                video={"fade.amount": 0.26, "optics.soft_focus": 0.34, "grain.amount": 0.58},
                audio={"a_analog_dub.generations": 4, "a_analog_dub.hiss_db": -47.0,
                       "a_projector.level_db": -40.0}),
    ],
))


register_preset(Preset(
    id="vistavision-release-1956",
    name="VistaVision Release Print",
    family="film",
    era="1956",
    desc="A fine-grain reduction from an eight-perf horizontal negative: clean 1.85 detail, restrained Eastman color, gentle printer halation and broad mono theater sound.",
    tagline="Fine reduction detail, restrained Eastman",
    tags=("50s", "vistavision", "35mm", "reduction-print"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.58}),
        ("tone", {"contrast": 1.14, "lift": 0.018, "knee": 0.84, "pivot": 0.44}),
        ("balance", {"warmth": 0.08, "shadow_tint": "blue", "shadow_amt": 0.1,
                     "high_tint": "cream", "high_amt": 0.08}),
        ("saturation", {"amount": 1.02, "vibrance": 0.08}),
        ("optics", {"soft_focus": 0.055, "diffusion": 0.08, "veiling_flare": 0.1}),
        ("grain", {"amount": 0.24, "size": 1.55, "chroma_grain": 0.11,
                   "stock": "fine_35", "layers": "print_from_neg", "mottle": 0.07}),
        ("halation", {"strength": 0.22, "tint": "red_orange", "threshold": 0.76}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.12, "acutance": 0.34}),
        ("gate_weave", {"amount": 0.46, "splice_bump": 0.32}),
        ("flicker", {"amount": 0.05, "spatial": 0.06}),
        ("dust", {"density": 0.16, "hairs": 0.07}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 0.85}),
        ("a_analog_dub", {"format": "reel_15ips", "generations": 2,
                          "alignment": 0.08, "compression": 0.25, "hiss_db": -64.0}),
        ("a_optical_track", {"low_hz": 70.0, "high_hz": 8200.0,
                             "academy_rolloff": "none", "cell_noise": -58.0,
                             "flutter": 0.18, "drive": 1.25}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 2.4, "attack_ms": 12.0, "release_ms": 260.0}),
    ],
    variants=[
        Variant("dye-transfer", "Dye-Transfer Show Print", "Denser blacks, cleaner color separation and a steadier premium print.",
                video={"stock.strength": 0.78, "tone.contrast": 1.2, "grain.amount": 0.2,
                       "gate_weave.amount": 0.28}),
        Variant("general-release", "General Release", "A conventional reduction with softer edges, more dust and a louder optical floor.",
                video={"optics.soft_focus": 0.14, "grain.amount": 0.34, "dust.density": 0.42},
                audio={"a_optical_track.cell_noise": -49.0, "a_optical_track.flutter": 0.4}),
    ],
))


register_preset(Preset(
    id="todd-ao-roadshow-1958",
    name="Todd-AO Roadshow Print",
    family="exhibition",
    era="1958",
    desc="A 70 mm roadshow element: smooth large-format grain, open amber highlights, deep cyan-blue shadows, wide magnetic stereo and distant booth machinery.",
    tagline="Large-format smoothness, wide mag stereo",
    tags=("50s", "70mm", "roadshow", "magnetic-stereo"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.7}),
        ("tone", {"contrast": 1.13, "lift": 0.014, "knee": 0.86, "pivot": 0.45}),
        ("balance", {"warmth": 0.12, "shadow_tint": "teal", "shadow_amt": 0.14,
                     "high_tint": "yellow", "high_amt": 0.12}),
        ("saturation", {"amount": 1.06, "vibrance": 0.12}),
        ("optics", {"soft_focus": 0.035, "diffusion": 0.06, "veiling_flare": 0.08}),
        ("grain", {"amount": 0.19, "size": 1.35, "chroma_grain": 0.08,
                   "stock": "fine_35", "layers": "print_from_neg", "mottle": 0.05}),
        ("halation", {"strength": 0.18, "tint": "red_orange", "threshold": 0.8}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.09, "acutance": 0.3}),
        ("gate_weave", {"amount": 0.25, "splice_bump": 0.2}),
        ("dust", {"density": 0.12, "hairs": 0.04}),
        ("projection", {"shutter_flicker": 0.04, "keystone": 0.0, "ambient_lift": 0.02,
                        "screen_gain_falloff": 0.12}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.003}),
    ],
    audio=[
        ("a_analog_dub", {"format": "reel_15ips", "generations": 1,
                          "alignment": 0.03, "compression": 0.18, "hiss_db": -70.0}),
        ("a_channel_aging", {"width": 1.18, "imbalance_db": -0.15, "crosstalk_db": -52.0,
                             "skew_us": 12.0, "phase_wander": 0.03, "mono_bass_hz": 70.0}),
        ("a_compressor", {"threshold_db": -15.0, "ratio": 1.8, "attack_ms": 18.0, "release_ms": 320.0}),
        ("a_room", {"mode": "chamber", "size": 1.8, "decay_s": 1.1, "mix": 0.1,
                    "damp": 0.68, "predelay_ms": 24.0}),
        ("a_projector", {"machine": "proj_35mm_booth", "level_db": -57.0, "distance": 0.92}),
    ],
    variants=[
        Variant("front-row", "Front Row", "The screen fills more of the eye while the magnetic channels and room move closer.",
                video={"framing.zoom": 0.06, "projection.screen_gain_falloff": 0.2},
                audio={"a_channel_aging.width": 1.32, "a_room.mix": 0.17,
                       "a_projector.level_db": -60.0}),
        Variant("road-worn", "Road-Worn Print", "The roadshow element returns with dust, gate movement and a lightly misaligned magnetic rack.",
                video={"grain.amount": 0.29, "gate_weave.amount": 0.75, "dust.density": 0.38},
                audio={"a_analog_dub.generations": 3, "a_analog_dub.alignment": 0.24,
                       "a_channel_aging.skew_us": 85.0}),
    ],
))


register_preset(Preset(
    id="hammer-eastmancolor-1960",
    name="British Eastmancolor Print",
    family="world",
    era="1960",
    desc="A British studio Eastmancolor release: warm complexions, dense crimson dye, cool stone shadows, soft diffusion, red halation and a compact mono optical track.",
    tagline="Crimson dye, cool stone, diffused print",
    tags=("60s", "british", "eastmancolor", "studio"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.88}),
        ("tone", {"contrast": 1.25, "lift": 0.012, "knee": 0.78, "pivot": 0.42}),
        ("balance", {"warmth": 0.1, "shadow_tint": "blue", "shadow_amt": 0.22,
                     "high_tint": "pink", "high_amt": 0.1}),
        ("saturation", {"amount": 1.1, "vibrance": 0.14}),
        ("optics", {"soft_focus": 0.11, "diffusion": 0.18, "corner_softness": 0.1,
                    "veiling_flare": 0.16}),
        ("grain", {"amount": 0.34, "size": 1.75, "chroma_grain": 0.15,
                   "stock": "fine_35", "layers": "print_from_neg", "mottle": 0.1}),
        ("halation", {"strength": 0.42, "tint": "red_orange", "threshold": 0.67}),
        ("print_char", {"contrast_buildup": 2, "dmax_breath": 0.18, "acutance": 0.18}),
        ("fade", {"amount": 0.09, "profile": "eastman_pink", "bloom_whites": 0.1}),
        ("gate_weave", {"amount": 0.72, "splice_bump": 0.45}),
        ("flicker", {"amount": 0.07, "color_flicker": 0.05}),
        ("dust", {"density": 0.28, "hairs": 0.12}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 90.0, "high_hz": 7200.0, "academy_rolloff": "none",
                             "cell_noise": -52.0, "flutter": 0.32, "drive": 1.5}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 3.2, "attack_ms": 8.0, "release_ms": 240.0}),
        ("a_room", {"mode": "chamber", "size": 1.0, "decay_s": 0.65, "mix": 0.12,
                    "damp": 0.72}),
    ],
    variants=[
        Variant("tungsten-stage", "Tungsten Stage", "Hard studio lamps push the amber highlights and red halation while the soundstage opens slightly.",
                video={"balance.warmth": 0.23, "halation.strength": 0.52, "optics.diffusion": 0.24},
                audio={"a_room.mix": 0.18, "a_room.decay_s": 0.9}),
        Variant("television-print", "Television Print", "A softer 4:3 element with faded dye, extra dust and reduced optical bandwidth.",
                video={"framing.aspect": "source", "fade.amount": 0.22, "optics.soft_focus": 0.22,
                       "dust.density": 0.55},
                audio={"a_optical_track.high_hz": 5800.0, "a_optical_track.cell_noise": -46.0}),
    ],
))


register_preset(Preset(
    id="techniscope-blowup-1966",
    name="Techniscope Blowup",
    family="film",
    era="1966",
    desc="A two-perf Techniscope negative enlarged to anamorphic release: coarse horizontal grain, printer softness, saturated Eastman dye and a narrow mono optical stripe.",
    tagline="Two-perf grain, printer soft, scope stripe",
    tags=("60s", "techniscope", "scope", "blowup"),
    proc_height=720,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.78}),
        ("tone", {"contrast": 1.19, "lift": 0.022, "knee": 0.8, "pivot": 0.43}),
        ("balance", {"warmth": 0.12, "shadow_tint": "blue", "shadow_amt": 0.14}),
        ("saturation", {"amount": 1.08, "vibrance": 0.12}),
        ("optics", {"soft_focus": 0.15, "corner_softness": 0.16, "focus_drift": 0.1,
                    "veiling_flare": 0.14}),
        ("optical_composite", {"softness": 0.22, "matte_line": 0.04, "registration": 0.08,
                               "layer_haze": 0.08, "density_breath": 0.2}),
        ("grain", {"amount": 0.5, "size": 2.15, "chroma_grain": 0.2,
                   "stock": "print_dupe", "layers": "print_from_neg", "shadow_boost": 0.2}),
        ("halation", {"strength": 0.35, "tint": "red_orange", "threshold": 0.68}),
        ("print_char", {"contrast_buildup": 2, "dmax_breath": 0.22, "acutance": 0.16}),
        ("fade", {"amount": 0.12, "profile": "eastman_pink", "bloom_whites": 0.12}),
        ("gate_weave", {"amount": 0.92, "splice_bump": 0.6}),
        ("dust", {"density": 0.34, "hairs": 0.14}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 90.0, "high_hz": 7000.0, "academy_rolloff": "none",
                             "cell_noise": -50.0, "flutter": 0.4, "drive": 1.55}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.5, "attack_ms": 7.0, "release_ms": 210.0}),
    ],
    variants=[
        Variant("camera-original", "Camera Original Scan", "The two-perf frame before the anamorphic printer generation, with cleaner dye and tighter grain.",
                video={"optical_composite.softness": 0.05, "grain.amount": 0.36,
                       "fade.amount": 0.0, "framing.aspect": "source"}),
        Variant("drive-in-copy", "Drive-In Copy", "A road-worn scope print with more grain, faded dye and a louder optical cell.",
                video={"grain.amount": 0.62, "fade.amount": 0.28, "gate_weave.amount": 1.45,
                       "dust.density": 0.72},
                audio={"a_optical_track.cell_noise": -42.0, "a_optical_track.flutter": 0.72}),
    ],
))


register_preset(Preset(
    id="supermarionation-print-1966",
    name="Supermarionation Print",
    family="world",
    era="1966",
    desc="A bright British miniature-stage print: dense primary dyes, crisp model highlights, shallow-scale haze, controlled optical joins and clean compressed mono sound.",
    tagline="Primary dye, model haze, tidy optical joins",
    tags=("60s", "british", "miniature", "studio"),
    proc_height=700,
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.82}),
        ("tone", {"contrast": 1.2, "lift": 0.018, "knee": 0.82, "pivot": 0.43}),
        ("balance", {"warmth": 0.09, "shadow_tint": "blue", "shadow_amt": 0.12,
                     "high_tint": "yellow", "high_amt": 0.14}),
        ("saturation", {"amount": 1.22, "vibrance": 0.18}),
        ("optics", {"soft_focus": 0.07, "diffusion": 0.1, "corner_softness": 0.08,
                    "focus_drift": 0.06}),
        ("optical_composite", {"softness": 0.12, "matte_line": 0.18, "registration": 0.12,
                               "layer_haze": 0.18, "density_breath": 0.13}),
        ("grain", {"amount": 0.3, "size": 1.65, "chroma_grain": 0.14,
                   "stock": "fine_35", "layers": "print_from_neg", "mottle": 0.08}),
        ("halation", {"strength": 0.27, "tint": "orange", "threshold": 0.74}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.14, "acutance": 0.3}),
        ("gate_weave", {"amount": 0.52, "splice_bump": 0.35}),
        ("flicker", {"amount": 0.05, "color_flicker": 0.04}),
        ("dust", {"density": 0.2, "hairs": 0.08}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 80.0, "high_hz": 7600.0, "academy_rolloff": "none",
                             "cell_noise": -56.0, "flutter": 0.2, "drive": 1.35}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 4.0, "attack_ms": 5.0, "release_ms": 180.0}),
        ("a_room", {"mode": "plate1960", "size": 0.72, "decay_s": 0.55, "mix": 0.1,
                    "damp": 0.35}),
    ],
    variants=[
        Variant("effects-reel", "Effects Reel", "Optical generations soften the model edges and show brighter matte seams through the haze.",
                video={"optical_composite.softness": 0.4, "optical_composite.matte_line": 0.55,
                       "optical_composite.registration": 0.48, "optical_composite.layer_haze": 0.32}),
        Variant("studio-master", "Studio Master", "The protected element has finer grain, clean joins and almost no gate movement.",
                video={"grain.amount": 0.22, "optical_composite.matte_line": 0.04,
                       "optical_composite.registration": 0.02, "gate_weave.amount": 0.24},
                audio={"a_optical_track.cell_noise": -62.0}),
    ],
))


register_preset(Preset(
    id="psychedelic-optical-1968",
    name="Psychedelic Optical Print",
    family="stylized",
    era="1968",
    desc="A multi-generation optical color print: dense dye, flared highlights, drifting RGB registration, printer haze, color flicker and saturated quarter-inch stereo.",
    tagline="Dense dye, RGB drift, flared optical dupes",
    tags=("60s", "optical", "color", "experimental"),
    proc_height=680,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.9}),
        ("tone", {"contrast": 1.25, "lift": 0.025, "knee": 0.72, "pivot": 0.4}),
        ("balance", {"warmth": 0.16, "tint": 0.12, "shadow_tint": "blue", "shadow_amt": 0.24,
                     "high_tint": "pink", "high_amt": 0.2}),
        ("saturation", {"amount": 1.34, "vibrance": 0.26}),
        ("optics", {"soft_focus": 0.2, "diffusion": 0.28, "chromatic_aberration": 2.2,
                    "veiling_flare": 0.42, "aperture_ghost": 0.3}),
        ("optical_composite", {"softness": 0.38, "matte_line": 0.16, "registration": 1.4,
                               "layer_haze": 0.32, "density_breath": 0.48}),
        ("grain", {"amount": 0.46, "size": 2.0, "chroma_grain": 0.24,
                   "stock": "print_dupe", "layers": "print_from_neg", "mottle": 0.18}),
        ("halation", {"strength": 0.5, "tint": "red_orange", "threshold": 0.62}),
        ("print_char", {"contrast_buildup": 3, "dmax_breath": 0.4, "acutance": 0.08}),
        ("fade", {"amount": 0.16, "profile": "eastman_pink", "bloom_whites": 0.2}),
        ("flicker", {"amount": 0.2, "color_flicker": 0.45, "spatial": 0.28}),
        ("gate_weave", {"amount": 1.0, "splice_bump": 0.7}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_analog_dub", {"format": "reel_75ips", "generations": 3,
                          "alignment": 0.32, "compression": 0.56, "hiss_db": -55.0}),
        ("a_tape_sat", {"drive": 3.2, "bump_db": 2.2, "hf_loss": 0.28}),
        ("a_channel_aging", {"width": 1.18, "imbalance_db": -0.8, "crosstalk_db": -30.0,
                             "skew_us": 130.0, "phase_wander": 0.38, "mono_bass_hz": 160.0}),
        ("a_room", {"mode": "plate1960", "size": 0.8, "decay_s": 1.0, "mix": 0.24,
                    "damp": 0.22}),
    ],
    variants=[
        Variant("fourth-generation", "Fourth Generation", "Another printer pass pushes the registration apart and packs more haze into the blacks.",
                video={"optical_composite.softness": 0.62, "optical_composite.registration": 2.4,
                       "optical_composite.layer_haze": 0.55, "print_char.contrast_buildup": 4},
                audio={"a_analog_dub.generations": 5, "a_analog_dub.alignment": 0.62}),
        Variant("clean-separation", "Clean Separation", "The color records nearly meet, the dye relaxes and the quarter-inch channels sit closer together.",
                video={"optical_composite.registration": 0.35, "saturation.amount": 1.16,
                       "flicker.color_flicker": 0.12, "optics.chromatic_aberration": 0.7},
                audio={"a_channel_aging.width": 0.92, "a_channel_aging.skew_us": 35.0}),
    ],
))


register_preset(Preset(
    id="panavision-disaster-print-1974",
    name="Panavision Disaster Print",
    family="film",
    era="1974",
    desc="A 35 mm anamorphic release print: warm Eastman practicals, steel-blue smoke shadows, wide flare, dense answer-print contrast and broad magnetic theater sound.",
    tagline="Warm practicals, smoke, anamorphic flare",
    tags=("70s", "panavision", "scope", "answer-print"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.88}),
        ("tone", {"contrast": 1.2, "lift": 0.018, "knee": 0.78, "pivot": 0.42}),
        ("balance", {"warmth": 0.12, "shadow_tint": "blue", "shadow_amt": 0.28,
                     "high_tint": "yellow", "high_amt": 0.14}),
        ("saturation", {"amount": 0.98, "vibrance": 0.12}),
        ("optics", {"soft_focus": 0.09, "diffusion": 0.1, "corner_softness": 0.12,
                    "veiling_flare": 0.32, "aperture_ghost": 0.2}),
        ("grain", {"amount": 0.38, "size": 1.9, "chroma_grain": 0.18,
                   "stock": "fine_35", "layers": "print_from_neg", "shadow_boost": 0.2}),
        ("halation", {"strength": 0.34, "tint": "red_orange", "threshold": 0.68}),
        ("print_char", {"contrast_buildup": 2, "dmax_breath": 0.22, "acutance": 0.24}),
        ("fade", {"amount": 0.11, "profile": "eastman_pink", "bloom_whites": 0.12}),
        ("gate_weave", {"amount": 0.62, "splice_bump": 0.45}),
        ("flicker", {"amount": 0.06, "spatial": 0.08}),
        ("dust", {"density": 0.28, "hairs": 0.12}),
        ("scratches", {"count": 1, "transient_rate": 0.35}),
        ("vignette", {"amount": 0.28, "softness": 0.72}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_analog_dub", {"format": "reel_15ips", "generations": 2,
                          "alignment": 0.11, "compression": 0.32, "hiss_db": -64.0}),
        ("a_channel_aging", {"width": 1.08, "imbalance_db": 0.2, "crosstalk_db": -44.0,
                             "skew_us": 38.0, "phase_wander": 0.1, "mono_bass_hz": 90.0}),
        ("a_compressor", {"threshold_db": -17.0, "ratio": 2.4, "attack_ms": 12.0, "release_ms": 280.0}),
        ("a_room", {"mode": "chamber", "size": 1.4, "decay_s": 0.85, "mix": 0.11,
                    "damp": 0.62}),
    ],
    variants=[
        Variant("smoke-stage", "Smoke Stage", "Denser haze lifts the blue shadows and lets the anamorphic flare wash farther across the print.",
                video={"tone.lift": 0.04, "balance.shadow_amt": 0.42,
                       "optics.veiling_flare": 0.5, "saturation.amount": 0.9}),
        Variant("reissue-print", "Reissue Print", "A later Eastman copy with pinker dye, softer detail and a narrower magnetic playback rack.",
                video={"fade.amount": 0.3, "optics.soft_focus": 0.2, "grain.amount": 0.48},
                audio={"a_analog_dub.generations": 4, "a_channel_aging.width": 0.78,
                       "a_analog_dub.hiss_db": -56.0}),
    ],
))


register_preset(Preset(
    id="slasher-answer-print-1980",
    name="Slasher Answer Print",
    family="film",
    era="1980",
    desc="An underexposed 35 mm answer print: warm tungsten pools, green-blue shadow grain, oily flare, dense blacks with detail and a compressed optical mono track.",
    tagline="Tungsten pools, green-blue grain, oily flare",
    tags=("80s", "35mm", "answer-print", "low-light"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "kodak_80s", "strength": 0.76}),
        ("tone", {"exposure": -0.25, "contrast": 1.22, "lift": 0.024, "knee": 0.8, "pivot": 0.4}),
        ("balance", {"warmth": 0.06, "shadow_tint": "green", "shadow_amt": 0.28,
                     "high_tint": "yellow", "high_amt": 0.2}),
        ("saturation", {"amount": 0.9, "vibrance": 0.1}),
        ("optics", {"soft_focus": 0.11, "diffusion": 0.08, "corner_softness": 0.14,
                    "focus_drift": 0.12, "veiling_flare": 0.28, "aperture_ghost": 0.16}),
        ("grain", {"amount": 0.48, "size": 2.0, "chroma_grain": 0.2,
                   "stock": "push_process", "layers": "color_neg", "shadow_boost": 0.42}),
        ("halation", {"strength": 0.36, "tint": "red_orange", "threshold": 0.66}),
        ("print_char", {"contrast_buildup": 2, "dmax_breath": 0.24, "acutance": 0.18}),
        ("fade", {"amount": 0.08, "profile": "eastman_pink", "bloom_whites": 0.08}),
        ("gate_weave", {"amount": 0.7, "splice_bump": 0.5}),
        ("flicker", {"amount": 0.06, "spatial": 0.08}),
        ("dust", {"density": 0.3, "hairs": 0.14}),
        ("scratches", {"count": 1, "transient_rate": 0.4}),
        ("vignette", {"amount": 0.42, "softness": 0.68}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 70.0, "high_hz": 8200.0, "academy_rolloff": "none",
                             "cell_noise": -55.0, "flutter": 0.24, "drive": 1.4}),
        ("a_compressor", {"threshold_db": -21.0, "ratio": 4.0, "attack_ms": 6.0, "release_ms": 220.0}),
        ("a_room", {"mode": "room", "size": 0.92, "decay_s": 0.48, "mix": 0.1}),
    ],
    variants=[
        Variant("night-exterior", "Night Exterior", "A further stop down with cooler shadow grain, harder practical halation and more focus drift.",
                video={"tone.exposure": -0.55, "balance.warmth": -0.06, "balance.shadow_amt": 0.46,
                       "grain.shadow_boost": 0.68, "optics.focus_drift": 0.28}),
        Variant("vault-print", "Vault Answer Print", "The protected print keeps cleaner blacks, steadier focus and a quieter optical cell.",
                video={"fade.amount": 0.0, "dust.density": 0.12, "grain.amount": 0.38,
                       "optics.focus_drift": 0.04, "gate_weave.amount": 0.35},
                audio={"a_optical_track.cell_noise": -62.0, "a_optical_track.flutter": 0.12}),
    ],
))
