"""Audiovisual presets for broadcast, videotape and early digital carriers."""

from ..engine.presets import Preset, Variant, register_preset


register_preset(Preset(
    id="quadruplex-variety-1958",
    name="Quadruplex Variety Master",
    family="broadcast",
    era="1958",
    desc="A live monochrome studio signal preserved on two-inch quadruplex tape: bright image-orthicon bloom, soft horizontal detail, interlace twitter, head-switch residue and a compressed control-room mono track.",
    tagline="Image-orthicon bloom on two-inch videotape",
    tags=("50s", "quadruplex", "live-tv", "black-and-white"),
    proc_height=560,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.12}),
        ("tone", {"contrast": 1.15, "lift": 0.045, "knee": 0.67, "gamma": 1.04}),
        ("optics", {"soft_focus": 0.15, "diffusion": 0.1, "veiling_flare": 0.16}),
        ("ntsc", {"strength": 0.46, "luma_bw": 3.1, "chroma_bw": 0.5,
                  "phase_noise": 0.0, "setup_level": 0.055, "sync_jitter": 0.12}),
        ("interlace", {"field_order": "tff", "combing": 0.58, "twitter": 0.38}),
        ("crt", {"scan_strength": 0.16, "bloom": 0.54, "beam_bloom": 0.42,
                 "glass_glow": 0.18, "curvature": 0.03}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_analog_dub", {"format": "reel_15ips", "generations": 1,
                          "alignment": 0.12, "compression": 0.38, "hiss_db": -57.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -57.0, "hum_db": -61.0, "comp": 0.62}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 4.4,
                          "attack_ms": 4.0, "release_ms": 260.0}),
        ("a_room", {"mode": "room", "size": 0.9, "decay_s": 0.45, "mix": 0.12}),
    ],
    variants=[
        Variant("rehearsal-feed", "Rehearsal Feed", "A cleaner studio line before the air-chain limiter and second tape pass.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.36, "interlace.twitter": 0.24},
                audio={"a_analog_dub.generations": 0, "a_compressor.ratio": 2.5,
                       "a_tv_sound.buzz_db": -68.0}),
        Variant("syndication-copy", "Syndication Copy", "A later tape copy with softer edges, louder head buzz and less stable sync.",
                video={"ntsc.luma_bw": 2.4, "ntsc.sync_jitter": 0.32, "crt.bloom": 0.7},
                audio={"a_analog_dub.generations": 3, "a_analog_dub.alignment": 0.42,
                       "a_tv_sound.buzz_db": -49.0}),
    ],
))


register_preset(Preset(
    id="regional-weather-1973",
    name="Regional Weather Studio",
    family="broadcast",
    era="1973",
    desc="An early-color local weather segment from plumbicon cameras and a composite microwave feed: raised setup, cyan shadow drift, warm faces, smeared map colors and dry booth mono.",
    tagline="Early-color tubes, raised setup, smeared maps",
    tags=("70s", "weather", "local-tv", "tube-camera"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.82}),
        ("tone", {"exposure": 0.1, "contrast": 1.04, "lift": 0.055, "knee": 0.7}),
        ("balance", {"warmth": 0.08, "shadow_tint": "teal", "shadow_amt": 0.2,
                     "high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 1.08, "vibrance": -0.06}),
        ("exposure_auto", {"target": 0.42, "lag": 1.3, "overshoot": 0.18,
                           "max_boost": 2.0, "agc_gain_noise": 0.22, "wb_amount": 0.24}),
        ("ntsc", {"strength": 0.8, "luma_bw": 3.4, "chroma_bw": 0.72,
                  "rainbow": 0.26, "dot_crawl": 0.3, "phase_error": -4.0,
                  "phase_noise": 2.2, "setup_level": 0.062, "diff_phase": 1.4}),
        ("interlace", {"combing": 0.52, "twitter": 0.3}),
        ("crt", {"bloom": 0.3, "beam_bloom": 0.24, "misconvergence": 0.45}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "lavalier_1972", "amount": 0.5,
                              "proximity": 0.1, "overload": 0.12, "self_noise_db": -60.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -54.0, "hum_db": -59.0, "comp": 0.5}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 4.0,
                          "attack_ms": 5.0, "release_ms": 220.0}),
        ("a_room", {"mode": "room", "size": 0.65, "decay_s": 0.28, "mix": 0.08}),
    ],
    variants=[
        Variant("microwave-hop", "Microwave Hop", "One more relay softens the chart lettering and adds phase shimmer to the color feed.",
                video={"ntsc.luma_bw": 2.7, "ntsc.phase_noise": 4.4,
                       "ntsc.rainbow": 0.44, "crt.misconvergence": 0.8},
                audio={"a_tv_sound.buzz_db": -48.0, "a_compressor.ratio": 5.5}),
        Variant("new-camera", "New Camera Chain", "A recently aligned tube chain holds cleaner whites, steadier hue and wider luma detail.",
                video={"ntsc.luma_bw": 4.1, "ntsc.phase_error": 0.0,
                       "ntsc.phase_noise": 0.8, "tone.lift": 0.03},
                audio={"a_tv_sound.buzz_db": -64.0, "a_historical_mic.amount": 0.3}),
    ],
))


register_preset(Preset(
    id="disco-variety-master-1979",
    name="Disco Variety Master",
    family="broadcast",
    era="1979",
    desc="A saturated late-1970s variety-stage master: tube-camera highlight trails, red flare, hot magenta lighting, soft composite edges and a wide reel-to-reel program track under broadcast limiting.",
    tagline="Hot tube color, red flare, wide tape master",
    tags=("70s", "variety", "studio", "quadruplex"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.9}),
        ("tone", {"exposure": 0.12, "contrast": 1.14, "lift": 0.03, "knee": 0.64}),
        ("balance", {"warmth": 0.13, "tint": 0.08, "shadow_tint": "blue", "shadow_amt": 0.14,
                     "high_tint": "pink", "high_amt": 0.22}),
        ("saturation", {"amount": 1.32, "vibrance": 0.18}),
        ("optics", {"soft_focus": 0.1, "diffusion": 0.18, "veiling_flare": 0.28,
                    "chromatic_aberration": 0.8}),
        ("phosphor_decay", {"decay": 0.46, "mode": "p22"}),
        ("ntsc", {"strength": 0.72, "luma_bw": 3.7, "chroma_bw": 0.86,
                  "rainbow": 0.3, "dot_crawl": 0.32, "phase_noise": 2.4,
                  "diff_phase": 2.6, "chroma_agc": 0.2, "setup_level": 0.05}),
        ("interlace", {"combing": 0.48, "twitter": 0.24}),
        ("crt", {"bloom": 0.38, "beam_bloom": 0.38, "misconvergence": 0.55}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_analog_dub", {"format": "reel_15ips", "generations": 1,
                          "alignment": 0.08, "compression": 0.32, "hiss_db": -65.0}),
        ("a_tape_sat", {"drive": 2.5, "bump_db": 1.8, "hf_loss": 0.16}),
        ("a_channel_aging", {"width": 0.92, "imbalance_db": -0.35,
                             "crosstalk_db": -43.0, "skew_us": 35.0,
                             "phase_wander": 0.1, "mono_bass_hz": 110.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.8,
                          "attack_ms": 8.0, "release_ms": 180.0}),
        ("a_room", {"mode": "plate1960", "size": 1.0, "decay_s": 0.75,
                    "damp": 0.48, "predelay_ms": 14.0, "mix": 0.1}),
    ],
    variants=[
        Variant("stage-lights", "Stage Lights", "The tube chain is driven harder by saturated lamps, with more trails, flare and program-track compression.",
                video={"saturation.amount": 1.5, "phosphor_decay.decay": 0.64,
                       "crt.beam_bloom": 0.55, "ntsc.diff_phase": 4.2},
                audio={"a_tape_sat.drive": 3.6, "a_compressor.ratio": 5.2}),
        Variant("studio-line", "Studio Line", "The direct control-room feed before the final composite hop, with tighter chroma and a quieter tape path.",
                video={"ntsc.strength": 0.38, "ntsc.chroma_bw": 1.25,
                       "crt.misconvergence": 0.2},
                audio={"a_analog_dub.generations": 0, "a_analog_dub.hiss_db": -74.0,
                       "a_channel_aging.phase_wander": 0.02}),
    ],
))


register_preset(Preset(
    id="cband-superstation-1982",
    name="C-Band Superstation Feed",
    family="transmission",
    era="1982",
    desc="A cable-headend recording of a C-band superstation: soft tube-origin color, satellite fade, co-channel ghosts, composite ringing, interlace and a narrowed mono subcarrier passed through two analog generations.",
    tagline="C-band fade, co-channel ghosts, cable mono",
    tags=("80s", "satellite", "cable", "c-band"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.74}),
        ("tone", {"contrast": 1.04, "lift": 0.045, "knee": 0.78}),
        ("saturation", {"amount": 0.94, "vibrance": -0.1}),
        ("rf_dx", {"fade_depth": 0.22, "fade_rate": 0.055, "noise_floor": 0.25,
                   "co_channel": 0.2, "co_delay_s": 1.6, "venetian": 0.1}),
        ("signal_rf", {"snow": 0.12, "sparkle": 2.4, "ghost_n": 2,
                       "ghost_px": 9.0, "ghost_alpha": 0.14, "hum_bar": 0.08,
                       "hum_speed": 0.1, "impulse_noise": 1.8, "weak_signal": 0.18}),
        ("ntsc", {"strength": 0.82, "luma_bw": 3.1, "chroma_bw": 0.65,
                  "rainbow": 0.38, "dot_crawl": 0.35, "phase_noise": 3.2,
                  "fringing": 2.1, "setup_level": 0.055}),
        ("interlace", {"combing": 0.54, "twitter": 0.24}),
        ("crt", {"bloom": 0.25, "beam_bloom": 0.2}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_analog_dub", {"format": "reel_75ips", "generations": 2,
                          "alignment": 0.3, "compression": 0.42, "hiss_db": -51.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -49.0, "hum_db": -58.0, "comp": 0.68}),
        ("a_compressor", {"threshold_db": -23.0, "ratio": 5.2,
                          "attack_ms": 3.0, "release_ms": 280.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.25}),
    ],
    variants=[
        Variant("clear-sky", "Clear-Sky Feed", "The downlink is well peaked, leaving only the composite decoder and mild headend generation loss.",
                video={"rf_dx.fade_depth": 0.04, "rf_dx.noise_floor": 0.08,
                       "signal_rf.snow": 0.03, "signal_rf.ghost_alpha": 0.05},
                audio={"a_analog_dub.generations": 1, "a_tv_sound.buzz_db": -60.0}),
        Variant("rain-fade", "Rain Fade", "A marginal downlink breathes in noise, loses color density and admits a second station underneath.",
                video={"rf_dx.fade_depth": 0.65, "rf_dx.noise_floor": 0.62,
                       "rf_dx.co_channel": 0.48, "signal_rf.weak_signal": 0.6},
                audio={"a_analog_dub.hiss_db": -43.0, "a_compressor.ratio": 7.0}),
    ],
))


register_preset(Preset(
    id="fitness-vhs-1984",
    name="Fitness VHS Master",
    family="vhs",
    era="1984",
    desc="A brightly lit fitness program on early VHS: hard tube-camera whites, warm studio skin, saturated wardrobe color, color-under smear, head-switch bending and an AGC-heavy linear mono track.",
    tagline="Hot studio whites on early linear-mono VHS",
    tags=("80s", "fitness", "vhs", "studio"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.84}),
        ("tone", {"exposure": 0.18, "contrast": 1.1, "lift": 0.03, "knee": 0.63}),
        ("balance", {"warmth": 0.14, "shadow_tint": "blue", "shadow_amt": 0.1,
                     "high_tint": "cream", "high_amt": 0.14}),
        ("saturation", {"amount": 1.25, "vibrance": 0.12}),
        ("ntsc", {"strength": 0.7, "luma_bw": 3.5, "chroma_bw": 0.72,
                  "rainbow": 0.28, "dot_crawl": 0.3, "phase_noise": 1.8,
                  "diff_phase": 2.2, "setup_level": 0.055}),
        ("vhs", {"mode": "sp", "luma_bw": 3.05, "chroma_bw": 0.36,
                 "chroma_delay": 1.8, "sharpen": 0.52, "luma_noise": 0.24,
                 "chroma_noise": 0.3, "head_switch": 0.58, "dropouts": 0.7,
                 "time_base_error": 0.24, "flagging": 0.15, "tracking_error": 0.04}),
        ("interlace", {"combing": 0.58, "twitter": 0.3}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_video_tape_audio", {"format": "vhs_linear", "tracking": 0.25,
                                "dropout_rate": 4.0, "noise_db": -47.0,
                                "head_switch_db": -57.0, "compander_error": 0.04}),
        ("a_agc", {"target_db": -17.0, "max_gain_db": 10.0,
                   "attack_ms": 18.0, "release_ms": 620.0, "amount": 0.72}),
        ("a_room", {"mode": "room", "size": 1.25, "decay_s": 0.5,
                    "damp": 0.64, "mix": 0.13}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.14}),
    ],
    variants=[
        Variant("studio-master", "Studio Master", "A first-pass SP cassette with cleaner tracking, tighter chroma and less linear-track noise.",
                video={"vhs.luma_noise": 0.12, "vhs.chroma_noise": 0.16,
                       "vhs.dropouts": 0.0, "vhs.time_base_error": 0.1},
                audio={"a_video_tape_audio.tracking": 0.08,
                       "a_video_tape_audio.noise_db": -53.0, "a_agc.amount": 0.45}),
        Variant("living-room-copy", "Living-Room Copy", "A copied cassette adds broad color smear, oxide losses and louder pumping between instructions.",
                video={"vhs.generation": 3, "vhs.chroma_bw": 0.22,
                       "vhs.dropouts": 2.8, "vhs.time_base_error": 0.48},
                audio={"a_video_tape_audio.tracking": 0.65,
                       "a_video_tape_audio.dropout_rate": 18.0, "a_agc.amount": 0.9}),
        Variant("source-clean", "Source-Clean Transfer",
                "Preserves the period carrier and color response while disabling momentary source loss or masking.",
                audio={"a_video_tape_audio.dropout_rate": 0.0}),
    ],
))


register_preset(Preset(
    id="home-shopping-cable-1987",
    name="Home Shopping Cable Studio",
    family="broadcast",
    era="1987",
    desc="A continuously lit cable shopping set from three tube cameras: lifted blacks, white-card bloom, glossy saturated products, composite crawl and a hard-limited mono line through a small television speaker.",
    tagline="White-card bloom, glossy color, hard cable mono",
    tags=("80s", "cable", "shopping", "studio"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.9}),
        ("tone", {"exposure": 0.22, "contrast": 1.04, "lift": 0.055, "knee": 0.6}),
        ("balance", {"warmth": 0.08, "high_tint": "cream", "high_amt": 0.14}),
        ("saturation", {"amount": 1.22, "vibrance": 0.16}),
        ("exposure_auto", {"target": 0.48, "lag": 0.8, "overshoot": 0.32,
                           "max_boost": 2.4, "agc_gain_noise": 0.28, "wb_amount": 0.32}),
        ("ntsc", {"strength": 0.78, "luma_bw": 3.7, "chroma_bw": 0.78,
                  "rainbow": 0.24, "dot_crawl": 0.46, "phase_noise": 1.6,
                  "fringing": 1.8, "diff_phase": 2.8, "setup_level": 0.06,
                  "sync_jitter": 0.12}),
        ("interlace", {"combing": 0.54, "twitter": 0.36}),
        ("crt", {"bloom": 0.42, "beam_bloom": 0.46, "misconvergence": 0.35}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "lavalier_1972", "amount": 0.42,
                              "proximity": 0.14, "overload": 0.24, "self_noise_db": -62.0}),
        ("a_compressor", {"threshold_db": -24.0, "ratio": 7.2,
                          "attack_ms": 2.0, "release_ms": 170.0, "knee_db": 3.0}),
        ("a_agc", {"target_db": -15.0, "max_gain_db": 8.0,
                   "attack_ms": 12.0, "release_ms": 450.0, "amount": 0.58}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -55.0, "hum_db": -62.0, "comp": 0.7}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.28}),
    ],
    variants=[
        Variant("jewelry-hour", "Jewelry Hour", "Specular products drive the pickup tubes and composite phase harder than the neutral set.",
                video={"tone.exposure": 0.32, "crt.beam_bloom": 0.65,
                       "ntsc.diff_phase": 4.8, "saturation.amount": 1.35},
                audio={"a_historical_mic.proximity": 0.25, "a_compressor.ratio": 9.0}),
        Variant("headend-copy", "Headend Copy", "A cable-system tape adds softer luma, more crawl and a boxed-down return audio path.",
                video={"ntsc.luma_bw": 2.8, "ntsc.dot_crawl": 0.68,
                       "ntsc.phase_noise": 3.4},
                audio={"a_tv_sound.buzz_db": -48.0, "a_speaker.strength": 0.55}),
    ],
))


register_preset(Preset(
    id="music-countdown-master-1987",
    name="Music-Channel Countdown Master",
    family="broadcast",
    era="1987",
    desc="An analog music-channel countdown compiled from mixed studio and tape sources: hot composite color, chroma delay, switcher-soft edges, mild master-tape noise and a dense stereo program path.",
    tagline="Mixed-source composite color and dense stereo tape",
    tags=("80s", "music-tv", "countdown", "master-tape"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.76}),
        ("tone", {"contrast": 1.12, "lift": 0.028, "knee": 0.7}),
        ("balance", {"warmth": 0.08, "tint": 0.05, "shadow_tint": "blue", "shadow_amt": 0.16,
                     "high_tint": "pink", "high_amt": 0.12}),
        ("saturation", {"amount": 1.3, "vibrance": 0.18}),
        ("optics", {"soft_focus": 0.07, "diffusion": 0.08, "chromatic_aberration": 0.7,
                    "veiling_flare": 0.12}),
        ("ntsc", {"strength": 0.72, "luma_bw": 3.6, "chroma_bw": 0.76,
                  "rainbow": 0.3, "dot_crawl": 0.4, "phase_noise": 2.1,
                  "fringing": 2.4, "diff_phase": 2.4, "chroma_agc": 0.18,
                  "setup_level": 0.05}),
        ("vhs", {"mode": "sp", "luma_bw": 4.2, "chroma_bw": 0.75,
                 "chroma_delay": 0.9, "sharpen": 0.35, "luma_noise": 0.12,
                 "chroma_noise": 0.14, "head_switch": 0.12, "dropouts": 0.2,
                 "time_base_error": 0.1, "flagging": 0.04, "tracking_error": 0.0}),
        ("interlace", {"combing": 0.48, "twitter": 0.25}),
        ("crt", {"bloom": 0.16, "beam_bloom": 0.12, "misconvergence": 0.14}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_video_tape_audio", {"format": "betahifi", "tracking": 0.12,
                                "dropout_rate": 1.0, "noise_db": -61.0,
                                "head_switch_db": -66.0, "compander_error": -0.08}),
        ("a_tape_sat", {"drive": 2.8, "bump_db": 1.4, "hf_loss": 0.12}),
        ("a_channel_aging", {"width": 1.06, "imbalance_db": 0.25,
                             "crosstalk_db": -39.0, "skew_us": 45.0,
                             "phase_wander": 0.12, "mono_bass_hz": 120.0}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 4.2,
                          "attack_ms": 7.0, "release_ms": 160.0}),
    ],
    variants=[
        Variant("live-studio", "Live Studio Feed", "The studio segment pushes tube highlights while keeping a first-generation stereo program line.",
                video={"crt.enabled": False, "tone.exposure": 0.18,
                       "ntsc.diff_phase": 3.8, "saturation.amount": 1.42},
                audio={"a_video_tape_audio.tracking": 0.04,
                       "a_video_tape_audio.dropout_rate": 0.0, "a_tape_sat.drive": 2.2}),
        Variant("archive-repeat", "Archive Repeat", "A later rebroadcast copy carries softer chroma, more time-base motion and a mistracking stereo carrier.",
                video={"vhs.generation": 3, "vhs.time_base_error": 0.32,
                       "ntsc.chroma_bw": 0.52, "ntsc.phase_noise": 3.8},
                audio={"a_video_tape_audio.tracking": 0.52,
                       "a_video_tape_audio.dropout_rate": 11.0,
                       "a_video_tape_audio.compander_error": -0.42}),
    ],
))


register_preset(Preset(
    id="corporate-umatic-1988",
    name="Corporate U-matic Presentation",
    family="vhs",
    era="1988",
    desc="An industrial presentation edited to three-quarter-inch U-matic: beige fluorescent whites, restrained tube color, component-like luma with composite edges and a dry linear mono narration track.",
    tagline="Fluorescent beige on an industrial U-matic edit",
    tags=("80s", "corporate", "umatic", "industrial"),
    proc_height=600,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.68}),
        ("tone", {"contrast": 1.02, "lift": 0.04, "knee": 0.78}),
        ("balance", {"warmth": 0.06, "tint": -0.035, "shadow_tint": "green", "shadow_amt": 0.1,
                     "high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 0.92, "vibrance": -0.1}),
        ("ntsc", {"strength": 0.56, "luma_bw": 4.4, "chroma_bw": 0.9,
                  "rainbow": 0.18, "dot_crawl": 0.25, "phase_noise": 1.2,
                  "fringing": 1.1, "setup_level": 0.055,
                  "comb_mode": "comb_1line"}),
        ("vhs", {"mode": "sp", "luma_bw": 4.5, "chroma_bw": 0.78,
                 "chroma_delay": 0.7, "sharpen": 0.42, "luma_noise": 0.14,
                 "chroma_noise": 0.15, "head_switch": 0.28, "dropouts": 0.35,
                 "time_base_error": 0.12, "flagging": 0.06, "tracking_error": 0.01}),
        ("interlace", {"combing": 0.5, "twitter": 0.28}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_video_tape_audio", {"format": "umatic_linear", "tracking": 0.2,
                                "dropout_rate": 3.0, "noise_db": -50.0,
                                "head_switch_db": -60.0, "compander_error": 0.0}),
        ("a_historical_mic", {"profile": "lavalier_1972", "amount": 0.35,
                              "proximity": 0.08, "overload": 0.08, "self_noise_db": -65.0}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.5,
                          "attack_ms": 8.0, "release_ms": 260.0}),
        ("a_room", {"mode": "room", "size": 0.8, "decay_s": 0.32, "mix": 0.08}),
    ],
    variants=[
        Variant("conference-copy", "Conference Copy", "A second-generation event cassette has greener whites, softer color and a noisier narration track.",
                video={"vhs.generation": 2, "vhs.chroma_noise": 0.32,
                       "vhs.time_base_error": 0.26, "balance.shadow_amt": 0.2},
                audio={"a_video_tape_audio.tracking": 0.48,
                       "a_video_tape_audio.noise_db": -43.0,
                       "a_video_tape_audio.dropout_rate": 12.0}),
        Variant("edit-master", "Edit Master", "The protected edit master keeps wider luma, steadier setup and a cleaner linear track.",
                video={"ntsc.strength": 0.3, "vhs.luma_noise": 0.06,
                       "vhs.dropouts": 0.0, "vhs.time_base_error": 0.04},
                audio={"a_video_tape_audio.tracking": 0.04,
                       "a_video_tape_audio.noise_db": -57.0}),
        Variant("source-clean", "Source-Clean Transfer",
                "Preserves the period carrier and color response while disabling momentary source loss or masking.",
                audio={"a_video_tape_audio.dropout_rate": 0.0}),
    ],
))


register_preset(Preset(
    id="tabloid-reenactment-1992",
    name="Tabloid Reenactment Tape",
    family="broadcast",
    era="1992",
    desc="A low-light reenactment shot to analog field video and finished for tabloid television: clipped camera gain, blue noise, streaked practicals, sharp tape edges and limiter-heavy location audio.",
    tagline="Blue gain noise, streaked lamps, hard location limiter",
    tags=("90s", "tabloid", "reenactment", "field-video"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.65}),
        ("tone", {"exposure": -0.18, "contrast": 1.28, "lift": 0.045, "knee": 0.7}),
        ("balance", {"warmth": -0.12, "shadow_tint": "blue", "shadow_amt": 0.34,
                     "high_tint": "yellow", "high_amt": 0.1}),
        ("saturation", {"amount": 0.9, "vibrance": -0.08}),
        ("exposure_auto", {"target": 0.38, "lag": 1.6, "overshoot": 0.62,
                           "max_boost": 5.2, "agc_gain_noise": 0.78, "wb_amount": 0.46}),
        ("optics", {"soft_focus": 0.06, "focus_drift": 0.16,
                    "hunt_rate": 0.38, "veiling_flare": 0.18}),
        ("phosphor_decay", {"decay": 0.32, "mode": "p22"}),
        ("ntsc", {"strength": 0.5, "luma_bw": 4.0, "chroma_bw": 0.82,
                  "rainbow": 0.18, "dot_crawl": 0.22, "phase_noise": 1.8,
                  "fringing": 1.2, "setup_level": 0.055,
                  "comb_mode": "comb_2d_adaptive"}),
        ("vhs", {"mode": "sp", "luma_bw": 4.6, "chroma_bw": 0.76,
                 "chroma_delay": 0.8, "sharpen": 0.76, "luma_noise": 0.25,
                 "chroma_noise": 0.24, "head_switch": 0.22, "dropouts": 0.4,
                 "time_base_error": 0.1, "flagging": 0.05, "fm_sparkle": 0.18}),
        ("interlace", {"combing": 0.62, "twitter": 0.34}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "shotgun_1975", "amount": 0.58,
                              "proximity": 0.08, "overload": 0.35,
                              "self_noise_db": -54.0, "handling": 0.16}),
        ("a_video_tape_audio", {"format": "video8_afm", "tracking": 0.28,
                                "dropout_rate": 4.0, "noise_db": -54.0,
                                "head_switch_db": -61.0, "compander_error": 0.12}),
        ("a_agc", {"target_db": -15.0, "max_gain_db": 14.0,
                   "attack_ms": 8.0, "release_ms": 760.0, "amount": 0.82}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 6.5,
                          "attack_ms": 2.0, "release_ms": 210.0}),
        ("a_room", {"mode": "room", "size": 1.1, "decay_s": 0.55,
                    "damp": 0.7, "mix": 0.15}),
    ],
    variants=[
        Variant("street-night", "Street Night", "More camera gain exposes blue chroma noise, blown practical streaks and louder AGC breathing.",
                video={"tone.exposure": -0.35, "exposure_auto.max_boost": 7.2,
                       "exposure_auto.agc_gain_noise": 0.95,
                       "vhs.luma_noise": 0.42, "vhs.chroma_noise": 0.4,
                       "phosphor_decay.decay": 0.5},
                audio={"a_historical_mic.self_noise_db": -47.0, "a_agc.amount": 0.96}),
        Variant("studio-insert", "Studio Insert", "A controlled insert uses less gain, steadier focus and a cleaner field tape path.",
                video={"tone.exposure": 0.05, "exposure_auto.max_boost": 1.8,
                       "exposure_auto.agc_gain_noise": 0.16,
                       "optics.focus_drift": 0.04, "vhs.luma_noise": 0.12},
                audio={"a_video_tape_audio.tracking": 0.08,
                       "a_historical_mic.handling": 0.0, "a_room.mix": 0.08}),
        Variant("source-clean", "Source-Clean Transfer",
                "Preserves the period carrier and color response while disabling momentary source loss or masking.",
                audio={"a_video_tape_audio.dropout_rate": 0.0}),
    ],
))


register_preset(Preset(
    id="cdrom-mjpeg-1995",
    name="CD-ROM MJPEG Window",
    family="digital",
    era="1995",
    desc="A 240-line multimedia clip decoded from CD-ROM: chunky intraframe JPEG blocks, reduced pixel detail, crushed gradients and 8-bit 22 kHz mono audio under a noisy early-computer quantizer.",
    tagline="240-line MJPEG and 8-bit 22 kHz mono",
    tags=("90s", "cd-rom", "mjpeg", "multimedia"),
    proc_height=480,
    upscale="pixel",
    video=[
        ("tone", {"contrast": 1.08, "lift": 0.018, "knee": 0.82}),
        ("saturation", {"amount": 0.95, "vibrance": -0.06}),
        ("pixel_era", {"res_h": 240, "palette": "vga256", "dither": "bayer4",
                       "contrast_snap": 0.16, "pixel_aspect": 1.0}),
        ("codec_era", {"codec": "mjpeg", "kbps": 380, "qscale": 14,
                       "res": "240p", "gop": 1, "passes": 1,
                       "field_mode": "progressive", "denoise_pre": 0.0}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bitcrush", {"bits": 8, "dither": False, "sr_hz": 22050.0,
                        "antialias": True, "mix": 0.92}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 2.8,
                          "attack_ms": 5.0, "release_ms": 180.0}),
        ("a_speaker", {"device": "pc_speaker_1992", "strength": 0.18}),
    ],
    variants=[
        Variant("double-speed", "Double-Speed Disc", "A carefully authored disc keeps more JPEG detail and uses 16-bit 22 kHz audio.",
                video={"codec_era.kbps": 700, "codec_era.qscale": 8,
                       "pixel_era.palette": "none"},
                audio={"a_bitcrush.bits": 16, "a_bitcrush.mix": 0.7,
                       "a_speaker.strength": 0.08}),
        Variant("cover-disc", "Magazine Cover Disc", "A packed cover disc cuts the window and audio rate until gradients step and motion breaks into larger JPEG cells.",
                video={"pixel_era.res_h": 180, "codec_era.kbps": 180,
                       "codec_era.qscale": 22, "codec_era.res": "144p"},
                audio={"a_bitcrush.bits": 6, "a_bitcrush.sr_hz": 11025.0,
                       "a_bitcrush.antialias": False, "a_speaker.strength": 0.36}),
    ],
))


register_preset(Preset(
    id="local-cable-infomercial-1997",
    name="Local Cable Infomercial",
    family="broadcast",
    era="1997",
    desc="A late-night local infomercial assembled on aging analog decks: clipped setup, fluorescent green drift, S-VHS-like edge ringing, composite crawl and an aggressively processed mono cable track.",
    tagline="Fluorescent drift, edge ringing, squeezed cable mono",
    tags=("90s", "infomercial", "cable", "svhs"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.58}),
        ("tone", {"exposure": 0.12, "contrast": 1.12, "lift": 0.05, "knee": 0.66}),
        ("balance", {"warmth": 0.04, "tint": -0.055, "shadow_tint": "green", "shadow_amt": 0.12,
                     "high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 1.1, "vibrance": 0.04}),
        ("exposure_auto", {"target": 0.46, "lag": 1.0, "overshoot": 0.4,
                           "max_boost": 3.0, "agc_gain_noise": 0.38, "wb_amount": 0.4}),
        ("ntsc", {"strength": 0.72, "luma_bw": 3.8, "chroma_bw": 0.78,
                  "rainbow": 0.22, "dot_crawl": 0.5, "phase_noise": 2.3,
                  "fringing": 2.0, "diff_phase": 2.5, "setup_level": 0.062,
                  "comb_mode": "comb_1line", "sync_jitter": 0.16}),
        ("vhs", {"mode": "sp", "luma_bw": 4.8, "chroma_bw": 0.72,
                 "chroma_delay": 1.0, "sharpen": 0.72, "luma_noise": 0.18,
                 "chroma_noise": 0.22, "head_switch": 0.24, "dropouts": 0.7,
                 "time_base_error": 0.2, "flagging": 0.08, "tracking_error": 0.02,
                 "fm_sparkle": 0.22}),
        ("interlace", {"combing": 0.58, "twitter": 0.34}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_video_tape_audio", {"format": "vhs_hifi", "tracking": 0.34,
                                "dropout_rate": 5.0, "noise_db": -55.0,
                                "head_switch_db": -57.0, "compander_error": -0.22}),
        ("a_compressor", {"threshold_db": -25.0, "ratio": 8.5,
                          "attack_ms": 1.5, "release_ms": 140.0, "knee_db": 2.0}),
        ("a_agc", {"target_db": -14.0, "max_gain_db": 10.0,
                   "attack_ms": 10.0, "release_ms": 520.0, "amount": 0.75}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -52.0, "hum_db": -60.0, "comp": 0.72}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.32}),
    ],
    variants=[
        Variant("master-dub", "Master Dub", "The station receives a clean dub with steadier time base, less crawl and a quieter Hi-Fi carrier.",
                video={"ntsc.dot_crawl": 0.25, "vhs.time_base_error": 0.08,
                       "vhs.dropouts": 0.1, "vhs.fm_sparkle": 0.08},
                audio={"a_video_tape_audio.tracking": 0.08,
                       "a_video_tape_audio.noise_db": -64.0, "a_tv_sound.buzz_db": -62.0}),
        Variant("overnight-repeat", "Overnight Repeat", "A reused station cassette adds green phase drift, dropouts and limiter pumping around every pause.",
                video={"vhs.generation": 3, "vhs.dropouts": 3.2,
                       "vhs.time_base_error": 0.45, "ntsc.phase_noise": 4.6,
                       "balance.shadow_amt": 0.24},
                audio={"a_video_tape_audio.tracking": 0.7,
                       "a_video_tape_audio.dropout_rate": 22.0, "a_agc.amount": 0.95}),
        Variant("source-clean", "Source-Clean Transfer",
                "Preserves the period carrier and color response while disabling momentary source loss or masking.",
                audio={"a_video_tape_audio.dropout_rate": 0.0}),
    ],
))


register_preset(Preset(
    id="digicam-mjpeg-2002",
    name="Digicam MJPEG Movie Mode",
    family="digital",
    era="2002",
    desc="A compact still camera recording a tiny MJPEG movie: clipped automatic exposure, oversharpened 240-line detail, coarse JPEG blocks, color noise and an electret mono track at a low sample rate.",
    tagline="Tiny MJPEG, clipped auto exposure, electret mono",
    tags=("2000s", "digicam", "mjpeg", "compact-camera"),
    proc_height=480,
    upscale="pixel",
    video=[
        ("tone", {"exposure": 0.08, "contrast": 1.12, "lift": 0.018, "knee": 0.72}),
        ("saturation", {"amount": 1.14, "vibrance": 0.08}),
        ("exposure_auto", {"target": 0.44, "lag": 0.45, "overshoot": 0.7,
                           "max_boost": 5.5, "agc_gain_noise": 0.7,
                           "wb_amount": 0.58, "iris_step": 0.32}),
        ("optics", {"soft_focus": 0.04, "focus_drift": 0.13,
                    "hunt_rate": 0.45, "chromatic_aberration": 0.75,
                    "corner_softness": 0.16}),
        ("chroma_dv", {"ratio": "4:2:0", "edge_sharpen": 0.9, "dct_blocks": 0.24}),
        ("codec_era", {"codec": "mjpeg", "kbps": 900, "qscale": 12,
                       "res": "240p", "gop": 1, "passes": 1,
                       "field_mode": "progressive", "denoise_pre": 0.0}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "electret_1985", "amount": 0.7,
                              "proximity": 0.0, "overload": 0.32,
                              "self_noise_db": -50.0, "handling": 0.12}),
        ("a_bitcrush", {"bits": 12, "dither": False, "sr_hz": 16000.0,
                        "antialias": True, "mix": 0.72}),
        ("a_agc", {"target_db": -16.0, "max_gain_db": 15.0,
                   "attack_ms": 10.0, "release_ms": 850.0, "amount": 0.88}),
    ],
    variants=[
        Variant("bright-day", "Bright Day", "The tiny sensor holds cleaner gain but clips speculars and sharpens hard edges more aggressively.",
                video={"tone.exposure": 0.25, "tone.knee": 0.62,
                       "exposure_auto.max_boost": 2.2, "exposure_auto.agc_gain_noise": 0.25,
                       "chroma_dv.edge_sharpen": 1.3,
                       "codec_era.kbps": 1200},
                audio={"a_historical_mic.self_noise_db": -56.0, "a_agc.amount": 0.65}),
        Variant("indoor-mode", "Indoor Mode", "Sensor gain raises color noise, focus hunts more often and the microphone AGC lifts room tone.",
                video={"tone.exposure": -0.2, "optics.focus_drift": 0.28,
                       "optics.hunt_rate": 0.8, "chroma_dv.dct_blocks": 0.42,
                       "codec_era.kbps": 560, "codec_era.qscale": 18},
                audio={"a_historical_mic.self_noise_db": -43.0,
                       "a_historical_mic.handling": 0.26, "a_agc.amount": 0.98}),
    ],
))
