"""Broadcast-family presets: live television from kinescope to cable."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="kinescope-1953",
    name="Kinescope",
    family="broadcast",
    era="1953",
    desc="Live TV preserved by filming a monitor: silvery blown highlights, scanline ghosts under film grain, the earliest television memory.",
    tagline="Blown silver highlights under film grain",
    tags=("bw", "50s", "live-tv", "film"),
    proc_height=520,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.3}),
        ("tone", {"contrast": 1.22, "lift": 0.06, "knee": 0.72, "gamma": 1.05}),
        ("crt", {"scan_strength": 0.3, "bloom": 0.6, "glass_glow": 0.35, "curvature": 0.15}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.5}),
        ("grain", {"amount": 0.32, "size": 2.2, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("gate_weave", {"amount": 1.2}),
        ("flicker", {"amount": 0.25}),
        ("dust", {"density": 0.4}),
        ("vignette", {"amount": 0.4, "softness": 0.7}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.10, "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_optical_track", {"cell_noise": -48.0, "academy_rolloff": "feature_1940s"}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.6}),
        ("a_hum", {"hz": 60, "level_db": -46.0}),
    ],
    variants=[
        Variant("archive", "Archive Print", "A dupe of a dupe — softer, dirtier, wobblier.",
                video={"grain.amount": 0.7, "dust.density": 0.9, "gate_weave.amount": 2.0,
                       "tone.contrast": 1.1}),
    ],
))

register_preset(Preset(
    id="network-bw-1959",
    name="Network Studio",
    family="broadcast",
    era="1959",
    desc="Big-three studio B&W: crisp orthicon cameras with comet-tail glow, velvet grays, an image that smells of cigarettes and klieg lights.",
    tagline="Velvet grays, comet-tail orthicon glow",
    tags=("bw", "50s", "studio"),
    proc_height=540,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.14, "lift": 0.05, "knee": 0.78}),
        ("phosphor_decay", {"decay": 0.25, "mode": "p22"}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.22, "bloom": 0.45, "curvature": 0.1, "misconvergence": 0.0}),
        ("signal_rf", {"snow": 0.08}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.09}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
        ("a_hum", {"hz": 60, "level_db": -48.0}),
    ],
))

register_preset(Preset(
    id="early-color-1967",
    name="Early Color Broadcast",
    family="broadcast",
    era="1967",
    desc="When color arrived and nobody's set agreed on hue: glowing NTSC rainbow edges, drifting flesh tones, peacock-proud saturation.",
    tagline="Rainbow edges, drifting flesh tones",
    tags=("60s", "color", "ntsc"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.1, "lift": 0.04, "knee": 0.8}),
        ("saturation", {"amount": 1.18}),
        ("ntsc", {"strength": 1.0, "phase_noise": 4.5, "phase_error": 4.0, "rainbow": 0.45,
                  "dot_crawl": 0.4, "chroma_bw": 0.5}),
        ("interlace", {"combing": 0.55, "twitter": 0.35}),
        ("crt", {"scan_strength": 0.2, "bloom": 0.5, "curvature": 0.12, "misconvergence": 0.6}),
        ("signal_rf", {"snow": 0.12, "ghost_px": 10.0, "ghost_alpha": 0.12}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.09}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -42.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.55}),
    ],
))

register_preset(Preset(
    id="news-film-1975",
    name="Eyewitness News Film",
    family="broadcast",
    era="1975",
    desc="16mm reversal rushed from the scene to the 6 o'clock news: mustard-and-avocado color, honest grain, telecine cadence. Film at eleven.",
    tagline="Mustard grain, weave, telecine judder",
    tags=("70s", "16mm", "news", "film"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.09, "lift": 0.045, "knee": 0.82}),
        ("balance", {"warmth": 0.18, "shadow_tint": "brown", "shadow_amt": 0.3}),
        ("optics", {"soft_focus": 0.2, "corner_softness": 0.2}),
        ("grain", {"amount": 0.33, "size": 2.6, "chroma_grain": 0.18, "stock": "doc_16"}),
        ("halation", {"strength": 0.22, "tint": "orange"}),
        ("gate_weave", {"amount": 1.4}),
        ("flicker", {"amount": 0.16}),
        ("dust", {"density": 0.5, "hairs": 0.3}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.4}),
        ("ntsc", {"strength": 0.5, "phase_noise": 1.6}),
        ("vignette", {"amount": 0.28}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 110.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -50.0, "academy_rolloff": "classroom_16mm"}),
        ("a_agc", {"amount": 0.5}),
        ("a_hum", {"hz": 60, "level_db": -50.0}),
    ],
    variants=[
        Variant("archival", "Archival Reel", "The station's vault copy, several careless decades later.",
                video={"grain.amount": 0.7, "dust.density": 1.0,
                       "gate_weave.amount": 2.0}),
    ],
))

register_preset(Preset(
    id="talk-show-1984",
    name="Daytime Talk Show",
    family="broadcast",
    era="1984",
    desc="Studio cameras under hot lights: waxy skin, smeared reds, comet trails on the sequins — the exact texture of a 1984 station archive tape.",
    tagline="Waxy skin, smeared reds, comet trails",
    tags=("80s", "studio", "vhs"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.8}),
        ("tone", {"contrast": 1.07, "lift": 0.035, "knee": 0.78}),
        ("saturation", {"amount": 1.1}),
        ("phosphor_decay", {"decay": 0.18, "mode": "p22"}),
        ("ntsc", {"strength": 0.9, "phase_noise": 2.4, "rainbow": 0.3, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "luma_bw": 3.6, "luma_noise": 0.4, "chroma_noise": 0.45,
                 "head_switch": 0.5, "time_base_error": 0.35, "sharpen": 0.6}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.1}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.06}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 10000.0}),
        ("a_agc", {"amount": 0.6}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tape_hiss", {"level_db": -46.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.35}),
    ],
))

register_preset(Preset(
    id="sitcom-1993",
    name="Multi-Cam Sitcom",
    family="broadcast",
    era="1993",
    desc="Warm, soft, forgiving studio video with that Friday-night glow: gentle bloom, easy saturation, laugh-track-ready sound glue.",
    tagline="Soft bloom, cream highlights, easy color",
    tags=("90s", "sitcom", "studio"),
    proc_height=600,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.02, "knee": 0.82}),
        ("balance", {"warmth": 0.22, "high_tint": "cream", "high_amt": 0.3}),
        ("saturation", {"amount": 1.08, "vibrance": 0.15}),
        ("optics", {"diffusion": 0.3}),
        ("ntsc", {"strength": 0.5, "phase_noise": 1.0}),
        ("vhs", {"mode": "sp", "luma_bw": 4.2, "luma_noise": 0.2, "chroma_noise": 0.25,
                 "head_switch": 0.3, "time_base_error": 0.15, "sharpen": 0.5}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.4}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 12000.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_agc", {"amount": 0.35}),
        ("a_tape_hiss", {"level_db": -50.0}),
    ],
))

register_preset(Preset(
    id="public-access-1989",
    name="Public Access",
    family="broadcast",
    era="1989",
    desc="Channel 19 after midnight: one tired camera, fluorescent hum, black that never quite reaches black. Outsider television.",
    tagline="Milky blacks, dropouts, fluorescent hum",
    tags=("80s", "lofi", "cable"),
    proc_height=500,
    upscale="soft",
    video=[
        ("tone", {"contrast": 0.98, "lift": 0.07, "knee": 0.8}),
        ("exposure_auto", {}),
        ("ntsc", {"strength": 0.9, "phase_noise": 3.2, "rainbow": 0.3}),
        ("vhs", {"mode": "sp", "luma_noise": 0.35, "chroma_noise": 0.3, "head_switch": 0.6,
                 "time_base_error": 0.5, "flagging": 0.35, "dropouts": 0.8}),
        ("phosphor_decay", {"decay": 0.22}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.12}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_hum", {"hz": 60, "buzz": 0.5, "level_db": -38.0}),
        ("a_room", {"size": 0.4, "decay_s": 0.5, "mix": 0.25}),
        ("a_agc", {"amount": 0.7}),
    ],
))

register_preset(Preset(
    id="portable-bw-1963",
    name="Portable B&W Set",
    family="broadcast",
    era="1963",
    desc="A rabbit-eared portable in the kitchen: swimming snow, ghosting from the neighbor's roofline, a tiny speaker doing its best.",
    tagline="Swimming snow, roofline ghost, tiny speaker",
    tags=("bw", "60s", "rf"),
    proc_height=480,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.12, "lift": 0.06, "knee": 0.75}),
        ("signal_rf", {"snow": 0.45, "ghost_px": 18.0, "ghost_alpha": 0.25, "hum_bar": 0.25,
                       "impulse_noise": 0.5}),
        ("interlace", {"combing": 0.5, "twitter": 0.4}),
        ("crt", {"scan_strength": 0.3, "bloom": 0.5, "curvature": 0.2, "vignette_crt": 0.4}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.12}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_tv_sound", {"buzz_db": -40.0}),
        ("a_speaker", {"device": "transistor_pocket_1965", "strength": 0.7}),
        ("a_hum", {"hz": 60, "level_db": -40.0}),
    ],
    variants=[
        Variant("storm", "Storm Reception", "Antenna in a thunderstorm — the picture fights to exist.",
                video={"signal_rf.snow": 0.8, "signal_rf.impulse_noise": 2.0, "signal_rf.hum_bar": 0.4},
                audio={"a_tv_sound.buzz_db": -35.0}),
    ],
))

register_preset(Preset(
    id="satellite-feed-1991",
    name="Satellite News Feed",
    family="broadcast",
    era="1991",
    desc="A raw bird feed grabbed between commercials: analog sparklies, slight smear, comms-grade audio with that long-distance sheen.",
    tagline="Sparklies, slight smear, comms-clean audio",
    tags=("90s", "news", "satellite"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.02}),
        ("ntsc", {"strength": 0.7, "phase_noise": 1.6}),
        ("signal_rf", {"snow": 0.2, "sparkle": 2.0, "impulse_noise": 1.0}),
        ("vhs", {"mode": "sp", "luma_bw": 4.0, "luma_noise": 0.3, "chroma_noise": 0.3,
                 "head_switch": 0.0, "time_base_error": 0.2}),
        ("interlace", {"combing": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7500.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tape_hiss", {"level_db": -44.0}),
        ("a_digital_glitch", {"stutter_rate": 0.5, "mute_rate": 0.3}),
    ],
))
