"""Broadcast-family presets, third wave: what a KIND of program looked like in its year.

Not a network house style and not a signal fault: the acquisition medium, the
network chain and the set in the corner, chosen by program type. A filmed 1957
western through a vidicon film chain, a 1985 pastel cop show through MTS stereo,
a 2009 procedural through a sharpener and a 16:9 mask.
"""

from ..engine.presets import Preset, Variant, register_preset

# nearest: network-bw-1959; differs: a filmed backlot series on 16 mm syndication
# prints run through a vidicon film chain, not a live orthicon studio.
register_preset(Preset(
    id="tv-western-series-1957",
    name="Filmed Western Series",
    family="broadcast",
    era="1957",
    desc="A half-hour backlot oater shot on 35 mm, struck to 16 mm station prints and pulled through a vidicon film chain: silver panchromatic grays, print grain, sprocket hop and a beam that blooms on every white hat.",
    tagline="Backlot 16 mm silver, film-chain vidicon",
    tags=("50s", "16mm", "television", "film-chain", "vidicon"),
    keywords=("western", "tv-series", "fifties", "backlot", "cowboy", "episodic",
              "filmed", "bw", "syndicated", "half-hour"),
    proc_height=600,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.14}),
        ("tone", {"contrast": 1.2, "lift": 0.03, "knee": 0.8, "pivot": 0.44}),
        ("optics", {"soft_focus": 0.06, "corner_softness": 0.1}),
        ("grain", {"amount": 0.4, "size": 1.9, "chroma_grain": 0.0, "roughness": 0.55,
                   "stock": "newsreel_35", "layers": "mono"}),
        ("halation", {"strength": 0.2, "tint": "neutral", "threshold": 0.78}),
        ("print_char", {"contrast_buildup": 1, "acutance": 0.24, "dmax_breath": 0.12}),
        ("gate_weave", {"amount": 0.7, "hz": 0.7, "splice_bump": 0.8}),
        ("dust", {"density": 0.22, "hairs": 0.12}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 0.6}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.3}),
        ("ntsc", {"strength": 0.55, "luma_bw": 3.2, "chroma_bw": 0.5, "phase_noise": 1.2,
                  "rainbow": 0.05, "dot_crawl": 0.08}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"bloom": 0.42, "beam_bloom": 0.3, "curvature": 0.04, "scan_strength": 0.1,
                 "glass_glow": 0.1, "vignette_crt": 0.25}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"low_hz": 110.0, "high_hz": 6200.0,
                             "academy_rolloff": "classroom_16mm", "cell_noise": -50.0,
                             "flutter": 0.4, "drive": 1.4}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 3.0, "release_ms": 260.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -56.0, "hum_db": -58.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.75}),
    ],
    variants=[
        Variant("syndication-print-1965", "Syndication Print",
                "Eighth year in the rotation: a dupe of a dupe, gritty and speckled, running on the independent at four in the afternoon.",
                video={"grain.amount": 0.5, "dust.density": 0.4, "dust.hairs": 0.22,
                       "print_char.contrast_buildup": 2, "gate_weave.amount": 1.0},
                audio={"a_optical_track.cell_noise": -44.0, "a_optical_track.flutter": 0.55}),
        Variant("network-master", "Network Master",
                "The protected element before it left the network: finer grain, a steadier gate and a film chain that has just been lined up.",
                video={"grain.amount": 0.3, "dust.density": 0.08, "gate_weave.amount": 0.35,
                       "ntsc.strength": 0.3, "crt.bloom": 0.3, "crt.beam_bloom": 0.16},
                audio={"a_optical_track.cell_noise": -56.0, "a_tv_sound.buzz_db": -64.0}),
    ],
))

# nearest: color-premiere-1966; differs: a filmed 35 mm action series rather than a
# live studio show, so gloss and gate motion sit under the hot 1967 composite.
register_preset(Preset(
    id="tv-spy-series-1967",
    name="Color Spy Series",
    family="broadcast",
    era="1967",
    desc="Filmed 35 mm espionage gloss pushed through a hot 1967 network composite: candy Eastman dye, red halation on every gadget, chroma wandering a couple of degrees and a console speaker doing the rest.",
    tagline="Glossy 35 mm color, hot NTSC, mod sheen",
    tags=("60s", "35mm", "television", "telecine", "glossy"),
    keywords=("spy", "tv-series", "sixties", "secret-agent", "color", "mod", "episodic",
              "gadgets", "network", "action"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.85}),
        ("tone", {"contrast": 1.08, "lift": 0.015, "knee": 0.84, "pivot": 0.44}),
        ("balance", {"warmth": 0.05, "high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 1.12, "vibrance": 0.18}),
        ("optics", {"soft_focus": 0.04, "veiling_flare": 0.12}),
        ("grain", {"amount": 0.3, "size": 1.75, "chroma_grain": 0.15,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.28, "tint": "red_orange", "threshold": 0.74}),
        ("fade", {"enabled": False, "amount": 0.15, "profile": "eastman_pink",
                  "bloom_whites": 0.2}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 0.5}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.3}),
        ("ntsc", {"strength": 0.8, "luma_bw": 3.5, "chroma_bw": 0.8, "phase_noise": 2.5,
                  "diff_phase": 2.0, "chroma_agc": 0.12, "rainbow": 0.34,
                  "dot_crawl": 0.3}),
        ("signal_rf", {"enabled": False, "snow": 0.08, "sparkle": 2.0, "ghost_n": 1,
                       "ghost_px": 16.0, "ghost_alpha": 0.18}),
        ("interlace", {"combing": 0.55, "twitter": 0.25}),
        ("crt", {"bloom": 0.4, "misconvergence": 0.6, "scan_strength": 0.1,
                 "curvature": 0.04, "vignette_crt": 0.2}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 8000.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.5, "release_ms": 220.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -55.0, "hum_db": -58.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.7}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "Straight off the film chain with the encoder freshly aligned: dye still hot, hue finally sitting still.",
                video={"ntsc.strength": 0.35, "ntsc.phase_noise": 1.2, "ntsc.rainbow": 0.12,
                       "ntsc.diff_phase": 0.6, "crt.bloom": 0.3}),
        Variant("rerun-1978-uhf", "1978 UHF Rerun",
                "Eleven years later on channel 43: the print has gone pink, the tower is far away and the antenna is on the roof.",
                video={"fade.enabled": True, "signal_rf.enabled": True,
                       "ntsc.strength": 0.95, "ntsc.phase_noise": 3.4,
                       "saturation.amount": 1.05},
                audio={"a_tv_sound.buzz_db": -48.0, "a_bandlimit.high_hz": 6000.0}),
    ],
))

# nearest: auth-movie-of-the-week-melodrama-1975; differs: a pink-faded street print
# with zoom-lens fringing and raised setup, cut as a weekly crime hour.
register_preset(Preset(
    id="tv-cop-show-1976",
    name="Seventies Cop Show",
    family="broadcast",
    era="1976",
    desc="Location 35 mm on a faded release print: dull Eastman browns, color fringing off a hard-worked zoom, raised setup crushing the alley blacks and a sync-buzzing console mono.",
    tagline="Faded 35 mm streets, lens smear, buzz mono",
    tags=("70s", "35mm", "television", "telecine", "faded"),
    keywords=("cop-show", "police", "seventies", "tv-series", "detective", "streets",
              "telephoto", "episodic", "network", "crime"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.8}),
        ("tone", {"contrast": 1.05, "lift": 0.03, "knee": 0.82, "pivot": 0.44}),
        ("balance", {"warmth": 0.12, "high_tint": "yellow", "high_amt": 0.1}),
        ("saturation", {"amount": 0.95, "vibrance": 0.06}),
        ("optics", {"chromatic_aberration": 0.7, "soft_focus": 0.05,
                    "corner_softness": 0.12, "focus_drift": 0.08}),
        ("grain", {"amount": 0.36, "size": 1.75, "chroma_grain": 0.16,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.25, "tint": "orange", "threshold": 0.76}),
        ("print_char", {"contrast_buildup": 1, "acutance": 0.18}),
        ("dust", {"density": 0.16, "hairs": 0.1}),
        ("fade", {"amount": 0.12, "profile": "eastman_pink", "bloom_whites": 0.2}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 0.7}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.3}),
        ("ntsc", {"strength": 0.8, "luma_bw": 3.5, "chroma_bw": 0.8, "phase_noise": 2.2,
                  "setup_level": 0.06, "rainbow": 0.28, "dot_crawl": 0.28}),
        ("signal_rf", {"enabled": False, "snow": 0.06, "sparkle": 2.0, "ghost_n": 1,
                       "ghost_px": 14.0, "ghost_alpha": 0.14}),
        ("interlace", {"combing": 0.55, "twitter": 0.22}),
        ("crt", {"bloom": 0.4, "misconvergence": 0.55, "scan_strength": 0.1,
                 "curvature": 0.04, "vignette_crt": 0.22}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 7500.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.5, "release_ms": 240.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -54.0, "hum_db": -56.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.7}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "The unfaded element on air night one: neutral dye, a lined-up encoder, the zoom still misbehaving.",
                video={"fade.amount": 0.0, "ntsc.strength": 0.35, "ntsc.setup_level": 0.03,
                       "crt.bloom": 0.3, "dust.density": 0.06}),
        Variant("syndication-1984", "Stripped for Syndication",
                "Five nights a week at six: a beaten print, pinker every month, coming in off a distant transmitter.",
                video={"fade.amount": 0.25, "grain.amount": 0.44, "dust.density": 0.35,
                       "print_char.contrast_buildup": 2, "signal_rf.enabled": True},
                audio={"a_tv_sound.buzz_db": -48.0}),
    ],
))

# nearest: auth-prestige-historical-miniseries; differs: glamour diffusion, warm cream
# highlights and MTS stereo instead of a restrained, narrow-stereo period master.
register_preset(Preset(
    id="tv-primetime-soap-1984",
    name="Eighties Primetime Soap",
    family="broadcast",
    era="1984",
    desc="Oil money on 35 mm: a diffusion filter over every close-up, cream highlights blooming off the chandeliers, pin-registered telecine and an early MTS stereo mix with a plate on the strings.",
    tagline="Glossy mansion light, diffusion, MTS stereo",
    tags=("80s", "35mm", "television", "diffusion", "stereo"),
    keywords=("primetime-soap", "dynasty", "dallas", "eighties", "glossy", "oil",
              "mansion", "shoulder-pads", "glamour", "network"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodak_80s", "strength": 0.8}),
        ("tone", {"contrast": 1.06, "lift": 0.02, "knee": 0.84, "pivot": 0.45}),
        ("balance", {"warmth": 0.12, "high_tint": "cream", "high_amt": 0.26}),
        ("saturation", {"amount": 1.1, "vibrance": 0.1}),
        ("optics", {"diffusion": 0.32, "soft_focus": 0.18, "veiling_flare": 0.1}),
        ("grain", {"amount": 0.26, "size": 1.8, "chroma_grain": 0.14,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.44, "tint": "warm_white", "threshold": 0.7}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.3}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.25}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.9, "chroma_bw": 1.0, "phase_noise": 1.6,
                  "rainbow": 0.2, "dot_crawl": 0.18}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.3, "chroma_noise": 0.32,
                 "sharpen": 0.45, "dropouts": 1.2, "time_base_error": 0.3, "head_switch": 0.6}),
        ("interlace", {"combing": 0.5, "twitter": 0.18}),
        ("crt", {"bloom": 0.32, "misconvergence": 0.4, "scan_strength": 0.08,
                 "vignette_crt": 0.18}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 55.0, "high_hz": 12000.0}),
        ("a_room", {"mode": "plate1960", "size": 1.4, "decay_s": 1.1, "mix": 0.08,
                    "damp": 0.6, "predelay_ms": 16.0}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 3.0, "release_ms": 260.0}),
        ("a_channel_aging", {"width": 1.1, "imbalance_db": -0.3, "crosstalk_db": -38.0,
                             "skew_us": 20.0, "mono_bass_hz": 110.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -60.0, "hum_db": -64.0, "comp": 0.4}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.6}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "The clean 1-inch master: the same glamour without the encoder softening every rhinestone.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.24, "crt.misconvergence": 0.2},
                audio={"a_tv_sound.buzz_db": -68.0, "a_channel_aging.width": 1.2}),
        Variant("vhs-timer", "Taped Off the Timer",
                "Somebody set the VCR before the dinner party: the mansion arrives on a T-120 with the tracking almost right.",
                video={"vhs.enabled": True, "crt.bloom": 0.36},
                audio={"a_channel_aging.width": 0.85, "a_tv_sound.buzz_db": -52.0}),
    ],
))

# nearest: tv-primetime-soap-1984; differs: teal shadows and pink highs with lens
# flare and a wide synth stereo instead of warm glamour diffusion.
register_preset(Preset(
    id="tv-pastel-cop-show-1985",
    name="Pastel Cop Show",
    family="broadcast",
    era="1985",
    desc="Art-deco pastel on 35 mm: pink highlights over teal shadows, veiling flare and aperture ghosts off every neon sign, and a wide stereo synth bed leaning on the tape.",
    tagline="Miami pastel 35 mm, neon night, stereo synth",
    tags=("80s", "35mm", "television", "teal", "stereo"),
    keywords=("miami-vice", "pastel", "cop-show", "eighties", "neon", "art-deco",
              "speedboat", "synth", "glossy", "network"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodak_80s", "strength": 0.85}),
        ("tone", {"contrast": 1.04, "lift": 0.045, "knee": 0.8, "pivot": 0.44}),
        ("balance", {"warmth": -0.05, "shadow_tint": "teal", "shadow_amt": 0.52,
                     "high_tint": "pink", "high_amt": 0.28}),
        ("saturation", {"amount": 1.06, "vibrance": 0.34, "hue": -6.0}),
        ("optics", {"veiling_flare": 0.28, "aperture_ghost": 0.15, "diffusion": 0.1}),
        ("grain", {"amount": 0.28, "size": 1.8, "chroma_grain": 0.15,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.3, "tint": "red_orange", "threshold": 0.72}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.3}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.25}),
        ("ntsc", {"strength": 0.55, "luma_bw": 4.0, "chroma_bw": 1.1, "phase_noise": 1.4,
                  "rainbow": 0.16, "dot_crawl": 0.16}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.3, "chroma_noise": 0.34,
                 "sharpen": 0.5, "dropouts": 1.4, "time_base_error": 0.32, "head_switch": 0.6}),
        ("interlace", {"combing": 0.5, "twitter": 0.18}),
        ("crt", {"bloom": 0.3, "misconvergence": 0.35, "scan_strength": 0.08,
                 "vignette_crt": 0.2}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 13000.0}),
        ("a_tape_sat", {"drive": 1.3, "bump_db": 3.0, "hf_loss": 0.2, "eq_era": "modern"}),
        ("a_channel_aging", {"width": 1.2, "imbalance_db": -0.2, "crosstalk_db": -42.0,
                             "skew_us": 14.0, "mono_bass_hz": 90.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.0, "release_ms": 280.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -62.0, "hum_db": -66.0, "comp": 0.35}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.25}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "Off the 1-inch before the encoder: the pastels stay separated and the neon keeps its edges.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.24},
                audio={"a_tv_sound.buzz_db": -70.0}),
        Variant("vhs-timer", "Taped Off the Timer",
                "Friday at ten on a T-120, watched until the tape wore a line through the pink.",
                video={"vhs.enabled": True, "saturation.amount": 1.05},
                audio={"a_channel_aging.width": 0.9, "a_speaker.device": "tv_mono_1985",
                       "a_speaker.strength": 0.6}),
    ],
))

# nearest: sitcom-1993; differs: single-camera warm film drama with soft-focus
# diffusion and a grille-masked set, not multi-camera studio bloom.
register_preset(Preset(
    id="tv-teen-drama-1996",
    name="Nineties Teen Drama",
    family="broadcast",
    era="1996",
    desc="Single-camera 35 mm shot warm and soft for a nine o'clock hour: cream highlights, gentle diffusion, a clean late-analog encoder and a Trinitron grille under the sound of somebody's feelings.",
    tagline="Soft 35 mm, warm creek light, MTS stereo",
    tags=("90s", "35mm", "television", "single-camera", "telecine"),
    keywords=("teen-drama", "nineties", "wb", "dawson", "high-school", "soft", "warm",
              "network", "series", "angst"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "vision_90s", "strength": 0.8}),
        ("tone", {"contrast": 1.04, "lift": 0.02, "knee": 0.86, "pivot": 0.45}),
        ("balance", {"warmth": 0.12, "high_tint": "cream", "high_amt": 0.15}),
        ("saturation", {"amount": 1.05, "vibrance": 0.08}),
        ("optics", {"soft_focus": 0.08, "diffusion": 0.08}),
        ("grain", {"amount": 0.26, "size": 1.8, "chroma_grain": 0.14,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.26, "tint": "warm_white", "threshold": 0.76}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.25}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.2}),
        ("ntsc", {"strength": 0.45, "luma_bw": 4.2, "chroma_bw": 1.2, "phase_noise": 1.2,
                  "rainbow": 0.12, "dot_crawl": 0.12}),
        ("vhs", {"enabled": False, "mode": "ep", "luma_noise": 0.3, "chroma_noise": 0.3,
                 "sharpen": 0.4, "dropouts": 2.0, "time_base_error": 0.4, "head_switch": 0.7}),
        ("interlace", {"combing": 0.5, "twitter": 0.16}),
        ("crt", {"bloom": 0.25, "phosphor_mask": "grille", "mask_strength": 0.03,
                 "mask_scale": 3.6, "scan_strength": 0.06}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 14000.0}),
        ("a_channel_aging", {"width": 1.15, "imbalance_db": -0.2, "crosstalk_db": -46.0,
                             "skew_us": 10.0, "mono_bass_hz": 90.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.0, "release_ms": 260.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -64.0, "hum_db": -68.0, "comp": 0.35}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.6}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "The delivery tape: same soft warmth, encoder barely doing anything at all.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.2, "crt.mask_strength": 0.03},
                audio={"a_tv_sound.buzz_db": -70.0}),
        Variant("vhs-timer-ep", "Six Hours on EP",
                "Taped in EP with three other episodes to save a cassette, and watched that way for years.",
                video={"vhs.enabled": True, "optics.soft_focus": 0.14},
                audio={"a_channel_aging.width": 0.8, "a_bandlimit.high_hz": 9000.0}),
    ],
))

# nearest: hd-1080i-2008; differs: a teal-desaturated forensic grade with heavy
# sharpening and DVNR wax, delivered 16:9 from a 35 mm origin.
register_preset(Preset(
    id="tv-procedural-hd-2005",
    name="Aughts Desaturated Procedural",
    family="broadcast",
    era="2005",
    desc="Film-originated crime lab in early HD: saturation pulled out, shadows tipped to teal, noise reduction waxing the skin and a sharpener putting a ring around every evidence bag.",
    tagline="Cool desaturated HD, sharp lab light, 16:9",
    tags=("00s", "1080i", "television", "widescreen", "grade"),
    keywords=("procedural", "csi", "crime-lab", "aughts", "hd", "desaturated", "cool",
              "sharpened", "series", "forensic"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "vision_90s", "strength": 0.7}),
        ("tone", {"exposure": 0.07, "contrast": 1.15, "lift": 0.012, "knee": 0.85,
                  "pivot": 0.46}),
        ("balance", {"warmth": -0.08, "shadow_tint": "teal", "shadow_amt": 0.2,
                     "high_tint": "cyan", "high_amt": 0.1}),
        ("saturation", {"amount": 0.8, "vibrance": 0.05}),
        ("grain", {"amount": 0.22, "size": 1.8, "chroma_grain": 0.1,
                   "stock": "fine_35", "layers": "color_neg"}),
        ("halation", {"strength": 0.2, "tint": "neutral", "threshold": 0.8}),
        ("dvnr", {"strength": 0.25, "wax": 0.25}),
        ("sharpen", {"amount": 0.4, "radius": 1.0}),
        ("ntsc", {"enabled": False, "strength": 0.4, "luma_bw": 4.2, "chroma_bw": 1.2,
                  "phase_noise": 1.2, "rainbow": 0.12, "dot_crawl": 0.12}),
        ("interlace", {"combing": 0.45, "twitter": 0.15}),
        ("framing", {"aspect": "16:9", "mode": "box", "edge_soft": 0.004}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 35.0, "high_hz": 16000.0}),
        ("a_channel_aging", {"width": 1.25, "imbalance_db": -0.1, "crosstalk_db": -52.0,
                             "skew_us": 6.0, "mono_bass_hz": 80.0}),
        ("a_compressor", {"threshold_db": -17.0, "ratio": 3.0, "release_ms": 240.0}),
        ("a_codec_aac", {"kbps": 160, "mono": False}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.25}),
    ],
    variants=[
        Variant("sd-broadcast-4x3", "Downconverted to 4:3",
                "The same episode centre-cut for the analog feed, composite and all, for the half of the country still watching a tube.",
                video={"framing.aspect": "4:3", "framing.mode": "crop",
                       "ntsc.enabled": True, "interlace.combing": 0.55,
                       "sharpen.amount": 0.5},
                audio={"a_codec_aac.kbps": 96, "a_channel_aging.width": 0.9,
                       "a_speaker.device": "tv_mono_1985", "a_speaker.strength": 0.6}),
        Variant("bluray", "Season Box Set",
                "The later disc release: the noise reducer backed off, the halos trimmed and the fields gone.",
                video={"dvnr.strength": 0.1, "dvnr.wax": 0.1, "sharpen.amount": 0.15,
                       "interlace.enabled": False, "grain.amount": 0.26},
                audio={"a_codec_aac.kbps": 256}),
    ],
))

# nearest: auth-italian-prime-time-variety-show; differs: warm British studio light,
# laugh-room compression at 50 Hz and a dormant 16 mm exterior insert.
register_preset(Preset(
    id="tv-british-studio-sitcom-1975",
    name="British Studio Sitcom",
    family="broadcast",
    era="1975",
    desc="Three cameras and an audience in a warm PAL studio: plumbicon tube color with a little lag, 50 Hz intercarrier buzz and a compressor that ducks the room every time the laugh comes.",
    tagline="PAL studio video, laugh track, 16 mm inserts",
    tags=("70s", "tube-camera", "television", "britain", "studio"),
    keywords=("sitcom", "british", "seventies", "pal", "studio-video", "laugh-track",
              "bbc", "itv", "comedy", "uk"),
    proc_height=576,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.04, "lift": 0.03, "knee": 0.84, "pivot": 0.45}),
        ("balance", {"warmth": 0.12, "high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 1.0, "vibrance": 0.06}),
        ("optics", {"soft_focus": 0.06, "veiling_flare": 0.1}),
        ("grain", {"enabled": False, "amount": 0.42, "size": 1.8, "chroma_grain": 0.18,
                   "stock": "doc_16", "layers": "color_neg"}),
        ("gate_weave", {"enabled": False, "amount": 0.8, "hz": 0.7, "splice_bump": 0.6}),
        ("phosphor_decay", {"decay": 0.35, "mode": "p22"}),
        ("ntsc", {"system": "pal", "strength": 0.75, "luma_bw": 3.7, "chroma_bw": 0.9,
                  "phase_noise": 0.8, "rainbow": 0.1, "dot_crawl": 0.15}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.34, "chroma_noise": 0.36,
                 "sharpen": 0.5, "dropouts": 2.0, "time_base_error": 0.35, "head_switch": 0.65}),
        ("interlace", {"combing": 0.55, "twitter": 0.22}),
        ("crt", {"bloom": 0.38, "misconvergence": 0.5, "scan_strength": 0.1,
                 "curvature": 0.04, "vignette_crt": 0.2}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 7500.0}),
        ("a_room", {"mode": "plate1960", "size": 1.5, "decay_s": 0.9, "mix": 0.12,
                    "damp": 0.6, "predelay_ms": 14.0}),
        ("a_compressor", {"threshold_db": -21.0, "ratio": 4.0, "attack_ms": 12.0,
                          "release_ms": 340.0}),
        ("a_tv_sound", {"hz": "50", "buzz_db": -55.0, "hum_db": -56.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.8}),
    ],
    variants=[
        Variant("film-exterior-16mm", "16 mm Exterior",
                "The bit shot outdoors on film: grain, a wandering gate and none of the tube lag the studio has.",
                video={"grain.enabled": True, "gate_weave.enabled": True,
                       "phosphor_decay.decay": 0.08, "ntsc.strength": 0.6,
                       "saturation.amount": 0.94}),
        Variant("vhs-off-air-1982", "Off-Air on VHS",
                "Taped off the second showing in 1982 and kept in a cupboard ever since.",
                video={"vhs.enabled": True, "crt.bloom": 0.42},
                audio={"a_bandlimit.high_hz": 6000.0, "a_tv_sound.buzz_db": -48.0}),
    ],
))

# nearest: tv-spy-series-1967; differs: PAL keeps the hue locked, so the mod palette
# reads clean and cool instead of drifting through a hot NTSC encoder.
register_preset(Preset(
    id="tv-british-spy-series-1966",
    name="British Spy Series",
    family="broadcast",
    era="1966",
    desc="Swinging 35 mm shot at a British studio and encoded to PAL: pop-art dye that stays exactly where it was graded, red halation on the sports cars and a clean dubbed mono.",
    tagline="Swinging 35 mm color, mod pop, clean mono",
    tags=("60s", "35mm", "television", "britain", "telecine"),
    keywords=("avengers", "british", "spy", "sixties", "mod", "color", "film-series",
              "uk", "pop", "gadgets"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.3}),
        ("tone", {"contrast": 1.16, "lift": 0.008, "knee": 0.88, "pivot": 0.44}),
        ("balance", {"warmth": -0.14, "high_tint": "cyan", "high_amt": 0.18}),
        ("saturation", {"amount": 1.12, "vibrance": 0.16, "hue": 7.0}),
        ("optics", {"soft_focus": 0.04, "corner_softness": 0.08}),
        ("grain", {"amount": 0.3, "size": 1.75, "chroma_grain": 0.15,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.2, "tint": "red", "threshold": 0.78}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 0.5}),
        ("cadence", {"pattern": "none", "field_blend": 0.25}),
        ("ntsc", {"system": "pal", "strength": 0.6, "luma_bw": 3.8, "chroma_bw": 0.9,
                  "phase_noise": 0.6, "rainbow": 0.08, "dot_crawl": 0.12}),
        ("interlace", {"combing": 0.55, "twitter": 0.2}),
        ("crt", {"bloom": 0.38, "misconvergence": 0.5, "scan_strength": 0.1,
                 "curvature": 0.04, "vignette_crt": 0.2}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 9000.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.5, "release_ms": 220.0}),
        ("a_tv_sound", {"hz": "50", "buzz_db": -57.0, "hum_db": -60.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.78}),
    ],
    variants=[
        Variant("network-master", "Transmission Master",
                "The telecine transfer before it went to the transmitter: dye at full strength, encoder polite.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.3, "telecine_scan.hop_px": 0.25}),
        Variant("us-syndication-ntsc", "US Syndication Print",
                "Standards-converted for American stations: 3:2 judder arrives, and so does the hue drifting off the trench coats.",
                video={"ntsc.system": "ntsc", "ntsc.phase_noise": 2.5, "ntsc.rainbow": 0.3,
                       "ntsc.diff_phase": 1.6, "ntsc.dot_crawl": 0.28,
                       "cadence.pattern": "pulldown_judder", "grain.amount": 0.38},
                audio={"a_tv_sound.hz": "60"}),
    ],
))

# nearest: auth-analog-science-education-television-1974; differs: hotter saturation,
# a brighter street set and a film-insert path instead of a clean U-matic lecture.
register_preset(Preset(
    id="tv-public-kids-studio-1973",
    name="Public TV Kids Studio",
    family="broadcast",
    era="1973",
    desc="A brownstone stoop built inside a studio and lit hot for plumbicon tubes: pumped saturation, raised setup, beam bloom on the yellow feathers and a compressed console mono.",
    tagline="Bright plumbicon street set, warm mono",
    tags=("70s", "plumbicon", "television", "childrens", "pbs"),
    keywords=("sesame", "kids", "public-television", "seventies", "studio", "puppets",
              "street", "educational", "workshop", "warm"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.9}),
        ("tone", {"exposure": 0.1, "contrast": 1.02, "lift": 0.03, "knee": 0.8, "pivot": 0.45}),
        ("balance", {"warmth": 0.1, "high_tint": "cream", "high_amt": 0.1}),
        ("saturation", {"amount": 1.15, "vibrance": 0.15}),
        ("optics", {"veiling_flare": 0.12, "soft_focus": 0.04}),
        ("grain", {"enabled": False, "amount": 0.45, "size": 1.8, "chroma_grain": 0.18,
                   "stock": "doc_16", "layers": "color_neg"}),
        ("gate_weave", {"enabled": False, "amount": 0.9, "hz": 0.7, "splice_bump": 0.9}),
        ("fade", {"enabled": False, "amount": 0.1, "profile": "eastman_pink"}),
        ("phosphor_decay", {"decay": 0.35, "mode": "p22"}),
        ("ntsc", {"strength": 0.8, "luma_bw": 3.4, "chroma_bw": 0.75, "phase_noise": 2.0,
                  "setup_level": 0.06, "rainbow": 0.28, "dot_crawl": 0.3}),
        ("interlace", {"combing": 0.55, "twitter": 0.25}),
        ("crt", {"bloom": 0.42, "beam_bloom": 0.3, "misconvergence": 0.55,
                 "scan_strength": 0.1, "curvature": 0.04, "vignette_crt": 0.22}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 110.0, "high_hz": 7000.0}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.5, "release_ms": 280.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -56.0, "hum_db": -58.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.7}),
    ],
    variants=[
        Variant("film-insert-16mm", "16 mm Film Insert",
                "Cut to the filmed segment: grain, a hopping gate, a slightly pink print and no tube lag at all.",
                video={"grain.enabled": True, "gate_weave.enabled": True, "fade.enabled": True,
                       "phosphor_decay.decay": 0.06, "ntsc.strength": 0.6,
                       "saturation.amount": 1.02}),
        Variant("distribution-master", "Distribution Master",
                "The tape the stations were sent: the same hot set with the encoder behaving.",
                video={"ntsc.strength": 0.35, "ntsc.setup_level": 0.03, "crt.bloom": 0.3,
                       "crt.beam_bloom": 0.16}),
    ],
))

# nearest: auth-public-television-science-lecture-1968; differs: a glare-blown kitchen
# rather than a measured gray lecture, with 60 Hz hum riding the demonstration mic.
register_preset(Preset(
    id="tv-cooking-show-bw-1963",
    name="Black-and-White Cooking Show",
    family="broadcast",
    era="1963",
    desc="An image orthicon aimed at a copper pan under kitchen floods: highlights blow to white, the beam blooms around the whisk, and a dynamic mic picks up the hum in the studio wall.",
    tagline="Orthicon kitchen glare, chalkboard, hum mono",
    tags=("60s", "orthicon", "television", "monochrome", "instructional"),
    keywords=("cooking", "kitchen", "sixties", "bw", "public-television", "chef",
              "demonstration", "studio", "live", "how-to"),
    proc_height=520,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.1}),
        ("tone", {"exposure": 0.1, "contrast": 1.06, "lift": 0.03, "knee": 0.7, "pivot": 0.44}),
        ("optics", {"veiling_flare": 0.15, "soft_focus": 0.05}),
        ("grain", {"enabled": False, "amount": 0.4, "size": 1.65, "chroma_grain": 0.0,
                   "stock": "newsreel_35", "layers": "mono"}),
        ("dust", {"enabled": False, "density": 0.2, "hairs": 0.12}),
        ("phosphor_decay", {"decay": 0.35, "mode": "p22"}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.0, "chroma_bw": 0.5, "phase_noise": 1.0,
                  "rainbow": 0.04, "dot_crawl": 0.06}),
        ("interlace", {"combing": 0.6, "twitter": 0.35}),
        ("crt", {"bloom": 0.5, "beam_bloom": 0.4, "glass_glow": 0.15, "curvature": 0.04,
                 "scan_strength": 0.12, "vignette_crt": 0.28}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.6,
                              "proximity": 0.2, "overload": 0.2, "self_noise_db": -58.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.0, "release_ms": 300.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -54.0, "hum_db": -56.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.8}),
        ("a_hum", {"hz": "60", "level_db": -58.0, "buzz": 0.25}),
    ],
    variants=[
        Variant("station-master", "Station Master",
                "The line feed before it went out: still glaring off the copper, but the encoder is not adding to it.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.35, "crt.beam_bloom": 0.24},
                audio={"a_hum.level_db": -66.0, "a_tv_sound.buzz_db": -62.0}),
        Variant("kinescope-copy", "Kinescope Copy",
                "The only surviving copy: a 16 mm kinescope shot off a monitor, grain and dirt included.",
                video={"grain.enabled": True, "dust.enabled": True, "tone.contrast": 1.15,
                       "crt.bloom": 0.42, "interlace.combing": 0.35},
                audio={"a_bandlimit.high_hz": 5000.0, "a_historical_mic.self_noise_db": -50.0}),
    ],
))

# nearest: auth-paranormal-investigation-dv-2004; differs: a lit daytime DV house on
# an MPEG-2 cable feed, with the night-vision look held back in a variant.
register_preset(Preset(
    id="tv-reality-house-2001",
    name="Aughts Reality House",
    family="broadcast",
    era="2001",
    desc="Twenty cameras bolted to a house: 4:1:1 DV color with the edge enhancer on, an iris hunting every time somebody opens the fridge, and the whole thing squeezed into an MPEG-2 cable slot.",
    tagline="Mixed DV house cams, confessional AAC",
    tags=("00s", "minidv", "television", "unscripted", "cable"),
    keywords=("big-brother", "reality", "aughts", "house", "night-vision", "confessional",
              "dv", "cctv", "24-hour", "competition"),
    upscale="soft",
    video=[
        ("mono", {"enabled": False, "amount": 0.7, "response": "modern",
                  "tint": "phosphor_green", "tint_amt": 0.5}),
        ("tone", {"contrast": 1.05, "lift": 0.02, "knee": 0.82, "pivot": 0.44}),
        ("saturation", {"amount": 0.9, "vibrance": 0.08}),
        ("exposure_auto", {"target": 0.4, "lag": 0.8, "overshoot": 0.3, "max_boost": 3.0,
                           "agc_gain_noise": 0.5, "wb_amount": 0.3}),
        ("chroma_dv", {"ratio": "4:1:1", "edge_sharpen": 0.5, "dct_blocks": 0.15}),
        ("codec_era", {"codec": "mpeg2video", "kbps": 3500, "gop": 15,
                       "field_mode": "interlaced_tff"}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.2, "scan_strength": 0.08}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.005}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "lavalier_1972", "amount": 0.5, "proximity": 0.25,
                              "self_noise_db": -56.0}),
        ("a_agc", {"target_db": -15.0, "max_gain_db": 10.0, "amount": 0.6}),
        ("a_codec_aac", {"kbps": 96, "mono": False}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
    ],
    variants=[
        Variant("night-cam-ir", "Night Cam",
                "Lights out and the infrared cameras take over: everything one shade of green, gain wide open and grain crawling across the duvets.",
                video={"mono.enabled": True, "mono.amount": 0.85, "mono.tint_amt": 0.6,
                       "exposure_auto.max_boost": 6.0, "exposure_auto.agc_gain_noise": 0.9,
                       "chroma_dv.edge_sharpen": 0.8, "tone.lift": 0.06},
                audio={"a_historical_mic.self_noise_db": -48.0, "a_agc.max_gain_db": 16.0}),
        Variant("live-feed-web", "24-Hour Web Feed",
                "The subscription live stream: a postage stamp of a picture at whatever the modem could carry.",
                video={"codec_era.codec": "msmpeg4", "codec_era.kbps": 300,
                       "codec_era.res": "240p", "codec_era.field_mode": "progressive",
                       "chroma_dv.ratio": "4:2:0"},
                audio={"a_codec_aac.kbps": 32, "a_codec_aac.mono": True}),
    ],
))

# nearest: teal-orange-2012; differs: a broadcast reality chain, over-sharpened and
# H.264 delivered, rather than a theatrical grade.
register_preset(Preset(
    id="tv-reality-glossy-2013",
    name="Tens Glossy Reality",
    family="broadcast",
    era="2013",
    desc="Confessional HD with the contrast pushed and the detail knob abused: amber skin against teal walls, halos around every earring, and a delivery H.264 that gives up on the sequins.",
    tagline="HD gloss, orange-teal skin, sharpened jewelry",
    tags=("10s", "1080p", "television", "widescreen", "grade"),
    keywords=("reality", "housewives", "tens", "glossy", "hd", "orange-teal",
              "confessional", "drama", "sharpened", "bravo"),
    upscale="sharp",
    video=[
        ("tone", {"contrast": 1.1, "lift": 0.01, "knee": 0.85, "pivot": 0.44}),
        ("balance", {"warmth": 0.1, "shadow_tint": "teal", "shadow_amt": 0.2,
                     "high_tint": "yellow", "high_amt": 0.15}),
        ("saturation", {"amount": 1.15, "vibrance": 0.2}),
        ("optics", {"diffusion": 0.05}),
        ("sharpen", {"amount": 0.45, "radius": 0.9}),
        ("codec_era", {"codec": "h264", "crf": 24, "gop": 60, "res": "native"}),
        ("framing", {"aspect": "16:9", "mode": "box", "edge_soft": 0.003}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 40.0, "high_hz": 16000.0}),
        ("a_channel_aging", {"width": 1.1, "imbalance_db": -0.1, "crosstalk_db": -54.0,
                             "skew_us": 4.0, "mono_bass_hz": 80.0}),
        ("a_compressor", {"threshold_db": -16.0, "ratio": 4.0, "release_ms": 180.0,
                          "makeup_db": 2.0}),
        ("a_codec_aac", {"kbps": 128, "mono": False}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.2}),
    ],
    variants=[
        Variant("web-clip-720p", "Web Clip",
                "The scene everyone screenshotted, re-encoded small for the recap site.",
                video={"codec_era.crf": 30, "codec_era.res": "480p", "sharpen.amount": 0.3},
                audio={"a_codec_aac.kbps": 64}),
        Variant("broadcast-master", "Broadcast Master",
                "The delivery file before the cable plant got at it: the grade intact and the halos dialed back.",
                video={"codec_era.crf": 18, "sharpen.amount": 0.3},
                audio={"a_codec_aac.kbps": 256}),
    ],
))

# nearest: game-show-1978; differs: CCD cameras in 1992 mean no comet trails and no
# orange flesh, just a hard-lit saturated stage and applause on a plate.
register_preset(Preset(
    id="tv-game-show-1992",
    name="Nineties Game Show",
    family="broadcast",
    era="1992",
    desc="A daytime stage lit to the point of no shadows: saturation pushed into the prize signage, a mild sharpener on the podiums, clean CCD cameras and applause hitting a limiter.",
    tagline="Stage glare, saturated set, applause stereo",
    tags=("90s", "ntsc", "television", "ccd", "syndication"),
    keywords=("game-show", "price-is-right", "nineties", "contestants", "stage",
              "applause", "prizes", "wheel", "daytime", "studio"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"exposure": 0.08, "contrast": 1.04, "lift": 0.02, "knee": 0.7, "pivot": 0.46}),
        ("saturation", {"amount": 1.25, "vibrance": 0.2}),
        ("optics", {"veiling_flare": 0.1}),
        ("sharpen", {"amount": 0.2, "radius": 1.0}),
        ("ntsc", {"strength": 0.55, "luma_bw": 4.0, "chroma_bw": 1.1, "phase_noise": 1.5,
                  "rainbow": 0.2, "dot_crawl": 0.2}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.32, "chroma_noise": 0.34,
                 "sharpen": 0.5, "dropouts": 1.6, "time_base_error": 0.3, "head_switch": 0.65}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.35, "misconvergence": 0.4, "scan_strength": 0.08,
                 "vignette_crt": 0.16}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 12000.0}),
        ("a_room", {"mode": "plate1960", "size": 1.4, "decay_s": 0.8, "mix": 0.12,
                    "damp": 0.55, "predelay_ms": 12.0}),
        ("a_channel_aging", {"width": 1.05, "imbalance_db": -0.3, "crosstalk_db": -40.0,
                             "skew_us": 18.0, "mono_bass_hz": 110.0}),
        ("a_compressor", {"threshold_db": -21.0, "ratio": 4.5, "attack_ms": 6.0,
                          "release_ms": 180.0, "makeup_db": 2.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -60.0, "hum_db": -64.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.65}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The line cut on the 1-inch: the set is still shouting, the encoder is not.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.28},
                audio={"a_tv_sound.buzz_db": -68.0}),
        Variant("vhs-off-air", "Taped Off Air",
                "Recorded at eleven in the morning by somebody home sick, ads and all.",
                video={"vhs.enabled": True, "saturation.amount": 1.15},
                audio={"a_channel_aging.width": 0.85, "a_bandlimit.high_hz": 8000.0}),
    ],
))

# nearest: tv-game-show-1992; differs: hotter neon set with chroma AGC pumping, a live
# audience room and five-to-one compression on the screaming.
register_preset(Preset(
    id="tv-kids-game-show-1993",
    name="Kids Slime Game Show",
    family="broadcast",
    era="1993",
    desc="An obstacle course painted in fluorescent orange and green: saturation past what the encoder can carry, chroma AGC pumping on the slime, and an audience of children run through a hard compressor.",
    tagline="Neon set, slime green, screaming audience",
    tags=("90s", "ntsc", "television", "childrens", "studio"),
    keywords=("slime", "kids", "game-show", "nickelodeon", "nineties", "obstacle-course",
              "neon", "audience", "cable", "physical"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"exposure": 0.1, "contrast": 1.06, "lift": 0.02, "knee": 0.72, "pivot": 0.46}),
        ("balance", {"high_tint": "yellow", "high_amt": 0.15}),
        ("saturation", {"amount": 1.35, "vibrance": 0.3}),
        ("sharpen", {"amount": 0.15, "radius": 1.0}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.8, "chroma_bw": 1.0, "phase_noise": 1.8,
                  "chroma_agc": 0.1, "rainbow": 0.3, "dot_crawl": 0.28}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.34, "chroma_noise": 0.4,
                 "sharpen": 0.5, "dropouts": 2.0, "time_base_error": 0.32, "head_switch": 0.7}),
        ("interlace", {"combing": 0.5, "twitter": 0.22}),
        ("crt", {"bloom": 0.38, "misconvergence": 0.45, "scan_strength": 0.08,
                 "vignette_crt": 0.18}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 11000.0}),
        ("a_room", {"mode": "room", "size": 2.0, "decay_s": 0.9, "mix": 0.12,
                    "damp": 0.5, "predelay_ms": 14.0}),
        ("a_channel_aging", {"width": 1.0, "imbalance_db": -0.4, "crosstalk_db": -34.0,
                             "skew_us": 24.0, "mono_bass_hz": 120.0}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 5.0, "attack_ms": 5.0,
                          "release_ms": 160.0, "makeup_db": 2.5}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -58.0, "hum_db": -62.0, "comp": 0.55}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.65}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The tape the network archived: the same impossible orange with the encoder given a chance.",
                video={"ntsc.strength": 0.3, "ntsc.chroma_agc": 0.04, "crt.bloom": 0.3},
                audio={"a_tv_sound.buzz_db": -66.0}),
        Variant("vhs-off-cable", "Taped Off Cable",
                "Recorded after school on a tape already used twice, in the era when that was normal.",
                video={"vhs.enabled": True, "saturation.amount": 1.25},
                audio={"a_bandlimit.high_hz": 7500.0, "a_channel_aging.width": 0.8}),
    ],
))

# nearest: cable-news-1991; differs: 1986 network Betacam and a blue chroma-key desk
# instead of a satellite-smeared cable remote.
register_preset(Preset(
    id="tv-network-news-1986",
    name="Network Evening News",
    family="broadcast",
    era="1986",
    desc="Two studio cameras on an anchor desk with a blue key backdrop behind it: mild tube color, a lavalier through a broadcast limiter, and the nightly bulletin arriving clean at 6:30.",
    tagline="Betacam field, chroma-key desk, anchor mono",
    tags=("80s", "videotape", "television", "studio", "ntsc"),
    keywords=("network-news", "evening-news", "eighties", "anchor", "betacam",
              "chroma-key", "desk", "correspondents", "nightly", "authoritative"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.5}),
        ("tone", {"contrast": 1.08, "lift": 0.02, "knee": 0.84, "pivot": 0.45}),
        ("balance", {"warmth": -0.04, "shadow_tint": "blue", "shadow_amt": 0.22}),
        ("saturation", {"amount": 0.98, "vibrance": 0.04}),
        ("exposure_auto", {"enabled": False, "target": 0.45, "lag": 0.9, "overshoot": 0.35,
                           "max_boost": 2.4, "agc_gain_noise": 0.4, "wb_amount": 0.25}),
        ("phosphor_decay", {"decay": 0.2, "mode": "p22"}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.9, "chroma_bw": 1.0, "phase_noise": 1.6,
                  "rainbow": 0.18, "dot_crawl": 0.18}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.3, "misconvergence": 0.4, "scan_strength": 0.08,
                 "vignette_crt": 0.16}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "lavalier_1972", "amount": 0.6, "proximity": 0.3,
                              "self_noise_db": -60.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 8000.0}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 3.5, "release_ms": 240.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -60.0, "hum_db": -64.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.65}),
    ],
    variants=[
        Variant("field-package", "Correspondent Package",
                "Cut to the field: a Betacam iris chasing the light and a shade less bandwidth than the desk had.",
                video={"exposure_auto.enabled": True, "ntsc.luma_bw": 3.5,
                       "stock.strength": 0.7, "saturation.amount": 0.98,
                       "phosphor_decay.decay": 0.1},
                audio={"a_historical_mic.profile": "shotgun_1975",
                       "a_historical_mic.self_noise_db": -52.0}),
        Variant("studio-master", "Studio Master",
                "The network line feed: the key edge crisp, the anchor exactly as lit.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.24},
                audio={"a_tv_sound.buzz_db": -68.0}),
    ],
))

# nearest: auth-wrestling-broadcast-tape; differs: 1998 CCD cameras, pyro smoke veiling
# the lens and a stereo arena instead of crushed 1987 field tape.
register_preset(Preset(
    id="tv-monday-night-wrestling-1998",
    name="Monday-Night Wrestling",
    family="broadcast",
    era="1998",
    desc="Live from an arena with the pyro still hanging in the air: veiling flare across the lens, a video wall blooming behind the entrance ramp, and eighteen thousand people compressed into stereo.",
    tagline="Arena pyro bloom, glare, crowd stereo",
    tags=("90s", "ntsc", "television", "live", "stereo"),
    keywords=("wrestling", "attitude-era", "nineties", "arena", "pyro", "titantron",
              "crowd", "monday-night", "entrance", "cable"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"exposure": 0.1, "contrast": 1.18, "lift": 0.035, "knee": 0.7, "pivot": 0.44}),
        ("balance", {"warmth": 0.06, "high_tint": "yellow", "high_amt": 0.1}),
        ("saturation", {"amount": 1.28, "vibrance": 0.16}),
        ("optics", {"veiling_flare": 0.36, "aperture_ghost": 0.14}),
        ("ntsc", {"strength": 0.5, "luma_bw": 4.0, "chroma_bw": 1.1, "phase_noise": 1.4,
                  "rainbow": 0.16, "dot_crawl": 0.15}),
        ("vhs", {"enabled": False, "mode": "sp", "generation": 2, "luma_noise": 0.4,
                 "chroma_noise": 0.42, "sharpen": 0.55, "dropouts": 2.4,
                 "time_base_error": 0.4, "head_switch": 0.7}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.45, "beam_bloom": 0.3, "misconvergence": 0.4,
                 "scan_strength": 0.08, "vignette_crt": 0.18}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 13000.0}),
        ("a_room", {"mode": "room", "size": 2.8, "decay_s": 1.4, "mix": 0.15,
                    "damp": 0.45, "predelay_ms": 26.0}),
        ("a_channel_aging", {"width": 1.1, "imbalance_db": -0.2, "crosstalk_db": -44.0,
                             "skew_us": 12.0, "mono_bass_hz": 90.0}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 5.0, "attack_ms": 5.0,
                          "release_ms": 200.0, "makeup_db": 2.5}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -60.0, "hum_db": -64.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.65}),
    ],
    variants=[
        Variant("studio-master", "Truck Master",
                "Straight off the production truck: the crowd pulled back and the encoder out of the way.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.34},
                audio={"a_room.mix": 0.05, "a_tv_sound.buzz_db": -68.0}),
        Variant("vhs-tape-trade", "Traded Tape",
                "A second-generation dub that went through the mail twice before it got to you.",
                video={"vhs.enabled": True, "saturation.amount": 1.1},
                audio={"a_channel_aging.width": 0.8, "a_bandlimit.high_hz": 7000.0}),
    ],
))

# nearest: news-film-1975; differs: color negative on long lenses with an orchestral
# chamber and a baritone, cut as a highlight film rather than a news story.
register_preset(Preset(
    id="tv-sports-highlight-film-1975",
    name="Sports Highlight Film",
    family="broadcast",
    era="1975",
    desc="Long-lens 16 mm color negative shot at 48 frames and slowed down: grain crawling in the mud, corner softness off a 600 mm, and a baritone narrator in a scoring chamber.",
    tagline="Telephoto 16 mm grain, baritone narration",
    tags=("70s", "eastmancolor", "telecine", "narrated", "long-lens"),
    keywords=("nfl-films", "highlights", "football", "seventies", "16mm", "telephoto",
              "narration", "orchestral", "slow-motion", "sports-film"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.08, "lift": 0.02, "knee": 0.84, "pivot": 0.44}),
        ("balance", {"warmth": 0.06, "high_tint": "yellow", "high_amt": 0.08}),
        ("saturation", {"amount": 1.1, "vibrance": 0.1}),
        ("optics", {"soft_focus": 0.12, "focus_drift": 0.1, "corner_softness": 0.1,
                    "veiling_flare": 0.12}),
        ("grain", {"amount": 0.33, "size": 1.7, "chroma_grain": 0.12, "roughness": 0.45,
                   "stock": "doc_16", "layers": "color_neg"}),
        ("halation", {"strength": 0.3, "tint": "red_orange", "threshold": 0.74}),
        ("gate_weave", {"amount": 0.7, "hz": 0.6, "splice_bump": 0.8}),
        ("flicker", {"amount": 0.08, "character": "slow_drift", "spatial": 0.12}),
        ("dust", {"density": 0.2, "hairs": 0.12}),
        ("scratches", {"strength": 0.3, "count": 1, "transient_rate": 1.0}),
        ("fade", {"enabled": False, "amount": 0.15, "profile": "eastman_pink"}),
        ("ntsc", {"enabled": False, "strength": 0.7, "luma_bw": 3.6, "chroma_bw": 0.85,
                  "phase_noise": 2.0, "rainbow": 0.25, "dot_crawl": 0.25}),
        ("interlace", {"enabled": False, "combing": 0.55, "twitter": 0.25}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.5,
                              "proximity": 0.4, "self_noise_db": -60.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 10000.0}),
        ("a_room", {"mode": "chamber", "size": 1.6, "decay_s": 1.2, "mix": 0.1,
                    "damp": 0.6, "predelay_ms": 20.0}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.0, "release_ms": 300.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.35}),
    ],
    variants=[
        Variant("tv-broadcast-1976", "Sunday Broadcast",
                "The same reel going out on a network pregame show, film chain and fields included.",
                video={"ntsc.enabled": True, "interlace.enabled": True, "grain.amount": 0.3},
                audio={"a_bandlimit.high_hz": 7000.0, "a_speaker.strength": 0.7}),
        Variant("museum-print", "Hall of Fame Print",
                "The projection print that has been run for visitors twice an hour since 1979.",
                video={"dust.density": 0.5, "dust.hairs": 0.3, "scratches.count": 3,
                       "fade.enabled": True, "gate_weave.amount": 1.1}),
    ],
))

# nearest: golf-sunday-1977; differs: a hard-lit stadium with chroma AGC pumping on the
# turf and an iris hunting the shadow line, not soft long-lens greens.
register_preset(Preset(
    id="tv-sports-broadcast-1984",
    name="Eighties Sports Broadcast",
    family="broadcast",
    era="1984",
    desc="Tube cameras on a stadium rim in October: the turf pumped until the chroma AGC gives up, the iris stepping every time the shot crosses the shadow line, crowd on one channel.",
    tagline="Tube glare on turf, chyron score, crowd mono",
    tags=("80s", "tube-camera", "ntsc", "live", "outside-broadcast"),
    keywords=("sports", "football", "eighties", "broadcast", "chyron", "network",
              "stadium", "turf", "replay", "announcers"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.7}),
        ("tone", {"contrast": 1.05, "lift": 0.02, "knee": 0.78, "pivot": 0.45}),
        ("balance", {"warmth": 0.02}),
        ("saturation", {"amount": 1.15, "vibrance": 0.12}),
        ("exposure_auto", {"target": 0.45, "lag": 0.8, "overshoot": 0.35, "max_boost": 2.2,
                           "agc_gain_noise": 0.3, "wb_amount": 0.22, "iris_step": 0.3}),
        ("phosphor_decay", {"decay": 0.3, "mode": "p22"}),
        ("ntsc", {"strength": 0.75, "luma_bw": 3.6, "chroma_bw": 0.85, "phase_noise": 2.2,
                  "chroma_agc": 0.15, "diff_phase": 1.4, "rainbow": 0.3, "dot_crawl": 0.3}),
        ("vhs", {"enabled": False, "mode": "ep", "luma_noise": 0.3, "chroma_noise": 0.3,
                 "sharpen": 0.4, "dropouts": 2.4, "time_base_error": 0.42, "head_switch": 0.7}),
        ("interlace", {"combing": 0.55, "twitter": 0.24}),
        ("crt", {"bloom": 0.4, "beam_bloom": 0.3, "misconvergence": 0.55,
                 "scan_strength": 0.1, "vignette_crt": 0.2}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 110.0, "high_hz": 7500.0}),
        ("a_room", {"mode": "room", "size": 3.0, "decay_s": 1.2, "mix": 0.12,
                    "damp": 0.5, "predelay_ms": 28.0}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 4.0, "release_ms": 220.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -55.0, "hum_db": -58.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.7}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "The truck feed with the iris locked and the encoder lined up: still tube color, no pumping.",
                video={"exposure_auto.enabled": False, "ntsc.strength": 0.35,
                       "ntsc.chroma_agc": 0.04, "crt.bloom": 0.3},
                audio={"a_tv_sound.buzz_db": -64.0}),
        Variant("vhs-timer-ep", "Taped in EP",
                "Six hours of Sunday on one cassette, so the turf goes to soup by the fourth quarter.",
                video={"vhs.enabled": True, "saturation.amount": 1.05},
                audio={"a_bandlimit.high_hz": 6000.0}),
    ],
))

# nearest: tv-sports-broadcast-1984; differs: 1995 Betacam CCDs, a sharpened glossy
# picture on an aperture-grille set and stereo crowd instead of pumping tubes.
register_preset(Preset(
    id="tv-sports-broadcast-1995",
    name="Nineties Sports Broadcast",
    family="broadcast",
    era="1995",
    desc="Betacam SP off a stadium rim with the detail enhancer up: crisp jersey numbers, a persistent score box in the corner, an aperture grille on the living-room set and a stereo crowd.",
    tagline="Betacam SP gloss, score box, stereo crowd",
    tags=("90s", "ntsc", "television", "live", "outside-broadcast"),
    keywords=("sports", "nineties", "betacam", "score-box", "glossy", "stadium",
              "network", "replay", "fox", "stereo"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.1, "lift": 0.015, "knee": 0.8, "pivot": 0.45}),
        ("saturation", {"amount": 1.15, "vibrance": 0.1}),
        ("sharpen", {"amount": 0.25, "radius": 0.9}),
        ("ntsc", {"strength": 0.45, "luma_bw": 4.2, "chroma_bw": 1.2, "phase_noise": 1.2,
                  "rainbow": 0.12, "dot_crawl": 0.12}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.2, "chroma_noise": 0.24,
                 "sharpen": 0.45, "dropouts": 1.0, "time_base_error": 0.22,
                 "head_switch": 0.55}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.3, "misconvergence": 0.3, "phosphor_mask": "grille",
                 "mask_strength": 0.03, "mask_scale": 3.6, "scan_strength": 0.06}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 13000.0}),
        ("a_room", {"mode": "room", "size": 3.0, "decay_s": 1.1, "mix": 0.1,
                    "damp": 0.5, "predelay_ms": 24.0}),
        ("a_channel_aging", {"width": 1.15, "imbalance_db": -0.2, "crosstalk_db": -46.0,
                             "skew_us": 10.0, "mono_bass_hz": 85.0}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 4.0, "release_ms": 200.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -62.0, "hum_db": -66.0, "comp": 0.4}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.6}),
    ],
    variants=[
        Variant("studio-master", "Truck Master",
                "Off the truck before the plant: the sharpening still there, the composite almost gone.",
                video={"ntsc.strength": 0.2, "crt.mask_strength": 0.015, "crt.bloom": 0.24},
                audio={"a_tv_sound.buzz_db": -70.0}),
        Variant("svhs-timer", "S-VHS Timer Tape",
                "Recorded on the good tape at SP, because this one was worth keeping.",
                video={"vhs.enabled": True},
                audio={"a_channel_aging.width": 0.95, "a_bandlimit.high_hz": 10000.0}),
    ],
))

# nearest: quadruplex-variety-1958; differs: an arena blast rather than a studio, with
# cigarette smoke veiling the lens and a ringside room under the mono.
register_preset(Preset(
    id="tv-boxing-broadcast-1962",
    name="Boxing Broadcast",
    family="broadcast",
    era="1962",
    desc="Ring lights straight into an image orthicon while the arena smokes: whites blown to paper, a veiling haze over the ropes, comet trails off the gloves and a ringside mic in a hard room.",
    tagline="Orthicon ring blast, smoke, ringside mono",
    tags=("60s", "tube-camera", "television", "live", "monochrome"),
    keywords=("boxing", "sixties", "bw", "ring", "fight-night", "arena", "orthicon",
              "smoke", "ringside", "gillette"),
    proc_height=520,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.08}),
        ("tone", {"exposure": 0.15, "contrast": 1.1, "lift": 0.03, "knee": 0.66, "pivot": 0.44}),
        ("optics", {"veiling_flare": 0.38, "soft_focus": 0.07}),
        ("grain", {"enabled": False, "amount": 0.4, "size": 1.65, "chroma_grain": 0.0,
                   "stock": "newsreel_35", "layers": "mono"}),
        ("dust", {"enabled": False, "density": 0.3, "hairs": 0.16}),
        ("phosphor_decay", {"decay": 0.4, "mode": "p22"}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.1, "chroma_bw": 0.5, "phase_noise": 1.2,
                  "rainbow": 0.04, "dot_crawl": 0.06}),
        ("interlace", {"combing": 0.6, "twitter": 0.35}),
        ("crt", {"bloom": 0.5, "beam_bloom": 0.45, "glass_glow": 0.15, "curvature": 0.04,
                 "scan_strength": 0.12, "vignette_crt": 0.3}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.6,
                              "proximity": 0.25, "overload": 0.25, "self_noise_db": -56.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 130.0, "high_hz": 6000.0}),
        ("a_room", {"mode": "room", "size": 2.5, "decay_s": 1.2, "mix": 0.15,
                    "damp": 0.45, "predelay_ms": 22.0}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 4.0, "release_ms": 240.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -54.0, "hum_db": -56.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.8}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "The line feed on a good night: the blast is still there, the encoder is not making it worse.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.35, "crt.beam_bloom": 0.28},
                audio={"a_tv_sound.buzz_db": -62.0}),
        Variant("kinescope-archive", "Kinescope Archive",
                "All that is left of the fight: a 16 mm kinescope with a decade of dirt on it.",
                video={"grain.enabled": True, "dust.enabled": True, "tone.contrast": 1.18,
                       "interlace.combing": 0.3},
                audio={"a_bandlimit.high_hz": 5000.0, "a_historical_mic.self_noise_db": -48.0}),
    ],
))

# nearest: tv-game-show-1992; differs: the loudest chain in the family, sharpened and
# waxed with a tape-saturated stereo instead of a flat daytime stage.
register_preset(Preset(
    id="tv-network-promo-1994",
    name="Nineties Network Promo",
    family="broadcast",
    era="1994",
    desc="Thirty seconds cut to sell Thursday: contrast and saturation past legal, a noise reducer waxing the faces so the sharpener can put a ring on them, and a stereo mix mashed into a limiter.",
    tagline="Fast-cut promo gloss, saturated, loud stereo",
    tags=("90s", "ntsc", "television", "stereo", "interstitial"),
    keywords=("promo", "network", "nineties", "must-see", "fall-preview", "glossy",
              "bumper", "saturated", "loud", "ident"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.15, "lift": 0.01, "knee": 0.78, "pivot": 0.44}),
        ("saturation", {"amount": 1.25, "vibrance": 0.25}),
        ("dvnr", {"strength": 0.15, "wax": 0.18}),
        ("sharpen", {"amount": 0.45, "radius": 0.9}),
        ("ntsc", {"strength": 0.4, "luma_bw": 4.2, "chroma_bw": 1.3, "phase_noise": 1.0,
                  "rainbow": 0.1, "dot_crawl": 0.1}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_noise": 0.32, "chroma_noise": 0.34,
                 "sharpen": 0.5, "dropouts": 1.6, "time_base_error": 0.3, "head_switch": 0.65}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.28, "phosphor_mask": "grille", "mask_strength": 0.03,
                 "mask_scale": 3.6, "scan_strength": 0.06}),
        ("vignette", {"amount": 0.15, "softness": 0.8}),
        ("framing", {"aspect": "4:3", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 13000.0}),
        ("a_tape_sat", {"drive": 1.5, "bump_db": 3.0, "hf_loss": 0.15, "eq_era": "modern"}),
        ("a_channel_aging", {"width": 1.2, "imbalance_db": -0.2, "crosstalk_db": -46.0,
                             "skew_us": 8.0, "mono_bass_hz": 85.0}),
        ("a_compressor", {"threshold_db": -24.0, "ratio": 5.0, "attack_ms": 4.0,
                          "release_ms": 140.0, "makeup_db": 3.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -64.0, "hum_db": -68.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.6}),
    ],
    variants=[
        Variant("studio-master", "Promo Department Master",
                "The version before the loudness war: same cut, half the compression and a clean composite.",
                video={"ntsc.strength": 0.2, "sharpen.amount": 0.3, "dvnr.wax": 0.08},
                audio={"a_compressor.ratio": 3.0, "a_compressor.makeup_db": 1.0,
                       "a_tape_sat.drive": 1.1}),
        Variant("vhs-timer", "Caught on a Timer Tape",
                "The promo that survived because it sat between two acts of something else.",
                video={"vhs.enabled": True, "saturation.amount": 1.15},
                audio={"a_channel_aging.width": 0.85, "a_bandlimit.high_hz": 8000.0}),
    ],
))
