"""Broadcast-family presets, second wave: local air, network iron and the far fringe."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="fantasy-sitcom-1964",
    name="Network Fantasy Sitcom",
    family="broadcast",
    era="1964",
    desc="A polished 35mm network print: luminous black-and-white faces, diffused soundstage practicals and tidy optical tricks softened by a careful film-to-broadcast chain.",
    tagline="Luminous faces, tidy tricks, soft broadcast",
    tags=("60s", "sitcom", "fantasy", "35mm", "network"),
    proc_height=600,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.0}),
        ("balance", {"warmth": 0.1, "high_tint": "cream", "high_amt": 0.14}),
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.18}),
        ("tone", {"contrast": 1.1, "lift": 0.035, "knee": 0.84, "pivot": 0.45}),
        ("saturation", {"amount": 1.06, "vibrance": 0.1}),
        ("optics", {"soft_focus": 0.12, "diffusion": 0.22, "corner_softness": 0.08,
                    "focus_drift": 0.05}),
        ("optical_composite", {"softness": 0.14, "matte_line": 0.14, "registration": 0.0,
                               "layer_haze": 0.08, "density_breath": 0.14}),
        ("grain", {"amount": 0.3, "size": 1.8, "chroma_grain": 0.0, "stock": "fine_35",
                   "layers": "print_from_neg", "mottle": 0.1}),
        ("halation", {"strength": 0.26, "tint": "neutral", "threshold": 0.75}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.18, "acutance": 0.22}),
        ("gate_weave", {"amount": 0.6, "splice_bump": 0.4}),
        ("flicker", {"amount": 0.08, "spatial": 0.1}),
        ("dust", {"density": 0.28, "hairs": 0.14}),
        ("scratches", {"count": 1, "transient_rate": 0.3}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.2}),
        ("ntsc", {"strength": 0.22, "luma_bw": 4.6, "chroma_bw": 1.2,
                  "phase_noise": 0.6, "rainbow": 0.08, "dot_crawl": 0.06}),
        ("interlace", {"combing": 0.18, "twitter": 0.1}),
        ("crt", {"scan_strength": 0.04, "bloom": 0.18, "glass_glow": 0.08}),
        ("vignette", {"amount": 0.2, "softness": 0.75}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 7600.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"size": 0.8, "decay_s": 0.42, "mix": 0.1, "mode": "room"}),
        ("a_optical_track", {"low_hz": 100.0, "high_hz": 7000.0, "academy_rolloff": "none",
                             "cell_noise": -52.0, "flutter": 0.3, "drive": 1.35}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.5, "attack_ms": 8.0,
                          "release_ms": 220.0}),
    ],
    variants=[
        Variant("early-color", "Early Color Episode", "The color-season print: warm faces, candy interiors and a little chroma wandering off the props.",
                video={"stock.strength": 0.8, "mono.amount": 0.0, "grain.chroma_grain": 0.16,
                       "halation.tint": "orange", "optical_composite.registration": 0.22,
                       "ntsc.phase_noise": 1.6, "ntsc.diff_phase": 0.8,
                       "ntsc.chroma_agc": 0.12, "crt.bloom": 0.24}),
        Variant("magic-trick", "Magic Trick Insert", "The effects shot: a softer optical generation, visible matte seams and stronger diffusion.",
                video={"optical_composite.softness": 0.38, "optical_composite.matte_line": 0.48,
                       "optical_composite.registration": 0.42, "optical_composite.layer_haze": 0.18,
                       "optics.diffusion": 0.3}),
        Variant("network-negative", "Network Vault Print", "The protected network element: finer grain, steadier gate and only a breath of composite softness.",
                video={"grain.amount": 0.22, "dust.density": 0.12, "scratches.count": 0,
                       "gate_weave.amount": 0.35, "ntsc.strength": 0.1,
                       "optical_composite.softness": 0.08},
                audio={"a_optical_track.cell_noise": -57.0}),
    ],
))

register_preset(Preset(
    id="color-premiere-1966",
    name="Color Spectacular",
    family="broadcast",
    era="1966",
    desc="The night the peacock spread its tail: showroom saturation, bright faces drifting sunburn-orange as the transmitter overdrives, the receiver's color AGC quietly hunting.",
    tagline="Sunburn faces, chroma hunting, guns adrift",
    tags=("60s", "color", "ntsc", "studio"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.1, "lift": 0.035, "knee": 0.8}),
        ("saturation", {"amount": 1.28, "vibrance": 0.1}),
        ("ntsc", {"strength": 1.0, "phase_noise": 2.0, "diff_phase": 3.0, "chroma_agc": 0.4,
                  "rainbow": 0.35, "dot_crawl": 0.35, "chroma_bw": 0.55}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.18, "bloom": 0.5, "curvature": 0.14, "misconvergence": 0.9,
                 "vignette_crt": 0.25}),
        ("framing", {"aspect": "source", "corner_radius": 0.09}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -44.0}),
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_tube_amp", {"drive": 2.0, "sag": 0.4, "hum_db": -56.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.6}),
    ],
    variants=[
        Variant("showroom", "Appliance Showroom", "The floor model with everything turned to eleven.",
                video={"saturation.amount": 1.45, "crt.bloom": 0.6, "ntsc.diff_phase": 4.0}),
        Variant("rooftop-antenna", "Rooftop Antenna", "The same premiere, four suburbs out.",
                video={"ntsc.phase_noise": 3.5, "crt.misconvergence": 1.2},
                audio={"a_tv_sound.buzz_db": -38.0}),
    ],
))

register_preset(Preset(
    id="pbs-pledge-1983",
    name="Pledge Drive",
    family="broadcast",
    era="1983",
    desc="Channel 13 at hour four: soft patient cameras, folding tables and phone volunteers, fluorescent hum in the walls, a tote bag if you call in the next ten minutes.",
    tagline="Soft cameras, mild tape noise, room hum",
    tags=("80s", "pbs", "studio"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.7}),
        ("tone", {"contrast": 1.02, "lift": 0.03, "knee": 0.84}),
        ("saturation", {"amount": 0.98}),
        ("optics", {"diffusion": 0.18, "soft_focus": 0.08}),
        ("phosphor_decay", {"decay": 0.2, "mode": "p22"}),
        ("ntsc", {"strength": 0.8, "phase_noise": 1.8, "rainbow": 0.22, "dot_crawl": 0.25}),
        ("vhs", {"mode": "sp", "luma_bw": 4.0, "luma_noise": 0.25, "chroma_noise": 0.3,
                 "head_switch": 0.3, "time_base_error": 0.2, "flagging": 0.1, "dropouts": 0.3,
                 "sharpen": 0.45}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.5}),
        ("a_hum", {"hz": 60, "buzz": 0.4, "level_db": -48.0}),
        ("a_bed", {"bed": "fluorescent_office", "level_db": -38.0, "duck": 0.4}),
    ],
    variants=[
        Variant("phone-bank", "Phone Bank Wide Shot", "Twelve ringing lines and the hum turned up.",
                audio={"a_hum.level_db": -44.0, "a_bed.level_db": -32.0, "a_agc.amount": 0.7}),
    ],
))

register_preset(Preset(
    id="car-dealer-ad-1986",
    name="Car Dealer Spot",
    family="broadcast",
    era="1986",
    desc="Thirty seconds of NO MONEY DOWN: chroma cranked past legal, edges sharpened to a whine, the owner's kid hollering through a PA compressor. Sunday! Sunday! Sunday!",
    tagline="Illegal chroma, whining edges, shouted mix",
    tags=("80s", "local", "commercial"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.75}),
        ("tone", {"contrast": 1.12, "lift": 0.02, "knee": 0.78}),
        ("saturation", {"amount": 1.28, "vibrance": 0.15}),
        ("ntsc", {"strength": 0.9, "phase_noise": 2.8, "rainbow": 0.35, "dot_crawl": 0.35}),
        ("vhs", {"mode": "sp", "luma_bw": 3.8, "luma_noise": 0.4, "chroma_noise": 0.5,
                 "head_switch": 0.5, "time_base_error": 0.35, "flagging": 0.2, "dropouts": 0.6,
                 "sharpen": 0.85}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 6.0, "threshold_db": -24.0, "attack_ms": 3.0, "makeup_db": 5.0}),
        ("a_distortion", {"type": "soft", "drive": 1.8}),
        ("a_agc", {"amount": 0.6}),
    ],
    variants=[
        Variant("cable-run", "Cable Insert Reel", "Dubbed once more for the cable head-end.",
                video={"vhs.generation": 2, "vhs.luma_noise": 0.5, "ntsc.phase_noise": 3.6},
                audio={"a_distortion.drive": 2.4}),
        Variant("year-end", "Year-End Blowout", "Louder. Somehow louder.",
                video={"saturation.amount": 1.4, "vhs.sharpen": 1.0},
                audio={"a_compressor.ratio": 9.0, "a_distortion.drive": 2.6}),
    ],
))

register_preset(Preset(
    id="closed-circuit-1970",
    name="Closed-Circuit Feed",
    family="broadcast",
    era="1970",
    desc="The building's own channel: vidicon gray with a rumor of color, flyback lines ghosting up through the dark, the intercom horn in the ceiling doing the talking.",
    tagline="Vidicon gray, flyback lines, ceiling horn",
    tags=("70s", "cctv", "institutional"),
    proc_height=480,
    upscale="soft",
    video=[
        ("saturation", {"amount": 0.2}),
        ("tone", {"contrast": 1.08, "lift": 0.07, "knee": 0.78}),
        ("optics", {"corner_softness": 0.3, "distortion": 0.1}),
        ("phosphor_decay", {"decay": 0.35, "mode": "p22"}),
        ("ntsc", {"strength": 0.6, "phase_noise": 1.5, "rainbow": 0.1, "dot_crawl": 0.15}),
        ("signal_rf", {"snow": 0.12, "ghost_alpha": 0.0, "hum_bar": 0.25, "hum_speed": 0.1}),
        ("interlace", {"combing": 0.5, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.2, "bloom": 0.35, "curvature": 0.16, "retrace_lines": 0.3,
                 "vignette_crt": 0.35}),
        ("framing", {"aspect": "source", "corner_radius": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 200.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "intercom_horn_1950", "strength": 0.75}),
        ("a_hum", {"hz": 60, "buzz": 0.5, "level_db": -42.0}),
        ("a_bed", {"bed": "fluorescent_office", "level_db": -36.0, "duck": 0.3}),
    ],
    variants=[
        Variant("lobby-monitor", "Lobby Monitor", "The tube by the elevators, brightness maxed for years.",
                video={"crt.retrace_lines": 0.5, "signal_rf.hum_bar": 0.4, "tone.lift": 0.1},
                audio={"a_hum.level_db": -38.0}),
    ],
))

register_preset(Preset(
    id="sign-off-1979",
    name="Sign-Off",
    family="broadcast",
    era="1979",
    desc="After the anthem: the transmitter left breathing on its own - color AGC sighing, sync leaning under bright frames, a hum bar strolling up into the small hours.",
    tagline="Sighing color AGC, leaning sync, hum bar",
    tags=("70s", "late-night", "melancholy"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.05, "lift": 0.045, "knee": 0.8}),
        ("saturation", {"amount": 0.92}),
        ("ntsc", {"strength": 0.95, "phase_noise": 2.8, "chroma_agc": 0.5, "sync_jitter": 0.35,
                  "rainbow": 0.3, "dot_crawl": 0.3}),
        ("signal_rf", {"snow": 0.15, "ghost_px": 10.0, "ghost_alpha": 0.1, "hum_bar": 0.22,
                       "hum_speed": 0.07}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"scan_strength": 0.15, "bloom": 0.4, "curvature": 0.12, "vignette_crt": 0.3,
                 "glass_glow": 0.15}),
        ("framing", {"aspect": "source", "corner_radius": 0.08}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -46.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_tube_amp", {"drive": 1.8, "sag": 0.5, "hum_db": -50.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.6}),
        ("a_hum", {"hz": 60, "level_db": -46.0}),
    ],
    variants=[
        Variant("adrift", "Nearly Gone", "The engineer is asleep and the signal knows it.",
                video={"ntsc.chroma_agc": 0.8, "ntsc.sync_jitter": 0.6, "signal_rf.snow": 0.35,
                       "signal_rf.weak_signal": 0.25},
                audio={"a_hum.level_db": -40.0}),
    ],
))

register_preset(Preset(
    id="morning-block-1990",
    name="Syndicated Morning",
    family="broadcast",
    era="1990",
    desc="Cheap and cheerful at 7 AM: bright pumped color, comet trails on the mascot suit, every jingle compressed to sell cereal to the back row.",
    tagline="Pumped color, comet trails, loud jingles",
    tags=("90s", "syndication", "kids"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.6}),
        ("tone", {"contrast": 1.08, "lift": 0.02, "knee": 0.82}),
        ("saturation", {"amount": 1.18, "vibrance": 0.15}),
        ("phosphor_decay", {"decay": 0.15, "mode": "p22"}),
        ("ntsc", {"strength": 0.8, "phase_noise": 2.0, "rainbow": 0.25, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "luma_bw": 4.0, "luma_noise": 0.3, "chroma_noise": 0.35,
                 "head_switch": 0.4, "time_base_error": 0.25, "flagging": 0.15, "dropouts": 0.4,
                 "sharpen": 0.7}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.32, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 11000.0}),
        ("a_compressor", {"ratio": 4.0, "makeup_db": 2.0}),
        ("a_agc", {"amount": 0.45}),
        ("a_tape_hiss", {"level_db": -48.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.3}),
    ],
    variants=[
        Variant("rerun-decade", "Decade-Old Rerun", "The syndication print has been around the block.",
                video={"vhs.generation": 3, "vhs.luma_noise": 0.45, "vhs.dropouts": 1.2,
                       "ntsc.phase_noise": 3.0},
                audio={"a_tape_hiss.level_db": -42.0}),
    ],
))

register_preset(Preset(
    id="uhf-horror-host-1971",
    name="UHF Creature Feature",
    family="broadcast",
    era="1971",
    desc="Channel 62 at midnight: snow that never melts, a herringbone weave from the next channel over, a lamp reflected in the tube glass, the host's cackle buzzing a three-inch speaker.",
    tagline="Permanent snow, herringbone, tube glare",
    tags=("70s", "uhf", "horror", "late-night"),
    proc_height=500,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.1, "lift": 0.06, "knee": 0.76}),
        ("saturation", {"amount": 0.82}),
        ("ntsc", {"strength": 0.95, "phase_noise": 3.0, "rainbow": 0.35, "dot_crawl": 0.3}),
        ("signal_rf", {"snow": 0.5, "sparkle": 2.5, "ghost_px": 16.0, "ghost_alpha": 0.2,
                       "weak_signal": 0.35, "impulse_noise": 0.3}),
        ("herringbone", {"amount": 0.22, "pattern": "herringbone", "wavelength": 6.0, "drift": 0.8}),
        ("interlace", {"combing": 0.5, "twitter": 0.35}),
        ("crt", {"scan_strength": 0.22, "bloom": 0.45, "curvature": 0.16, "vignette_crt": 0.35,
                 "glare": 0.25, "glare_pos": "tr"}),
        ("framing", {"aspect": "source", "corner_radius": 0.1}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -38.0}),
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.75}),
        ("a_hum", {"hz": 60, "buzz": 0.4, "level_db": -44.0}),
    ],
    variants=[
        Variant("bw-set", "On the B&W Portable", "Watched from the bedroom set, sound down low.",
                video={"saturation.amount": 0.0, "crt.curvature": 0.2, "signal_rf.snow": 0.6},
                audio={"a_speaker.device": "transistor_pocket_1965", "a_speaker.strength": 0.8}),
        Variant("antenna-wiggle", "Go Jiggle the Antenna", "Somebody moved and the ghosts noticed.",
                video={"signal_rf.ghost_alpha": 0.35, "signal_rf.snow": 0.65,
                       "herringbone.amount": 0.35}),
    ],
))

register_preset(Preset(
    id="network-feed-raw-1988",
    name="Network Backhaul",
    family="broadcast",
    era="1988",
    desc="The bird feed before the affiliate dresses it: pristine studio color, comms-clean sound, and every so often the microwave hop shatters a frame and pretends it didn't.",
    tagline="Pristine studio color, rare hop shatter",
    tags=("80s", "satellite", "feed", "clean"),
    proc_height=600,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.07, "lift": 0.01, "knee": 0.86}),
        ("ntsc", {"strength": 0.5, "phase_noise": 1.0, "rainbow": 0.15, "dot_crawl": 0.15}),
        ("signal_rf", {"snow": 0.06, "sparkle": 2.5, "ghost_alpha": 0.0, "impulse_noise": 0.2}),
        ("vhs", {"mode": "sp", "luma_bw": 4.8, "chroma_bw": 0.8, "luma_noise": 0.12,
                 "chroma_noise": 0.15, "head_switch": 0.0, "flagging": 0.0, "jitter_v": 0.05,
                 "time_base_error": 0.1, "dropouts": 0.1, "sharpen": 0.55}),
        ("microwave_hit", {"rate": 0.8, "strength": 0.85}),
        ("interlace", {"combing": 0.55}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 14000.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_dat_error", {"error_rate": 2.0, "mute_rate": 0.2}),
        ("a_tape_hiss", {"level_db": -54.0}),
    ],
    variants=[
        Variant("rain-fade", "Rain Fade", "A storm cell between the dishes.",
                video={"microwave_hit.rate": 6.0, "signal_rf.snow": 0.2,
                       "signal_rf.impulse_noise": 1.5},
                audio={"a_dat_error.error_rate": 12.0, "a_dat_error.mute_rate": 2.0}),
    ],
))

register_preset(Preset(
    id="golf-sunday-1977",
    name="Sunday Golf",
    family="broadcast",
    era="1977",
    desc="Whispered commentary over eight acres of noisy green: tube cameras on long soft lenses, chroma boiling gently in the fairways, applause arriving like distant rain.",
    tagline="Soft long lens, chroma boiling in green",
    tags=("70s", "sports", "outdoor"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.06, "lift": 0.03, "knee": 0.8}),
        ("optics", {"soft_focus": 0.15, "corner_softness": 0.25, "chromatic_aberration": 0.8}),
        ("phosphor_decay", {"decay": 0.15, "mode": "p22"}),
        ("ntsc", {"strength": 0.95, "phase_noise": 2.5, "chroma_bw": 0.4, "rainbow": 0.3,
                  "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "luma_bw": 3.6, "luma_noise": 0.3, "chroma_noise": 0.5,
                 "head_switch": 0.3, "time_base_error": 0.25, "flagging": 0.1, "dropouts": 0.3,
                 "sharpen": 0.4}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.12, "curvature": 0.1}),
        ("framing", {"aspect": "source", "corner_radius": 0.08}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 2.5, "release_ms": 600.0}),
        ("a_agc", {"amount": 0.5}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.5}),
        ("a_hum", {"hz": 60, "level_db": -52.0}),
    ],
    variants=[
        Variant("final-round", "Final Round Sun", "High glare, deeper greens, hotter chroma noise.",
                video={"tone.exposure": 0.15, "vhs.chroma_noise": 0.6, "ntsc.phase_noise": 3.0}),
        Variant("source-clean", "Source-Clean Transfer",
                "Preserves the period carrier and color response while disabling momentary source loss or masking.",
                video={"framing.corner_radius": 0.0}),
    ],
))

register_preset(Preset(
    id="cable-news-1991",
    name="Cable News Desk",
    family="broadcast",
    era="1991",
    desc="The 24-hour desk during the big story: clean studio cameras, a satellite window's smeared remote, AGC riding every anchor breath - urgency as a house style.",
    tagline="Clean studio, smeared remote, riding AGC",
    tags=("90s", "news", "cable"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.07, "lift": 0.015, "knee": 0.85}),
        ("saturation", {"amount": 1.06}),
        ("phosphor_decay", {"decay": 0.12, "mode": "p22"}),
        ("ntsc", {"strength": 0.6, "phase_noise": 1.2, "rainbow": 0.18, "dot_crawl": 0.2}),
        ("vhs", {"mode": "sp", "luma_bw": 4.4, "luma_noise": 0.18, "chroma_noise": 0.22,
                 "head_switch": 0.2, "time_base_error": 0.15, "flagging": 0.05, "dropouts": 0.2,
                 "sharpen": 0.65}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.25, "scan_strength": 0.08}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 10000.0}),
        ("a_agc", {"amount": 0.6}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tape_hiss", {"level_db": -50.0}),
    ],
    variants=[
        Variant("tape-archive", "Aircheck Tape", "The master control VHS that kept the receipts.",
                video={"vhs.generation": 2, "vhs.luma_noise": 0.35, "vhs.chroma_noise": 0.4,
                       "ntsc.strength": 0.85, "vhs.head_switch": 0.5},
                audio={"a_tape_hiss.level_db": -44.0}),
        Variant("live-shot", "Satellite Live Shot", "The remote window takes over the frame.",
                video={"vhs.luma_noise": 0.3, "vhs.time_base_error": 0.3, "ntsc.phase_noise": 2.0},
                audio={"a_bandlimit.high_hz": 7000.0, "a_compressor.ratio": 6.0}),
    ],
))

register_preset(Preset(
    id="local-morning-1985",
    name="Local Morning Show",
    family="broadcast",
    era="1985",
    desc="Rise and shine with Channel 8: cream-warm studio light, gentle diffusion on the hosts, and the kitchen-counter set's rabbit ears doing their modest best.",
    tagline="Cream diffusion, faint ghost, light snow",
    tags=("80s", "local", "morning", "studio"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.8}),
        ("balance", {"warmth": 0.2, "high_tint": "cream", "high_amt": 0.3}),
        ("tone", {"contrast": 1.04, "lift": 0.025, "knee": 0.82}),
        ("saturation", {"amount": 1.08}),
        ("optics", {"diffusion": 0.22}),
        ("signal_rf", {"snow": 0.12, "ghost_px": 10.0, "ghost_alpha": 0.12, "hum_bar": 0.0}),
        ("ntsc", {"strength": 0.85, "phase_noise": 2.2, "rainbow": 0.28, "dot_crawl": 0.3}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.12, "curvature": 0.1}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -46.0}),
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.5}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.45}),
    ],
    variants=[
        Variant("kitchen-set", "Kitchen Counter Set", "The little 9-incher next to the coffee maker.",
                video={"signal_rf.snow": 0.25, "crt.curvature": 0.18, "crt.vignette_crt": 0.3},
                audio={"a_speaker.device": "clock_radio_1988", "a_speaker.strength": 0.7}),
    ],
))

register_preset(Preset(
    id="dx-tv-1963",
    name="TV DX Catch",
    family="broadcast",
    era="1963",
    desc="A station five hundred miles past the horizon: the picture surfaces out of the snow, rides a slow skywave swell, then sinks under a rolling co-channel ghost. Logbook television.",
    tagline="Skywave fades, drifting co-channel ghost",
    tags=("60s", "dx", "rf", "bw"),
    proc_height=460,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.2}),
        ("tone", {"contrast": 1.12, "lift": 0.06, "knee": 0.75}),
        ("ntsc", {"strength": 0.45, "rainbow": 0.1, "dot_crawl": 0.1, "phase_noise": 1.0}),
        ("rf_dx", {"fade_depth": 0.6, "fade_rate": 0.08, "noise_floor": 0.6, "co_channel": 0.45,
                   "co_delay_s": 1.5, "venetian": 0.4}),
        ("herringbone", {"amount": 0.15, "pattern": "diagonal_bars", "wavelength": 9.0,
                         "drift": 0.5}),
        ("interlace", {"combing": 0.5, "twitter": 0.35}),
        ("crt", {"scan_strength": 0.25, "bloom": 0.45, "curvature": 0.18, "vignette_crt": 0.4}),
        ("framing", {"aspect": "source", "corner_radius": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_am_radio", {"hi_hz": 5500.0, "static_db": -38.0, "fade": 0.75, "whistle_db": -50.0,
                        "pump": 0.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.7}),
        ("a_hum", {"hz": 60, "level_db": -44.0}),
    ],
    variants=[
        Variant("es-opening", "Sporadic-E Opening", "For two shining minutes it's almost local.",
                video={"rf_dx.fade_depth": 0.3, "rf_dx.noise_floor": 0.35, "rf_dx.co_channel": 0.2,
                       "herringbone.amount": 0.08},
                audio={"a_am_radio.fade": 0.4, "a_am_radio.static_db": -46.0}),
        Variant("sinking", "Losing the Opening", "The band closes while you watch.",
                video={"rf_dx.fade_depth": 0.8, "rf_dx.noise_floor": 0.8, "rf_dx.venetian": 0.55,
                       "rf_dx.co_channel": 0.6},
                audio={"a_am_radio.fade": 0.9, "a_am_radio.static_db": -32.0}),
    ],
))
