"""Cartoon-family presets, third wave: the animation industry's carriers.

From a hand-cranked 1924 ink-on-paper print through TV package dupes, xerox
features, syndication one-inch, digital ink-and-paint, console FMV and HD
simulcast. Chain order follows the brief's cel anatomy: hold pattern -> cel
stack (flatten / line / paint / dirt) -> photographic grade -> film print or
video transfer -> display -> framing.
"""

from ..engine.presets import Preset, Variant, register_preset


# nearest: cartoon-rubberhose-1932; differs: silent 16-in-24 cadence and hand-crank
# flicker instead of a sound-era print, orthochromatic paper stock, no optical track.
register_preset(Preset(
    id="cartoon-silent-era-1924",
    name="Silent-Era Cartoon",
    family="cartoon",
    era="1924",
    desc="Ink and brush on paper shot one-to-one, printed to a worn orthochromatic dupe and hand-cranked back at sixteen a second: rubbery blacks, paper tooth in the whites, the accompanist's disc grinding underneath.",
    tagline="Hand-cranked flicker, inky rubber blacks",
    tags=("20s", "35mm", "animation", "cartoon", "damaged"),
    keywords=("silent", "felix", "twenties", "ink", "paper", "flicker",
              "hand-cranked", "black-cat", "early-animation", "bw"),
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.3, "levels": 8, "flatness": 0.4, "sat_snap": 0.0}),
        ("ink_line", {"weight": 0.45, "xerox_grit": 0.2, "line_wobble": 0.3}),
        ("paper_texture", {"amount": 0.05, "scale": 1.2}),
        ("cel_wobble", {"amount": 1.5, "rot": 0.08}),
        ("cel_dirt", {"density": 0.5, "visibility": 0.1, "hair_in_gate_rate": 0.4}),
        ("mono", {"amount": 1.0, "response": "orthochromatic", "tint": "silver",
                  "tint_amt": 0.12}),
        ("tone", {"contrast": 1.22, "lift": 0.05, "knee": 0.76}),
        ("grain", {"amount": 0.42, "size": 2.1, "chroma_grain": 0.0,
                   "stock": "newsreel_35", "layers": "mono"}),
        ("gate_weave", {"amount": 1.9, "hz": 0.7, "splice_bump": 1.4}),
        ("flicker", {"amount": 0.3, "character": "hand_cranked", "spatial": 0.3,
                     "color_flicker": 0.0}),
        ("dust", {"density": 0.5, "size": 1.2, "hairs": 0.5}),
        ("scratches", {"count": 2, "strength": 0.45, "transient_rate": 1.4}),
        ("nitrate", {"enabled": False, "stage": 2, "spread": 0.45}),
        ("cadence", {"pattern": "silent_irregular", "speed": "silent_16fps_in_24",
                     "field_blend": 0.3}),
        ("vignette", {"amount": 0.4, "softness": 0.75}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_transcription_disc", {"band": 1.0, "swish": 0.5, "crackle": 3.5, "wear": 0.4}),
        ("a_wow_flutter", {"wow_depth": 10.0, "flutter_depth": 5.0}),
        ("a_speaker", {"device": "gramophone_horn_1915", "strength": 0.5}),
        ("a_compressor", {"ratio": 3.0}),
    ],
    variants=[
        Variant("archive-restoration", "Archive Restoration",
                "A wet-gate scan off the best surviving element: the crank steadies, the dirt goes.",
                video={"flicker.amount": 0.1, "dust.density": 0.1, "scratches.count": 0,
                       "gate_weave.amount": 0.9, "cel_dirt.visibility": 0.06}),
        Variant("nitrate-worn", "Nitrate Decay",
                "The reel that sat in a hot vault: the emulsion has started to go.",
                video={"nitrate.enabled": True, "dust.density": 0.8,
                       "scratches.count": 4}),
    ],
))


# nearest: cartoon-technicolor-1944; differs: feature multiplane depth haze and soft
# focus over deeper paint levels, orchestral chamber sound, far cleaner print.
register_preset(Preset(
    id="cartoon-multiplane-feature-1940",
    name="Multiplane Technicolor Feature",
    family="cartoon",
    era="1940",
    desc="A feature shot down a multiplane crane onto three-strip Technicolor: painted layers separated by real atmospheric haze, dye-transfer reds glowing at the edges, an orchestra sitting in a scoring chamber behind it.",
    tagline="Deep painted layers, glowing dyes, haze depth",
    tags=("40s", "35mm", "cel", "animation", "roadshow"),
    keywords=("disney", "feature", "forties", "multiplane", "technicolor", "fairy-tale",
              "painted-backgrounds", "lush", "classic", "princess"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"smooth": 0.3, "levels": 16, "flatness": 0.3,
                         "protect_gradients": True, "sat_snap": 0.12}),
        ("ink_line", {"weight": 0.28, "xerox_grit": 0.05}),
        ("color_era", {"profile": "technicolor_cartoon_1940s", "strength": 0.8}),
        ("cel_wobble", {"amount": 0.55, "rot": 0.04}),
        ("stock", {"profile": "technicolor3", "strength": 0.5}),
        ("saturation", {"amount": 1.06, "vibrance": 0.08}),
        ("optics", {"diffusion": 0.22, "soft_focus": 0.12, "bloom_mids": 0.32}),
        ("grain", {"amount": 0.28, "size": 1.9, "chroma_grain": 0.12,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.3, "tint": "red_orange", "threshold": 0.76,
                      "radius": 0.06}),
        ("fade", {"enabled": False, "amount": 0.28, "profile": "eastman_pink",
                  "bloom_whites": 0.2}),
        ("gate_weave", {"amount": 0.7, "splice_bump": 0.4}),
        ("flicker", {"amount": 0.08, "color_flicker": 0.05}),
        ("dust", {"density": 0.12, "hairs": 0.15}),
        ("vignette", {"amount": 0.25, "softness": 0.7}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"mode": "chamber", "size": 1.5, "decay_s": 1.4, "mix": 0.14}),
        ("a_optical_track", {"academy_rolloff": "feature_1940s", "drive": 1.3,
                             "cell_noise": -52.0}),
        ("a_compressor", {"ratio": 3.0}),
    ],
    variants=[
        Variant("reissue-eastman-1970s", "1970s Reissue Print",
                "Struck on Eastman for the umpteenth re-release: the dyes have gone pink.",
                video={"fade.enabled": True, "dust.density": 0.3, "grain.amount": 0.34}),
        Variant("restored-bluray", "Restoration Scan",
                "The 4K element cleaned frame by frame for the anniversary disc.",
                video={"dust.density": 0.02, "grain.amount": 0.2, "gate_weave.amount": 0.35}),
    ],
))


# nearest: cartoon-technicolor-1944; differs: crisper mid-fifties flats with sat snap and
# a hard-inked line, brass distortion on the optical track, almost no halation.
register_preset(Preset(
    id="cartoon-theatrical-short-1955",
    name="Theatrical Cartoon Short",
    family="cartoon",
    era="1955",
    desc="Seven minutes before the feature: flat mid-fifties paint on crisp 35 mm Technicolor, a hard black line, and a brass section hitting the optical track harder than the track wants.",
    tagline="Crisp 35 mm Technicolor cels, loud brass",
    tags=("50s", "35mm", "cel", "animation", "comedy"),
    keywords=("looney", "warner", "fifties", "theatrical", "short", "technicolor",
              "gags", "brass", "classic-cartoon", "matinee"),
    upscale="sharp",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.4, "levels": 12, "flatness": 0.45, "sat_snap": 0.3}),
        ("ink_line", {"weight": 0.35, "xerox_grit": 0.1}),
        ("color_era", {"profile": "technicolor_cartoon_1940s", "strength": 0.6}),
        ("cel_wobble", {"amount": 0.7}),
        ("cel_dirt", {"density": 0.45, "visibility": 0.05, "glass_shadows": 0.2}),
        ("stock", {"profile": "technicolor3", "strength": 0.6}),
        ("saturation", {"amount": 1.2, "vibrance": 0.1}),
        ("grain", {"amount": 0.3, "size": 1.85, "chroma_grain": 0.12,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.25, "tint": "warm_white", "threshold": 0.8}),
        ("print_char", {"acutance": 0.3, "contrast_buildup": 0, "dmax_breath": 0.1}),
        ("fade", {"enabled": False, "amount": 0.15, "profile": "eastman_pink"}),
        ("gate_weave", {"amount": 0.8, "splice_bump": 0.6}),
        ("flicker", {"amount": 0.1}),
        ("dust", {"density": 0.2, "hairs": 0.2}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"mode": "plate1960", "size": 1.0, "decay_s": 0.7, "mix": 0.1}),
        ("a_optical_track", {"academy_rolloff": "feature_1940s", "drive": 1.7,
                             "cell_noise": -48.0}),
        ("a_distortion", {"type": "soft", "drive": 1.4}),
        ("a_compressor", {"ratio": 4.0}),
    ],
    variants=[
        Variant("tv-syndication-print-1965", "Syndication Print",
                "The package print the local station ran into the ground.",
                video={"grain.amount": 0.45, "print_char.contrast_buildup": 2,
                       "fade.enabled": True, "dust.density": 0.5}),
        Variant("restored", "Restored Element",
                "Scanned off the original nitrate separations: dirt-free, dyes intact.",
                video={"dust.density": 0.03, "grain.amount": 0.24, "gate_weave.amount": 0.45}),
    ],
))


# nearest: cartoon-saturday-1969; differs: 1958 theatrical-to-TV dupe rather than an
# original 16 mm airing - faded dye, splice damage, print buildup, no broadcast chain.
register_preset(Preset(
    id="cartoon-tv-print-terry-1958",
    name="TV Cartoon Package Print",
    family="cartoon",
    era="1958",
    desc="A theatrical short dupe-printed to 16 mm for the kids-hour package: dye gone muddy and pink, splices every reel, gate wear rocking the drawing, an optical track two generations down.",
    tagline="16 mm dupe cels, muddy dye, splicey kids-hour",
    tags=("50s", "16mm", "cel", "animation", "faded"),
    keywords=("terrytoons", "tv-package", "fifties", "16mm", "dupe", "syndicated",
              "kids-hour", "muddy", "cheap", "local-tv"),
    proc_height=600,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.35, "levels": 12, "flatness": 0.4}),
        ("ink_line", {"weight": 0.35, "xerox_grit": 0.3}),
        ("color_era", {"profile": "tv_print_faded", "strength": 0.7}),
        ("cel_wobble", {"amount": 1.1}),
        ("cel_dirt", {"density": 0.5, "visibility": 0.09, "tape_splice": 0.35}),
        ("grain", {"amount": 0.5, "size": 1.9, "chroma_grain": 0.14,
                   "stock": "print_dupe", "layers": "print_from_neg"}),
        ("print_char", {"contrast_buildup": 3, "acutance": 0.2, "dmax_breath": 0.16}),
        ("fade", {"amount": 0.25, "profile": "eastman_pink", "bloom_whites": 0.25}),
        ("scratches", {"count": 3, "strength": 0.5, "transient_rate": 1.6}),
        ("dust", {"density": 0.6, "hairs": 0.5}),
        ("frame_damage", {"splice_skip_rate": 2.0, "slip_rate": 1.5, "blotch_rate": 5.0}),
        ("gate_weave", {"amount": 1.5, "splice_bump": 1.6}),
        ("flicker", {"amount": 0.12}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 1.4}),
        ("signal_rf", {"enabled": False, "snow": 0.1, "sparkle": 2.0, "ghost_n": 1,
                       "ghost_px": 16.0, "ghost_alpha": 0.22, "weak_signal": 0.3}),
        ("ntsc", {"enabled": False, "strength": 0.7, "luma_bw": 3.2, "chroma_bw": 0.7,
                  "phase_noise": 2.6, "dot_crawl": 0.3}),
        ("crt", {"enabled": False, "bloom": 0.34, "scan_strength": 0.12}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "drive": 2.0,
                             "cell_noise": -42.0}),
        ("a_wow_flutter", {"wow_depth": 6.0, "flutter_depth": 5.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tv_sound", {"enabled": False, "buzz_db": -52.0, "hum_db": -56.0}),
    ],
    variants=[
        Variant("station-vault-print", "Station Vault Print",
                "The copy that stayed in the can between airings: still faded, less chewed.",
                video={"print_char.contrast_buildup": 2, "dust.density": 0.3,
                       "fade.amount": 0.12, "scratches.count": 1}),
        Variant("uhf-broadcast-1965", "UHF Airing",
                "The same print going out over a weak channel 43 signal.",
                video={"signal_rf.enabled": True, "ntsc.enabled": True, "crt.enabled": True},
                audio={"a_tv_sound.enabled": True}),
    ],
))


# nearest: cartoon-saturday-1969; differs: threes instead of hb_mixed, a thin xerox line
# and harder posterized flats, and a 1961 receiver that many homes still watched in B&W.
register_preset(Preset(
    id="cartoon-limited-tv-1961",
    name="Limited-Animation TV Cartoon",
    family="cartoon",
    era="1961",
    desc="Made for the network on a budget: three-frame holds, paint snapped to ten flat steps, a thin photocopied line, and a 1961 set doing its best with the color subcarrier.",
    tagline="Threes holds, flat cels, xerox-thin line",
    tags=("60s", "16mm", "cel", "animation", "tv"),
    keywords=("jay-ward", "hanna-barbera", "sixties", "limited-animation", "threes",
              "flat", "cheap", "tv-cartoon", "moose", "squirrel"),
    proc_height=600,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "threes"}),
        ("cel_flatten", {"smooth": 0.45, "levels": 10, "flatness": 0.5, "sat_snap": 0.35}),
        ("ink_line", {"weight": 0.3, "xerox_grit": 0.35}),
        ("color_era", {"profile": "limited_1960s_tv", "strength": 0.5}),
        ("paper_texture", {"amount": 0.03}),
        ("cel_wobble", {"amount": 0.9}),
        ("cel_dirt", {"density": 0.45, "visibility": 0.06}),
        ("saturation", {"amount": 1.12, "vibrance": 0.1}),
        ("grain", {"amount": 0.35, "size": 1.9, "chroma_grain": 0.12, "stock": "doc_16"}),
        ("fade", {"enabled": False, "amount": 0.2, "profile": "eastman_pink"}),
        ("dust", {"density": 0.25, "hairs": 0.25}),
        ("gate_weave", {"amount": 1.0}),
        ("ntsc", {"strength": 0.5, "luma_bw": 3.4, "chroma_bw": 0.7, "phase_noise": 2.0,
                  "dot_crawl": 0.22, "setup_level": 0.05}),
        ("mono", {"enabled": False, "amount": 1.0, "response": "modern"}),
        ("interlace", {"combing": 0.5, "twitter": 0.24}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "cell_noise": -46.0}),
        ("a_tv_sound", {"buzz_db": -56.0, "hum_db": -60.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
    ],
    variants=[
        Variant("bw-set-1961", "Black-and-White Set",
                "Half the country watched it on a monochrome receiver anyway.",
                video={"mono.enabled": True, "ntsc.strength": 0.4}),
        Variant("syndication-1975", "Syndication Package",
                "Fourteen years of reruns later, off a print that has been everywhere.",
                video={"fade.enabled": True, "dust.density": 0.55, "grain.amount": 0.45,
                       "ntsc.phase_noise": 3.0}),
    ],
))


# nearest: cartoon-saturday-1969; differs: hand-inked warm holiday special on 16 mm with
# halation and a jazz-trio plate, cut with a 1966 color receiver rather than a UHF print.
register_preset(Preset(
    id="cartoon-tv-special-1966",
    name="Animated TV Special",
    family="cartoon",
    era="1966",
    desc="The half-hour special that airs once a year: warm hand-inked cel paint on soft 16 mm, a piano trio on a studio plate, all of it arriving through a 1966 color console.",
    tagline="Warm cel paint, 16 mm soft, jazz-trio mono",
    tags=("60s", "16mm", "animation", "tv", "holiday"),
    keywords=("peanuts", "charlie-brown", "holiday-special", "sixties", "cel", "warm",
              "jazz", "tv-special", "children", "prime-time"),
    proc_height=620,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.4, "levels": 12, "flatness": 0.4}),
        ("ink_line", {"weight": 0.4, "xerox_grit": 0.2, "line_wobble": 0.15}),
        ("paper_texture", {"amount": 0.04}),
        ("color_era", {"profile": "limited_1960s_tv", "strength": 0.3}),
        ("cel_wobble", {"amount": 1.0}),
        ("cel_dirt", {"density": 0.45, "visibility": 0.06}),
        ("balance", {"warmth": 0.16, "high_tint": "cream", "high_amt": 0.18}),
        ("saturation", {"amount": 1.08}),
        ("grain", {"amount": 0.4, "size": 1.85, "chroma_grain": 0.14, "stock": "doc_16"}),
        ("halation", {"strength": 0.25, "tint": "warm_white", "threshold": 0.78}),
        ("gate_weave", {"amount": 1.0}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 1.2}),
        ("ntsc", {"strength": 0.7, "luma_bw": 3.5, "chroma_bw": 0.8, "phase_noise": 2.2,
                  "dot_crawl": 0.28, "setup_level": 0.055}),
        ("vhs", {"enabled": False, "mode": "sp", "generation": 2, "luma_bw": 2.9,
                 "chroma_bw": 0.35, "luma_noise": 0.4, "chroma_noise": 0.4,
                 "head_switch": 0.65, "time_base_error": 0.45, "flagging": 0.35,
                 "dropouts": 1.4, "sharpen": 0.55}),
        ("interlace", {"combing": 0.5, "twitter": 0.22}),
        ("crt", {"bloom": 0.38, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"mode": "plate1960", "size": 1.1, "decay_s": 0.9, "mix": 0.1}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "cell_noise": -48.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_tv_sound", {"buzz_db": -56.0, "hum_db": -60.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.45}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "The tape the network struck before the transmitter got hold of it.",
                video={"ntsc.strength": 0.35, "crt.bloom": 0.28, "grain.amount": 0.34}),
        Variant("vhs-reissue-1985", "VHS Reissue",
                "The 1985 cassette your family wore out every December.",
                video={"vhs.enabled": True, "ntsc.strength": 0.8}),
    ],
))


# nearest: auth-educational-interstitial-animation-1975; differs: hotter 1973 palette with
# hand-lettered line wobble and a color-TV display stage instead of a tape master.
register_preset(Preset(
    id="cartoon-educational-insert-1973",
    name="Educational Cartoon Insert",
    family="cartoon",
    era="1973",
    desc="Three minutes of counting between the puppets: hot seventies poster paint shot on a rostrum in 16 mm, hand-lettered titles swimming a little, misconverged on a public-television set.",
    tagline="Funky rostrum cels, hot color, PBS video",
    tags=("70s", "16mm", "animation", "tv", "kids"),
    keywords=("schoolhouse", "sesame", "seventies", "educational", "insert", "funky",
              "rostrum", "hot-color", "counting", "groovy"),
    proc_height=600,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.4, "levels": 12, "flatness": 0.45, "sat_snap": 0.3}),
        ("ink_line", {"weight": 0.4, "xerox_grit": 0.15, "line_wobble": 0.2}),
        ("color_era", {"profile": "limited_1970s", "strength": 0.6}),
        ("cel_wobble", {"amount": 1.0, "rot": 0.07}),
        ("cel_dirt", {"density": 0.5, "visibility": 0.07, "glass_shadows": 0.4}),
        ("saturation", {"amount": 1.25, "vibrance": 0.2}),
        ("grain", {"amount": 0.42, "size": 1.9, "chroma_grain": 0.15, "stock": "doc_16"}),
        ("gate_weave", {"amount": 1.1}),
        ("telecine_scan", {"pin_stability": "sprocket_worn", "hop_px": 1.3}),
        ("ntsc", {"strength": 0.75, "luma_bw": 3.4, "chroma_bw": 0.8, "phase_noise": 2.2,
                  "dot_crawl": 0.3, "rainbow": 0.3, "setup_level": 0.06}),
        ("vhs", {"enabled": False, "mode": "sp", "generation": 3, "luma_bw": 2.6,
                 "chroma_bw": 0.3, "luma_noise": 0.45, "chroma_noise": 0.45,
                 "head_switch": 0.7, "time_base_error": 0.5, "flagging": 0.4,
                 "dropouts": 2.0, "sharpen": 0.5}),
        ("interlace", {"combing": 0.5, "twitter": 0.24}),
        ("crt", {"bloom": 0.4, "misconvergence": 0.5, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "cell_noise": -46.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tv_sound", {"buzz_db": -55.0, "hum_db": -58.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.5}),
    ],
    variants=[
        Variant("network-master", "Network Master",
                "Straight off the sponsor's tape, before the transmitter.",
                video={"ntsc.strength": 0.35, "crt.bloom": 0.3, "crt.misconvergence": 0.2}),
        Variant("vhs-classroom-copy-1984", "Classroom Copy",
                "The cassette the AV cart carried from room to room for a decade.",
                video={"vhs.enabled": True, "ntsc.strength": 0.85}),
    ],
))


# nearest: cartoon-euro-short-1965; differs: rotoscoped line swimming over live-action
# underlays with optical composite haze, murky Eastman 1.85 print, not a festival short.
register_preset(Preset(
    id="cartoon-rotoscope-feature-1978",
    name="Rotoscoped Fantasy Feature",
    family="cartoon",
    era="1978",
    desc="Animation traced frame by frame off live-action plates and composited back over painted armies: the line never quite settles, the optical dupes haze the layers, and the Eastman print is already going brown.",
    tagline="Traced-live wobble, haze, murky Eastman",
    tags=("70s", "35mm", "animation", "fantasy", "eastmancolor"),
    keywords=("rotoscope", "bakshi", "seventies", "fantasy", "traced", "wizards",
              "rings", "murky", "adult-animation", "painted"),
    upscale="soft",
    video=[
        ("cel_flatten", {"smooth": 0.5, "levels": 12, "flatness": 0.5, "line_gap_fill": 0.3}),
        ("ink_line", {"weight": 0.5, "xerox_grit": 0.25, "line_wobble": 0.4}),
        ("cel_wobble", {"amount": 1.4, "rot": 0.09, "layers": 2}),
        ("optical_composite", {"softness": 0.2, "layer_haze": 0.2, "registration": 0.4,
                               "density_breath": 0.14}),
        ("stock", {"profile": "eastman_70s", "strength": 0.7}),
        ("balance", {"warmth": 0.1}),
        ("saturation", {"amount": 0.95}),
        ("grain", {"amount": 0.4, "size": 2.1, "chroma_grain": 0.18,
                   "stock": "fine_35", "layers": "color_neg"}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("fade", {"amount": 0.15, "profile": "eastman_pink", "bloom_whites": 0.2}),
        ("scratches", {"count": 1, "strength": 0.4, "transient_rate": 1.0}),
        ("dust", {"density": 0.3, "hairs": 0.3}),
        ("gate_weave", {"amount": 0.9}),
        ("flicker", {"amount": 0.08}),
        ("vignette", {"amount": 0.3, "softness": 0.7}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"mode": "chamber", "size": 1.6, "decay_s": 1.6, "mix": 0.12}),
        ("a_optical_track", {"academy_rolloff": "none", "low_hz": 80.0, "high_hz": 8000.0,
                             "drive": 1.5, "cell_noise": -48.0}),
        ("a_compressor", {"ratio": 3.5}),
    ],
    variants=[
        Variant("midnight-movie-print", "Midnight Movie Print",
                "Four years on the midnight circuit: pinker, dirtier, scratched down the middle.",
                video={"fade.amount": 0.3, "dust.density": 0.6, "scratches.count": 4,
                       "grain.amount": 0.48}),
        Variant("restored-bluray", "Restoration Scan",
                "The 2K scan for the disc: the dyes come back, the traced line stops shaking.",
                video={"fade.amount": 0.0, "dust.density": 0.05, "ink_line.line_wobble": 0.3,
                       "grain.amount": 0.3, "scratches.count": 0}),
    ],
))


# nearest: cartoon-syndicated-1975; differs: 1961 feature on a clean Technicolor print with
# no holds at all, the xerox grit carried by the line itself rather than by print wear.
register_preset(Preset(
    id="cartoon-xerox-feature-1961",
    name="Xerox-Line Feature",
    family="cartoon",
    era="1961",
    desc="The first feature to skip inking entirely: the animators' pencil drawings photocopied straight onto the cels, so every line arrives ragged and sketchy over otherwise immaculate dye-transfer paint.",
    tagline="Photocopied line grit, clean Technicolor",
    tags=("60s", "35mm", "cel", "animation", "technicolor"),
    keywords=("dalmatians", "xerox", "sixties", "disney", "scratchy-line", "sketchy",
              "feature", "modern", "london", "classic"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"smooth": 0.35, "levels": 14, "flatness": 0.35, "sat_snap": 0.15}),
        ("ink_line", {"weight": 0.5, "xerox_grit": 0.7, "line_color": "black",
                      "line_wobble": 0.1}),
        ("paper_texture", {"amount": 0.03}),
        ("cel_wobble", {"amount": 0.6}),
        ("cel_dirt", {"density": 0.4, "visibility": 0.05}),
        ("stock", {"profile": "technicolor3", "strength": 0.4}),
        ("tone", {"contrast": 1.06, "knee": 0.85}),
        ("saturation", {"amount": 1.05}),
        ("grain", {"amount": 0.28, "size": 1.9, "chroma_grain": 0.12,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.22, "tint": "warm_white", "threshold": 0.8}),
        ("fade", {"enabled": False, "amount": 0.25, "profile": "eastman_pink"}),
        ("gate_weave", {"amount": 0.7}),
        ("dust", {"density": 0.12, "hairs": 0.15}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"mode": "chamber", "size": 1.2, "decay_s": 1.0, "mix": 0.12}),
        ("a_optical_track", {"academy_rolloff": "none", "low_hz": 60.0, "high_hz": 9000.0,
                             "drive": 1.3, "cell_noise": -52.0}),
        ("a_compressor", {"ratio": 3.0}),
    ],
    variants=[
        Variant("reissue-print-1979", "1979 Reissue",
                "The re-release print: pinker stock, a decade of dirt on the negative.",
                video={"fade.enabled": True, "dust.density": 0.4, "grain.amount": 0.36}),
        Variant("restored", "Restoration Scan",
                "Cleaned for the disc: the copier line survives, everything else goes.",
                video={"ink_line.xerox_grit": 0.5, "dust.density": 0.02,
                       "grain.amount": 0.22}),
    ],
))


# nearest: cartoon-syndicated-1975; differs: clean overseas-inked mid-eighties cels with no
# xerox line or print wear, delivered on one-inch syndication video rather than a 16 mm print.
register_preset(Preset(
    id="cartoon-toy-line-syndicated-1985",
    name="Toy-Line Syndicated Cartoon",
    family="cartoon",
    era="1985",
    desc="Sixty-five episodes ordered to sell a shelf of figures: clean cels inked overseas, the same three transformation cycles reused all season, mastered to one-inch and bicycled to a hundred stations.",
    tagline="Japan-inked cels, holds, 1-inch syndication",
    tags=("80s", "16mm", "cel", "animation", "action"),
    keywords=("he-man", "transformers", "gi-joe", "eighties", "toy-line", "syndicated",
              "cel", "stock-footage", "action-figure", "after-school"),
    proc_height=580,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.4, "levels": 12, "flatness": 0.45, "sat_snap": 0.3}),
        ("ink_line", {"weight": 0.35, "xerox_grit": 0.15}),
        ("color_era", {"profile": "syndication_1975", "strength": 0.4}),
        ("cel_wobble", {"amount": 0.7}),
        ("cel_dirt", {"density": 0.4, "visibility": 0.05}),
        ("saturation", {"amount": 1.2, "vibrance": 0.12}),
        ("grain", {"amount": 0.35, "size": 1.9, "chroma_grain": 0.14, "stock": "doc_16"}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.6}),
        ("ntsc", {"strength": 0.65, "luma_bw": 3.7, "chroma_bw": 0.9, "phase_noise": 2.0,
                  "dot_crawl": 0.25}),
        ("vhs", {"enabled": False, "mode": "ep", "luma_bw": 2.2, "chroma_bw": 0.25,
                 "luma_noise": 0.3, "chroma_noise": 0.28, "head_switch": 0.7,
                 "time_base_error": 0.5, "flagging": 0.4, "dropouts": 2.5,
                 "tracking_error": 0.2, "sharpen": 0.5}),
        ("interlace", {"combing": 0.5, "twitter": 0.22}),
        ("crt", {"bloom": 0.35, "misconvergence": 0.45, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 10000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tv_sound", {"buzz_db": -58.0, "hum_db": -62.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The one-inch master before a hundred station transmitters got it.",
                video={"ntsc.strength": 0.3, "crt.bloom": 0.28, "crt.misconvergence": 0.2}),
        Variant("vhs-off-air-ep", "Six-Hour Tape",
                "Taped off channel 11 at EP with three other episodes on the same cassette.",
                video={"vhs.enabled": True, "ntsc.strength": 0.8}),
    ],
))


# nearest: cartoon-toy-line-syndicated-1985; differs: 1990 Betacam-clean cels with almost
# no dirt or grain, brighter paint, a tidier NTSC pass and a mild broadcast sharpener.
register_preset(Preset(
    id="cartoon-afternoon-block-1990",
    name="Afternoon Cartoon Block",
    family="cartoon",
    era="1990",
    desc="Four o'clock, five days a week: bright clean cels finished on Betacam SP, edges crisped by the house sharpener, sitting steady on a color set with the homework not started.",
    tagline="Clean TV cels, bright ink, Betacam-tidy NTSC",
    tags=("90s", "betacam", "cel", "animation", "tv"),
    keywords=("disney-afternoon", "nineties", "afternoon", "cel", "clean", "bright",
              "syndicated", "duck", "rescue", "block"),
    proc_height=580,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.35, "levels": 14, "flatness": 0.4, "sat_snap": 0.2}),
        ("ink_line", {"weight": 0.3, "xerox_grit": 0.05}),
        ("cel_wobble", {"amount": 0.5}),
        ("cel_dirt", {"density": 0.3, "visibility": 0.03}),
        ("saturation", {"amount": 1.15, "vibrance": 0.12}),
        ("sharpen", {"amount": 0.2, "radius": 0.9}),
        ("grain", {"amount": 0.25, "size": 1.8, "chroma_grain": 0.1, "stock": "doc_16"}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.4}),
        ("ntsc", {"strength": 0.5, "luma_bw": 4.0, "chroma_bw": 1.1, "phase_noise": 1.4,
                  "dot_crawl": 0.2}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_bw": 3.0, "chroma_bw": 0.4,
                 "luma_noise": 0.3, "chroma_noise": 0.3, "head_switch": 0.6,
                 "time_base_error": 0.35, "dropouts": 1.0, "sharpen": 0.6}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.3, "misconvergence": 0.35, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 11000.0}),
        ("a_channel_aging", {"width": 1.0, "crosstalk_db": -46.0, "skew_us": 20.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tv_sound", {"buzz_db": -62.0, "hum_db": -66.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.38}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The delivery tape: no transmitter, no set, just the artwork.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.24, "crt.misconvergence": 0.15}),
        Variant("vhs-off-air", "Off-Air Tape",
                "Recorded after school on a cassette already used twice.",
                video={"vhs.enabled": True, "ntsc.strength": 0.7}),
    ],
))


# nearest: cartoon-afternoon-block-1990; differs: black-paper backgrounds crush the blacks
# under a blue-shadow deco grade with 35 mm grain and an orchestral chamber, not bright TV.
register_preset(Preset(
    id="cartoon-deco-animated-series-1992",
    name="Deco Animated Series",
    family="cartoon",
    era="1992",
    desc="Backgrounds painted on black paper so the shadows are genuinely empty: deco highlights picked out in cream over crushed blue-black, shot on 35 mm and scored by a real orchestra.",
    tagline="Black-paper backgrounds, deco highlights",
    tags=("90s", "35mm", "cel", "animation", "tv"),
    keywords=("batman", "deco", "nineties", "dark", "black-paper", "animated-series",
              "noir", "gotham", "art-deco", "brooding"),
    proc_height=580,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.4, "levels": 12, "flatness": 0.45}),
        ("ink_line", {"weight": 0.4, "xerox_grit": 0.05}),
        ("cel_wobble", {"amount": 0.5}),
        ("cel_dirt", {"density": 0.3, "visibility": 0.03}),
        ("tone", {"exposure": -0.25, "contrast": 1.3, "gamma": 0.84, "lift": 0.0,
                  "knee": 0.8}),
        ("balance", {"shadow_tint": "blue", "shadow_amt": 0.22,
                     "high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 0.88}),
        ("grain", {"amount": 0.28, "size": 1.8, "chroma_grain": 0.1,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.25, "tint": "warm_white", "threshold": 0.8}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.4}),
        ("ntsc", {"strength": 0.45, "luma_bw": 4.0, "chroma_bw": 1.1, "phase_noise": 1.2,
                  "dot_crawl": 0.18}),
        ("codec_era", {"enabled": False, "codec": "mpeg2video", "kbps": 4500, "gop": 15,
                       "res": "native"}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 12000.0}),
        ("a_channel_aging", {"width": 1.05, "crosstalk_db": -46.0}),
        ("a_room", {"mode": "chamber", "size": 1.5, "decay_s": 1.4, "mix": 0.1}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_tv_sound", {"buzz_db": -62.0, "hum_db": -66.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.35}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The film-to-tape master with the transmitter left out of it.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.24}),
        Variant("dvd-2004", "Season Set DVD",
                "The 2004 box set: MPEG-2 mosquitoes crawling around the deco edges.",
                video={"codec_era.enabled": True, "ntsc.strength": 0.2,
                       "interlace.combing": 0.2}),
    ],
))


# nearest: cartoon-afternoon-block-1990; differs: overseas paint-overshoot slop and cel
# registration drift under a warmer yellow-biased primetime grade, no broadcast sharpener.
register_preset(Preset(
    id="cartoon-primetime-korean-cel-1990",
    name="Primetime Family Cartoon",
    family="cartoon",
    era="1990",
    desc="An animated sitcom inked overseas at speed: paint overshooting the ink lines in patches, cel layers landing a hair off register, everything pushed yellow-bright for an eight o'clock network slot.",
    tagline="Overseas-inked cels, yellow-bright sitcom",
    tags=("90s", "cel", "animation", "tv", "comedy"),
    keywords=("simpsons", "primetime", "nineties", "family", "yellow", "cel",
              "overseas-ink", "sitcom", "fox", "animated-sitcom"),
    proc_height=580,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.4, "levels": 12, "flatness": 0.45, "sat_snap": 0.35,
                         "line_gap_fill": 0.2}),
        ("ink_line", {"weight": 0.35, "xerox_grit": 0.1}),
        ("cel_wobble", {"amount": 0.6}),
        ("cel_dirt", {"density": 0.35, "visibility": 0.04}),
        ("optical_composite", {"softness": 0.08, "registration": 0.35, "layer_haze": 0.05}),
        ("balance", {"warmth": 0.05, "high_tint": "yellow", "high_amt": 0.12}),
        ("saturation", {"amount": 1.2, "vibrance": 0.2}),
        ("grain", {"amount": 0.3, "size": 1.85, "chroma_grain": 0.12, "stock": "doc_16"}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.5}),
        ("ntsc", {"strength": 0.55, "luma_bw": 3.9, "chroma_bw": 1.0, "phase_noise": 1.6,
                  "dot_crawl": 0.22}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_bw": 2.9, "chroma_bw": 0.38,
                 "luma_noise": 0.32, "chroma_noise": 0.32, "head_switch": 0.6,
                 "time_base_error": 0.4, "dropouts": 1.2, "sharpen": 0.55}),
        ("interlace", {"combing": 0.5, "twitter": 0.22}),
        ("crt", {"bloom": 0.32, "misconvergence": 0.4, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 11000.0}),
        ("a_channel_aging", {"width": 1.0, "crosstalk_db": -44.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tv_sound", {"buzz_db": -60.0, "hum_db": -64.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The network delivery tape with the slop still there and the set gone.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.26, "crt.misconvergence": 0.18}),
        Variant("vhs-timer", "Timer Recording",
                "The VCR caught it while everybody was out: SP, tracking almost right.",
                video={"vhs.enabled": True, "ntsc.strength": 0.7}),
    ],
))


# nearest: cartoon-mtv-1994; differs: painted close-up detail is protected instead of
# posterized, sick green-yellow split tone, elastic line swell and a distorted hot mono.
register_preset(Preset(
    id="cartoon-gross-out-1991",
    name="Gross-Out Painted Cartoon",
    family="cartoon",
    era="1991",
    desc="The show that stops every ninety seconds for a fully painted close-up of something awful: detail kept in the paint, greens pushed toward mildew, the line swelling like it is made of rubber, voices driven into the limiter.",
    tagline="Painted close-up cels, sick greens, hot mono",
    tags=("90s", "35mm", "cel", "animation", "cable"),
    keywords=("ren-stimpy", "gross-out", "nineties", "painted", "close-up", "sick-green",
              "elastic", "spumco", "nickelodeon", "wild"),
    proc_height=600,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "twos"}),
        ("cel_flatten", {"smooth": 0.3, "levels": 16, "flatness": 0.3,
                         "protect_gradients": True}),
        ("ink_line", {"weight": 0.45, "xerox_grit": 0.15, "line_wobble": 0.35}),
        ("cel_wobble", {"amount": 1.2, "rot": 0.08}),
        ("cel_dirt", {"density": 0.4, "visibility": 0.05}),
        ("balance", {"shadow_tint": "green", "shadow_amt": 0.26,
                     "high_tint": "yellow", "high_amt": 0.2}),
        ("saturation", {"amount": 1.28, "vibrance": 0.18, "hue": -5.0}),
        ("grain", {"amount": 0.3, "size": 1.85, "chroma_grain": 0.14,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.25, "tint": "warm_white"}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.5}),
        ("ntsc", {"strength": 0.55, "luma_bw": 3.9, "chroma_bw": 1.0, "phase_noise": 1.8,
                  "dot_crawl": 0.3}),
        ("vhs", {"enabled": False, "mode": "sp", "generation": 2, "luma_bw": 2.8,
                 "chroma_bw": 0.35, "luma_noise": 0.38, "chroma_noise": 0.38,
                 "head_switch": 0.65, "time_base_error": 0.45, "dropouts": 1.6,
                 "sharpen": 0.55}),
        ("interlace", {"combing": 0.5, "twitter": 0.22}),
        ("crt", {"bloom": 0.32, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 10000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_distortion", {"type": "soft", "drive": 1.5}),
        ("a_compressor", {"ratio": 4.5, "attack_ms": 4.0}),
        ("a_tv_sound", {"buzz_db": -60.0, "hum_db": -64.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("studio-master", "Studio Master",
                "The delivery tape: the paint is still sick, the screaming is merely loud.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.26},
                audio={"a_distortion.drive": 1.2, "a_compressor.ratio": 3.0}),
        Variant("vhs-off-cable", "Taped Off Cable",
                "Recorded on the family deck by somebody who was told not to watch it.",
                video={"vhs.enabled": True, "ntsc.strength": 0.75}),
    ],
))


# nearest: auth-magical-girl-cel-broadcast; differs: late-cel action series on a
# first-generation cable NTSC feed with a grille mask, threes holds, harder line and edge.
register_preset(Preset(
    id="cartoon-anime-dub-block-1999",
    name="Anime Dub Block",
    family="cartoon",
    era="1999",
    desc="The late-nineties afternoon action block: end-of-the-cel-era Japanese animation on threes, transferred to an NTSC dub master with the dialogue re-recorded, arriving through a cable box onto a Trinitron.",
    tagline="Late cel anime, NTSC dub, tube glass",
    tags=("90s", "cel", "animation", "japan", "cable"),
    keywords=("toonami", "anime", "nineties", "dub", "cable", "cel", "dragon",
              "letterbox", "after-school", "action-anime"),
    proc_height=620,
    upscale="soft",
    video=[
        ("animate_on", {"pattern": "threes"}),
        ("cel_flatten", {"smooth": 0.3, "levels": 16, "flatness": 0.3}),
        ("ink_line", {"weight": 0.3, "xerox_grit": 0.05}),
        ("cel_wobble", {"amount": 0.5}),
        ("balance", {"high_tint": "cream", "high_amt": 0.12}),
        ("saturation", {"amount": 1.1, "vibrance": 0.08}),
        ("sharpen", {"amount": 0.25, "radius": 0.9}),
        ("grain", {"amount": 0.25, "size": 1.8, "chroma_grain": 0.1,
                   "stock": "fine_35", "layers": "print_from_neg"}),
        ("halation", {"strength": 0.22, "tint": "red_orange", "threshold": 0.8}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.4}),
        ("ntsc", {"strength": 0.5, "luma_bw": 4.0, "chroma_bw": 1.1, "phase_noise": 1.4,
                  "dot_crawl": 0.2}),
        ("vhs", {"enabled": False, "mode": "ep", "luma_bw": 2.1, "chroma_bw": 0.22,
                 "luma_noise": 0.3, "chroma_noise": 0.28, "head_switch": 0.7,
                 "time_base_error": 0.55, "flagging": 0.45, "dropouts": 2.8,
                 "tracking_error": 0.25, "sharpen": 0.5}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.3, "glass_glow": 0.15, "vignette_crt": 0.22,
                 "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 12000.0}),
        ("a_channel_aging", {"width": 1.05, "crosstalk_db": -44.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tv_sound", {"buzz_db": -62.0, "hum_db": -66.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.35}),
    ],
    variants=[
        Variant("studio-master", "Dub Master",
                "The tape the dub house delivered, before the cable headend saw it.",
                video={"ntsc.strength": 0.25, "crt.bloom": 0.24}),
        Variant("vhs-off-cable-ep", "EP Off Cable",
                "Six episodes crammed onto one cassette so nothing gets missed.",
                video={"vhs.enabled": True, "ntsc.strength": 0.75}),
    ],
))


# nearest: cartoon-nick-90s; differs: digital ink-and-paint with dead-clean vector line and
# no film medium at all, hard unprotected posterization, DVD-rate MPEG-2 instead of tape.
register_preset(Preset(
    id="cartoon-digital-ink-2001",
    name="Digital Ink-and-Paint Cartoon",
    family="cartoon",
    era="2001",
    desc="Painted in the computer and never photographed: fills that are exactly one color, a line with no grit or wobble in it anywhere, delivered at DVD bitrate with the grain budget spent on nothing.",
    tagline="Flat vector fills, hard line, DVD-clean 4:3",
    tags=("00s", "animation", "tv", "digital", "kids"),
    keywords=("powerpuff", "samurai", "aughts", "digital-ink", "flat", "vector", "clean",
              "cartoon-network", "geometric", "dvd"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"smooth": 0.5, "levels": 10, "flatness": 0.5, "sat_snap": 0.4,
                         "protect_gradients": False}),
        ("ink_line", {"weight": 0.35, "xerox_grit": 0.0, "line_wobble": 0.0}),
        ("tone", {"contrast": 1.08, "knee": 0.9}),
        ("saturation", {"amount": 1.2, "vibrance": 0.1}),
        ("codec_era", {"codec": "mpeg2video", "kbps": 6000, "gop": 15, "res": "native",
                       "field_mode": "progressive"}),
        ("interlace", {"enabled": False, "combing": 0.45, "twitter": 0.2}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 25.0, "high_hz": 18000.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("cable-broadcast-2001", "Cable Broadcast",
                "The same master squeezed into a shared cable multiplex and interlaced.",
                video={"codec_era.kbps": 2800, "codec_era.field_mode": "interlaced_tff",
                       "interlace.enabled": True}),
        Variant("hd-remaster-2012", "HD Remaster",
                "Reframed and re-encoded for the streaming era: wide, and far too clean.",
                video={"codec_era.kbps": 8000, "framing.aspect": "source"}),
    ],
))


# nearest: webvideo-2006; differs: vector cartoon posterization and an eight-level palette
# ahead of the FLV, plus an LCD panel stage - not live video mush.
register_preset(Preset(
    id="cartoon-flash-web-2005",
    name="Flash Web Cartoon",
    family="cartoon",
    era="2005",
    desc="Drawn with the pen tool and tweened on the timeline, exported to a 240-line FLV small enough to stream over DSL, watched at full screen on a monitor that never asked to be enlarged.",
    tagline="Vector tweens, 240-line FLV, soft pixels",
    tags=("00s", "web", "animation", "lcd", "comedy"),
    keywords=("flash", "newgrounds", "web-cartoon", "aughts", "vector", "tween", "flv",
              "stick-figure", "internet", "browser"),
    upscale="soft",
    video=[
        ("cel_flatten", {"smooth": 0.5, "levels": 8, "flatness": 0.5, "sat_snap": 0.5,
                         "protect_gradients": False}),
        ("ink_line", {"weight": 0.4, "xerox_grit": 0.0, "line_wobble": 0.0}),
        ("saturation", {"amount": 1.15}),
        ("codec_era", {"codec": "flv1", "kbps": 350, "res": "240p", "gop": 90, "passes": 1}),
        ("lcd_screen", {"grid": 0.16, "scale": 4, "response_smear": 0.3,
                        "backlight_bleed": 0.15, "viewing_angle": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 11000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_codec_mp3", {"kbps": "32", "mono": True}),
        ("a_speaker", {"device": "laptop_2006", "strength": 0.6}),
    ],
    variants=[
        Variant("full-quality-swf", "Local SWF",
                "The projector file off the artist's own drive: vectors, no encoder.",
                video={"codec_era.enabled": False, "lcd_screen.grid": 0.06}),
        Variant("youtube-reupload-2008", "Reupload",
                "Somebody screen-grabbed it and put it up again three years later.",
                video={"codec_era.kbps": 250, "codec_era.passes": 2,
                       "lcd_screen.response_smear": 0.35}),
    ],
))


# nearest: auth-early-cgi-demo-reel-1988; differs: a smooth-shaded weekly TV series whose
# hard CG edges crawl and twitter through broadcast NTSC, not a VGA raster showreel.
register_preset(Preset(
    id="cartoon-early-cgi-series-1995",
    name="Early CGI Series",
    family="cartoon",
    era="1995",
    desc="A whole season rendered on a room full of workstations: smooth Gouraud shading and plastic speculars, every hard-edged polygon crawling with dot crawl and twittering across the interlace.",
    tagline="Smooth CG shading, specular pop, NTSC crawl",
    tags=("90s", "animation", "tv", "3d", "broadcast"),
    keywords=("reboot", "cgi", "nineties", "computer-animation", "mainframe", "smooth",
              "specular", "early-3d", "saturday-morning", "render"),
    proc_height=580,
    upscale="soft",
    video=[
        ("cel_flatten", {"smooth": 0.2, "levels": 20, "flatness": 0.2,
                         "protect_gradients": True, "sat_snap": 0.0}),
        ("balance", {"high_tint": "cyan", "high_amt": 0.1}),
        ("saturation", {"amount": 1.15, "vibrance": 0.1}),
        ("sharpen", {"amount": 0.4, "radius": 0.9}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.9, "chroma_bw": 1.0, "phase_noise": 1.4,
                  "dot_crawl": 0.45, "rainbow": 0.35}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_bw": 2.9, "chroma_bw": 0.38,
                 "luma_noise": 0.32, "chroma_noise": 0.32, "head_switch": 0.6,
                 "time_base_error": 0.4, "dropouts": 1.2, "sharpen": 0.6}),
        ("interlace", {"combing": 0.5, "twitter": 0.35}),
        ("crt", {"bloom": 0.32, "misconvergence": 0.4, "scan_strength": 0.1}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 11000.0}),
        ("a_channel_aging", {"width": 1.0, "crosstalk_db": -46.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tv_sound", {"buzz_db": -62.0, "hum_db": -66.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.38}),
    ],
    variants=[
        Variant("studio-master", "Render Master",
                "Straight off the render farm's tape: the edges stop crawling.",
                video={"ntsc.strength": 0.25, "interlace.twitter": 0.1, "crt.bloom": 0.26}),
        Variant("vhs-off-air", "Off-Air Tape",
                "Saturday morning, one cassette, whatever was on before it still on the head.",
                video={"vhs.enabled": True, "ntsc.strength": 0.75}),
    ],
))


# nearest: cdrom-mjpeg-1995; differs: console rather than PC - fifteen-frame cadence,
# MDEC-style intra blocks on a living-room CRT, and 8-bit ADPCM instead of PC audio.
register_preset(Preset(
    id="cartoon-ps1-fmv-1997",
    name="PlayStation FMV",
    family="cartoon",
    era="1997",
    desc="The pre-rendered cutscene that took a third of the disc: a 320 by 240 window of MDEC blocks running at fifteen frames, blown up by the console onto a family television.",
    tagline="MDEC blocks, 15 fps holds, 8-bit ADPCM",
    tags=("90s", "games", "pixel", "cd-rom", "3d"),
    keywords=("playstation", "fmv", "nineties", "cutscene", "mdec", "320x240", "blocky",
              "console", "pre-rendered", "video-game"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.015}),
        ("saturation", {"amount": 1.05}),
        ("pixel_era", {"res_h": 240, "palette": "none", "dither": "none",
                       "contrast_snap": 0.1, "pixel_aspect": 1.0}),
        ("cadence", {"pattern": "twos", "field_blend": 0.0}),
        ("codec_era", {"codec": "mjpeg", "qscale": 15, "res": "240p", "gop": 1}),
        ("crt", {"bloom": 0.26, "scan_strength": 0.15, "curvature": 0.03}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_codec_speech", {"codec": "adpcm_ima_22k"}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("vcd-quality-ps1", "Generous Bitrate",
                "A studio that gave the movie half the disc: the blocks loosen their grip.",
                video={"codec_era.qscale": 6, "pixel_era.contrast_snap": 0.06}),
        Variant("emulator-upscale", "Emulator Upscale",
                "Same disc image, twenty years later, no television in the way.",
                video={"crt.enabled": False, "pixel_era.res_h": 480,
                       "codec_era.res": "native"}),
    ],
))


# nearest: cartoon-ps1-fmv-1997; differs: a 144-line dithered 256-color window four years
# earlier, coarser pixel aspect and CRT scanlines, 8-bit 11 kHz sound.
register_preset(Preset(
    id="cartoon-sega-cd-fmv-1993",
    name="Sega CD FMV",
    family="cartoon",
    era="1993",
    desc="Full-motion video on a console with no business attempting it: a postage-stamp window of ordered-dither color, stretched wide by the pixel clock and printed onto a CRT at eleven kilohertz.",
    tagline="Dither grid, 144-line window, 8-bit sound",
    tags=("90s", "games", "pixel", "cd-rom", "lofi"),
    keywords=("sega-cd", "fmv", "nineties", "night-trap", "64-color", "dither", "console",
              "grainy-video", "cinepak", "retro"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.1, "lift": 0.02}),
        ("saturation", {"amount": 0.95}),
        ("pixel_era", {"res_h": 144, "palette": "vga256", "dither": "bayer4",
                       "contrast_snap": 0.4, "pixel_aspect": 1.2}),
        ("cadence", {"pattern": "twos", "field_blend": 0.0}),
        ("codec_era", {"codec": "mjpeg", "qscale": 10, "res": "144p", "gop": 1}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.2, "curvature": 0.03}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 200.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bitcrush", {"bits": 8, "sr_hz": 11025.0, "antialias": False}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.45}),
    ],
    variants=[
        Variant("full-screen-hack", "Full-Screen Mode",
                "The version that fills the screen and pays for it in everything else.",
                video={"pixel_era.res_h": 200, "codec_era.res": "240p"}),
        Variant("emulator-clean", "Emulator Capture",
                "Grabbed straight from the framebuffer: the dither stays, the tube goes.",
                video={"crt.enabled": False, "pixel_era.dither": "bayer2"}),
    ],
))


# nearest: auth-anime-web-fansub-encode-2006; differs: banded digital paint and an
# oversharpened line baked into a 2004 MPEG-2 DVD master rather than an x264 web encode.
register_preset(Preset(
    id="cartoon-anime-digital-paint-2004",
    name="Early Digital-Paint Anime",
    family="cartoon",
    era="2004",
    desc="The first seasons painted entirely on computers: eight-bit sky gradients breaking into visible bands, the line ringing from an unsharp mask, everything sealed into a mid-rate MPEG-2 DVD.",
    tagline="Banded gradients, oversharp line, DVD 16:9",
    tags=("00s", "animation", "japan", "digital", "widescreen"),
    keywords=("anime", "aughts", "digital-paint", "banding", "dvd", "letterbox",
              "gradients", "oversharp", "tv-anime", "early-digital"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"smooth": 0.45, "levels": 10, "flatness": 0.45,
                         "protect_gradients": False, "sat_snap": 0.2}),
        ("ink_line", {"weight": 0.35, "xerox_grit": 0.0}),
        ("saturation", {"amount": 1.15, "vibrance": 0.1}),
        ("sharpen", {"amount": 0.5, "radius": 1.0}),
        ("codec_era", {"codec": "mpeg2video", "kbps": 3500, "gop": 15, "res": "480p",
                       "field_mode": "progressive"}),
        ("interlace", {"enabled": False, "combing": 0.45, "twitter": 0.22}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 40.0, "high_hz": 16000.0}),
        ("a_channel_aging", {"width": 1.1, "crosstalk_db": -50.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_codec_aac", {"kbps": 192, "mono": False}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.2}),
    ],
    variants=[
        Variant("tv-broadcast-2004", "Broadcast Version",
                "The interlaced version that actually went out at one in the morning.",
                video={"codec_era.kbps": 2800, "codec_era.field_mode": "interlaced_tff",
                       "interlace.enabled": True}),
        Variant("bluray-2010", "Later Disc",
                "The high-definition reissue: the bands soften, the ringing calms down.",
                video={"codec_era.kbps": 8000, "codec_era.res": "native", "sharpen.amount": 0.2}),
    ],
))


# nearest: cartoon-anime-digital-paint-2004; differs: 2013 HD simulcast - x264 at CRF with
# no MPEG-2 banding, gentle sharpening, clean AAC out of a laptop instead of a disc.
register_preset(Preset(
    id="cartoon-anime-hd-web-2013",
    name="HD Web Anime",
    family="cartoon",
    era="2013",
    desc="Streaming an hour after it airs in Tokyo: 1080 lines of digital paint through a constant-quality x264 pass, gradients holding together, stereo AAC coming out of a laptop on a bed.",
    tagline="Crisp 1080 lines, x264 gradients, clean AAC",
    tags=("10s", "animation", "japan", "streaming", "hd"),
    keywords=("anime", "tens", "hd", "crunchyroll", "simulcast", "x264", "crisp", "web",
              "seasonal", "clean"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"smooth": 0.3, "levels": 16, "flatness": 0.3, "sat_snap": 0.12}),
        ("ink_line", {"weight": 0.25, "xerox_grit": 0.0}),
        ("tone", {"contrast": 1.04, "knee": 0.9}),
        ("saturation", {"amount": 1.1, "vibrance": 0.08}),
        ("sharpen", {"amount": 0.15, "radius": 0.9}),
        ("codec_era", {"codec": "h264", "crf": 22, "gop": 120, "res": "native"}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 30.0, "high_hz": 17000.0}),
        ("a_compressor", {"ratio": 2.5}),
        ("a_codec_aac", {"kbps": 128, "mono": False}),
        ("a_speaker", {"device": "laptop_2006", "strength": 0.4}),
    ],
    variants=[
        Variant("480p-mobile", "Phone On The Bus",
                "The 480-line ladder rung, chosen for you by a bar of signal.",
                video={"codec_era.res": "480p", "codec_era.crf": 28},
                audio={"a_codec_aac.kbps": 64}),
        Variant("bluray", "Disc Release",
                "The version somebody paid for: near-transparent, no speaker in the way.",
                video={"codec_era.crf": 16},
                audio={"a_speaker.enabled": False}),
    ],
))
