"""Cartoon-family presets: cel animation through period print and broadcast chains."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="cartoon-saturday-1969",
    name="Saturday Morning 1969",
    family="cartoon",
    era="1969",
    desc="The Hanna-Barbera chain complete: cels on twos with wobbling registration, dirt under the rostrum glass, a 16mm print aired through NTSC. Cereal not included.",
    tagline="Cels on twos, rostrum dirt, 16mm print",
    tags=("hanna-barbera", "60s", "cel", "tv"),
    proc_height=576,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 14, "flatness": 0.5}),
        ("color_era", {"profile": "hb_1960s_tv", "strength": 0.9}),
        ("animate_on", {"pattern": "hb_mixed"}),
        ("cel_wobble", {"amount": 1.2}),
        ("cel_dirt", {"density": 0.5, "visibility": 0.09, "glass_shadows": 0.15}),
        ("paper_texture", {"amount": 0.05}),
        ("ink_line", {"weight": 0.4, "xerox_grit": 0.4}),
        ("grain", {"amount": 0.38, "size": 1.89, "chroma_grain": 0.15, "stock": "doc_16"}),
        ("gate_weave", {"amount": 1.3}),
        ("flicker", {"amount": 0.15}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("ntsc", {"strength": 0.6, "phase_noise": 2.0, "dot_crawl": 0.25, "rainbow": 0.25}),
        ("interlace", {"combing": 0.45}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 110.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -50.0, "academy_rolloff": "classroom_16mm"}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.45}),
    ],
    variants=[
        Variant("rerun", "Syndicated Rerun", "The same episode a decade of airings later.",
                video={"grain.amount": 0.7, "dust.density": 0.9, "cel_dirt.visibility": 0.16,
                       "ntsc.phase_noise": 3.2}),
        Variant("uhf", "UHF Afternoon", "Weak-signal broadcast of the print.",
                video={"ntsc.strength": 0.85, "crt.scan_strength": 0.18}),
    ],
))

register_preset(Preset(
    id="cartoon-rubberhose-1932",
    name="Rubber Hose",
    family="cartoon",
    era="1932",
    desc="Pre-code black-and-white bounce: heavy grain and flicker over inky cels, everything alive and slightly haunted.",
    tagline="Inky cels, heavy flicker, scratched dupe",
    tags=("30s", "bw", "cel"),
    proc_height=560,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 10, "flatness": 0.55}),
        ("mono", {"response": "orthochromatic"}),
        ("tone", {"contrast": 1.28, "lift": 0.06, "knee": 0.75}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 1.6}),
        ("cel_dirt", {"density": 0.6, "visibility": 0.12}),
        ("ink_line", {"weight": 0.5}),
        ("grain", {"amount": 0.55, "size": 2.19, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("gate_weave", {"amount": 2.2, "splice_bump": 1.5}),
        ("flicker", {"amount": 0.45, "character": "projector", "spatial": 0.3}),
        ("dust", {"density": 0.9, "size": 1.3, "hairs": 0.6}),
        ("scratches", {"count": 4, "transient_rate": 1.2}),
        ("vignette", {"amount": 0.45}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 180.0, "high_hz": 4800.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -38.0, "academy_rolloff": "newsreel_1930s", "drive": 2.2}),
        ("a_wow_flutter", {"wow_depth": 8.0, "flutter_depth": 6.0}),
        ("a_compressor", {"ratio": 5.0}),
    ],
))

register_preset(Preset(
    id="cartoon-technicolor-1944",
    name="Golden Age Technicolor",
    family="cartoon",
    era="1944",
    desc="Full-animation splendor on nitrate: rich three-strip inks, painterly backgrounds under gentle grain, the plush theatrical look.",
    tagline="Rich three-strip inks, fine grain, halos",
    tags=("40s", "technicolor", "cel"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"levels": 18, "flatness": 0.35}),
        ("color_era", {"profile": "technicolor_cartoon_1940s", "strength": 0.9}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 0.8}),
        ("ink_line", {"weight": 0.3}),
        ("grain", {"amount": 0.36, "size": 1.9, "chroma_grain": 0.15, "stock": "fine_35"}),
        ("halation", {"strength": 0.3, "tint": "warm_white"}),
        ("gate_weave", {"amount": 1.0}),
        ("flicker", {"amount": 0.12}),
        ("dust", {"density": 0.5}),
        ("vignette", {"amount": 0.3}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -52.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 3.5}),
    ],
))

register_preset(Preset(
    id="cartoon-vhs-1985",
    name="Cartoon VHS Rip",
    family="cartoon",
    era="1985",
    desc="Saturday's cartoons taped for Sunday: the cel-print look smeared through consumer tape — chroma bleeding out of the ink lines.",
    tagline="Chroma bleeding out of the ink lines",
    tags=("80s", "vhs", "cel"),
    proc_height=520,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 14, "flatness": 0.4}),
        ("color_era", {"profile": "hb_1970s", "strength": 0.85}),
        ("animate_on", {"pattern": "hb_mixed"}),
        ("cel_wobble", {"amount": 1.0}),
        ("grain", {"amount": 0.3, "size": 2.0, "chroma_grain": 0.15, "stock": "doc_16"}),
        ("ntsc", {"strength": 0.9, "phase_noise": 2.4, "rainbow": 0.35, "dot_crawl": 0.35}),
        ("vhs", {"mode": "sp", "luma_noise": 0.35, "chroma_noise": 0.35, "head_switch": 0.6,
                 "time_base_error": 0.4, "flagging": 0.3, "dropouts": 0.6, "sharpen": 0.6}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.32, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_tv_sound", {"buzz_db": -46.0}),
        ("a_wow_flutter", {"wow_depth": 5.0, "flutter_depth": 4.0}),
        ("a_tape_hiss", {"level_db": -44.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
))

register_preset(Preset(
    id="anime-ova-1988",
    name="OVA Cel Anime",
    family="cartoon",
    era="1988",
    desc="Direct-to-video cel anime sheen: fine 16mm grain over lush painted cels, warm highlights, laserdisc-clean composite color.",
    tagline="Lush cels, fine grain, warm halation",
    tags=("80s", "anime", "cel"),
    proc_height=640,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 20, "flatness": 0.3}),
        ("tone", {"contrast": 1.1, "lift": 0.02, "knee": 0.85}),
        ("balance", {"warmth": 0.12, "high_tint": "cream", "high_amt": 0.25}),
        ("saturation", {"amount": 1.08}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 0.7}),
        ("ink_line", {"weight": 0.3}),
        ("grain", {"amount": 0.34, "size": 1.8, "chroma_grain": 0.15, "stock": "doc_16"}),
        ("halation", {"strength": 0.35, "tint": "warm_white", "threshold": 0.8}),
        ("gate_weave", {"amount": 0.7}),
        ("ntsc", {"strength": 0.45, "dot_crawl": 0.2}),
        ("interlace", {"combing": 0.4}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 14000.0}),
        ("a_tape_hiss", {"level_db": -52.0}),
        ("a_compressor", {"ratio": 2.5}),
    ],
))
