"""Cartoon-family presets, second wave: studio eras from inkwell to cable.

Chain order per the authoring guide: cel stage -> print/film -> transfer ->
display -> presentation.
"""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="cartoon-fleischer-1936",
    name="Fleischer New York",
    family="cartoon",
    era="1936",
    desc="Inkwell-to-nitrate NYC animation: two stacked cels drifting apart, blacks like wet ink, gritty dupe grain and a jazz-age optical track squawking along.",
    tagline="Two cel layers drifting, wet-ink blacks",
    tags=("30s", "bw", "cel", "fleischer"),
    proc_height=576,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 12, "flatness": 0.5}),
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.3, "lift": 0.05, "knee": 0.76}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 1.3, "layers": 2}),
        ("cel_dirt", {"density": 0.6, "visibility": 0.11, "hair_in_gate_rate": 0.35}),
        ("ink_line", {"weight": 0.55, "line_wobble": 0.5}),
        ("grain", {"amount": 0.5, "size": 1.89, "chroma_grain": 0.0, "stock": "newsreel_35"}),
        ("halation", {"strength": 0.25, "tint": "neutral"}),
        ("gate_weave", {"amount": 1.8, "splice_bump": 1.2}),
        ("flicker", {"amount": 0.35, "character": "projector"}),
        ("dust", {"density": 0.85, "hairs": 0.5}),
        ("scratches", {"count": 3, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.4}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -40.0, "academy_rolloff": "newsreel_1930s", "drive": 2.0}),
        ("a_wow_flutter", {"wow_depth": 7.0, "flutter_depth": 5.0}),
        ("a_compressor", {"ratio": 4.5}),
    ],
    variants=[
        Variant("uptown", "First-Run Print", "A fresh print in a good house: the ink still gleams.",
                video={"grain.amount": 0.4, "dust.density": 0.5, "flicker.amount": 0.22,
                       "scratches.count": 1, "cel_dirt.visibility": 0.08}),
        Variant("bounced", "Bounced Around", "Decades of reissue duty: every splice a small accident.",
                video={"gate_weave.splice_bump": 2.2, "dust.density": 1.0,
                       "scratches.count": 6, "flicker.amount": 0.45}),
    ],
))

register_preset(Preset(
    id="cartoon-upa-1957",
    name="UPA Modernist",
    family="cartoon",
    era="1957",
    desc="Flat-planes-of-color modernism: shading snapped to poster paint, a live brush line, clean 35mm - animation that hangs like a gallery print and sounds like cool jazz.",
    tagline="Poster-paint flats, live brush line",
    tags=("50s", "upa", "cel", "modernist"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"levels": 10, "flatness": 0.65, "sat_snap": 0.5}),
        ("tone", {"contrast": 1.1, "lift": 0.02, "knee": 0.85}),
        ("balance", {"warmth": 0.08}),
        ("saturation", {"amount": 1.05}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 0.8}),
        ("paper_texture", {"amount": 0.04}),
        ("ink_line", {"weight": 0.4, "line_wobble": 0.35}),
        ("grain", {"amount": 0.32, "size": 1.8, "chroma_grain": 0.12, "stock": "fine_35"}),
        ("halation", {"strength": 0.2, "tint": "warm_white"}),
        ("gate_weave", {"amount": 0.9}),
        ("flicker", {"amount": 0.1}),
        ("dust", {"density": 0.3}),
        ("vignette", {"amount": 0.25}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -52.0, "academy_rolloff": "feature_1940s"}),
        ("a_tube_amp", {"drive": 1.6, "sag": 0.3}),
        ("a_room", {"size": 1.0, "decay_s": 0.6, "mix": 0.12}),
        ("a_compressor", {"ratio": 3.0}),
    ],
    variants=[
        Variant("festival", "Festival Print", "The pristine copy that toured the art houses.",
                video={"grain.amount": 0.26, "dust.density": 0.15, "gate_weave.amount": 0.6}),
    ],
))

register_preset(Preset(
    id="cartoon-filmation-1975",
    name="Filmation Economy",
    family="cartoon",
    era="1975",
    desc="The economy plan: heroic four-frame holds, the same run cycle you saw last week, xerox lines over syndication-print wear, one tired mono TV speaker.",
    tagline="Four-frame holds, xerox lines, print wear",
    tags=("70s", "filmation", "cel", "tv"),
    proc_height=560,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 14, "flatness": 0.5}),
        ("color_era", {"profile": "filmation_1975", "strength": 0.9}),
        ("animate_on", {"pattern": "filmation"}),
        ("cel_wobble", {"amount": 1.0}),
        ("cel_dirt", {"density": 0.5, "visibility": 0.08}),
        ("ink_line", {"weight": 0.45, "xerox_grit": 0.5}),
        ("grain", {"amount": 0.35, "size": 2.19, "chroma_grain": 0.1, "stock": "doc_16"}),
        ("gate_weave", {"amount": 1.2}),
        ("flicker", {"amount": 0.15}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("ntsc", {"strength": 0.65, "phase_noise": 2.2, "dot_crawl": 0.25}),
        ("interlace", {"combing": 0.45}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -46.0, "academy_rolloff": "classroom_16mm"}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.55}),
    ],
    variants=[
        Variant("decade-later", "Decade Of Reruns", "The same print, five hundred airings on.",
                video={"grain.amount": 0.55, "dust.density": 0.9, "scratches.count": 4,
                       "ntsc.phase_noise": 3.2, "cel_dirt.visibility": 0.12}),
    ],
))

register_preset(Preset(
    id="cartoon-toy-ad-1985",
    name="Saturday Toy Spot",
    family="cartoon",
    era="1985",
    desc="Thirty seconds between cartoons: candy-bright cels on crisp 16mm, everything animated like it's on sale, audio compressed until it shouts. Each sold separately.",
    tagline="Candy cels, crisp 16mm, shouting audio",
    tags=("80s", "commercial", "cel", "tv"),
    proc_height=600,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 16, "flatness": 0.45}),
        ("color_era", {"profile": "nick_90s", "strength": 0.55}),
        ("tone", {"contrast": 1.12, "knee": 0.84}),
        ("saturation", {"amount": 1.12, "vibrance": 0.15}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 0.7}),
        ("ink_line", {"weight": 0.35}),
        ("grain", {"amount": 0.34, "size": 1.97, "chroma_grain": 0.15, "stock": "doc_16"}),
        ("halation", {"strength": 0.25, "tint": "warm_white"}),
        ("gate_weave", {"amount": 0.8}),
        ("dust", {"density": 0.4}),
        ("ntsc", {"strength": 0.7, "phase_noise": 2.0, "dot_crawl": 0.25}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.32, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 10000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 8.0, "attack_ms": 4.0, "release_ms": 150.0}),
        ("a_agc", {"amount": 0.7}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("taped", "Taped Off Air", "The ad your sibling refused to fast-forward.",
                video={"ntsc.strength": 0.85, "ntsc.phase_noise": 2.6, "crt.bloom": 0.38}),
    ],
))

register_preset(Preset(
    id="cartoon-nick-90s",
    name="90s Cable Cartoon",
    family="cartoon",
    era="1995",
    desc="Orange-and-slime palette pushed through an S-VHS master: sharp-ish edges, humming saturation, the after-school feed in its natural habitat.",
    tagline="Slime palette through an S-VHS master",
    tags=("90s", "nick", "cel", "cable"),
    proc_height=540,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 16, "flatness": 0.45, "sat_snap": 0.35}),
        ("color_era", {"profile": "nick_90s", "strength": 0.9}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 0.8}),
        ("ink_line", {"weight": 0.4}),
        ("grain", {"amount": 0.3, "size": 1.9, "chroma_grain": 0.12, "stock": "fine_35"}),
        ("ntsc", {"strength": 0.6, "phase_noise": 1.6, "dot_crawl": 0.25}),
        ("vhs", {"mode": "sp", "luma_bw": 5.0, "luma_noise": 0.25, "chroma_noise": 0.25,
                 "head_switch": 0.4, "time_base_error": 0.2, "sharpen": 0.6}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 12000.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tape_hiss", {"level_db": -50.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.35}),
    ],
    variants=[
        Variant("sick-day", "Sick Day", "Six straight hours of it on the living-room floor.",
                video={"vhs.luma_noise": 0.35, "vhs.time_base_error": 0.35,
                       "crt.bloom": 0.38, "ntsc.strength": 0.75}),
    ],
))

register_preset(Preset(
    id="cartoon-mtv-1994",
    name="MTV Animation",
    family="cartoon",
    era="1994",
    desc="Liquid-television grunge: acid palette, a line that shakes like it's nervous, 16mm dirt worn like a leather jacket, bass-heavy tape-saturated audio.",
    tagline="Acid palette, nervous line, 16mm dirt",
    tags=("90s", "mtv", "cel", "grunge"),
    proc_height=560,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 12, "flatness": 0.5}),
        ("color_era", {"profile": "mtv_1994", "strength": 0.9}),
        ("animate_on", {"pattern": "threes"}),
        ("cel_wobble", {"amount": 1.4}),
        ("cel_dirt", {"density": 0.5, "visibility": 0.1}),
        ("ink_line", {"weight": 0.5, "xerox_grit": 0.6, "line_wobble": 0.6}),
        ("grain", {"amount": 0.45, "size": 2.19, "chroma_grain": 0.18, "stock": "doc_16"}),
        ("gate_weave", {"amount": 1.5}),
        ("flicker", {"amount": 0.15}),
        ("dust", {"density": 0.8, "hairs": 0.5}),
        ("scratches", {"count": 2, "transient_rate": 1.2}),
        ("ntsc", {"strength": 0.6, "phase_noise": 1.8}),
        ("interlace", {"combing": 0.45}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 11000.0}),
        ("a_tape_sat", {"drive": 2.6, "bump_db": 4.5}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tape_hiss", {"level_db": -46.0}),
    ],
    variants=[
        Variant("late-block", "2 A.M. Block", "The weird one they only aired after midnight.",
                video={"grain.amount": 0.55, "cel_wobble.amount": 1.8,
                       "ink_line.line_wobble": 0.8, "dust.density": 1.0}),
    ],
))

register_preset(Preset(
    id="cartoon-anime-tv-1979",
    name="TV Anime Cel",
    family="cartoon",
    era="1979",
    desc="Weeknight TV anime: warm-brown trace lines on banked cels, a taped seam gliding past, the print already fading toward tea-stain - mono broadcast and proud of it.",
    tagline="Warm-brown trace lines, tea-stain fade",
    tags=("70s", "anime", "cel", "tv"),
    proc_height=576,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 16, "flatness": 0.4}),
        ("color_era", {"profile": "tv_print_faded", "strength": 0.6}),
        ("balance", {"warmth": 0.15}),
        ("animate_on", {"pattern": "threes"}),
        ("cel_wobble", {"amount": 1.0, "layers": 2}),
        ("cel_dirt", {"density": 0.4, "visibility": 0.08, "tape_splice": 0.4}),
        ("ink_line", {"weight": 0.45, "line_color": "warm_brown"}),
        ("grain", {"amount": 0.34, "size": 1.89, "chroma_grain": 0.1, "stock": "doc_16"}),
        ("halation", {"strength": 0.25, "tint": "orange"}),
        ("gate_weave", {"amount": 1.1}),
        ("flicker", {"amount": 0.12}),
        ("dust", {"density": 0.5}),
        ("ntsc", {"strength": 0.6, "phase_noise": 2.0}),
        ("interlace", {"combing": 0.45}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -48.0, "academy_rolloff": "classroom_16mm"}),
        ("a_tv_sound", {"buzz_db": -48.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
    ],
    variants=[
        Variant("movie", "Theatrical Cut", "The compilation film: cleaner print, no broadcast chain.",
                video={"ntsc.strength": 0.0, "crt.bloom": 0.0, "grain.amount": 0.32,
                       "color_era.strength": 0.4}),
    ],
))

register_preset(Preset(
    id="cartoon-anime-fansub-1992",
    name="Fansub Third Gen",
    family="cartoon",
    era="1992",
    desc="The tape that toured the club: anime cels under three generations of VHS, recorded on somebody else's deck - chroma riding low, hiss like surf, treasure anyway.",
    tagline="Drained chroma, dropout specks, hiss",
    tags=("90s", "anime", "vhs", "fansub"),
    proc_height=500,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 18, "flatness": 0.35}),
        ("tone", {"contrast": 1.06, "lift": 0.03}),
        ("saturation", {"amount": 1.05}),
        ("animate_on", {"pattern": "threes"}),
        ("cel_wobble", {"amount": 0.8}),
        ("ink_line", {"weight": 0.3}),
        ("grain", {"amount": 0.3, "size": 1.95, "chroma_grain": 0.12, "stock": "doc_16"}),
        ("ntsc", {"strength": 0.85, "phase_noise": 2.8, "rainbow": 0.35, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "generation": 3, "interchange": 0.6, "luma_noise": 0.45,
                 "chroma_noise": 0.45, "head_switch": 0.6, "time_base_error": 0.5,
                 "flagging": 0.4, "dropouts": 1.2, "sharpen": 0.65}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 9000.0}),
        ("a_wow_flutter", {"wow_depth": 7.0, "flutter_depth": 5.0}),
        ("a_tape_sat", {"drive": 2.4}),
        ("a_tape_hiss", {"level_db": -38.0, "type": "cassette"}),
        ("a_tape_dropouts", {"rate": 2.0, "azimuth": 0.4}),
    ],
    variants=[
        Variant("gen5", "Fifth Generation", "Copied at the con, from a copy made at the last con.",
                video={"vhs.generation": 5, "vhs.dropouts": 2.0, "vhs.time_base_error": 0.7,
                       "vhs.flagging": 0.55},
                audio={"a_tape_hiss.level_db": -34.0, "a_wow_flutter.wow_depth": 10.0}),
    ],
))

register_preset(Preset(
    id="cartoon-sunday-comic-1972",
    name="Sunday Funnies",
    family="cartoon",
    era="1972",
    desc="The cartoon as a printed page: four rotated CMYK screens blooming into rosettes on newsprint, colors landing a half-step off the lines, motion still on twos - the comics section come alive.",
    tagline="CMYK rosettes on newsprint",
    tags=("70s", "print", "halftone", "comic"),
    upscale="sharp",
    video=[
        ("cel_flatten", {"levels": 12, "flatness": 0.6, "sat_snap": 0.4, "line_gap_fill": 0.5}),
        ("animate_on", {"pattern": "twos"}),
        ("ink_line", {"weight": 0.55}),
        ("halftone", {"process": "comic_cmyk", "lpi": 38.0, "paper": 0.5,
                      "misregister": 0.8, "ink_tone": 1.05}),
        ("paper_texture", {"amount": 0.06, "scale": 1.2}),
    ],
    audio=[
        ("a_am_radio", {"hi_hz": 4800.0, "static_db": -50.0, "pump": 0.4}),
        ("a_speaker", {"device": "portable_radio_1975", "strength": 0.6}),
        ("a_hum", {"hz": "60", "level_db": -52.0}),
    ],
    variants=[
        Variant("pulp", "Cheap Pulp Run", "Rushed press, thirsty paper: dots swell, colors wander further.",
                video={"halftone.lpi": 30.0, "halftone.misregister": 1.2, "halftone.paper": 0.7,
                       "paper_texture.amount": 0.07}),
        Variant("tight-press", "Quality Insert", "The syndicate's good press: tighter dots, honest color.",
                video={"halftone.lpi": 55.0, "halftone.misregister": 0.35, "halftone.paper": 0.35}),
    ],
))

register_preset(Preset(
    id="cartoon-pencil-test-1968",
    name="Pencil Test Reel",
    family="cartoon",
    era="1968",
    desc="The animator's rough pass shot on the down-shooter: blue construction lines under graphite, smudged bond paper jumping in the pegs, a projector clattering in a dark sweatbox.",
    tagline="Blue construction lines on bond paper",
    tags=("60s", "pencil-test", "paper", "workprint"),
    proc_height=620,
    upscale="soft",
    video=[
        ("mono", {"response": "modern"}),
        ("tone", {"contrast": 1.1, "lift": 0.02, "knee": 0.65, "exposure": 1.8, "gamma": 0.75}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 1.6}),
        ("cel_dirt", {"density": 0.7, "visibility": 0.12, "smudge_size": 0.8,
                      "hair_in_gate_rate": 0.4}),
        ("paper_texture", {"amount": 0.06, "scale": 1.1}),
        ("ink_line", {"weight": 0.75, "line_color": "blue_pencil", "line_wobble": 0.7,
                      "xerox_grit": 0.3}),
        ("grain", {"amount": 0.3, "size": 2.0, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("gate_weave", {"amount": 1.4}),
        ("flicker", {"amount": 0.2, "character": "projector"}),
        ("dust", {"density": 0.6}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_bed", {"bed": "projector_16mm_run", "level_db": -26.0}),
        ("a_hum", {"hz": "60", "level_db": -52.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio under the projector.",
                audio={"a_gain.db": 0.0, "a_bed.level_db": -30.0}),
        Variant("clean-pass", "Cleanup Pass", "The assistant's tied-down drawings: steadier, less graphite.",
                video={"cel_wobble.amount": 1.0, "cel_dirt.density": 0.4,
                       "cel_dirt.visibility": 0.08, "ink_line.line_wobble": 0.4}),
    ],
))

register_preset(Preset(
    id="cartoon-cereal-mascot-1962",
    name="Cereal Mascot Spot",
    family="cartoon",
    era="1962",
    desc="A minute of pure breakfast: three-strip-bright mascot colors on immaculate cels, tight pro animation, a jingle squeezed warm through the console TV. Part of this balanced Saturday.",
    tagline="Immaculate cels, bright inks, hot jingle",
    tags=("60s", "commercial", "cel", "tv"),
    proc_height=600,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 14, "flatness": 0.5, "sat_snap": 0.3}),
        ("color_era", {"profile": "technicolor_cartoon_1940s", "strength": 0.7}),
        ("saturation", {"amount": 1.12}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 0.6}),
        ("ink_line", {"weight": 0.4}),
        ("grain", {"amount": 0.3, "size": 1.8, "chroma_grain": 0.12, "stock": "fine_35"}),
        ("halation", {"strength": 0.3, "tint": "warm_white"}),
        ("gate_weave", {"amount": 0.7}),
        ("flicker", {"amount": 0.1}),
        ("dust", {"density": 0.3}),
        ("ntsc", {"strength": 0.55, "phase_noise": 1.8}),
        ("interlace", {"combing": 0.45}),
        ("crt", {"bloom": 0.35}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.08}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_tube_amp", {"drive": 2.0, "sag": 0.4}),
        ("a_compressor", {"ratio": 6.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
    ],
    variants=[
        Variant("kinescope", "Agency Kinescope", "The account team's film copy of the aired spot.",
                video={"grain.amount": 0.42, "flicker.amount": 0.2, "dust.density": 0.6,
                       "ntsc.strength": 0.4}),
    ],
))

register_preset(Preset(
    id="cartoon-euro-short-1965",
    name="European Festival Short",
    family="cartoon",
    era="1965",
    desc="A quiet prize-winner from a small studio: painterly texture in every field, muted Agfa color, a drawn line that breathes - projected calmly to a room that claps softly.",
    tagline="Muted Agfa, paper tooth, breathing line",
    tags=("60s", "european", "cel", "arthouse"),
    proc_height=620,
    upscale="soft",
    video=[
        ("cel_flatten", {"levels": 12, "flatness": 0.45}),
        ("stock", {"profile": "agfa_60s", "strength": 0.7}),
        ("tone", {"contrast": 1.05, "lift": 0.03}),
        ("saturation", {"amount": 0.82}),
        ("animate_on", {"pattern": "twos"}),
        ("cel_wobble", {"amount": 1.0}),
        ("cel_dirt", {"density": 0.4, "visibility": 0.08}),
        ("paper_texture", {"amount": 0.07, "scale": 1.3}),
        ("ink_line", {"weight": 0.45, "line_wobble": 0.6}),
        ("grain", {"amount": 0.4, "size": 2.03, "chroma_grain": 0.15, "stock": "doc_16"}),
        ("gate_weave", {"amount": 1.2}),
        ("flicker", {"amount": 0.12}),
        ("dust", {"density": 0.5}),
        ("scratches", {"count": 1, "transient_rate": 0.6}),
        ("vignette", {"amount": 0.35}),
        ("framing", {"aspect": "1.37"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -52.0, "academy_rolloff": "classroom_16mm"}),
        ("a_room", {"mode": "chamber", "size": 1.2, "decay_s": 1.1, "mix": 0.15}),
        ("a_compressor", {"ratio": 2.5}),
    ],
    variants=[
        Variant("retrospective", "Retrospective Print", "Struck decades later for the box set: cleaner, still soft-spoken.",
                video={"grain.amount": 0.32, "dust.density": 0.25, "gate_weave.amount": 0.8,
                       "scratches.count": 0}),
    ],
))
