"""Decay-family presets: what time, chemistry and bad storage do to the element
itself — nitrate goo, vinegar warp, water, mold, fire and dying binder."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="nitrate-vault-1937",
    name="Vault Nitrate",
    family="decay",
    era="1937",
    desc="A studio vault reel gone amber at the edges: honey fog creeping in, emulsion starting to bubble, splices and blotches keeping the projectionist honest.",
    tags=("30s", "nitrate", "decay", "bw"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "nitrate_warm", "tint_amt": 0.35}),
        ("tone", {"contrast": 1.2, "lift": 0.06, "knee": 0.74}),
        ("grain", {"amount": 0.5, "size": 2.3, "chroma_grain": 0.0, "stock": "print_dupe",
                   "mottle": 0.3}),
        ("nitrate", {"stage": 3, "spread": 0.55}),
        ("fade", {"amount": 0.4, "profile": "nitrate_amber", "bloom_whites": 0.35}),
        ("flicker", {"amount": 0.3, "character": "projector"}),
        ("gate_weave", {"amount": 2.0, "splice_bump": 2.0}),
        ("dust", {"density": 0.9, "hairs": 0.5}),
        ("scratches", {"count": 4, "transient_rate": 1.5}),
        ("frame_damage", {"splice_skip_rate": 2.0, "blotch_rate": 2.0}),
        ("vignette", {"amount": 0.45}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -38.0, "academy_rolloff": "newsreel_1930s", "drive": 2.2}),
        ("a_compressor", {"ratio": 4.5}),
        ("a_tube_amp", {"drive": 1.8, "sag": 0.5, "hum_db": -50.0}),
    ],
    variants=[
        Variant("first-blush", "First Blush", "Stage two: the stain has arrived, the bubbles have not.",
                video={"nitrate.stage": 2, "nitrate.spread": 0.45, "fade.amount": 0.28}),
        Variant("spreading", "Spreading Fast", "The inspection they should have done last year.",
                video={"nitrate.spread": 0.85, "frame_damage.blotch_rate": 4.0}),
    ],
))

register_preset(Preset(
    id="nitrate-terminal-1929",
    name="The Melting Reel",
    family="decay",
    era="1929",
    desc="Terminal nitrate, projected one last time: emulsion bubbling into honey-rimmed voids, amber goo swallowing the frame while the hand-crank flicker fights through.",
    tags=("20s", "nitrate", "decay", "terminal", "silent"),
    proc_height=560,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic", "tint": "nitrate_warm", "tint_amt": 0.5}),
        ("tone", {"contrast": 1.28, "lift": 0.08, "knee": 0.7, "gamma": 0.95}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("grain", {"amount": 0.6, "size": 2.6, "chroma_grain": 0.0, "stock": "print_dupe",
                   "intermittent": 0.4}),
        ("nitrate", {"stage": 4, "spread": 0.8}),
        ("fade", {"amount": 0.55, "profile": "nitrate_amber", "bloom_whites": 0.5}),
        ("flicker", {"amount": 0.5, "character": "hand_cranked", "spatial": 0.45}),
        ("gate_weave", {"amount": 3.0, "splice_bump": 2.5}),
        ("scratches", {"count": 5, "transient_rate": 2.0}),
        ("dust", {"density": 1.0, "size": 1.4, "hairs": 0.6}),
        ("frame_damage", {"splice_skip_rate": 3.0, "blotch_rate": 3.0, "static_flash": 2.0}),
        ("plate", {"pack": "emulsion_decay", "opacity": 0.45, "blend": "screen", "cycle": "hold",
                   "drift": 4.0, "flicker": 0.2}),
        ("vignette", {"amount": 0.55, "softness": 0.55, "roundness": 0.9}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -26.0}),
        ("a_hum", {"hz": 50, "level_db": -50.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio under the projector.",
                audio={"a_gain.db": -6.0}),
        Variant("meltdown", "Full Meltdown", "Stage five: molten voids with honey edges. Goodbye, movie.",
                video={"nitrate.stage": 5, "nitrate.spread": 1.0, "fade.amount": 0.7,
                       "plate.opacity": 0.6}),
        Variant("still-fighting", "Still Fighting", "Stage three: the picture mostly wins. For now.",
                video={"nitrate.stage": 3, "nitrate.spread": 0.6, "fade.amount": 0.4,
                       "plate.opacity": 0.3}),
    ],
))

register_preset(Preset(
    id="vinegar-ektachrome-1974",
    name="Vinegar Reel",
    family="decay",
    era="1974",
    desc="You smell it before you thread it: acetate buckling in slow waves, dye layers sliding apart into red-blue ghosts, a milky bloom over color already gone pink.",
    tags=("70s", "vinegar-syndrome", "decay", "16mm"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.85}),
        ("tone", {"contrast": 1.05, "lift": 0.05}),
        ("fade", {"amount": 0.55, "profile": "eastman_pink", "bloom_whites": 0.4}),
        ("vinegar", {"warp": 0.55, "channel_split": 0.5, "haze": 0.45}),
        ("grain", {"amount": 0.48, "size": 2.4, "chroma_grain": 0.2, "stock": "doc_16"}),
        ("flicker", {"amount": 0.18}),
        ("gate_weave", {"amount": 2.0}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.35}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -44.0, "academy_rolloff": "classroom_16mm"}),
        ("a_wow_flutter", {"wow_depth": 18.0, "flutter_depth": 10.0, "scrape": 0.3}),
        ("a_hum", {"hz": 60, "level_db": -50.0}),
    ],
    variants=[
        Variant("advanced", "Advanced Case", "The reel that curls like a pencil shaving.",
                video={"vinegar.warp": 0.8, "vinegar.channel_split": 0.7, "vinegar.haze": 0.6,
                       "fade.amount": 0.7}),
        Variant("caught-early", "Caught Early", "A whiff at inspection: mild warp, color mostly loyal.",
                video={"vinegar.warp": 0.3, "vinegar.channel_split": 0.25, "vinegar.haze": 0.2,
                       "fade.amount": 0.3}),
    ],
))

register_preset(Preset(
    id="water-damaged-attic-1965",
    name="Attic Flood Reel",
    family="decay",
    era="1965",
    desc="The roof leaked onto the Kodachrome: tide marks ring every winter, emulsion blisters catch the projector lamp, and mold has signed the corners.",
    tags=("60s", "water-damage", "decay", "8mm", "silent"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 0.9}),
        ("tone", {"contrast": 1.12, "lift": 0.05}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.35}),
        ("grain", {"amount": 0.48, "size": 2.6, "chroma_grain": 0.2, "stock": "super8"}),
        ("water_damage", {"tide_marks": 0.75, "blistering": 0.5}),
        ("frame_damage", {"mold_edge": 0.35, "blotch_rate": 1.0, "splice_skip_rate": 1.5}),
        ("plate", {"pack": "water_stains", "opacity": 0.35, "blend": "multiply", "cycle": "hold",
                   "drift": 2.0}),
        ("flicker", {"amount": 0.3, "character": "projector"}),
        ("gate_weave", {"amount": 2.6, "splice_bump": 1.5}),
        ("dust", {"density": 0.8, "hairs": 0.4}),
        ("vignette", {"amount": 0.5}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -25.0}),
        ("a_hum", {"hz": 60, "level_db": -54.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio under the projector.",
                audio={"a_gain.db": -6.0}),
        Variant("dried-out", "Dried Out", "Rescued and rewound: the rings stay, the worst is over.",
                video={"water_damage.tide_marks": 0.45, "water_damage.blistering": 0.25,
                       "plate.opacity": 0.2, "frame_damage.mold_edge": 0.15}),
    ],
))

register_preset(Preset(
    id="moldy-basement-16mm-1958",
    name="Basement Mold 16mm",
    family="decay",
    era="1958",
    desc="Twenty damp winters under the stairs: mold blooming in from the reel edge, a mildew veil over the mids, the projector adding its own must.",
    tags=("50s", "mold", "decay", "16mm", "bw"),
    proc_height=620,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "sepia", "tint_amt": 0.2}),
        ("tone", {"contrast": 1.22, "lift": 0.05, "knee": 0.76}),
        ("grain", {"amount": 0.46, "size": 2.4, "chroma_grain": 0.0, "stock": "doc_16"}),
        ("vinegar", {"warp": 0.15, "channel_split": 0.0, "haze": 0.22}),
        ("frame_damage", {"mold_edge": 0.65, "blotch_rate": 1.0, "splice_skip_rate": 1.5}),
        ("plate", {"pack": "mold", "opacity": 0.35, "blend": "screen", "cycle": "hold",
                   "drift": 3.0}),
        ("flicker", {"amount": 0.28, "character": "projector"}),
        ("gate_weave", {"amount": 2.2, "splice_bump": 1.5}),
        ("dust", {"density": 0.9, "hairs": 0.6}),
        ("scratches", {"count": 3, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 140.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -42.0, "academy_rolloff": "classroom_16mm", "drive": 2.0}),
        ("a_room", {"size": 0.7, "decay_s": 0.5, "mix": 0.2}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -27.0}),
        ("a_hum", {"hz": 60, "level_db": -44.0, "buzz": 0.3}),
    ],
    variants=[
        Variant("spore-bloom", "Spore Bloom", "The reel they should have thrown out: lace to the sprockets.",
                video={"frame_damage.mold_edge": 0.9, "plate.opacity": 0.6, "vinegar.haze": 0.5}),
    ],
))

register_preset(Preset(
    id="sticky-shed-umatic-1981",
    name="Sticky-Shed U-matic",
    family="decay",
    era="1981",
    desc="The binder is coming off on the heads: bands of smeared dropout clot the picture in bouts, highs vanish mid-word, and every pass makes it worse.",
    tags=("80s", "umatic", "sticky-shed", "decay", "video"),
    proc_height=500,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.04, "lift": 0.04, "knee": 0.82}),
        ("stock", {"profile": "tube_70s", "strength": 0.6}),
        ("ntsc", {"strength": 0.8, "phase_noise": 2.8, "dot_crawl": 0.3}),
        ("sticky_shed", {"severity": 0.7}),
        ("vhs", {"mode": "sp", "luma_bw": 3.8, "chroma_bw": 0.5, "luma_noise": 0.4,
                 "chroma_noise": 0.4, "head_switch": 0.6, "time_base_error": 0.5,
                 "dropouts": 8.0, "dropout_burst": 0.6, "tracking_error": 0.2, "sharpen": 0.5}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.25}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.06}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 10.0, "flutter_depth": 8.0, "scrape": 0.4}),
        ("a_tape_sat", {"drive": 2.4, "hf_loss": 0.8}),
        ("a_tape_dropouts", {"rate": 30.0, "azimuth": 0.85, "depth_db": 24.0}),
        ("a_tape_hiss", {"level_db": -38.0}),
        ("a_hum", {"hz": 60, "level_db": -48.0}),
    ],
    variants=[
        Variant("baked", "After Baking", "Eight hours in the food dehydrator: one good transfer left in it.",
                video={"sticky_shed.severity": 0.25, "vhs.dropouts": 3.0},
                audio={"a_tape_dropouts.rate": 8.0, "a_tape_dropouts.azimuth": 0.4,
                       "a_tape_sat.hf_loss": 0.5}),
        Variant("unplayable", "Nearly Unplayable", "The pass you do with the archivist watching through fingers.",
                video={"sticky_shed.severity": 0.9, "vhs.dropouts": 16.0, "vhs.tracking_error": 0.4},
                audio={"a_tape_dropouts.rate": 60.0}),
    ],
))

register_preset(Preset(
    id="burned-reel-1968",
    name="Projector Fire",
    family="decay",
    era="1968",
    desc="The take-up jammed and the lamp did the rest: scorch-bleached color, burn scars blooming across the frame, a hot spot where the carbon arc found the base.",
    tags=("60s", "fire", "decay", "damaged"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.18, "lift": 0.05, "knee": 0.74}),
        ("fade", {"amount": 0.35, "profile": "bleach", "bloom_whites": 0.4}),
        ("grain", {"amount": 0.55, "size": 2.5, "chroma_grain": 0.2, "stock": "push_process"}),
        ("halation", {"strength": 0.45, "tint": "red", "threshold": 0.7}),
        ("flicker", {"amount": 0.45, "character": "projector", "spatial": 0.5}),
        ("gate_weave", {"amount": 3.0, "splice_bump": 3.0}),
        ("dust", {"density": 0.9, "hairs": 0.5}),
        ("scratches", {"count": 4, "transient_rate": 2.0}),
        ("frame_damage", {"burn": False, "splice_skip_rate": 3.0, "blotch_rate": 1.5}),
        ("plate", {"pack": "film_burns", "opacity": 0.55, "blend": "screen", "cycle": "shuffle_fast",
                   "gate": 0.35, "jitter": 40.0}),
        ("vignette", {"amount": 0.5, "hot_center": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 130.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -40.0, "academy_rolloff": "classroom_16mm", "drive": 2.4}),
        ("a_distortion", {"type": "soft", "drive": 2.2}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -26.0}),
        ("a_hum", {"hz": 60, "level_db": -48.0}),
    ],
    variants=[
        Variant("smolder", "Smolder", "Heat damage only: scars and scorch, no fresh flame.",
                video={"plate.opacity": 0.35, "flicker.amount": 0.3}),
        Variant("flashpoint", "Flashpoint", "The frame the film gives up: it whites out and burns through.",
                video={"frame_damage.burn": True, "frame_damage.burn_at_s": 2.0,
                       "plate.opacity": 0.7, "plate.gate": 0.5, "fade.amount": 0.5}),
    ],
))

register_preset(Preset(
    id="rescued-scan-2019",
    name="Rescued Nitrate Scan",
    family="decay",
    era="2019",
    desc="A dying reel, pin-registered and scanned with love: the amber stain and mottle preserved in 4K while the archive's auto-color gently chases the fading image.",
    tags=("archival", "scan", "nitrate", "restoration"),
    upscale="sharp",
    video=[
        ("mono", {"response": "panchromatic", "tint": "nitrate_warm", "tint_amt": 0.25}),
        ("tone", {"contrast": 1.1, "lift": 0.04, "knee": 0.8}),
        ("grain", {"amount": 0.42, "size": 2.2, "chroma_grain": 0.0, "stock": "print_dupe",
                   "mottle": 0.5, "intermittent": 0.3}),
        ("nitrate", {"stage": 2, "spread": 0.45}),
        ("fade", {"amount": 0.35, "profile": "nitrate_amber", "bloom_whites": 0.3}),
        ("flicker", {"amount": 0.12, "character": "slow_drift"}),
        ("gate_weave", {"amount": 0.5}),
        ("dust", {"density": 0.5, "hairs": 0.3}),
        ("scratches", {"count": 2, "transient_rate": 0.5}),
        ("telecine_scan", {"pin_stability": "pin_registered", "scanner_stripe": 0.25,
                           "frame_edge_crop": 0.4}),
        ("auto_color", {"wb_pump": 0.25, "level_pump": 0.3, "lag_s": 0.8}),
        ("vignette", {"amount": 0.25}),
        ("framing", {"aspect": "4:3", "matte_gray": 0.08}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -52.0, "academy_rolloff": "feature_1940s"}),
        ("a_codec_mp3", {"kbps": 96, "mono": True}),
    ],
    variants=[
        Variant("raw-scan", "Raw Scan", "Before the automatics: flat, honest, unchased.",
                video={"auto_color.wb_pump": 0.0, "auto_color.level_pump": 0.0,
                       "framing.matte_gray": 0.0}),
        Variant("worn-scanner", "Sprocket-Worn Pass", "The backup scanner with the tired claw.",
                video={"telecine_scan.pin_stability": "sprocket_worn", "telecine_scan.hop_px": 2.0}),
    ],
))
