"""Exhibition-family presets: not the film, the SHOWING of it - booths and
bedsheets, windshields and rec-room big screens."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="booth-changeover-1957",
    name="Changeover Booth",
    family="exhibition",
    era="1957",
    desc="Two projectors, one feature: cue dots blink in the corner, the splice bumps through the gate, and the whole show hums from the booth at the back of your neck.",
    tagline="Cue dots, splice bump, 35mm clatter",
    tags=("50s", "projection", "changeover", "bw"),
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.22, "lift": 0.03, "knee": 0.78}),
        ("grain", {"amount": 0.4, "size": 1.9, "chroma_grain": 0.0, "stock": "fine_35"}),
        ("halation", {"strength": 0.35, "tint": "neutral"}),
        ("print_char", {"dmax_breath": 0.35, "acutance": 0.3}),
        ("gate_weave", {"amount": 1.2, "splice_bump": 1.0}),
        ("flicker", {"amount": 0.15, "character": "projector"}),
        ("dust", {"density": 0.5, "hairs": 0.3}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("changeover", {"cue_dots": True, "force_at_s": 8.0, "splice_bump": 0.8}),
        ("framing", {"aspect": "source", "mode": "box"}),
        ("screen", {"surface": "matte_white", "hotspot": 0.25, "keystone_v": 0.03,
                    "room_spill": 0.12, "shake_event": 0.2}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -48.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_room", {"size": 1.4, "decay_s": 0.9, "mix": 0.16, "mode": "chamber"}),
        ("a_bed", {"bed": "projector_35mm_booth", "level_db": -28.0}),
    ],
    variants=[
        Variant("natural-reels", "Natural Reels", "No forced change: dots arrive on the reel's own schedule.",
                video={"changeover.force_at_s": -1.0}),
        Variant("second-run", "Second-Run House", "The print after the first-run houses were done with it.",
                video={"dust.density": 0.9, "scratches.count": 5, "gate_weave.splice_bump": 3.0,
                       "changeover.splice_bump": 1.0}),
    ],
))

register_preset(Preset(
    id="home-8mm-wall-1966",
    name="Living-Room Wall Show",
    family="exhibition",
    era="1966",
    desc="No screen tonight - straight onto the wall: roller-mottle under the picture, keystone from the bookshelf perch, the cart jolting every time someone finds the couch.",
    tagline="Roller-mottle plaster, keystone, jolts",
    tags=("60s", "8mm", "home-projection", "silent"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "agfa_60s", "strength": 0.9}),
        ("tone", {"contrast": 1.12, "lift": 0.05, "knee": 0.78}),
        ("balance", {"warmth": 0.2}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.4, "focus_drift": 0.3}),
        ("grain", {"amount": 0.5, "size": 2.03, "chroma_grain": 0.2, "stock": "super8"}),
        ("halation", {"strength": 0.25, "tint": "orange"}),
        ("gate_weave", {"amount": 2.6, "splice_bump": 1.5}),
        ("flicker", {"amount": 0.35, "character": "projector"}),
        ("dust", {"density": 0.9, "hairs": 0.5}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("framing", {"aspect": "source"}),
        ("screen", {"surface": "wall_paint", "hotspot": 0.45, "keystone_v": 0.09,
                    "room_spill": 0.3, "shake_event": 2.0}),
        ("vignette", {"amount": 0.4}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_bed", {"bed": "projector_8mm_run", "level_db": -22.0, "duck": 0.2}),
        ("a_hum", {"hz": 60, "level_db": -50.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio under the projector.",
                audio={"a_gain.db": -6.0}),
        Variant("steadier-cart", "Steadier Cart", "The projector found a real table this year.",
                video={"screen.shake_event": 0.3, "screen.keystone_v": 0.04}),
    ],
))

register_preset(Preset(
    id="bedsheet-backyard-1972",
    name="Backyard Bedsheet",
    family="exhibition",
    era="1972",
    desc="A bedsheet on the clothesline, Super 8 after dark: hotspot glowing through the weave, the picture billowing with every breeze, moths auditioning in the beam.",
    tagline="Hotspot through weave, billowing picture",
    tags=("70s", "super8", "backyard", "silent"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.1, "lift": 0.05, "knee": 0.78}),
        ("balance", {"warmth": 0.28, "shadow_tint": "brown", "shadow_amt": 0.25}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.35}),
        ("grain", {"amount": 0.5, "size": 2.03, "chroma_grain": 0.2, "stock": "super8"}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("fade", {"amount": 0.25, "profile": "eastman_pink"}),
        ("gate_weave", {"amount": 2.4, "splice_bump": 1.2}),
        ("flicker", {"amount": 0.32, "character": "projector"}),
        ("dust", {"density": 0.85, "hairs": 0.5}),
        ("light_leak", {"constant": 0.06, "frequency": 0.4}),
        ("framing", {"aspect": "source"}),
        ("screen", {"surface": "bedsheet", "hotspot": 0.55, "keystone_v": 0.07,
                    "room_spill": 0.18, "shake_event": 3.0}),
        ("vignette", {"amount": 0.45}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -24.0, "distance": 0.4}),
        ("a_bed", {"bed": "air_handler_hall", "level_db": -42.0, "duck": 0.1}),
        ("a_hum", {"hz": 60, "level_db": -56.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio under the night air.",
                audio={"a_gain.db": -6.0}),
        Variant("gusty", "Gusty Night", "The sheet has opinions about the wind.",
                video={"screen.shake_event": 6.0, "screen.hotspot": 0.7}),
    ],
))

register_preset(Preset(
    id="rptv-superbowl-1993",
    name="Rec-Room Big Screen",
    family="exhibition",
    era="1993",
    desc="The neighborhood's first big screen: three CRT guns drifting apart at the corners, a hotspot that follows you to the good couch, lenticular lines up close.",
    tagline="Corner misconvergence, hotspot, louvres",
    tags=("90s", "rptv", "big-screen", "broadcast"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.03, "knee": 0.82}),
        ("stock", {"profile": "tube_80s", "strength": 0.5}),
        ("saturation", {"amount": 1.08}),
        ("ntsc", {"strength": 0.7, "phase_noise": 1.8, "dot_crawl": 0.25, "rainbow": 0.2}),
        ("interlace", {"combing": 0.5}),
        ("rear_projection_tv", {"convergence": 0.7, "hotspot": 0.65, "screen_louvre": 0.55}),
        ("framing", {"aspect": "source", "corner_radius": 0.04}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -46.0}),
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 11000.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.55}),
        ("a_room", {"size": 1.1, "decay_s": 0.5, "mix": 0.2}),
    ],
    variants=[
        Variant("converged", "Freshly Converged", "The one afternoon someone did the service menu.",
                video={"rear_projection_tv.convergence": 0.25, "rear_projection_tv.hotspot": 0.45}),
        Variant("party", "Game-Day Party", "More people, more echo, more buzz.",
                audio={"a_room.mix": 0.3, "a_tv_sound.buzz_db": -40.0}),
    ],
))

register_preset(Preset(
    id="drive-in-dusk-1961",
    name="Drive-In Windshield",
    family="exhibition",
    era="1961",
    desc="Scope through a windshield at dusk: the screen ghosting in the glass, dashboard glow rising from the bottom of the world, one aluminum speaker doing the talking.",
    tagline="Screen ghosting in glass, dash glow",
    tags=("60s", "drive-in", "scope", "windshield"),
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.85}),
        ("tone", {"contrast": 1.12, "lift": 0.05, "knee": 0.78}),
        ("fade", {"amount": 0.25, "profile": "eastman_pink"}),
        ("grain", {"amount": 0.45, "size": 2.2, "chroma_grain": 0.18}),
        ("halation", {"strength": 0.32, "tint": "orange"}),
        ("gate_weave", {"amount": 1.8}),
        ("flicker", {"amount": 0.25, "character": "projector"}),
        ("dust", {"density": 0.9, "hairs": 0.4}),
        ("scratches", {"count": 3, "transient_rate": 1.0}),
        ("framing", {"aspect": "source", "mode": "box"}),
        ("drive_in", {"glass_ghost": 0.5, "dashboard_glow": 0.55}),
        ("vignette", {"amount": 0.45, "softness": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 200.0, "high_hz": 4000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "drive_in_speaker_1958", "strength": 0.85}),
        ("a_distortion", {"type": "soft", "drive": 2.4}),
        ("a_hum", {"hz": 60, "level_db": -46.0}),
    ],
    variants=[
        Variant("clear-night", "Clear Night", "Windshield freshly wiped, heater off.",
                video={"drive_in.glass_ghost": 0.3, "drive_in.dashboard_glow": 0.3}),
        Variant("fogging-up", "Fogging Up", "Two coffees against the glass: ghosts everywhere.",
                video={"drive_in.glass_ghost": 0.75, "drive_in.dashboard_glow": 0.7}),
    ],
))

register_preset(Preset(
    id="matinee-scope-1955",
    name="Saturday Matinee Scope",
    family="exhibition",
    era="1955",
    desc="A scope print that has met every projector in the county: pink-leaning color, splices at the reel ends, the hall's own echo under the optical hiss.",
    tagline="Reel-end splices, hall echo, faded dyes",
    tags=("50s", "scope", "matinee", "worn-print"),
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.75}),
        ("tone", {"contrast": 1.14, "lift": 0.05, "knee": 0.76}),
        ("optics", {"chromatic_aberration": 1.8, "distortion": -0.1}),
        ("fade", {"amount": 0.35, "profile": "eastman_pink", "bloom_whites": 0.35}),
        ("grain", {"amount": 0.48, "size": 2.2, "chroma_grain": 0.18, "layers": "print_from_neg"}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.3}),
        ("gate_weave", {"amount": 1.8, "splice_bump": 2.5}),
        ("flicker", {"amount": 0.22, "character": "projector"}),
        ("dust", {"density": 1.0, "size": 1.3, "hairs": 0.6}),
        ("scratches", {"count": 5, "transient_rate": 1.5}),
        ("frame_damage", {"splice_skip_rate": 2.0}),
        ("changeover", {"cue_dots": True, "splice_bump": 0.7}),
        ("framing", {"aspect": "source", "mode": "box"}),
        ("screen", {"surface": "matte_white", "hotspot": 0.3, "room_spill": 0.2,
                    "shake_event": 0.3}),
        ("vignette", {"amount": 0.35}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -44.0, "academy_rolloff": "feature_1940s", "drive": 2.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_room", {"size": 1.5, "decay_s": 1.0, "mix": 0.2, "mode": "chamber"}),
        ("a_bed", {"bed": "projector_35mm_booth", "level_db": -32.0}),
    ],
    variants=[
        Variant("kiddie-show", "Kiddie Show", "Ten years of Saturday mornings: the print is mostly splices.",
                video={"dust.density": 1.0, "scratches.count": 7, "frame_damage.splice_skip_rate": 4.0,
                       "fade.amount": 0.5}),
        Variant("evening-show", "Evening Show", "The good reel for the grown-ups: gentler wear.",
                video={"dust.density": 0.5, "scratches.count": 2, "fade.amount": 0.22,
                       "gate_weave.splice_bump": 1.0}),
    ],
))
