"""Film-family presets, third reel: the odd small gauges, the sponsored and
institutional 16 mm reels, and the big roadshow print at the other end of the
scale. Everything here is something a projector actually threaded.
"""

from ..engine.presets import Preset, Variant, register_preset


# nearest: super8-1974 (big soft grain, 18-frame heartbeat); differs: Polavision's
# additive stripe filter, a dim self-contained viewer and muddy undersaturated dye.
register_preset(Preset(
    id="polavision-instant-movie-1977",
    name="Polavision Instant Movie",
    family="film",
    era="1977",
    desc="Polaroid's instant movie cassette watched in its own back-projection viewer: an additive stripe filter eating two thirds of the light, dye that never gets there, and a two-minute reel.",
    tagline="Additive stripes, dim muddy color, viewer",
    tags=("70s", "super8", "home-movie", "polaroid"),
    keywords=("polavision", "instant-movie", "seventies", "polaroid", "additive",
              "cassette", "dim", "muddy", "home-movie", "viewer"),
    proc_height=500,
    upscale="soft",
    video=[
        ("balance", {"warmth": 0.08}),
        ("tone", {"exposure": -0.12, "contrast": 0.9, "lift": 0.08, "knee": 0.86}),
        ("saturation", {"amount": 0.65}),
        ("optics", {"soft_focus": 0.22, "corner_softness": 0.25}),
        ("crt", {"phosphor_mask": "grille", "mask_scale": 1.0, "mask_strength": 0.13,
                 "scan_strength": 0.0, "bloom": 0.0}),
        ("grain", {"amount": 0.42, "size": 1.85, "roughness": 0.6, "chroma_grain": 0.18,
                   "stock": "super8", "layers": "reversal", "mottle": 0.07}),
        ("halation", {"strength": 0.22, "tint": "warm_white", "threshold": 0.76}),
        ("fade", {"amount": 0.0, "profile": "neutral"}),
        ("flicker", {"amount": 0.15, "character": "projector"}),
        ("gate_weave", {"amount": 0.8, "splice_bump": 0.4}),
        ("dust", {"density": 0.25, "hairs": 0.15}),
        ("vignette", {"amount": 0.28, "softness": 0.55}),
        ("framing", {"aspect": "4:3", "mode": "box", "corner_radius": 0.02}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bed", {"bed": "projector_8mm_run", "level_db": -30.0, "duck": 0.3}),
    ],
    variants=[
        Variant("phototape-fresh", "Fresh Cassette",
                "Processed thirty seconds ago in the viewer, before the image settles down.",
                video={"tone.exposure": 0.0, "saturation.amount": 0.78,
                       "crt.mask_strength": 0.1}),
        Variant("faded-cassette-1995", "Faded Cassette",
                "Eighteen years in a drawer: the additive dyes have nearly given up.",
                video={"saturation.amount": 0.4, "fade.amount": 0.2, "tone.lift": 0.12,
                       "crt.mask_strength": 0.17}),
    ],
))


# nearest: bw-home-16mm-1938 (prewar mottled 16 mm reversal); differs: half the
# gauge in 1960, sprocket flash down one side and a wobblier hand-held camera.
register_preset(Preset(
    id="regular8-bw-home-1960",
    name="Regular 8 Home Movie",
    family="film",
    era="1960",
    desc="Double-8 stock slit down the middle after processing: a frame the size of a grain of rice, sprocket light flashing along one edge, and every splice bumping through the gate.",
    tagline="Tiny-gauge silver, sprocket glow, weave",
    tags=("60s", "8mm", "home-movie", "bw", "silent"),
    keywords=("regular-8", "8mm", "sixties", "home-movie", "bw", "tiny-gauge",
              "sprocket", "silent", "family", "backyard"),
    proc_height=500,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic",
                  "tint": "silver", "tint_amt": 0.1}),
        ("tone", {"exposure": 0.05, "contrast": 1.15, "lift": 0.03, "knee": 0.8}),
        ("optics", {"corner_softness": 0.25, "soft_focus": 0.15}),
        ("grain", {"amount": 0.5, "size": 1.85, "chroma_grain": 0.0,
                   "stock": "super8", "layers": "reversal", "mottle": 0.2,
                   "intermittent": 0.25}),
        ("print_char", {"perf_flash": 0.3, "frameline": 0.2, "dmax_breath": 0.15}),
        ("fade", {"amount": 0.0, "profile": "sepia"}),
        ("cadence", {"pattern": "silent_irregular", "speed": "silent_16fps_in_24"}),
        ("flicker", {"amount": 0.2, "character": "projector"}),
        ("gate_weave", {"amount": 1.8, "splice_bump": 2.0}),
        ("scratches", {"enabled": False, "count": 3, "transient_rate": 1.5}),
        ("dust", {"density": 0.4, "hairs": 0.3}),
        ("light_leak", {"amount": 0.35, "hue": "warm", "frequency": 0.8, "constant": 0.06}),
        ("vignette", {"amount": 0.4, "softness": 0.6}),
        ("framing", {"aspect": "4:3", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -28.0}),
    ],
    variants=[
        Variant("fresh-reel", "Fresh Reel",
                "Back from the drugstore this week, threaded carefully, nothing wrong with it yet.",
                video={"dust.density": 0.15, "gate_weave.amount": 1.0,
                       "light_leak.amount": 0.0, "light_leak.constant": 0.0}),
        Variant("attic-reel", "Attic Reel",
                "Found in a box over the garage: dirt in the gate, scratches, and the silver going warm.",
                video={"dust.density": 0.8, "scratches.enabled": True,
                       "fade.amount": 0.15, "gate_weave.splice_bump": 3.5}),
    ],
))


# nearest: super8-1974 (silent Super 8, 18-frame heartbeat); differs: the sound
# cartridge, with mag-stripe warble, stripe hiss and a running sync track.
register_preset(Preset(
    id="super8-sound-mag-1979",
    name="Super 8 Sound Cartridge",
    family="film",
    era="1979",
    desc="Ektasound cartridge running at eighteen frames with a magnetic stripe laid down the edge: sync voices warbling under the drive cogs, stripe hiss up behind them, projector in the room.",
    tagline="Mag-stripe Super 8, 18 fps, warbling sound",
    tags=("70s", "super8", "home-movie", "sound-cartridge"),
    keywords=("super-8", "sound", "mag-stripe", "seventies", "home-movie", "cartridge",
              "18fps", "warble", "ektasound", "birthday"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.95}),
        ("balance", {"warmth": 0.02, "shadow_tint": "teal", "shadow_amt": 0.14,
                     "high_tint": "cyan", "high_amt": 0.08}),
        ("tone", {"exposure": 0.08, "contrast": 1.06, "lift": 0.05, "knee": 0.84}),
        ("saturation", {"amount": 1.05}),
        ("optics", {"corner_softness": 0.12, "soft_focus": 0.08}),
        ("grain", {"amount": 0.48, "size": 1.9, "chroma_grain": 0.2,
                   "stock": "super8", "layers": "reversal"}),
        ("halation", {"strength": 0.26, "tint": "warm_white", "threshold": 0.74}),
        ("cadence", {"pattern": "projector_flutter"}),
        ("flicker", {"amount": 0.15, "character": "projector"}),
        ("gate_weave", {"amount": 1.2, "splice_bump": 0.8}),
        ("dust", {"density": 0.3, "hairs": 0.2}),
        ("vignette", {"amount": 0.22, "softness": 0.6}),
        ("framing", {"aspect": "4:3", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 12.0, "flutter_depth": 8.0, "cogging": 0.3,
                           "cogging_hz": 18.0}),
        ("a_tape_hiss", {"level_db": -44.0, "type": "dictaphone"}),
        ("a_tape_dropouts", {"enabled": False, "rate": 8.0, "depth_db": 22.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -32.0}),
    ],
    variants=[
        Variant("fresh-cartridge", "Fresh Cartridge",
                "A new cartridge in a serviced projector: the warble is almost polite.",
                audio={"a_wow_flutter.wow_depth": 6.0, "a_wow_flutter.flutter_depth": 4.0,
                       "a_tape_hiss.level_db": -50.0}),
        Variant("worn-stripe", "Worn Stripe",
                "The stripe scraped thin by twenty passes: warble, hiss and holes in the track.",
                audio={"a_wow_flutter.wow_depth": 20.0, "a_wow_flutter.flutter_depth": 12.0,
                       "a_tape_hiss.level_db": -38.0, "a_tape_dropouts.enabled": True}),
    ],
))


# nearest: todd-ao-roadshow-1958 (large-format smoothness, magnetic stereo); differs:
# a hotter desert grade, higher contrast and saturation, and a much drier house.
register_preset(Preset(
    id="roadshow-70mm-epic-1965",
    name="Sixties 70 mm Roadshow Epic",
    family="film",
    era="1965",
    desc="Super Panavision negative on a 70 mm roadshow print: grain almost absent at that negative area, sun baked into the yellows, an aperture ghost off the desert, and six magnetic tracks running wide.",
    tagline="Large-format scale, desert sun, six-track",
    tags=("60s", "70mm", "roadshow", "epic"),
    keywords=("70mm", "roadshow", "sixties", "epic", "super-panavision", "desert",
              "lawrence", "six-track", "overture", "large-format"),
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.85}),
        ("balance", {"warmth": 0.16, "shadow_tint": "teal", "shadow_amt": 0.1,
                     "high_tint": "yellow", "high_amt": 0.2}),
        ("tone", {"exposure": 0.05, "contrast": 1.16, "lift": 0.015, "knee": 0.86}),
        ("saturation", {"amount": 1.14, "vibrance": 0.12}),
        ("optics", {"aperture_ghost": 0.1, "veiling_flare": 0.14}),
        ("grain", {"amount": 0.2, "size": 1.6, "chroma_grain": 0.12,
                   "stock": "fine_35", "layers": "print_from_neg", "mottle": 0.04}),
        ("halation", {"strength": 0.25, "tint": "red_orange", "threshold": 0.8}),
        ("print_char", {"acutance": 0.3, "contrast_buildup": 1, "dmax_breath": 0.1}),
        ("fade", {"amount": 0.0, "profile": "eastman_pink"}),
        ("gate_weave", {"amount": 0.25, "splice_bump": 0.2}),
        ("dust", {"density": 0.12, "hairs": 0.05}),
        ("framing", {"aspect": "2.35", "mode": "box", "edge_soft": 0.003}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 30.0, "high_hz": 14000.0}),
        ("a_channel_aging", {"width": 1.4, "imbalance_db": -0.3, "crosstalk_db": -45.0,
                             "skew_us": 15.0, "phase_wander": 0.05, "mono_bass_hz": 80.0}),
        ("a_tape_sat", {"drive": 1.3, "bump_db": 2.0, "hf_loss": 0.25}),
        ("a_compressor", {"threshold_db": -16.0, "ratio": 2.5, "attack_ms": 16.0}),
        ("a_room", {"mode": "chamber", "size": 1.6, "decay_s": 0.9, "mix": 0.1,
                    "damp": 0.6, "predelay_ms": 20.0}),
    ],
    variants=[
        Variant("35mm-reduction-print", "35 mm Reduction",
                "The general-release reduction that played the neighbourhood houses: grain arrives, the stereo folds in.",
                video={"grain.amount": 0.36, "grain.size": 2.0, "fade.amount": 0.12,
                       "dust.density": 0.3},
                audio={"a_channel_aging.width": 1.0}),
        Variant("restored-70mm-scan", "Restored 70 mm Scan",
                "A modern scan off the original negative: almost nothing between you and the desert.",
                video={"grain.amount": 0.18, "dust.density": 0.04, "gate_weave.amount": 0.15}),
    ],
))


# nearest: classroom-1976 (pink fade, jumping splices, rain scratches); differs:
# a 1961 print still in good order, harder patrol-car sun and a close stern narrator.
register_preset(Preset(
    id="highway-safety-film-1961",
    name="Highway Safety Film",
    family="film",
    era="1961",
    desc="State-patrol driver-education reel on Ektachrome 16: highlights blown off chrome and asphalt, flat reversal color, and a narrator right on the microphone over an optical track.",
    tagline="Flat Ektachrome 16, hard sun, stern narrator",
    tags=("60s", "16mm", "educational", "scare-film"),
    keywords=("driver-ed", "highway-safety", "sixties", "scare-film", "ektachrome",
              "16mm", "patrol", "classroom", "wreck", "narration"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.85}),
        ("balance", {"warmth": 0.05}),
        ("tone", {"exposure": 0.1, "contrast": 1.12, "lift": 0.03, "knee": 0.7}),
        ("saturation", {"amount": 1.05}),
        ("optics", {"corner_softness": 0.12}),
        ("grain", {"amount": 0.46, "size": 1.95, "chroma_grain": 0.22,
                   "stock": "doc_16", "layers": "reversal"}),
        ("halation", {"strength": 0.28, "tint": "orange", "threshold": 0.7}),
        ("fade", {"amount": 0.1, "profile": "neutral"}),
        ("gate_weave", {"amount": 0.9, "splice_bump": 0.6}),
        ("flicker", {"amount": 0.16, "character": "projector"}),
        ("frame_damage", {"enabled": False, "splice_skip_rate": 2.0, "slip_rate": 1.0,
                          "blotch_rate": 2.0}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("dust", {"density": 0.35, "hairs": 0.25}),
        ("vignette", {"amount": 0.28, "softness": 0.6}),
        ("framing", {"aspect": "1.37", "mode": "box"}),
        ("projection", {"shutter_flicker": 0.2, "ambient_lift": 0.2, "keystone": 0.02}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.5,
                              "proximity": 0.3, "self_noise_db": -58.0}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "cell_noise": -45.0,
                             "flutter": 0.45, "drive": 1.6}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.5, "attack_ms": 8.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -34.0}),
    ],
    variants=[
        Variant("worn-classroom-print", "Worn Classroom Print",
                "The same reel in 1974 after a decade of gym-period screenings: pink, spliced and filthy.",
                video={"fade.profile": "eastman_pink", "fade.amount": 0.3,
                       "frame_damage.enabled": True, "dust.density": 0.6,
                       "scratches.count": 5}),
        Variant("restored-archive", "Restored Archive",
                "A state-archive scan off an unrun print found in the original can.",
                video={"dust.density": 0.05, "fade.amount": 0.0, "scratches.count": 0,
                       "gate_weave.amount": 0.5}),
    ],
))


# nearest: highway-safety-film-1961 (same gauge and sponsor economics); differs:
# olive-drab shadows, desaturated color and a badly serviced projector's flutter.
register_preset(Preset(
    id="army-training-16mm-1968",
    name="Army Training Film",
    family="film",
    era="1968",
    desc="Signal-corps instructional reel on Ektachrome 16: green pushed into every shadow by olive drab and canvas, drill narration over a worn optical track, and a base projector that will not hold speed.",
    tagline="Olive Ektachrome, drill narration, flutter",
    tags=("60s", "16mm", "military", "training"),
    keywords=("army", "training", "sixties", "military", "vietnam-era", "16mm",
              "ektachrome", "drill", "instructional", "olive-drab"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.8}),
        ("balance", {"warmth": 0.02, "shadow_tint": "green", "shadow_amt": 0.32,
                     "high_tint": "yellow", "high_amt": 0.1}),
        ("tone", {"contrast": 1.08, "lift": 0.05, "knee": 0.8}),
        ("saturation", {"amount": 0.88}),
        ("optics", {"corner_softness": 0.12}),
        ("grain", {"amount": 0.46, "size": 1.95, "chroma_grain": 0.2,
                   "stock": "doc_16", "layers": "reversal"}),
        ("halation", {"strength": 0.25, "tint": "orange", "threshold": 0.74}),
        ("print_char", {"acutance": 0.15, "contrast_buildup": 0, "dmax_breath": 0.12}),
        ("fade", {"amount": 0.06, "profile": "neutral"}),
        ("gate_weave", {"amount": 1.0, "splice_bump": 0.8}),
        ("flicker", {"amount": 0.18, "character": "projector"}),
        ("scratches", {"count": 1, "transient_rate": 0.8}),
        ("dust", {"density": 0.35, "hairs": 0.25}),
        ("vignette", {"amount": 0.3, "softness": 0.6}),
        ("framing", {"aspect": "1.37", "mode": "box"}),
        ("projection", {"shutter_flicker": 0.22, "ambient_lift": 0.22}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.5,
                              "self_noise_db": -56.0}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "cell_noise": -43.0,
                             "flutter": 0.6, "drive": 1.8}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 4.0, "attack_ms": 7.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -33.0}),
    ],
    variants=[
        Variant("archives-scan", "Archives Scan",
                "The preservation copy: dirt gone, speed steady, the olive still there.",
                video={"dust.density": 0.05, "scratches.count": 0, "gate_weave.amount": 0.5},
                audio={"a_optical_track.flutter": 0.2}),
        Variant("base-rec-hall-print", "Rec Hall Print",
                "The copy that lived at the post and got run on Tuesdays for eight years.",
                video={"dust.density": 0.7, "print_char.contrast_buildup": 2,
                       "scratches.count": 4}),
    ],
))


# nearest: student-film-1971 (uneven exposure, coarse reversal grain); differs:
# nineties hand-processing mottle, a wind-up Bolex flutter and electret sound.
register_preset(Preset(
    id="film-school-16mm-bw-1995",
    name="Film-School Bolex Reel",
    family="film",
    era="1995",
    desc="Black-and-white reversal run through a bucket in a campus darkroom: uneven development mottling the frame, a wind-up spring dragging by the end of the take, and scratches on the emulsion side.",
    tagline="Hand-processed reversal, wind-up flutter",
    tags=("90s", "16mm", "bw", "student"),
    keywords=("film-school", "bolex", "nineties", "student", "16mm", "bw", "reversal",
              "hand-processed", "wind-up", "mos"),
    proc_height=620,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "neutral"}),
        ("tone", {"exposure": -0.05, "contrast": 1.25, "lift": 0.03, "knee": 0.78}),
        ("optics", {"corner_softness": 0.15}),
        ("grain", {"amount": 0.55, "size": 2.0, "chroma_grain": 0.0, "stock": "doc_16",
                   "layers": "reversal", "intermittent": 0.4, "mottle": 0.2}),
        ("halation", {"strength": 0.25, "tint": "neutral", "threshold": 0.72}),
        ("cadence", {"pattern": "projector_flutter"}),
        ("flicker", {"amount": 0.2, "character": "projector"}),
        ("gate_weave", {"amount": 1.2, "splice_bump": 3.0}),
        ("scratches", {"count": 2, "transient_rate": 1.5, "emulsion_side": 0.4}),
        ("dust", {"density": 0.5, "hairs": 0.35}),
        ("light_leak", {"amount": 0.25, "hue": "warm", "frequency": 0.6, "constant": 0.05}),
        ("chroma_dv", {"enabled": False, "ratio": "4:1:1", "edge_sharpen": 0.35}),
        ("interlace", {"enabled": False, "combing": 0.5, "twitter": 0.3}),
        ("vignette", {"amount": 0.3, "softness": 0.6}),
        ("framing", {"aspect": "1.37", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "electret_1985", "amount": 0.6,
                              "handling": 0.3, "self_noise_db": -48.0}),
        ("a_wow_flutter", {"wow_depth": 5.0, "flutter_depth": 6.0}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 3.0, "attack_ms": 10.0}),
    ],
    variants=[
        Variant("telecine-to-minidv", "Telecined to MiniDV",
                "Shot off a wall into a camcorder for the crit: DV chroma and field combing over the grain.",
                video={"chroma_dv.enabled": True, "interlace.enabled": True}),
        Variant("festival-print", "Festival Print",
                "The one clean print, machine-processed for the student showcase.",
                video={"dust.density": 0.2, "grain.mottle": 0.05, "grain.intermittent": 0.12,
                       "scratches.count": 0, "gate_weave.splice_bump": 1.0}),
    ],
))


# nearest: travelogue-1958 (Kodachrome postcard saturation, projector cadence); differs:
# Ektachrome water glare through a long lens, blown highlights and a warm hall.
register_preset(Preset(
    id="surf-film-16mm-1966",
    name="Endless-Summer Surf Film",
    family="film",
    era="1966",
    desc="Four-hundred-foot loads of Ektachrome shot off the sand on a long lens: highlights blown off the water, veiling flare through salt haze, and a narrator working a rented hall.",
    tagline="Water-glare Ektachrome, long lens, hall mono",
    tags=("60s", "16mm", "surf", "travelogue"),
    keywords=("surf", "sixties", "endless-summer", "16mm", "ektachrome", "water",
              "beach", "narrator", "surf-rock", "travelogue"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.9}),
        ("balance", {"warmth": 0.1, "high_tint": "cyan", "high_amt": 0.1}),
        ("tone", {"exposure": 0.12, "contrast": 1.1, "lift": 0.02, "knee": 0.68}),
        ("saturation", {"amount": 1.2, "vibrance": 0.2}),
        ("optics", {"soft_focus": 0.12, "focus_drift": 0.12, "veiling_flare": 0.3,
                    "corner_softness": 0.1}),
        ("grain", {"amount": 0.44, "size": 1.95, "chroma_grain": 0.22,
                   "stock": "doc_16", "layers": "reversal"}),
        ("halation", {"strength": 0.35, "tint": "warm_white", "threshold": 0.7}),
        ("print_char", {"acutance": 0.15, "contrast_buildup": 0}),
        ("gate_weave", {"amount": 0.9, "splice_bump": 0.5}),
        ("flicker", {"amount": 0.14, "character": "projector"}),
        ("dust", {"density": 0.3, "hairs": 0.2}),
        ("ntsc", {"enabled": False, "strength": 0.7, "luma_bw": 3.2, "chroma_bw": 0.7,
                  "phase_noise": 2.0, "dot_crawl": 0.3, "rainbow": 0.25}),
        ("vignette", {"amount": 0.25, "softness": 0.6}),
        ("framing", {"aspect": "1.37", "mode": "box"}),
        ("projection", {"shutter_flicker": 0.18, "ambient_lift": 0.15}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.45,
                              "proximity": 0.25, "self_noise_db": -58.0}),
        ("a_optical_track", {"low_hz": 80.0, "high_hz": 8000.0, "academy_rolloff": "none",
                             "cell_noise": -48.0, "flutter": 0.4, "drive": 1.4}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 3.0, "attack_ms": 9.0}),
        ("a_room", {"mode": "chamber", "size": 1.4, "decay_s": 0.8, "mix": 0.1}),
    ],
    variants=[
        Variant("35mm-blowup-print", "35 mm Blowup",
                "Blown up for the distributor after the four-walling paid off: another generation of grain.",
                video={"grain.amount": 0.5, "grain.size": 2.0,
                       "print_char.contrast_buildup": 1, "dust.density": 0.2}),
        Variant("tv-broadcast-1972", "TV Broadcast",
                "Sold to a Sunday afternoon slot and run off a station telecine.",
                video={"ntsc.enabled": True, "saturation.amount": 1.1}),
    ],
))


# nearest: travelogue-1958 (Kodachrome, 16 mm, lecture circuit); differs: altitude
# blue and UV, snow blowing out the highlights, and a colder grade throughout.
register_preset(Preset(
    id="mountain-expedition-16mm-1953",
    name="Mountain Expedition 16 mm",
    family="film",
    era="1953",
    desc="Kodachrome carried above the icefall in a cine camera kept warm inside a jacket: ultraviolet stacking blue into every shadow, snow blowing straight through the highlights, ice glare veiling the lens.",
    tagline="Kodachrome altitude blue, snow glare, mono",
    tags=("50s", "16mm", "kodachrome", "expedition"),
    keywords=("mountaineering", "everest", "fifties", "expedition", "kodachrome",
              "16mm", "snow", "altitude", "documentary", "ice"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 0.9}),
        ("balance", {"warmth": -0.2, "tint": -0.05, "shadow_tint": "blue",
                     "shadow_amt": 0.42, "high_tint": "cyan", "high_amt": 0.18}),
        ("tone", {"exposure": 0.15, "contrast": 1.12, "lift": 0.02, "knee": 0.66}),
        ("saturation", {"amount": 1.1}),
        ("optics", {"veiling_flare": 0.25, "corner_softness": 0.12}),
        ("grain", {"amount": 0.4, "size": 1.95, "chroma_grain": 0.18,
                   "stock": "doc_16", "layers": "reversal"}),
        ("halation", {"strength": 0.3, "tint": "warm_white", "threshold": 0.68}),
        ("print_char", {"acutance": 0.2, "contrast_buildup": 0, "dmax_breath": 0.1}),
        ("fade", {"amount": 0.0, "profile": "neutral"}),
        ("gate_weave", {"amount": 1.0, "splice_bump": 0.6}),
        ("flicker", {"amount": 0.15, "character": "projector"}),
        ("dust", {"density": 0.3, "hairs": 0.2}),
        ("vignette", {"amount": 0.28, "softness": 0.6}),
        ("framing", {"aspect": "1.37", "mode": "box"}),
        ("projection", {"shutter_flicker": 0.2, "ambient_lift": 0.18}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.5,
                              "self_noise_db": -56.0}),
        ("a_optical_track", {"academy_rolloff": "classroom_16mm", "cell_noise": -46.0,
                             "flutter": 0.4, "drive": 1.5}),
        ("a_compressor", {"threshold_db": -19.0, "ratio": 3.5, "attack_ms": 9.0}),
        ("a_room", {"mode": "chamber", "size": 1.6, "decay_s": 0.9, "mix": 0.1}),
    ],
    variants=[
        Variant("lecture-hall-print", "Lecture Hall Print",
                "The print that toured geographical societies for a decade, printed up each time.",
                video={"dust.density": 0.6, "print_char.contrast_buildup": 2,
                       "fade.amount": 0.1, "gate_weave.amount": 1.3}),
        Variant("restored", "Restored",
                "A clean scan of the original camera reels, blue and all.",
                video={"dust.density": 0.05, "grain.amount": 0.34,
                       "gate_weave.amount": 0.5}),
    ],
))


# nearest: super8-sound-mag-1979 (the Super 8 Ektasound cartridge); differs:
# standard 8 in 1966 - Kodachrome, a worse stripe, mains hum and a cheaper lens.
register_preset(Preset(
    id="home-movie-sound8-mag-1966",
    name="Sound 8 Home Movie",
    family="film",
    era="1966",
    desc="Standard 8 with a magnetic stripe glued on after processing: Kodachrome reds, a cheap lens fringing at the corners, drive cogs beating through the birthday song and mains hum under everything.",
    tagline="Standard 8 mag stripe, warble and hum",
    tags=("60s", "8mm", "home-movie", "kodachrome"),
    keywords=("sound-8", "8mm", "sixties", "home-movie", "mag-stripe", "birthday",
              "warble", "family", "projector", "kodachrome"),
    proc_height=500,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 0.85}),
        ("balance", {"warmth": 0.2, "high_tint": "yellow", "high_amt": 0.12}),
        ("tone", {"contrast": 1.18, "lift": 0.035, "knee": 0.78}),
        ("saturation", {"amount": 1.2, "hue": -3.0}),
        ("optics", {"corner_softness": 0.3, "soft_focus": 0.12,
                    "chromatic_aberration": 1.2}),
        ("grain", {"amount": 0.48, "size": 1.85, "chroma_grain": 0.2,
                   "stock": "super8", "layers": "reversal"}),
        ("halation", {"strength": 0.3, "tint": "orange", "threshold": 0.72}),
        ("fade", {"amount": 0.0, "profile": "neutral"}),
        ("cadence", {"pattern": "projector_flutter"}),
        ("flicker", {"amount": 0.2, "character": "projector"}),
        ("gate_weave", {"amount": 1.5, "splice_bump": 2.0}),
        ("dust", {"density": 0.4, "hairs": 0.3}),
        ("light_leak", {"amount": 0.3, "hue": "warm", "frequency": 0.5, "constant": 0.06}),
        ("vignette", {"amount": 0.4, "softness": 0.6}),
        ("framing", {"aspect": "4:3", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 14.0, "flutter_depth": 9.0, "cogging": 0.35,
                           "cogging_hz": 24.0}),
        ("a_tape_hiss", {"level_db": -42.0, "type": "dictaphone"}),
        ("a_tape_dropouts", {"enabled": False, "rate": 6.0, "depth_db": 20.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -30.0}),
        ("a_hum", {"hz": "60", "level_db": -50.0, "buzz": 0.3}),
    ],
    variants=[
        Variant("fresh-stripe", "Fresh Stripe",
                "Striped last month and run on a serviced machine: still a warble, but a polite one.",
                audio={"a_wow_flutter.wow_depth": 8.0, "a_tape_hiss.level_db": -48.0,
                       "a_hum.level_db": -58.0}),
        Variant("drawer-reel-1990", "Drawer Reel",
                "Found behind the Christmas decorations: the stripe has shed and the reel has gone flat.",
                video={"fade.amount": 0.15},
                audio={"a_wow_flutter.wow_depth": 20.0, "a_tape_dropouts.enabled": True}),
    ],
))
