"""Film-family presets: a century of emulsion, from nitrate to release prints."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="silent-1918",
    name="Silent Nitrate",
    family="film",
    era="1918",
    desc="Hand-cranked orthochromatic nitrate: dark lips and white skies, violent flicker, a frame that never sits still. Optionally tinted like the exhibition prints.",
    tags=("silent", "1910s", "bw", "nitrate"),
    proc_height=560,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic", "tint": "nitrate_warm", "tint_amt": 0.4}),
        ("tone", {"contrast": 1.3, "lift": 0.07, "knee": 0.7, "gamma": 0.95}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("grain", {"amount": 0.8, "size": 2.6, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("flicker", {"amount": 0.55, "character": "hand_cranked", "spatial": 0.4}),
        ("gate_weave", {"amount": 2.6, "splice_bump": 2.0}),
        ("scratches", {"count": 4, "transient_rate": 1.5}),
        ("dust", {"density": 0.9, "size": 1.4, "hairs": 0.6}),
        ("frame_damage", {"splice_skip_rate": 2.0, "blotch_rate": 1.0}),
        ("vignette", {"amount": 0.55, "softness": 0.6, "roundness": 0.9}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.02}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -28.0}),
        ("a_hum", {"hz": 50, "level_db": -52.0}),
    ],
    variants=[
        Variant("amber", "Amber Tint", "Interior-scene amber exhibition tint.",
                video={"mono.tint": "sepia", "mono.tint_amt": 0.55}),
        Variant("night", "Night Blue", "Day-for-night blue exhibition tint.",
                video={"mono.tint": "cyanotype", "mono.tint_amt": 0.5}),
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio under the projector.",
                audio={"a_gain.db": -6.0}),
    ],
))

register_preset(Preset(
    id="twostrip-1929",
    name="Two-Strip Technicolor",
    family="film",
    era="1929",
    desc="Red and green glued back to back: peach skies, seafoam shadows, colors that never existed but you remember anyway. Fringes where the strips disagree.",
    tags=("technicolor", "20s", "early-color"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "technicolor2", "strength": 1.0}),
        ("tone", {"contrast": 1.16, "lift": 0.05, "knee": 0.78}),
        ("optics", {"chromatic_aberration": 2.5, "soft_focus": 0.25}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("grain", {"amount": 0.6, "size": 2.4, "chroma_grain": 0.35}),
        ("halation", {"strength": 0.4, "tint": "orange", "threshold": 0.75}),
        ("flicker", {"amount": 0.3, "color_flicker": 0.3}),
        ("gate_weave", {"amount": 2.0}),
        ("dust", {"density": 0.8, "hairs": 0.4}),
        ("scratches", {"count": 2}),
        ("vignette", {"amount": 0.4}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -42.0, "academy_rolloff": "newsreel_1930s", "drive": 1.8}),
        ("a_compressor", {"ratio": 4.0}),
    ],
))

register_preset(Preset(
    id="threestrip-1939",
    name="Glorious Technicolor",
    family="film",
    era="1939",
    desc="The full three-strip miracle: jewel saturation, creamy highlights with red halos, blacks like theater velvet. Somewhere over the rainbow, in 35mm.",
    tags=("technicolor", "30s", "golden-age"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "technicolor3", "strength": 1.0}),
        ("tone", {"contrast": 1.18, "lift": 0.03, "knee": 0.8, "pivot": 0.45}),
        ("optics", {"soft_focus": 0.18, "chromatic_aberration": 1.0}),
        ("grain", {"amount": 0.4, "size": 1.9, "chroma_grain": 0.3, "stock": "fine_35"}),
        ("halation", {"strength": 0.45, "tint": "red", "threshold": 0.72}),
        ("gate_weave", {"amount": 1.1}),
        ("flicker", {"amount": 0.12}),
        ("dust", {"density": 0.35}),
        ("vignette", {"amount": 0.3, "softness": 0.75}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -50.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 3.5}),
    ],
    variants=[
        Variant("premiere", "Premiere Print", "A pristine dye-transfer print, first reel, first night.",
                video={"grain.amount": 0.3, "dust.density": 0.15, "gate_weave.amount": 0.8}),
        Variant("revival", "Revival House", "Decades of touring: scratches, splices, faded glory.",
                video={"dust.density": 1.0, "grain.amount": 0.55, "gate_weave.amount": 1.8}),
    ],
))

register_preset(Preset(
    id="musical-1952",
    name="Technicolor Musical",
    family="film",
    era="1952",
    desc="MGM soundstage sunshine: saturated primaries, gentle diffusion on the close-ups, a print that glows from within. Gotta dance.",
    tags=("technicolor", "50s", "musical"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "technicolor3", "strength": 0.85}),
        ("tone", {"contrast": 1.12, "lift": 0.02, "knee": 0.83}),
        ("saturation", {"amount": 1.1, "vibrance": 0.2}),
        ("optics", {"diffusion": 0.25, "soft_focus": 0.1}),
        ("grain", {"amount": 0.35, "size": 1.7, "chroma_grain": 0.3, "stock": "fine_35"}),
        ("halation", {"strength": 0.35, "tint": "warm_white", "threshold": 0.78}),
        ("gate_weave", {"amount": 0.9}),
        ("flicker", {"amount": 0.08}),
        ("dust", {"density": 0.25}),
        ("vignette", {"amount": 0.25}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -56.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_room", {"size": 0.8, "decay_s": 0.6, "mix": 0.12}),
    ],
    variants=[
        Variant("worn-print", "Worn Print", "The touring copy: more grain, dirt, and shimmer.",
                video={"grain.amount": 0.55, "dust.density": 0.8, "gate_weave.amount": 1.6,
                       "flicker.amount": 0.2}),
    ],
))

register_preset(Preset(
    id="noir-1947",
    name="Film Noir",
    family="film",
    era="1947",
    desc="Panchromatic shadows you could drown in: hard contrast, halation blooming off wet asphalt and cigarette smoke, mono optical hiss.",
    tags=("bw", "40s", "noir"),
    upscale="sharp",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.32, "lift": 0.015, "knee": 0.8, "pivot": 0.38}),
        ("grain", {"amount": 0.45, "size": 1.9, "chroma_grain": 0.0, "stock": "fine_35"}),
        ("halation", {"strength": 0.5, "tint": "neutral", "threshold": 0.75}),
        ("gate_weave", {"amount": 1.0}),
        ("flicker", {"amount": 0.1}),
        ("dust", {"density": 0.4}),
        ("vignette", {"amount": 0.42, "softness": 0.65}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 6800.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -50.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 4.0}),
    ],
))

register_preset(Preset(
    id="scope-1958",
    name="CinemaScope Epic",
    family="film",
    era="1958",
    desc="Widescreen Eastman grandeur: 2.35 letterbox, anamorphic oval falloff, warm roadshow color a half-step past its prime.",
    tags=("50s", "widescreen", "epic"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.8}),
        ("tone", {"contrast": 1.12, "lift": 0.03, "knee": 0.8}),
        ("optics", {"chromatic_aberration": 1.5, "distortion": -0.12}),
        ("grain", {"amount": 0.42, "size": 2.0, "chroma_grain": 0.4}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("gate_weave", {"amount": 1.0}),
        ("dust", {"density": 0.35}),
        ("vignette", {"amount": 0.35, "roundness": 0.6}),
        ("fade", {"amount": 0.22, "profile": "eastman_pink"}),
        ("framing", {"aspect": "2.35", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 9500.0}),
        ("a_optical_track", {"cell_noise": -54.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_room", {"size": 1.1, "decay_s": 0.8, "mix": 0.14}),
    ],
))

register_preset(Preset(
    id="kodachrome-1964",
    name="Kodachrome Home Movie",
    family="film",
    era="1964",
    desc="8mm reversal out of a Brownie box in the attic: impossibly red reds, cyan skies, dust and weave and a projector somewhere behind you.",
    tags=("60s", "8mm", "home-movie", "kodachrome"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 1.0}),
        ("tone", {"contrast": 1.14, "lift": 0.04, "knee": 0.78}),
        ("balance", {"warmth": 0.25}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.4, "chromatic_aberration": 1.2}),
        ("grain", {"amount": 0.7, "size": 2.6, "chroma_grain": 0.5, "stock": "super8"}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("gate_weave", {"amount": 2.4, "splice_bump": 1.5}),
        ("flicker", {"amount": 0.35, "character": "projector"}),
        ("dust", {"density": 0.85, "size": 1.3, "hairs": 0.5}),
        ("scratches", {"count": 2, "transient_rate": 0.8}),
        ("light_leak", {"constant": 0.12, "frequency": 0.6}),
        ("vignette", {"amount": 0.5, "softness": 0.6}),
        ("projection", {"shutter_flicker": 0.25, "ambient_lift": 0.25}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -24.0}),
        ("a_hum", {"hz": 60, "level_db": -54.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain treated original audio under the projector clatter.",
                audio={"a_gain.db": -8.0}),
        Variant("attic", "Attic Reel", "Sixty summers of storage: heavy fade and damage.",
                video={"dust.density": 1.0, "scratches.count": 5, "flicker.amount": 0.5,
                       "gate_weave.amount": 3.2}),
    ],
))

register_preset(Preset(
    id="super8-1974",
    name="Super 8 Family Reel",
    family="film",
    era="1974",
    desc="Birthday cakes and back yards on Super 8: warm faded color, big soft grain, that 18-frame heartbeat and the projector's whir.",
    tags=("70s", "super8", "home-movie"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.08, "lift": 0.05, "knee": 0.8}),
        ("balance", {"warmth": 0.3, "shadow_tint": "brown", "shadow_amt": 0.25}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.35, "focus_drift": 0.25}),
        ("grain", {"amount": 0.75, "size": 2.9, "chroma_grain": 0.55, "stock": "super8"}),
        ("halation", {"strength": 0.28, "tint": "orange"}),
        ("gate_weave", {"amount": 2.2, "splice_bump": 1.2}),
        ("flicker", {"amount": 0.3, "character": "projector"}),
        ("dust", {"density": 0.9, "hairs": 0.5}),
        ("fade", {"amount": 0.3, "profile": "eastman_pink"}),
        ("light_leak", {"constant": 0.08, "frequency": 0.4}),
        ("vignette", {"amount": 0.45}),
        ("projection", {"shutter_flicker": 0.3, "ambient_lift": 0.2}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 12.0, "flutter_depth": 8.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -30.0}),
        ("a_tape_hiss", {"level_db": -42.0}),
    ],
))

register_preset(Preset(
    id="doc-16mm-1968",
    name="16mm Documentary",
    family="film",
    era="1968",
    desc="Vérité 16mm: muted Eastman color, honest grain, handheld gate weave — history as the crew actually saw it.",
    tags=("60s", "16mm", "documentary"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.1, "lift": 0.04}),
        ("grain", {"amount": 0.6, "size": 2.3, "chroma_grain": 0.5, "stock": "doc_16"}),
        ("halation", {"strength": 0.25, "tint": "orange"}),
        ("gate_weave", {"amount": 1.8}),
        ("flicker", {"amount": 0.15}),
        ("dust", {"density": 0.6, "hairs": 0.35}),
        ("scratches", {"count": 1, "transient_rate": 0.5}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -49.0, "academy_rolloff": "classroom_16mm"}),
        ("a_agc", {"amount": 0.4}),
    ],
))

register_preset(Preset(
    id="classroom-1976",
    name="Classroom Print",
    family="film",
    era="1976",
    desc="The AV-cart filmstrip look: a 16mm print gone pink, splices that jump, scratches like rain, and the Bell & Howell clattering along.",
    tags=("70s", "16mm", "educational", "faded"),
    proc_height=600,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.8}),
        ("tone", {"contrast": 1.02, "lift": 0.06, "knee": 0.8}),
        ("fade", {"amount": 0.55, "profile": "eastman_pink", "bloom_whites": 0.4}),
        ("grain", {"amount": 0.65, "size": 2.4, "chroma_grain": 0.45, "stock": "doc_16"}),
        ("halation", {"strength": 0.22, "tint": "orange"}),
        ("gate_weave", {"amount": 2.0, "splice_bump": 2.0}),
        ("flicker", {"amount": 0.28, "character": "projector"}),
        ("dust", {"density": 0.9, "size": 1.3, "hairs": 0.6}),
        ("scratches", {"count": 5, "transient_rate": 1.2}),
        ("frame_damage", {"splice_skip_rate": 1.5, "slip_rate": 0.5, "blotch_rate": 0.6}),
        ("plate", {"pack": "grime", "opacity": 0.25, "blend": "screen", "cycle": "hold"}),
        ("vignette", {"amount": 0.4}),
        ("projection", {"shutter_flicker": 0.35, "ambient_lift": 0.3, "keystone": 0.06}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 130.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -42.0, "academy_rolloff": "classroom_16mm", "drive": 1.8}),
        ("a_wow_flutter", {"wow_depth": 10.0, "flutter_depth": 7.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -26.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
    ],
))

register_preset(Preset(
    id="grindhouse-1973",
    name="Grindhouse Print",
    family="film",
    era="1973",
    desc="42nd-Street survivor: burned, spliced, scratched to ribbons, crushed contrast and a red-shifted soul. The print fights back.",
    tags=("70s", "exploitation", "damaged"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.22, "lift": 0.05, "knee": 0.74, "pivot": 0.4}),
        ("saturation", {"amount": 1.12}),
        ("fade", {"amount": 0.4, "profile": "cyan_loss"}),
        ("grain", {"amount": 0.8, "size": 2.5, "chroma_grain": 0.5, "stock": "push_process"}),
        ("halation", {"strength": 0.4, "tint": "red"}),
        ("gate_weave", {"amount": 2.2, "splice_bump": 2.5}),
        ("flicker", {"amount": 0.3, "character": "projector"}),
        ("dust", {"density": 1.0, "size": 1.5, "hairs": 0.8}),
        ("scratches", {"count": 7, "transient_rate": 2.0}),
        ("frame_damage", {"splice_skip_rate": 3.0, "slip_rate": 1.0, "blotch_rate": 1.2}),
        ("plate", {"pack": "film_burns", "opacity": 0.5, "blend": "screen", "cycle": "shuffle_fast",
                   "gate": 0.08, "jitter": 60.0}),
        ("vignette", {"amount": 0.45}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -38.0, "academy_rolloff": "classroom_16mm", "drive": 2.4}),
        ("a_distortion", {"type": "soft", "drive": 2.5}),
        ("a_hum", {"hz": 60, "level_db": -44.0}),
    ],
))

register_preset(Preset(
    id="eastman-faded-1979",
    name="Faded Eastman Print",
    family="film",
    era="1979",
    desc="The signature pink apocalypse of 70s color stock: cyan dye gone, magenta marching on, memories rose-tinted by chemistry.",
    tags=("70s", "faded", "pink"),
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.02, "lift": 0.05}),
        ("fade", {"amount": 0.72, "profile": "eastman_pink", "bloom_whites": 0.45}),
        ("grain", {"amount": 0.5, "size": 2.1, "chroma_grain": 0.4}),
        ("gate_weave", {"amount": 1.2}),
        ("flicker", {"amount": 0.14}),
        ("dust", {"density": 0.7}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_optical_track", {"cell_noise": -48.0, "academy_rolloff": "classroom_16mm"}),
    ],
))

register_preset(Preset(
    id="newsreel-1942",
    name="Wartime Newsreel",
    family="film",
    era="1942",
    desc="Movietone urgency: contrasty B&W, colder silver tone, dupey grain, the optical track crackling with static and history.",
    tags=("bw", "40s", "newsreel"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.3}),
        ("tone", {"contrast": 1.26, "lift": 0.04, "knee": 0.76}),
        ("grain", {"amount": 0.7, "size": 2.2, "chroma_grain": 0.0, "stock": "newsreel_35"}),
        ("halation", {"strength": 0.3, "tint": "neutral"}),
        ("gate_weave", {"amount": 1.6}),
        ("flicker", {"amount": 0.25}),
        ("dust", {"density": 0.8, "size": 1.2, "hairs": 0.5}),
        ("scratches", {"count": 3, "transient_rate": 1.0}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.3}),
        ("vignette", {"amount": 0.35}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -38.0, "academy_rolloff": "newsreel_1930s", "drive": 2.0}),
        ("a_compressor", {"ratio": 5.0}),
    ],
))

register_preset(Preset(
    id="tv-movie-1977",
    name="Made-for-TV Movie",
    family="film",
    era="1977",
    desc="Shot on 35, seen through the tube: film grain under NTSC softness, telecine cadence, that Sunday-night amber warmth.",
    tags=("70s", "telecine", "tv"),
    proc_height=560,
    upscale="soft",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.08, "lift": 0.04}),
        ("balance", {"warmth": 0.2}),
        ("grain", {"amount": 0.45, "size": 2.0, "chroma_grain": 0.4}),
        ("halation", {"strength": 0.25, "tint": "orange"}),
        ("gate_weave", {"amount": 0.8}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.5}),
        ("ntsc", {"strength": 0.8, "phase_noise": 2.4, "dot_crawl": 0.3}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.12, "curvature": 0.08}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.07}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -44.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
    ],
))

register_preset(Preset(
    id="drive-in-1959",
    name="Drive-In Feature",
    family="film",
    era="1959",
    desc="Dusk, a windshield, a tinny door-hung speaker: cheap saturated print, projection keystone, bugs in the beam.",
    tags=("50s", "drive-in", "b-movie"),
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.85}),
        ("tone", {"contrast": 1.14, "lift": 0.05, "knee": 0.78}),
        ("grain", {"amount": 0.55, "size": 2.2, "chroma_grain": 0.45}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("gate_weave", {"amount": 1.6}),
        ("flicker", {"amount": 0.22, "character": "projector"}),
        ("dust", {"density": 0.9, "hairs": 0.4}),
        ("scratches", {"count": 3}),
        ("projection", {"shutter_flicker": 0.3, "keystone": 0.1, "ambient_lift": 0.3}),
        ("vignette", {"amount": 0.5, "softness": 0.55}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 180.0, "high_hz": 4500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "car_dash_1978", "strength": 0.8}),
        ("a_distortion", {"type": "soft", "drive": 2.2}),
        ("a_hum", {"hz": 60, "level_db": -46.0}),
    ],
))
