"""Film-family presets, second reel: early cinema, small gauges, and print stocks
from the actuality era through the Sundance blowup."""

from ..engine.presets import Preset, Variant, register_preset


def _silent_audio(machine="proj_16mm", level=-27.0, hum_hz=60, hum_db=-54.0):
    """House style for silent-film presets: source muted under a projector bed."""
    return [
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": machine, "level_db": level}),
        ("a_hum", {"hz": hum_hz, "level_db": hum_db}),
    ]


_KEEP_SOUND = Variant("keep-sound", "Keep Sound",
                      "Retain the (treated) original audio under the projector.",
                      audio={"a_gain.db": -6.0})

register_preset(Preset(
    id="actuality-1900",
    name="Actuality Film",
    family="film",
    era="1900",
    desc="Cinema's first decade: blue-blind emulsion that turns skies to milk and lips to ink, hand-crank lurch at sixteen frames, static sparks biting the printer dark.",
    tagline="Blue-blind whites, 16 fps lurch, sparks",
    tags=("1900s", "bw", "silent", "actuality"),
    proc_height=520,
    upscale="soft",
    video=[
        ("mono", {"response": "blue_sensitive", "tint": "silver", "tint_amt": 0.2}),
        ("tone", {"contrast": 1.35, "lift": 0.08, "knee": 0.68, "gamma": 0.95}),
        ("optics", {"soft_focus": 0.2, "corner_softness": 0.5}),
        ("cadence", {"pattern": "silent_irregular", "speed": "silent_16fps_in_24"}),
        ("grain", {"amount": 0.62, "size": 2.03, "chroma_grain": 0.0, "stock": "print_dupe",
                   "intermittent": 0.4, "mottle": 0.3}),
        ("flicker", {"amount": 0.58, "character": "hand_cranked", "spatial": 0.5}),
        ("gate_weave", {"amount": 3.2, "splice_bump": 2.0}),
        ("scratches", {"count": 5, "transient_rate": 2.0}),
        ("dust", {"density": 1.0, "size": 1.5, "hairs": 0.7}),
        ("frame_damage", {"splice_skip_rate": 2.5, "blotch_rate": 1.5, "static_flash": 6.0}),
        ("vignette", {"amount": 0.62, "softness": 0.45, "roundness": 0.95}),
        ("framing", {"aspect": "source", "corner_radius": 0.02}),
    ],
    audio=_silent_audio(level=-26.0, hum_hz=50),
    variants=[
        _KEEP_SOUND,
        Variant("paper-print", "Paper Print", "Survived only as a copyright paper roll: softer, harsher, barely holding an image.",
                video={"optics.soft_focus": 0.5, "tone.contrast": 1.5, "grain.amount": 0.65,
                       "frame_damage.blotch_rate": 3.0}),
    ],
))

register_preset(Preset(
    id="kinemacolor-1912",
    name="Kinemacolor",
    family="film",
    era="1912",
    desc="Two-colour wonder of the Empire: red and green exposed a heartbeat apart, so every moving edge trails scarlet one way and emerald the other while the frame breathes color.",
    tagline="Scarlet-and-emerald trails on every edge",
    tags=("1910s", "early-color", "additive", "silent"),
    proc_height=600,
    upscale="soft",
    video=[
        ("balance", {"warmth": 0.35}),
        ("stock", {"profile": "technicolor2", "strength": 1.0}),
        ("tone", {"contrast": 1.2, "lift": 0.05, "knee": 0.75}),
        ("optics", {"chromatic_aberration": 3.0, "soft_focus": 0.2}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("phosphor_decay", {"decay": 0.6, "mode": "p22"}),
        ("flicker", {"amount": 0.35, "character": "projector", "color_flicker": 1.0, "spatial": 0.2}),
        ("grain", {"amount": 0.5, "size": 1.97, "chroma_grain": 0.12, "stock": "print_dupe"}),
        ("halation", {"strength": 0.4, "tint": "orange", "threshold": 0.72}),
        ("gate_weave", {"amount": 2.2, "splice_bump": 1.2}),
        ("dust", {"density": 0.8, "hairs": 0.4}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.5, "softness": 0.55}),
        ("framing", {"aspect": "source"}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_bed", {"bed": "projector_35mm_booth", "level_db": -30.0}),
        ("a_hum", {"hz": 50, "level_db": -54.0}),
    ],
    variants=[
        _KEEP_SOUND,
        Variant("steady", "Rock-Steady Demo", "The trade-show reel: filters matched, fringing tamed.",
                video={"phosphor_decay.decay": 0.3, "optics.chromatic_aberration": 1.6,
                       "flicker.color_flicker": 0.5, "gate_weave.amount": 1.2}),
        Variant("fairground", "Fairground Show", "A tired touring print cranked with enthusiasm.",
                video={"flicker.amount": 0.5, "flicker.character": "hand_cranked",
                       "gate_weave.amount": 3.0, "dust.density": 1.0}),
    ],
))

register_preset(Preset(
    id="pathe-stencil-1923",
    name="Pathé Stencil Color",
    family="film",
    era="1923",
    desc="Stencil-coloured photoplay: flat dye washes cut by hand in Vincennes, drifting a few pixels off the faces they were meant for, over honest black-and-white bones.",
    tagline="Hand-cut dye washes off the drawing",
    tags=("20s", "silent", "stencil-color", "pathe"),
    proc_height=560,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic"}),
        ("tone", {"contrast": 1.02, "lift": 0.06, "gamma": 0.82, "knee": 0.85}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("riso_print", {"inks": "teal_orange", "misregister": 3.0, "grain_ink": 0.15, "paper": 0.15}),
        ("tone", {"contrast": 1.18, "lift": 0.02, "knee": 0.82}),
        ("saturation", {"amount": 0.62}),
        ("grain", {"amount": 0.5, "size": 2.19, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("flicker", {"amount": 0.4, "character": "hand_cranked", "color_flicker": 0.5, "spatial": 0.3}),
        ("gate_weave", {"amount": 2.4, "splice_bump": 1.5}),
        ("dust", {"density": 0.9, "size": 1.3, "hairs": 0.5}),
        ("scratches", {"count": 3, "transient_rate": 1.2}),
        ("frame_damage", {"splice_skip_rate": 1.5, "blotch_rate": 0.8}),
        ("vignette", {"amount": 0.5, "softness": 0.55}),
        ("framing", {"aspect": "source"}),
    ],
    audio=_silent_audio(level=-28.0, hum_hz=50),
    variants=[
        _KEEP_SOUND,
        Variant("poster-inks", "Poster Inks", "The other drawer of dyes: Prussian shadows, vermilion washes.",
                video={"riso_print.inks": "blue_red"}),
        Variant("careful-hands", "Careful Hands", "A good day at the stencil bench: registration nearly true.",
                video={"riso_print.misregister": 1.2, "riso_print.grain_ink": 0.1}),
    ],
))

register_preset(Preset(
    id="home-95mm-1928",
    name="Pathé Baby 9.5mm",
    family="film",
    era="1928",
    desc="The gauge with the hole in the middle: center-perf flashes when a splice lifts, framelines bouncing into view, a parlor projector doing its clattering best.",
    tagline="Center-perf flashes, bouncing frameline",
    tags=("20s", "9.5mm", "home-movie", "silent"),
    proc_height=500,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic"}),
        ("tone", {"contrast": 1.16, "lift": 0.06, "knee": 0.75}),
        ("cadence", {"pattern": "silent_irregular", "speed": "silent_16fps_in_24"}),
        ("optics", {"soft_focus": 0.3, "corner_softness": 0.5}),
        ("grain", {"amount": 0.55, "size": 1.95, "chroma_grain": 0.0, "stock": "super8",
                   "intermittent": 0.3}),
        ("print_char", {"frameline": 0.5, "perf_flash": 0.7}),
        ("flicker", {"amount": 0.45, "character": "projector", "spatial": 0.3}),
        ("gate_weave", {"amount": 3.0, "splice_bump": 2.5}),
        ("dust", {"density": 0.9, "hairs": 0.5}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.55, "softness": 0.55}),
        ("framing", {"aspect": "source", "corner_radius": 0.02}),
    ],
    audio=_silent_audio(machine="proj_8mm", level=-25.0, hum_hz=50, hum_db=-52.0),
    variants=[
        _KEEP_SOUND,
        Variant("attic-spool", "Attic Spool", "Ninety years in a biscuit tin: heavier wear, wilder gate.",
                video={"dust.density": 1.0, "scratches.count": 5, "gate_weave.amount": 4.0,
                       "print_char.perf_flash": 0.9}),
    ],
))

register_preset(Preset(
    id="two-reeler-chase-1926",
    name="Two-Reel Chase",
    family="film",
    era="1926",
    desc="Undercranked pursuit picture: shot slow to play fast, so the cops corner like billiard balls - splices every gag, motion half again quicker than life.",
    tagline="Undercranked scramble, splice every gag",
    tags=("20s", "silent", "comedy", "undercranked"),
    proc_height=600,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic"}),
        ("tone", {"contrast": 1.24, "lift": 0.05, "knee": 0.75}),
        ("cadence", {"pattern": "silent_irregular", "speed": "silent_16fps_in_24"}),
        ("grain", {"amount": 0.55, "size": 1.97, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("flicker", {"amount": 0.42, "character": "hand_cranked", "spatial": 0.35}),
        ("gate_weave", {"amount": 2.5, "splice_bump": 3.0}),
        ("dust", {"density": 1.0, "size": 1.3, "hairs": 0.6}),
        ("scratches", {"count": 4, "transient_rate": 2.0}),
        ("frame_damage", {"splice_skip_rate": 3.0, "slip_rate": 1.0}),
        ("vignette", {"amount": 0.45, "softness": 0.6}),
        ("framing", {"aspect": "source"}),
    ],
    audio=_silent_audio(level=-27.0),
    variants=[
        _KEEP_SOUND,
        Variant("gentle-crank", "Gentle Crank", "Projected at a merciful speed: native motion, same battered print.",
                video={"cadence.speed": "native"}),
    ],
))

register_preset(Preset(
    id="newsreel-sound-1930",
    name="First Sound Newsreel",
    family="film",
    era="1930",
    desc="The news learns to talk: a squarish frame beside the new soundtrack stripe, hot dupey grain, and an optical track that hisses like a kettle under every word.",
    tagline="Kettle-hiss optical track, hot grain",
    tags=("30s", "bw", "newsreel", "early-sound"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.2}),
        ("tone", {"contrast": 1.28, "lift": 0.05, "knee": 0.74}),
        ("grain", {"amount": 0.58, "size": 2.1, "chroma_grain": 0.0, "stock": "newsreel_35"}),
        ("halation", {"strength": 0.28, "tint": "neutral"}),
        ("flicker", {"amount": 0.28, "character": "projector"}),
        ("gate_weave", {"amount": 1.8, "splice_bump": 1.5}),
        ("dust", {"density": 0.85, "size": 1.2, "hairs": 0.5}),
        ("scratches", {"count": 4, "transient_rate": 1.5}),
        ("frame_damage", {"splice_skip_rate": 1.5, "blotch_rate": 0.8}),
        ("vignette", {"amount": 0.4}),
        ("framing", {"aspect": "source"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 200.0, "high_hz": 4500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -35.0, "academy_rolloff": "newsreel_1930s",
                             "drive": 2.6, "flutter": 0.8}),
        ("a_compressor", {"ratio": 6.0}),
        ("a_tube_amp", {"drive": 1.8, "sag": 0.4, "hum_db": -52.0}),
    ],
    variants=[
        Variant("later-run", "1934 Improvements", "Four years of better galvanometers: quieter track, calmer frame.",
                video={"grain.amount": 0.5, "flicker.amount": 0.18},
                audio={"a_optical_track.cell_noise": -44.0, "a_optical_track.drive": 1.8}),
    ],
))

register_preset(Preset(
    id="bw-home-16mm-1938",
    name="Prewar Home 16mm",
    family="film",
    era="1938",
    desc="Sixteen-frame Sundays on reversal stock: boiling silver grain, a lens gone gently soft at the corners, one light leak per lifetime of rewinds.",
    tagline="Mottled reversal grain, soft corners",
    tags=("30s", "16mm", "home-movie", "bw", "silent"),
    proc_height=600,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.1, "lift": 0.07, "knee": 0.78, "exposure": 0.2}),
        ("cadence", {"pattern": "silent_irregular", "speed": "silent_16fps_in_24"}),
        ("optics", {"corner_softness": 0.4, "soft_focus": 0.15}),
        ("grain", {"amount": 0.5, "size": 1.97, "chroma_grain": 0.0, "stock": "doc_16",
                   "layers": "reversal", "intermittent": 0.35, "mottle": 0.35}),
        ("flicker", {"amount": 0.3, "character": "projector"}),
        ("gate_weave", {"amount": 2.4, "splice_bump": 1.2}),
        ("dust", {"density": 0.85, "hairs": 0.5}),
        ("scratches", {"count": 1, "transient_rate": 0.8}),
        ("light_leak", {"constant": 0.06, "frequency": 0.3}),
        ("vignette", {"amount": 0.42, "softness": 0.6}),
        ("framing", {"aspect": "source"}),
    ],
    audio=_silent_audio(level=-27.0),
    variants=[
        _KEEP_SOUND,
        Variant("well-kept", "Well-Kept Reel", "Stored flat, wound smooth: minimal wear, steadier gate.",
                video={"dust.density": 0.4, "gate_weave.amount": 1.6, "flicker.amount": 0.25}),
    ],
))

register_preset(Preset(
    id="three-strip-worn-1946",
    name="Touring Technicolor Print",
    family="film",
    era="1946",
    desc="A dye-transfer print on its fortieth town: dupe contrast stacked on, blacks breathing with the lamp, emulsion scratches flashing green where the dye tore away.",
    tagline="Dupe contrast, green emulsion scratches",
    tags=("40s", "technicolor", "worn-print"),
    upscale="soft",
    video=[
        ("stock", {"profile": "technicolor3", "strength": 0.95}),
        ("tone", {"contrast": 1.16, "lift": 0.04, "knee": 0.78, "pivot": 0.45}),
        ("optics", {"soft_focus": 0.15, "chromatic_aberration": 1.2}),
        ("print_char", {"acutance": 0.45, "dmax_breath": 0.45, "contrast_buildup": 2, "frameline": 0.15}),
        ("grain", {"amount": 0.45, "size": 2.1, "chroma_grain": 0.15, "stock": "fine_35",
                   "layers": "print_from_neg"}),
        ("halation", {"strength": 0.45, "tint": "red", "threshold": 0.72}),
        ("flicker", {"amount": 0.22, "character": "projector"}),
        ("gate_weave", {"amount": 1.8, "splice_bump": 3.0}),
        ("dust", {"density": 0.9, "size": 1.3, "hairs": 0.6}),
        ("scratches", {"count": 5, "transient_rate": 1.8, "emulsion_side": 0.4}),
        ("frame_damage", {"splice_skip_rate": 2.0, "slip_rate": 0.8, "blotch_rate": 0.8}),
        ("vignette", {"amount": 0.35}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -44.0, "academy_rolloff": "feature_1940s", "drive": 2.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tube_amp", {"drive": 1.7, "sag": 0.4, "hum_db": -55.0}),
    ],
    variants=[
        Variant("roadshow", "Roadshow Fresh", "Early bookings: the dyes still singing, wear barely started.",
                video={"dust.density": 0.4, "scratches.count": 2, "print_char.contrast_buildup": 1,
                       "gate_weave.splice_bump": 1.0}),
        Variant("final-booking", "Final Booking", "Last stop before the vault: every reel a fight.",
                video={"dust.density": 1.0, "scratches.count": 7, "frame_damage.splice_skip_rate": 4.0,
                       "print_char.dmax_breath": 0.6}),
    ],
))

register_preset(Preset(
    id="safety-print-1952",
    name="Fresh Safety Print",
    family="film",
    era="1952",
    desc="First-generation acetate off a good negative: fine quiet grain, velvet mids, a frame that finally sits still. The lab's proud Tuesday.",
    tagline="Fine quiet grain, a frame that sits still",
    tags=("50s", "bw", "safety", "clean"),
    upscale="sharp",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.16, "lift": 0.02, "knee": 0.82}),
        ("grain", {"amount": 0.32, "size": 1.7, "chroma_grain": 0.0, "stock": "fine_35",
                   "mottle": 0.25}),
        ("halation", {"strength": 0.32, "tint": "neutral", "threshold": 0.76}),
        ("print_char", {"acutance": 0.3, "dmax_breath": 0.2}),
        ("gate_weave", {"amount": 0.8}),
        ("flicker", {"amount": 0.08}),
        ("dust", {"density": 0.2}),
        ("scratches", {"count": 0, "transient_rate": 0.3}),
        ("vignette", {"amount": 0.28, "softness": 0.7}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 7500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -56.0, "academy_rolloff": "feature_1940s"}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_room", {"size": 1.0, "decay_s": 0.6, "mix": 0.1, "mode": "chamber"}),
    ],
    variants=[
        Variant("decade-later", "A Decade of Bookings", "The same print after the circuit: honest wear, nothing tragic.",
                video={"dust.density": 0.6, "scratches.count": 3, "gate_weave.amount": 1.4,
                       "flicker.amount": 0.16}),
    ],
))

register_preset(Preset(
    id="ektachrome-news-1972",
    name="Ektachrome Film News",
    family="film",
    era="1972",
    desc="The reversal reel the station never returned: chrome-blue shadows going pink at the edges, honest 16mm grain, the whole decade slightly overexposed.",
    tagline="Chrome-blue shadows going pink",
    tags=("70s", "16mm", "news", "reversal"),
    proc_height=620,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.9}),
        ("tone", {"contrast": 1.1, "lift": 0.04}),
        ("balance", {"warmth": 0.1, "shadow_tint": "brown", "shadow_amt": 0.2}),
        ("grain", {"amount": 0.48, "size": 2.03, "chroma_grain": 0.2, "stock": "doc_16",
                   "layers": "reversal", "shadow_boost": 0.25}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("fade", {"amount": 0.28, "profile": "eastman_pink", "bloom_whites": 0.3}),
        ("gate_weave", {"amount": 1.6}),
        ("flicker", {"amount": 0.15}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 110.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -46.0, "academy_rolloff": "classroom_16mm"}),
        ("a_agc", {"amount": 0.6}),
        ("a_compressor", {"ratio": 4.0}),
    ],
    variants=[
        Variant("fresh-soup", "Fresh From The Soup", "Processed this afternoon, aired at six: no fade yet.",
                video={"fade.amount": 0.08, "dust.density": 0.4}),
        Variant("station-vault", "Station Vault", "Filed under 'misc fires 72–74': deep pink, deep scratches.",
                video={"fade.amount": 0.55, "scratches.count": 5, "dust.density": 1.0}),
    ],
))

register_preset(Preset(
    id="fuji-8mm-1983",
    name="Fuji Single-8",
    family="film",
    era="1983",
    desc="The other cartridge: Fujichrome greens cool as pond water, tighter grain than the Kodak crowd, a small-gauge summer that never quite goes orange.",
    tagline="Pond-green cast, tight small-gauge grain",
    tags=("80s", "8mm", "home-movie", "fuji"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.45}),
        ("tone", {"contrast": 1.12, "lift": 0.03, "knee": 0.8}),
        ("balance", {"warmth": -0.08, "tint": -0.15, "shadow_tint": "teal", "shadow_amt": 0.15}),
        ("saturation", {"amount": 1.05, "vibrance": 0.1}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.3}),
        ("grain", {"amount": 0.42, "size": 2.11, "chroma_grain": 0.18, "stock": "super8",
                   "layers": "reversal"}),
        ("halation", {"strength": 0.25, "tint": "orange"}),
        ("gate_weave", {"amount": 2.0, "splice_bump": 1.0}),
        ("flicker", {"amount": 0.25, "character": "projector"}),
        ("dust", {"density": 0.6, "hairs": 0.35}),
        ("light_leak", {"constant": 0.05, "frequency": 0.3}),
        ("vignette", {"amount": 0.4}),
    ],
    audio=_silent_audio(machine="proj_8mm", level=-28.0),
    variants=[
        _KEEP_SOUND,
        Variant("sound-stripe", "Sound Stripe", "The magnetic-striped cartridge: thin warm mono rides along.",
                audio={"a_gain.db": -4.0, "a_projector.level_db": -34.0}),
    ],
))

register_preset(Preset(
    id="adventure-answer-print-1985",
    name="Adventure Answer Print",
    family="film",
    era="1985",
    desc="Warm Kodak 35mm under practical lamps: blue-gray shadow detail, damp green exteriors, flare in the haze and a well-traveled answer print with warm, slightly compressed theatrical sound.",
    tagline="Warm lamps, blue shadow, answer-print wear",
    tags=("80s", "adventure", "35mm", "kodak", "theatrical", "analog"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "kodak_80s", "strength": 0.9}),
        ("tone", {"contrast": 1.15, "lift": 0.025, "knee": 0.82, "pivot": 0.43}),
        ("balance", {"warmth": 0.12, "shadow_tint": "blue", "shadow_amt": 0.26,
                     "high_tint": "yellow", "high_amt": 0.14}),
        ("saturation", {"amount": 0.98, "vibrance": 0.15}),
        ("optics", {"soft_focus": 0.1, "diffusion": 0.1, "focus_drift": 0.1,
                    "veiling_flare": 0.24, "aperture_ghost": 0.14}),
        ("optical_composite", {"softness": 0.1, "matte_line": 0.05, "registration": 0.05,
                               "layer_haze": 0.05, "density_breath": 0.15}),
        ("grain", {"amount": 0.38, "size": 1.85, "chroma_grain": 0.18, "stock": "fine_35",
                   "layers": "color_neg", "mottle": 0.12}),
        ("halation", {"strength": 0.3, "tint": "red_orange", "threshold": 0.72}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.2, "acutance": 0.24}),
        ("fade", {"amount": 0.08, "profile": "eastman_pink", "bloom_whites": 0.1}),
        ("gate_weave", {"amount": 0.65, "splice_bump": 0.5}),
        ("flicker", {"amount": 0.07, "spatial": 0.1}),
        ("dust", {"density": 0.3, "hairs": 0.16}),
        ("scratches", {"count": 1, "transient_rate": 0.4}),
        ("vignette", {"amount": 0.3, "softness": 0.7}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 12500.0}),
        ("a_tape_sat", {"drive": 1.4, "bump_db": 1.2, "hf_loss": 0.15}),
        ("a_optical_track", {"low_hz": 60.0, "high_hz": 9000.0, "academy_rolloff": "none",
                             "cell_noise": -58.0, "flutter": 0.22, "drive": 1.2}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 2.8, "attack_ms": 10.0,
                          "release_ms": 260.0}),
        ("a_room", {"size": 1.15, "decay_s": 0.72, "mix": 0.12, "mode": "chamber"}),
    ],
    variants=[
        Variant("rainy-cavern", "Rainy Cavern", "Cooler and a stop down: wet flare, longer stone reflections and a more cavernous theatrical track.",
                video={"tone.exposure": -0.2, "balance.warmth": 0.02,
                       "balance.shadow_amt": 0.42, "saturation.amount": 0.88,
                       "optics.veiling_flare": 0.34, "vignette.amount": 0.4},
                audio={"a_room.decay_s": 1.4, "a_room.mix": 0.22}),
        Variant("saturday-matinee", "Saturday Matinee", "The crowd-pleasing reel: brighter amber, firmer track compression and a few more miles of print wear.",
                video={"tone.exposure": 0.12, "balance.warmth": 0.2, "fade.amount": 0.2,
                       "dust.density": 0.6, "scratches.count": 3, "gate_weave.amount": 1.1},
                audio={"a_compressor.ratio": 3.5}),
        Variant("vault-answer-print", "Vault Answer Print", "Before the roadshow: cleaner dyes, a steadier gate and quieter optical-track noise.",
                video={"fade.amount": 0.0, "dust.density": 0.12, "scratches.count": 0,
                       "gate_weave.amount": 0.35, "grain.amount": 0.32,
                       "optical_composite.softness": 0.06},
                audio={"a_optical_track.cell_noise": -64.0}),
    ],
))

register_preset(Preset(
    id="music-16mm-1991",
    name="Grunge Promo 16mm",
    family="film",
    era="1991",
    desc="Label money, film-school hands: pushed 16 printed hot, blacks crawling with grain, splice bumps kept in because the drummer liked them.",
    tagline="Pushed grain in the blacks, splice bumps",
    tags=("90s", "16mm", "music-video", "grunge"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "vision_90s", "strength": 0.7}),
        ("tone", {"contrast": 1.32, "lift": 0.02, "knee": 0.72, "pivot": 0.4}),
        ("saturation", {"amount": 0.92}),
        ("grain", {"amount": 0.58, "size": 2.1, "chroma_grain": 0.22, "stock": "push_process",
                   "layers": "print_from_neg", "shadow_boost": 0.5, "intermittent": 0.25}),
        ("halation", {"strength": 0.35, "tint": "red_orange"}),
        ("print_char", {"contrast_buildup": 1, "acutance": 0.5, "dmax_breath": 0.3}),
        ("gate_weave", {"amount": 2.0, "splice_bump": 4.0}),
        ("flicker", {"amount": 0.18, "character": "projector"}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("scratches", {"count": 3, "transient_rate": 2.0}),
        ("light_leak", {"amount": 0.4, "constant": 0.04, "frequency": 1.0}),
        ("vignette", {"amount": 0.38}),
        ("framing", {"aspect": "source"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 13000.0}),
        ("a_tape_sat", {"drive": 2.2, "bump_db": 3.0}),
        ("a_compressor", {"ratio": 3.5}),
        ("a_tape_hiss", {"level_db": -48.0, "type": "reel_15ips"}),
    ],
    variants=[
        Variant("answer-print", "Answer Print", "Before the dupes: cleaner, steadier, still moody.",
                video={"grain.amount": 0.45, "gate_weave.splice_bump": 1.0, "dust.density": 0.3,
                       "print_char.contrast_buildup": 0}),
    ],
))

register_preset(Preset(
    id="bolex-diary-1968",
    name="Bolex Diary",
    family="film",
    era="1968",
    desc="A wound-by-hand life: black-and-white reversal boiling with grain, the spring running down mid-thought, light leaking in every time the door opened.",
    tagline="Grain boil, spring wind-down, light leaks",
    tags=("60s", "16mm", "diary", "avant-garde", "bw", "silent"),
    proc_height=620,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.2, "lift": 0.05, "knee": 0.76}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.35, "focus_drift": 0.3}),
        ("grain", {"amount": 0.55, "size": 2.03, "chroma_grain": 0.0, "stock": "doc_16",
                   "layers": "reversal", "intermittent": 0.6, "mottle": 0.45}),
        ("flicker", {"amount": 0.4, "character": "hand_cranked", "spatial": 0.35}),
        ("gate_weave", {"amount": 2.4, "splice_bump": 3.0}),
        ("light_leak", {"constant": 0.1, "frequency": 1.2, "sprocket_side": 0.5}),
        ("dust", {"density": 0.8, "hairs": 0.5}),
        ("scratches", {"count": 2, "transient_rate": 1.5}),
        ("vignette", {"amount": 0.5, "softness": 0.55}),
    ],
    audio=_silent_audio(level=-27.0),
    variants=[
        _KEEP_SOUND,
        Variant("pixilated", "Single-Frame Days", "Shot a frame at a time: the world stutters in threes.",
                video={"cadence.pattern": "threes", "flicker.amount": 0.3}),
    ],
))

register_preset(Preset(
    id="press-reel-pool-1963",
    name="Press Pool 16mm",
    family="film",
    era="1963",
    desc="The pool camera's negative, printed before dawn: hard silver contrast, sprocket-bruised edges, history moving too fast for the focus puller.",
    tagline="Hard silver contrast, missed focus",
    tags=("60s", "16mm", "news", "bw"),
    proc_height=620,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.25}),
        ("tone", {"contrast": 1.3, "lift": 0.03, "knee": 0.72, "pivot": 0.4}),
        ("grain", {"amount": 0.55, "size": 2.03, "chroma_grain": 0.0, "stock": "doc_16",
                   "shadow_boost": 0.3}),
        ("halation", {"strength": 0.25, "tint": "neutral"}),
        ("gate_weave", {"amount": 1.6, "splice_bump": 2.0}),
        ("flicker", {"amount": 0.2}),
        ("dust", {"density": 0.8, "size": 1.2, "hairs": 0.5}),
        ("scratches", {"count": 3, "transient_rate": 2.0}),
        ("frame_damage", {"splice_skip_rate": 2.0, "slip_rate": 0.5}),
        ("vignette", {"amount": 0.35}),
        ("framing", {"aspect": "source"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 150.0, "high_hz": 5500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": -40.0, "academy_rolloff": "classroom_16mm", "drive": 2.2}),
        ("a_agc", {"amount": 0.7}),
        ("a_compressor", {"ratio": 5.0}),
    ],
    variants=[
        Variant("network-dupe", "Network Dupe", "The copy of the copy that actually aired: grain on grain.",
                video={"grain.amount": 0.65, "tone.contrast": 1.38, "dust.density": 1.0}),
    ],
))

register_preset(Preset(
    id="stag-loop-1959",
    name="Arcade Loop Machine",
    family="film",
    era="1959",
    desc="A coin-op loop viewer's only reel, spliced back together a hundred times: hooded vignette, quarters' worth of scratches, film worn to lace and still going around.",
    tagline="Hooded vignette, lacework scratches",
    tags=("50s", "loop", "arcade", "damaged", "bw"),
    proc_height=520,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.3, "lift": 0.08, "knee": 0.7}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("grain", {"amount": 0.62, "size": 2.03, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("flicker", {"amount": 0.5, "character": "projector", "spatial": 0.4}),
        ("gate_weave", {"amount": 3.4, "splice_bump": 5.0}),
        ("scratches", {"count": 7, "transient_rate": 3.0, "wander": 1.0, "gouge_rate": 1.0}),
        ("dust", {"density": 1.0, "size": 1.5, "hairs": 0.8}),
        ("frame_damage", {"splice_skip_rate": 5.0, "slip_rate": 2.0, "blotch_rate": 1.5}),
        ("plate", {"pack": "grime", "opacity": 0.3, "blend": "screen", "cycle": "hold"}),
        ("vignette", {"amount": 0.65, "softness": 0.5, "roundness": 0.85}),
        ("framing", {"aspect": "source", "corner_radius": 0.03}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_8mm", "level_db": -22.0, "distance": 0.1}),
        ("a_hum", {"hz": 60, "level_db": -44.0, "buzz": 0.4}),
    ],
    variants=[
        _KEEP_SOUND,
        Variant("fresh-reel", "Fresh Reel", "The week the machine was new: merely worn, not martyred.",
                video={"scratches.count": 3, "frame_damage.splice_skip_rate": 2.0,
                       "gate_weave.amount": 2.2, "dust.density": 0.7}),
    ],
))

register_preset(Preset(
    id="super16-indie-1994",
    name="Super 16 Blowup",
    family="film",
    era="1994",
    desc="Credit-card cinema at altitude: Super 16 blown to 35, grain enlarged along with the ambitions, one lab-grade print and a festival to win.",
    tagline="Blown-up grain, clean lab print",
    tags=("90s", "super16", "indie", "sundance"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "vision_90s", "strength": 0.85}),
        ("tone", {"contrast": 1.14, "lift": 0.03, "knee": 0.8}),
        ("saturation", {"amount": 0.96}),
        ("grain", {"amount": 0.5, "size": 2.1, "chroma_grain": 0.22, "stock": "doc_16",
                   "layers": "color_neg", "shadow_boost": 0.2, "mottle": 0.3}),
        ("halation", {"strength": 0.3, "tint": "red_orange"}),
        ("print_char", {"contrast_buildup": 1, "acutance": 0.35, "dmax_breath": 0.25}),
        ("gate_weave", {"amount": 1.1}),
        ("flicker", {"amount": 0.1}),
        ("dust", {"density": 0.35, "hairs": 0.25}),
        ("scratches", {"count": 1, "transient_rate": 0.5}),
        ("vignette", {"amount": 0.3}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 13500.0}),
        ("a_optical_track", {"cell_noise": -58.0, "academy_rolloff": "none", "flutter": 0.3}),
        ("a_compressor", {"ratio": 2.5}),
        ("a_room", {"size": 1.2, "decay_s": 0.7, "mix": 0.1, "mode": "chamber"}),
    ],
    variants=[
        Variant("festival-print", "Festival Print", "After the tour: the print has seen some projectors.",
                video={"dust.density": 0.7, "scratches.count": 3, "gate_weave.amount": 1.6}),
    ],
))
