"""Stylized-family presets: archival grammar deployed as art direction, physically grounded."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="analog-horror-1996",
    name="Analog Horror",
    family="stylized",
    era="1996",
    desc="Nothing is wrong with your television set: EP-speed fog with crushed blacks, a timestamp from the wrong hour of the night, bars that roll through once and decline to explain themselves.",
    tagline="Crushed EP blacks, 3 AM clock, jam bars",
    tags=("horror", "vhs", "ep", "unsettling"),
    proc_height=480,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.1, "lift": 0.02, "knee": 0.78, "gamma": 1.05}),
        ("saturation", {"amount": 0.82}),
        ("ntsc", {"strength": 0.9, "phase_noise": 2.2, "rainbow": 0.25, "dot_crawl": 0.25}),
        ("vhs", {"mode": "ep", "luma_noise": 0.16, "chroma_noise": 0.15, "head_switch": 0.6,
                 "time_base_error": 0.4, "flagging": 0.25, "dropouts": 0.6, "sharpen": 0.5,
                 "black_crush": 0.05, "white_clip": 0.95, "skew_tear": 0.15}),
        ("vcr_transport", {"random_glitch_rate": 0.8}),
        ("jam_bars", {"amount": 0.1, "bar_size": 0.5, "roll_speed": 0.12, "tear": 0.15}),
        ("timestamp", {"style": "vcr_white", "corner": "tl", "date_format": "dow_dmy_hms",
                       "start": "1996-03-08 03:33:07", "flicker": 0.45, "glow": 0.3}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.28, "scan_strength": 0.1, "retrace_lines": 0.12}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 7500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 7.0, "flutter_depth": 5.0, "drift_long": 0.4}),
        ("a_tape_hiss", {"level_db": -44.0}),
        ("a_bed", {"bed": "crt_whine", "level_db": -38.0, "duck": 0.2}),
        ("a_bed", {"bed": "air_handler_hall", "level_db": -40.0, "duck": 0.2}),
        ("a_hum", {"hz": 60, "level_db": -48.0, "buzz": 0.3}),
    ],
    variants=[
        Variant("the-tape", "The Tape", "The one the county archive refuses to discuss.",
                video={"vcr_transport.random_glitch_rate": 2.5, "jam_bars.amount": 0.3,
                       "vhs.tracking_error": 0.25, "vhs.skew_tear": 0.4,
                       "timestamp.flicker": 0.7},
                audio={"a_wow_flutter.wow_depth": 12.0, "a_bed.level_db": -32.0}),
        Variant("broadcast-intrusion", "Broadcast Intrusion", "Something else is on the channel with you.",
                video={"jam_bars.amount": 0.45, "jam_bars.tear": 0.5, "jam_bars.roll_speed": 0.3,
                       "ntsc.phase_noise": 3.5},
                audio={"a_hum.level_db": -38.0, "a_hum.buzz": 0.6}),
        Variant("daylight", "Daylight Segment", "The cheerful instructional part. Somehow worse.",
                video={"saturation.amount": 1.05, "tone.lift": 0.04, "jam_bars.amount": 0.04,
                       "vcr_transport.random_glitch_rate": 0.2}),
    ],
))

register_preset(Preset(
    id="liminal-cctv-2002",
    name="Liminal CCTV",
    family="stylized",
    era="2002",
    desc="Camera 7, food court, 3:12 AM: drained color under fluorescent green, three-frame holds, the DVR's MJPEG chewing the floor tiles - escalators running for nobody.",
    tagline="Fluorescent green, 3-frame holds, MJPEG",
    tags=("cctv", "liminal", "00s", "empty"),
    proc_height=520,
    upscale="soft",
    video=[
        ("saturation", {"amount": 0.6}),
        ("balance", {"warmth": -0.1, "tint": -0.18, "shadow_tint": "green", "shadow_amt": 0.2}),
        ("tone", {"contrast": 0.97, "lift": 0.06, "knee": 0.82}),
        ("optics", {"corner_softness": 0.3, "distortion": 0.12}),
        ("cadence", {"pattern": "threes"}),
        ("auto_color", {"wb_pump": 0.25, "level_pump": 0.3, "lag_s": 2.2}),
        ("phosphor_decay", {"decay": 0.3, "mode": "p22"}),
        ("codec_era", {"codec": "mjpeg", "qscale": 12, "res": "360p", "gop": 1}),
        ("timestamp", {"style": "security_green", "corner": "tl", "date_format": "dow_dmy_hms",
                       "start": "2002-10-14 03:12:45", "flicker": 0.2}),
        ("crt", {"scan_strength": 0.14, "bloom": 0.2}),
    ],
    audio=[
        ("a_gain", {"db": -34.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bed", {"bed": "fluorescent_office", "level_db": -28.0, "duck": 0.2}),
        ("a_bed", {"bed": "air_handler_hall", "level_db": -34.0, "duck": 0.2}),
        ("a_hum", {"hz": 60, "buzz": 0.35, "level_db": -44.0}),
    ],
    variants=[
        Variant("dead-hour", "Dead Hour", "No audio feed at all. Just the building breathing.",
                audio={"a_gain.db": -60.0, "a_bed.level_db": -26.0}),
        Variant("parking-level", "Parking Level B", "Concrete, one flickering tube, longer holds.",
                video={"saturation.amount": 0.45, "tone.lift": 0.03,
                       "auto_color.level_pump": 0.45, "codec_era.qscale": 15},
                audio={"a_bed#2.level_db": -28.0, "a_hum.level_db": -40.0}),
    ],
))

register_preset(Preset(
    id="mall-tv-wall-1989",
    name="TV Wall",
    family="stylized",
    era="1989",
    desc="Forty screens, one signal: aperture-grille stripes and beam bloom up close, showroom chroma cranked to move product, the whole electronics department humming in unison.",
    tagline="Grille stripes, beam bloom, hot chroma",
    tags=("80s", "retail", "crt", "mall"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.7}),
        ("tone", {"contrast": 1.12, "lift": 0.015, "knee": 0.8}),
        ("saturation", {"amount": 1.25, "vibrance": 0.15}),
        ("ntsc", {"strength": 0.85, "phase_noise": 1.8, "rainbow": 0.28, "dot_crawl": 0.35}),
        ("interlace", {"combing": 0.5, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.18, "phosphor_mask": "grille", "mask_scale": 2.5,
                 "mask_strength": 0.27, "beam_bloom": 0.4, "bloom": 0.4, "curvature": 0.12,
                 "misconvergence": 0.8, "mask_misalign": 0.3, "vignette_crt": 0.2}),
        ("plate", {"pack": "glass_glare", "opacity": 0.16, "blend": "screen", "cycle": "hold",
                   "drift": 2.0}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -46.0}),
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.55}),
        ("a_bed", {"bed": "tv_shop_wall", "level_db": -27.0, "duck": 0.35}),
        ("a_bed", {"bed": "fluorescent_office", "level_db": -38.0, "duck": 0.2}),
    ],
    variants=[
        Variant("flagship-set", "The Flagship Set", "The 27-inch Trinitron they aim at the aisle.",
                video={"crt.mask_strength": 0.18, "crt.misconvergence": 0.3,
                       "saturation.amount": 1.15, "crt.beam_bloom": 0.3}),
        Variant("closing-time", "Closing Time", "Half the wall switched off, the hum louder than the show.",
                video={"tone.exposure": -0.2, "saturation.amount": 1.1},
                audio={"a_bed.level_db": -32.0, "a_bed#2.level_db": -30.0,
                       "a_speaker.strength": 0.7}),
    ],
))

register_preset(Preset(
    id="vaporwave-vhs-1986",
    name="Vaporwave, Physically",
    family="stylized",
    era="1986",
    desc="The aesthetic with its receipts: a pristine tape of a composite source - teal shadows, pink highlights, phosphor trails dragging every move - over an FM broadcast dubbed to cassette.",
    tagline="Teal shadows, pink highlights, trails",
    tags=("vaporwave", "80s", "vhs", "dreamy"),
    proc_height=560,
    upscale="soft",
    video=[
        ("balance", {"warmth": 0.05, "tint": 0.18, "shadow_tint": "teal", "shadow_amt": 0.4,
                     "high_tint": "pink", "high_amt": 0.35}),
        ("tone", {"contrast": 1.04, "lift": 0.03, "knee": 0.82}),
        ("saturation", {"amount": 1.15, "vibrance": 0.1}),
        ("optics", {"diffusion": 0.3}),
        ("phosphor_decay", {"decay": 0.4, "mode": "p22"}),
        ("ntsc", {"strength": 0.95, "phase_noise": 1.2, "rainbow": 0.35, "dot_crawl": 0.4,
                  "fringing": 1.5}),
        ("vhs", {"mode": "sp", "luma_noise": 0.22, "chroma_noise": 0.25, "head_switch": 0.4,
                 "time_base_error": 0.25, "flagging": 0.15, "dropouts": 0.25, "sharpen": 0.35}),
        ("interlace", {"combing": 0.45}),
        ("crt", {"bloom": 0.45, "glass_glow": 0.2, "scan_strength": 0.1, "curvature": 0.08}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 13000.0}),
        ("a_fm_radio", {"hiss_db": -50.0, "comp": 0.6, "multipath": 0.5}),
        ("a_tape_sat", {"drive": 2.2, "hf_loss": 0.5, "bump_db": 3.0}),
        ("a_wow_flutter", {"wow_depth": 9.0, "flutter_depth": 4.0, "drift_long": 0.5}),
        ("a_tape_hiss", {"level_db": -42.0}),
    ],
    variants=[
        Variant("midnight-mall", "Midnight Mall", "Deeper trails, slower breathing, emptier.",
                video={"phosphor_decay.decay": 0.55, "optics.diffusion": 0.4,
                       "tone.exposure": -0.15, "crt.glass_glow": 0.3},
                audio={"a_wow_flutter.wow_depth": 14.0, "a_wow_flutter.drift_long": 0.8}),
        Variant("signal-clean", "Direct Line", "The dub before the radio: teal and pink, no flutter.",
                video={"vhs.luma_noise": 0.15, "vhs.dropouts": 0.1},
                audio={"a_fm_radio.multipath": 0.0, "a_fm_radio.hiss_db": -58.0,
                       "a_wow_flutter.wow_depth": 4.0}),
    ],
))

register_preset(Preset(
    id="webcore-2007",
    name="Webcore",
    family="stylized",
    era="2007",
    desc="Early-YouTube amber: FLV blocks twice re-uploaded, the subpixel stripes of a hand-me-down monitor, 32 kbps mono like a memory of sound. Embed this.",
    tagline="Amber FLV blocks on subpixel stripes",
    tags=("00s", "web", "nostalgia", "lofi"),
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.02}),
        ("saturation", {"amount": 1.06}),
        ("codec_era", {"codec": "flv1", "kbps": 220, "res": "240p", "gop": 90, "passes": 2}),
        ("upload_gen", {"gens": 2, "deband_loss": 0.3, "qscale": 7}),
        ("lcd_screen", {"grid": 0.22, "scale": 3, "subpixel": "rgb_stripe_lcd",
                        "response_smear": 0.25, "backlight_bleed": 0.15, "viewing_angle": 0.1}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_codec_mp3", {"kbps": 32, "mono": True}),
        ("a_digital_glitch", {"stutter_rate": 0.8, "mute_rate": 0.3, "crackle_rate": 0.5}),
        ("a_speaker", {"device": "laptop_2006", "strength": 0.5}),
    ],
    variants=[
        Variant("deep-fried", "Deep Reupload", "Fourth generation. The blocks have blocks.",
                video={"upload_gen.gens": 4, "upload_gen.deband_loss": 0.55,
                       "codec_era.kbps": 170},
                audio={"a_codec_mp3.kbps": 16}),
        Variant("no-monitor", "Raw File", "The .flv itself, before the screen.",
                video={"lcd_screen.grid": 0.0, "lcd_screen.subpixel": "none",
                       "lcd_screen.response_smear": 0.0, "lcd_screen.backlight_bleed": 0.0,
                       "lcd_screen.viewing_angle": 0.0}),
    ],
))

register_preset(Preset(
    id="retro-grain-1968",
    name="Retro Grain",
    family="stylized",
    era="1968",
    desc="The look a colour outside-broadcast camera left on tape before anyone went near a correction desk: warmed highlights, a lens that never quite resolves, corners falling away into the dark, and grain sitting evenly over all of it.",
    tagline="Warm grade, soft lens, dark corners, grain",
    tags=("retro", "grain", "warm", "broadcast", "simple"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.1, "exposure": 0.03}),
        ("saturation", {"amount": 1.2}),
        ("balance", {"warmth": 0.1}),
        ("optics", {"soft_focus": 0.14, "bloom_mids": 0.0}),
        # Fine and even rather than clumpy: this look wants grain laid flat over
        # the whole frame, so the smallest clump on the finest stock. A coarser
        # setting reads as boiling emulsion and buries skin.
        ("grain", {"amount": 0.3, "size": 0.8, "roughness": 1.0, "chroma_grain": 0.12,
                   "stock": "fine_35", "layers": "color_neg"}),
        ("vignette", {"amount": 0.55, "radius": 0.68, "softness": 0.55}),
    ],
    # Nothing here touches the sound: a look you reach for mid-edit should not
    # rewrite the mix.
    audio=[],
    variants=[
        Variant("light", "Light", "Gentle enough that you have to look twice to catch it.",
                video={"tone.contrast": 1.05, "saturation.amount": 1.1, "balance.warmth": 0.05,
                       "optics.soft_focus": 0.07, "grain.amount": 0.17,
                       "vignette.amount": 0.42, "vignette.radius": 0.76}),
        Variant("heavy", "Heavy", "Pushed until the corners close in and the grain has opinions.",
                video={"tone.contrast": 1.18, "saturation.amount": 1.3, "balance.warmth": 0.18,
                       "optics.soft_focus": 0.24, "grain.amount": 0.47,
                       "vignette.amount": 0.7, "vignette.radius": 0.6}),
    ],
))
