"""Videotape presets, third wave: open-reel decks, broadcast masters and dub culture.

The `vhs` family is the library's videotape shelf, so half-inch open reel, one-inch
Type C, D-2, Digital Betacam and DVCPRO all live here alongside the consumer decks.
"""

from ..engine.presets import Preset, Variant, register_preset


# nearest: closed-circuit-1970 (vidicon gray, flyback whine, institutional CCTV);
# differs: portable half-inch reel with skew/flagging/TBE chaos, camera-mic hum, art-video context.
register_preset(Preset(
    id="portapak-open-reel-1970",
    name="Portapak Open-Reel Video",
    family="vhs",
    era="1970",
    desc="A shoulder-slung half-inch Portapak reel played back off the deck it was shot on: silver-gray vidicon response, comet trails dragging off every highlight, skew tearing the top of frame at each head switch, and the camera microphone carrying the deck's own hum.",
    tagline="Half-inch skew, vidicon gray, camera hum",
    tags=("70s", "portapak", "videotape", "bw"),
    keywords=("open-reel", "seventies", "video-art", "vidicon", "half-inch",
              "guerrilla-tv", "skew", "sony"),
    proc_height=270,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.05}),
        ("tone", {"contrast": 1.1, "lift": 0.08, "knee": 0.7}),
        ("exposure_auto", {"target": 0.43, "lag": 1.5, "overshoot": 0.12,
                           "max_boost": 2.0, "agc_gain_noise": 0.14, "wb_amount": 0.0}),
        ("optics", {"soft_focus": 0.25, "veiling_flare": 0.1}),
        ("phosphor_decay", {"decay": 0.4, "mode": "p22"}),
        ("vhs", {"mode": "sp", "luma_bw": 2.0, "chroma_bw": 0.3, "sharpen": 0.1,
                 "luma_noise": 0.45, "chroma_noise": 0.0, "head_switch": 0.9,
                 "dropouts": 6.0, "dropout_burst": 0.4, "time_base_error": 0.7,
                 "flagging": 0.6, "jitter_v": 0.3, "skew_tear": 0.3,
                 "tracking_error": 0.06, "generation": 1}),
        ("interlace", {"field_order": "tff", "combing": 0.6, "twitter": 0.4}),
        ("crt", {"scan_strength": 0.12, "bloom": 0.45, "curvature": 0.04,
                 "vignette_crt": 0.12}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.6,
                              "handling": 0.3, "overload": 0.2, "self_noise_db": -56.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_video_tape_audio", {"format": "umatic_linear", "tracking": 0.3,
                                "dropout_rate": 10.0, "noise_db": -44.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.9}),
        ("a_hum", {"hz": "60", "level_db": -48.0, "buzz": 0.35}),
    ],
    variants=[
        Variant("tbc-restored-scan", "TBC-Restored Scan",
                "The same reel through a modern time base corrector, so the frame finally stands still.",
                video={"vhs.time_base_error": 0.1, "vhs.flagging": 0.1,
                       "vhs.skew_tear": 0.0, "vhs.jitter_v": 0.05},
                audio={"a_video_tape_audio.dropout_rate": 3.0}),
        Variant("third-generation-dub", "Third-Generation Dub",
                "A study copy of a copy, handed around the artists' collective until the oxide gave out.",
                video={"vhs.generation": 3, "vhs.luma_noise": 0.6, "vhs.dropouts": 15.0},
                audio={"a_video_tape_audio.noise_db": -39.0}),
    ],
))


# nearest: telethon-1976 (broadcast color video), portapak-open-reel-1970 (bw half-inch);
# differs: color-under half-inch with rainbow skew, community-access chaos rather than a station.
register_preset(Preset(
    id="eiaj-color-reel-1974",
    name="EIAJ Color Open-Reel",
    family="vhs",
    era="1974",
    desc="Half-inch EIAJ color reel off a community-video deck: chroma written under the luma and smeared three pixels wide, rainbow crawling every edge, skew bending the top of frame, and buzzy line sound out of the monitor.",
    tagline="Color-under smear, rainbow skew, buzz",
    tags=("70s", "eiaj", "videotape", "public-access"),
    keywords=("open-reel", "seventies", "color-video", "half-inch", "community-video",
              "skew", "rainbow", "cable-access", "guerrilla"),
    proc_height=300,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.6}),
        ("tone", {"exposure": 0.08, "contrast": 1.06, "lift": 0.06, "knee": 0.76}),
        ("saturation", {"amount": 1.04, "vibrance": 0.04}),
        ("exposure_auto", {"target": 0.43, "lag": 1.2, "overshoot": 0.2,
                           "max_boost": 2.2, "agc_gain_noise": 0.2, "wb_amount": 0.3}),
        ("ntsc", {"strength": 0.6, "luma_bw": 2.8, "chroma_bw": 0.5, "phase_noise": 2.6,
                  "rainbow": 0.3, "dot_crawl": 0.28, "chroma_agc": 0.18, "setup_level": 0.05}),
        ("vhs", {"mode": "sp", "luma_bw": 2.0, "chroma_bw": 0.25, "chroma_delay": 2.2,
                 "sharpen": 0.1, "luma_noise": 0.38, "chroma_noise": 0.32,
                 "head_switch": 0.8, "dropouts": 5.0, "time_base_error": 0.6,
                 "flagging": 0.5, "jitter_v": 0.22, "skew_tear": 0.2, "generation": 1}),
        ("interlace", {"combing": 0.6, "twitter": 0.35}),
        ("crt", {"scan_strength": 0.12, "bloom": 0.45, "misconvergence": 0.5,
                 "curvature": 0.04}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_video_tape_audio", {"format": "umatic_linear", "tracking": 0.25,
                                "dropout_rate": 8.0, "noise_db": -44.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -48.0, "hum_db": -56.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.9}),
        ("a_hum", {"hz": "60", "level_db": -50.0, "buzz": 0.3}),
    ],
    variants=[
        Variant("stable-playback", "Stable Playback",
                "A deck that has just been serviced, holding sync and hue for whole minutes at a time.",
                video={"vhs.time_base_error": 0.3, "vhs.flagging": 0.2,
                       "ntsc.phase_noise": 2.0, "vhs.skew_tear": 0.05}),
        Variant("dub-copy", "Access-Center Dub",
                "The cable channel's playback copy, one generation down and boiling with chroma speckle.",
                video={"vhs.generation": 2, "vhs.chroma_noise": 0.45, "vhs.dropouts": 9.0},
                audio={"a_video_tape_audio.noise_db": -40.0}),
    ],
))


# nearest: network-feed-raw-1988 (pristine studio color, rare hop shatter), betacam-eng-1989;
# differs: one-inch composite master with tiny dropouts and no field ENG, cut on a post bench.
register_preset(Preset(
    id="one-inch-type-c-1980",
    name="One-Inch Type C Master",
    family="vhs",
    era="1980",
    desc="A one-inch Type C reel off an Ampex machine with the time base corrector locked in: full composite bandwidth, a dropout every minute or so, and 15 ips reel sound on studio monitors.",
    tagline="Broadcast-clean 1-inch, dropout, TBC steady",
    tags=("80s", "one-inch", "type-c", "broadcast"),
    keywords=("eighties", "master", "ampex", "tbc", "clean", "post-production",
              "network", "variety", "special"),
    proc_height=580,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.4}),
        ("tone", {"contrast": 1.06, "lift": 0.018, "knee": 0.88}),
        ("saturation", {"amount": 1.05}),
        ("ntsc", {"strength": 0.5, "luma_bw": 3.9, "chroma_bw": 1.1, "phase_noise": 1.2,
                  "rainbow": 0.2, "dot_crawl": 0.26, "setup_level": 0.045}),
        ("vhs", {"mode": "sp", "luma_bw": 4.8, "chroma_bw": 1.0, "chroma_delay": 0.5,
                 "sharpen": 0.2, "luma_noise": 0.12, "chroma_noise": 0.12,
                 "head_switch": 0.0, "dropouts": 0.3, "time_base_error": 0.02,
                 "flagging": 0.0, "jitter_v": 0.03, "tracking_error": 0.0,
                 "generation": 1}),
        ("interlace", {"combing": 0.5, "twitter": 0.25}),
        ("crt", {"scan_strength": 0.1, "bloom": 0.25, "misconvergence": 0.3}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_analog_dub", {"format": "reel_15ips", "generations": 1,
                          "alignment": 0.05, "compression": 0.2, "hiss_db": -60.0}),
        ("a_mono", {"amount": 0.15}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.0,
                          "attack_ms": 8.0, "release_ms": 220.0}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.2}),
    ],
    variants=[
        Variant("played-100-times", "Hundredth Playback",
                "A library reel that has been through the machine all year and started shedding oxide.",
                video={"vhs.dropouts": 3.0, "vhs.luma_noise": 0.2, "vhs.dropout_burst": 0.5},
                audio={"a_analog_dub.hiss_db": -54.0}),
        Variant("edit-master-3rd-gen", "Third-Generation Edit Master",
                "Two assembly passes past the camera reel, with the high end sanded off.",
                video={"vhs.luma_bw": 4.2, "vhs.luma_noise": 0.2, "vhs.chroma_bw": 0.8},
                audio={"a_analog_dub.generations": 3, "a_analog_dub.alignment": 0.3}),
    ],
))


# nearest: betacam-eng-1989 (crisp component news staying in lane), umatic-news-1982;
# differs: long-form documentary body, iris hunting on the move, lavalier dropouts and a live room.
register_preset(Preset(
    id="betacam-sp-documentary-1990",
    name="Betacam SP Documentary",
    family="vhs",
    era="1990",
    desc="A Betacam SP documentary crew on component tape: the iris hunting as the subject crosses a window, edges crisp enough to count buttons, a lavalier losing contact every few seconds, and the room ringing behind the interview.",
    tagline="Component crispness, ENG iris, lav dropouts",
    tags=("90s", "betacam-sp", "documentary", "eng"),
    keywords=("nineties", "component", "crisp", "interview", "lavalier", "field", "verite"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.012, "knee": 0.86}),
        ("saturation", {"amount": 1.05}),
        ("exposure_auto", {"target": 0.44, "lag": 0.6, "overshoot": 0.15,
                           "max_boost": 2.5, "agc_gain_noise": 0.25, "wb_amount": 0.15}),
        ("sharpen", {"amount": 0.32, "radius": 0.85}),
        ("ntsc", {"strength": 0.25, "luma_bw": 4.5, "chroma_bw": 1.5, "phase_noise": 0.8,
                  "rainbow": 0.08, "dot_crawl": 0.12}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_bw": 2.6, "chroma_bw": 0.35,
                 "chroma_delay": 1.6, "sharpen": 0.3, "luma_noise": 0.35,
                 "chroma_noise": 0.4, "head_switch": 0.7, "dropouts": 2.0,
                 "time_base_error": 0.25, "flagging": 0.2, "generation": 2}),
        ("interlace", {"combing": 0.5, "twitter": 0.28}),
        ("crt", {"scan_strength": 0.09, "bloom": 0.2, "misconvergence": 0.18}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "lavalier_1972", "amount": 0.6,
                              "proximity": 0.25, "self_noise_db": -58.0}),
        ("a_mono", {"amount": 0.2}),
        ("a_tape_dropouts", {"rate": 2.0, "depth_db": 20.0, "azimuth": 0.2}),
        ("a_compressor", {"threshold_db": -20.0, "ratio": 3.0,
                          "attack_ms": 10.0, "release_ms": 260.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
        ("a_room", {"mode": "room", "size": 1.5, "decay_s": 0.5, "mix": 0.1}),
    ],
    variants=[
        Variant("studio-interview", "Locked-Off Interview",
                "Tripod, marked exposure, a proper mic: the format doing what it was sold to do.",
                video={"exposure_auto.enabled": False},
                audio={"a_tape_dropouts.rate": 0.3, "a_room.mix": 0.06}),
        Variant("vhs-viewing-copy", "VHS Viewing Copy",
                "The producer's screening dub, struck to a T-120 and mailed out for notes.",
                video={"vhs.enabled": True, "ntsc.strength": 0.55, "ntsc.dot_crawl": 0.3},
                audio={"a_speaker.strength": 0.7}),
    ],
))


# nearest: laserdisc-1985 (crawling dots, zero tape noise), one-inch-type-c-1980;
# differs: digital tape with absolutely no hue wobble, but a full composite comb signature.
register_preset(Preset(
    id="d2-composite-digital-1990",
    name="D-2 Composite Digital",
    family="vhs",
    era="1990",
    desc="A D-2 composite digital master: the picture carries no tape noise and the hue never wanders, but the composite sampling still leaves comb artifacts and dot crawl marching along every saturated edge.",
    tagline="Digital-clean composite: dot crawl, no noise",
    tags=("90s", "d-2", "composite-digital", "broadcast"),
    keywords=("nineties", "post", "clean", "dot-crawl", "composite", "ampex",
              "master", "commercials", "station-id", "playout"),
    proc_height=580,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "knee": 0.9}),
        ("saturation", {"amount": 1.04}),
        ("ntsc", {"strength": 0.65, "luma_bw": 3.6, "chroma_bw": 1.0, "comb": 0.35,
                  "dot_crawl": 0.55, "rainbow": 0.4, "phase_noise": 0.0,
                  "phase_error": 0.0, "setup_level": 0.055,
                  "comb_mode": "legacy_notch"}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_bw": 2.6, "chroma_bw": 0.35,
                 "chroma_delay": 1.8, "luma_noise": 0.36, "chroma_noise": 0.42,
                 "head_switch": 0.7, "dropouts": 2.5, "time_base_error": 0.3,
                 "flagging": 0.25, "generation": 2}),
        ("interlace", {"combing": 0.5, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.1, "bloom": 0.24}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 20.0, "high_hz": 20000.0, "order": 4}),
        ("a_mono", {"amount": 0.1}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 2.5,
                          "attack_ms": 12.0, "release_ms": 240.0}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.2}),
    ],
    variants=[
        Variant("dubbed-to-vhs", "Dubbed To VHS",
                "The composite artifacts survive the dub and pick up tape noise on the way down.",
                video={"vhs.enabled": True, "ntsc.dot_crawl": 0.5, "crt.bloom": 0.35},
                audio={"a_speaker.device": "tv_mono_1985", "a_speaker.strength": 0.6}),
        Variant("decoded-with-3d-comb", "Adaptive Comb Decode",
                "A later decoder that actually separates the subcarrier, leaving edges nearly clean.",
                video={"ntsc.comb_mode": "comb_2d_adaptive", "ntsc.dot_crawl": 0.15,
                       "ntsc.rainbow": 0.14}),
    ],
))


# nearest: d2-composite-digital-1990 (composite digital master), svhs-1992;
# differs: component digital with no composite artifacts at all, only faint DCT structure.
register_preset(Preset(
    id="digital-betacam-1996",
    name="Digital Betacam Master",
    family="vhs",
    era="1996",
    desc="A Digital Betacam component master: chroma resolved cleanly to the edges, faint DCT structure sitting in the flat areas, video white clipping hard at the legal ceiling, and 48 kHz PCM sound on the monitors.",
    tagline="Component 4:2:2 clean, faint DCT, white clip",
    tags=("90s", "digibeta", "videotape", "post-production"),
    keywords=("digital-betacam", "nineties", "component", "4-2-2", "clean",
              "master", "broadcast", "drama", "miniseries"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.04, "knee": 0.85}),
        ("saturation", {"amount": 1.03}),
        ("sharpen", {"amount": 0.24, "radius": 0.8}),
        ("chroma_dv", {"ratio": "4:2:0", "edge_sharpen": 0.2, "dct_blocks": 0.1}),
        ("vhs", {"enabled": False, "mode": "sp", "luma_bw": 2.6, "chroma_bw": 0.35,
                 "chroma_delay": 1.8, "luma_noise": 0.34, "chroma_noise": 0.4,
                 "head_switch": 0.7, "dropouts": 2.0, "time_base_error": 0.28,
                 "flagging": 0.2, "generation": 2}),
        ("interlace", {"combing": 0.5, "twitter": 0.15}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 20.0, "high_hz": 20000.0, "order": 4}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 2.5,
                          "attack_ms": 12.0, "release_ms": 240.0}),
        ("a_speaker", {"device": "studio_monitor", "strength": 0.2}),
    ],
    variants=[
        Variant("anamorphic-16x9", "Anamorphic 16:9",
                "The late-nineties widescreen delivery, squeezed on tape and unsqueezed on playout.",
                video={"framing.aspect": "source", "sharpen.amount": 0.2}),
        Variant("vhs-dub", "VHS Screener Dub",
                "The same master struck to tape for people who do not own a digital deck.",
                video={"vhs.enabled": True, "chroma_dv.dct_blocks": 0.16,
                       "sharpen.amount": 0.1},
                audio={"a_speaker.device": "tv_mono_1985", "a_speaker.strength": 0.6}),
    ],
))


# nearest: minidv-2000 (over-sharp 4:1:1 handycam), auth-live-truck-local-news-2004;
# differs: professional DVCPRO shoulder rig with a shotgun mic and hard AGC, 1998 news shift.
register_preset(Preset(
    id="dvcpro-news-1998",
    name="DVCPRO News Camera",
    family="vhs",
    era="1998",
    desc="A DVCPRO shoulder camera on a 1998 news shift: 4:1:1 chroma stepping across red graphics, DV edge halos on every contrast line, and a shotgun microphone riding hard into the camera's AGC.",
    tagline="4:1:1 chroma steps, DV halos, shoulder mic",
    tags=("90s", "dvcpro", "dv", "news"),
    keywords=("nineties", "eng", "4-1-1", "halos", "shoulder-camera", "field",
              "sd", "reporter", "local-news"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "knee": 0.86}),
        ("balance", {"warmth": -0.04}),
        ("saturation", {"amount": 1.02}),
        ("exposure_auto", {"target": 0.44, "lag": 0.5, "overshoot": 0.2,
                           "max_boost": 2.5, "agc_gain_noise": 0.3, "wb_amount": 0.2}),
        ("chroma_dv", {"ratio": "4:1:1", "edge_sharpen": 0.6, "dct_blocks": 0.15}),
        ("codec_era", {"enabled": False, "codec": "mpeg2video", "kbps": 2500,
                       "res": "480p", "gop": 30, "passes": 1,
                       "field_mode": "interlaced_tff"}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.09, "bloom": 0.18}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "shotgun_1975", "amount": 0.5,
                              "handling": 0.15, "self_noise_db": -58.0}),
        ("a_mono", {"amount": 0.25}),
        ("a_agc", {"target_db": -14.0, "max_gain_db": 12.0,
                   "attack_ms": 20.0, "release_ms": 500.0, "amount": 0.8}),
        ("a_compressor", {"threshold_db": -18.0, "ratio": 3.0,
                          "attack_ms": 8.0, "release_ms": 200.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
    ],
    variants=[
        Variant("studio-feed", "Studio Feed",
                "The same camera on a pedestal with the exposure and gain locked by an operator.",
                video={"exposure_auto.enabled": False},
                audio={"a_agc.enabled": False, "a_historical_mic.handling": 0.0}),
        Variant("sat-uplink-compressed", "Satellite Uplink",
                "Squeezed through the truck's encoder and back down to the station, blocks and all.",
                video={"codec_era.enabled": True, "chroma_dv.dct_blocks": 0.22},
                audio={"a_speaker.strength": 0.6}),
    ],
))


# nearest: minidv-2000 (handycam 4:1:1), video8-holiday-1990 (analog azimuth shimmer, AFM);
# differs: DV data written to 8 mm tape, so dropouts mute the audio outright, plus a burned-in date.
register_preset(Preset(
    id="digital8-family-1999",
    name="Digital8 Family Camcorder",
    family="vhs",
    era="1999",
    desc="A Digital8 camcorder writing DV data onto Video8 cassettes: sharpening halos on every edge, 4:1:1 chroma steps in the flowers, an orange date burned into the corner, and tape dropouts that mute the sound outright instead of hissing.",
    tagline="DV on Video8 tape, halos, mute dropouts",
    tags=("90s", "digital8", "camcorder", "home-video"),
    keywords=("nineties", "dv", "video8-cassette", "sony", "halos", "dropouts",
              "family", "birthday"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "knee": 0.86}),
        ("balance", {"warmth": 0.07}),
        ("saturation", {"amount": 1.16, "vibrance": 0.12}),
        ("exposure_auto", {"target": 0.42, "lag": 0.8, "overshoot": 0.3,
                           "max_boost": 3.0, "agc_gain_noise": 0.35, "wb_amount": 0.3}),
        ("chroma_dv", {"ratio": "4:1:1", "edge_sharpen": 0.9, "dct_blocks": 0.15}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("timestamp", {"style": "camcorder_orange", "corner": "br",
                       "date_format": "mon_d_yyyy", "start": "1999-07-04 15:22:10",
                       "opacity": 0.9, "glow": 0.5, "flicker": 0.2}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "camcorder_1994", "amount": 0.7,
                              "handling": 0.2, "overload": 0.3, "self_noise_db": -52.0}),
        ("a_mono", {"amount": 0.35}),
        ("a_agc", {"target_db": -15.0, "max_gain_db": 14.0,
                   "attack_ms": 30.0, "release_ms": 700.0, "amount": 0.9}),
        ("a_digital_glitch", {"stutter_rate": 0.0, "mute_rate": 3.0, "crackle_rate": 0.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
    ],
    variants=[
        Variant("clean-tape", "Fresh Cassette",
                "A tape out of the box and a head that has just been cleaned.",
                video={"chroma_dv.edge_sharpen": 0.6},
                audio={"a_digital_glitch.mute_rate": 0.0}),
        Variant("head-clog", "Clogged Head",
                "Somebody left it in a hot car: the DV stream drops blocks and the sound keeps cutting out.",
                video={"chroma_dv.dct_blocks": 0.3, "chroma_dv.edge_sharpen": 1.0},
                audio={"a_digital_glitch.mute_rate": 12.0}),
    ],
))


# nearest: vhs-1985-sp (soft but stable, faint chroma smear), betamax-1978;
# differs: pre-HQ 1978 machine, softer luma than Beta, unstable sync and barely-there color.
register_preset(Preset(
    id="first-gen-vhs-1978",
    name="First-Generation VHS",
    family="vhs",
    era="1978",
    desc="A first-generation VHS deck from before HQ circuitry: luma resolved to barely 240 lines, chroma so weak it slides off saturated objects, head switch and flagging untouched by any correction, and linear mono sound taped off the antenna overnight.",
    tagline="Two-hour soft luma, feeble chroma, no HQ",
    tags=("70s", "vhs", "off-air", "home-video"),
    keywords=("seventies", "first-generation", "jvc", "two-hour", "soft",
              "feeble-chroma", "early-vcr", "timer", "taped-off-air"),
    proc_height=520,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.04, "knee": 0.8}),
        ("saturation", {"amount": 0.8, "vibrance": -0.12}),
        ("ntsc", {"strength": 0.7, "luma_bw": 3.2, "chroma_bw": 0.7, "phase_noise": 3.0,
                  "rainbow": 0.3, "dot_crawl": 0.28, "chroma_agc": 0.3,
                  "setup_level": 0.05}),
        ("vhs", {"mode": "sp", "luma_bw": 2.4, "chroma_bw": 0.22, "chroma_delay": 2.6,
                 "sharpen": 0.1, "luma_noise": 0.4, "chroma_noise": 0.45,
                 "head_switch": 0.8, "dropouts": 3.0, "time_base_error": 0.5,
                 "flagging": 0.35, "jitter_v": 0.2, "tracking_error": 0.05,
                 "generation": 1}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.12, "bloom": 0.4, "misconvergence": 0.6,
                 "curvature": 0.03}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_video_tape_audio", {"format": "vhs_linear", "tracking": 0.4,
                                "dropout_rate": 8.0, "noise_db": -44.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -54.0, "hum_db": -60.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.85}),
    ],
    variants=[
        Variant("good-tape-good-deck", "Good Tape, Good Deck",
                "Fresh stock in a machine that has just been aligned, which is as clean as 1978 got.",
                video={"vhs.luma_noise": 0.3, "vhs.time_base_error": 0.35,
                       "vhs.flagging": 0.2},
                audio={"a_video_tape_audio.dropout_rate": 3.0}),
        Variant("hq-deck-playback", "Played On An HQ Deck",
                "The 1978 recording read back years later by a machine with detail enhancement.",
                video={"vhs.sharpen": 0.4, "vhs.luma_bw": 3.0, "vhs.luma_noise": 0.3}),
    ],
))


# nearest: vhs-dub-generation (chroma smeared wider, top of frame bent), vhs-rental-1992;
# differs: a compilation where every segment is re-timed by the copier's auto color and slammed loud.
register_preset(Preset(
    id="video-store-trailer-reel-1988",
    name="Video-Store Trailer Reel",
    family="vhs",
    era="1988",
    desc="The rental counter's coming-attractions tape, three dubs deep: each trailer re-timed by a different deck's automatic color, chroma pulsing at the head beat, and the promo mix slammed flat by the copier's level control.",
    tagline="Dub-of-dubs trailers, loud mix, level jumps",
    tags=("80s", "vhs", "trailer", "video-store"),
    keywords=("eighties", "promo", "dubs", "loud", "level-jumps", "rental",
              "coming-attractions", "compilation", "generation-loss"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.45}),
        ("tone", {"contrast": 1.12, "lift": 0.04, "knee": 0.76}),
        ("saturation", {"amount": 1.14, "vibrance": 0.1}),
        ("auto_color", {"wb_pump": 0.3, "level_pump": 0.4, "lag_s": 0.5}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.2, "chroma_bw": 0.7, "phase_noise": 2.5,
                  "rainbow": 0.28, "dot_crawl": 0.3, "chroma_agc": 0.2}),
        ("vhs", {"mode": "sp", "generation": 3, "luma_bw": 2.8, "chroma_bw": 0.32,
                 "chroma_delay": 2.8, "sharpen": 0.2, "luma_noise": 0.42,
                 "chroma_noise": 0.45, "head_switch": 0.7, "dropouts": 4.0,
                 "time_base_error": 0.3, "flagging": 0.22, "tracking_error": 0.08,
                 "head_beat": 0.2, "interchange": 0.3}),
        ("interlace", {"combing": 0.5, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.11, "bloom": 0.35, "misconvergence": 0.4}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_distortion", {"type": "soft", "drive": 1.8, "tone": 0.15}),
        ("a_video_tape_audio", {"format": "vhs_linear", "tracking": 0.3,
                                "dropout_rate": 6.0, "noise_db": -46.0}),
        ("a_agc", {"target_db": -14.0, "max_gain_db": 14.0,
                   "attack_ms": 20.0, "release_ms": 400.0, "amount": 1.0}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 5.0,
                          "attack_ms": 4.0, "release_ms": 160.0, "makeup_db": 2.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.8}),
        ("a_bed", {"enabled": False, "bed": "tv_shop_wall", "level_db": -30.0,
                   "duck": 0.25, "loop_jitter": 0.5}),
    ],
    variants=[
        Variant("fresh-promo-tape", "Fresh Promo Tape",
                "The reel the distributor actually sent, before six months of nightly copying.",
                video={"vhs.generation": 1, "auto_color.level_pump": 0.1,
                       "auto_color.wb_pump": 0.1, "vhs.head_beat": 0.05,
                       "vhs.luma_noise": 0.28, "vhs.chroma_noise": 0.3},
                audio={"a_distortion.drive": 1.2, "a_compressor.ratio": 3.0}),
        Variant("store-tv-loop", "Store TV Loop",
                "Playing to nobody on the wall of sets by the door, fourth generation and counting.",
                video={"vhs.generation": 4, "vhs.luma_noise": 0.45, "vhs.dropouts": 7.0},
                audio={"a_bed.enabled": True, "a_speaker.strength": 1.0}),
    ],
))


# nearest: vhs-camcorder-1989 (pumping iris, hunting focus, orange date), auth-warehouse-rave-vhs;
# differs: fluorescent basement flicker, a hard-clipped onboard mic on a guitar amp, three generations down.
register_preset(Preset(
    id="band-demo-vhs-1992",
    name="Band Demo Tape",
    family="vhs",
    era="1992",
    desc="A practice-room demo shot on a borrowed camcorder under basement fluorescents: gain pumping in the dark corners, the onboard microphone hard-clipping on the guitar cabinet, and three VHS generations of hiss between the band and whoever gets the tape.",
    tagline="Basement camcorder, clipped amp mix, 3rd gen",
    tags=("90s", "vhs", "camcorder", "band"),
    keywords=("demo", "garage", "nineties", "basement", "practice", "clipped",
              "third-gen", "punk", "rehearsal"),
    proc_height=520,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.08, "lift": 0.06, "knee": 0.78}),
        ("balance", {"warmth": -0.1, "shadow_tint": "green", "shadow_amt": 0.24,
                     "high_tint": "cyan", "high_amt": 0.1}),
        ("saturation", {"amount": 0.86, "vibrance": -0.08}),
        ("exposure_auto", {"target": 0.4, "lag": 1.2, "overshoot": 0.35,
                           "max_boost": 4.0, "agc_gain_noise": 0.5, "wb_amount": 0.3,
                           "flicker_60hz": 0.15}),
        ("ntsc", {"strength": 0.55, "luma_bw": 3.0, "chroma_bw": 0.6, "phase_noise": 2.5,
                  "rainbow": 0.25, "dot_crawl": 0.28}),
        ("vhs", {"mode": "sp", "generation": 3, "luma_bw": 2.6, "chroma_bw": 0.35,
                 "chroma_delay": 2.0, "sharpen": 0.2, "luma_noise": 0.4,
                 "chroma_noise": 0.4, "head_switch": 0.7, "dropouts": 4.0,
                 "time_base_error": 0.3, "flagging": 0.2, "tracking_error": 0.06}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.11, "bloom": 0.35, "misconvergence": 0.45}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "camcorder_1994", "amount": 0.9,
                              "overload": 0.8, "handling": 0.3, "self_noise_db": -48.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_distortion", {"type": "hard", "drive": 2.5, "tone": -0.1}),
        ("a_agc", {"target_db": -13.0, "max_gain_db": 12.0,
                   "attack_ms": 15.0, "release_ms": 500.0, "amount": 0.9}),
        ("a_video_tape_audio", {"format": "vhs_linear", "tracking": 0.3,
                                "dropout_rate": 10.0, "noise_db": -46.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.8}),
    ],
    variants=[
        Variant("soundboard-dub", "Soundboard Dub",
                "Somebody ran a line out of the mixer instead, so the guitars stop tearing.",
                audio={"a_distortion.drive": 1.3, "a_historical_mic.overload": 0.2,
                       "a_historical_mic.handling": 0.05}),
        Variant("fifth-gen-tape-trade", "Fifth-Generation Trade",
                "Two more copies down the mailing list, and the drummer is now a smear.",
                video={"vhs.generation": 5, "vhs.luma_noise": 0.5, "vhs.chroma_noise": 0.5},
                audio={"a_video_tape_audio.noise_db": -40.0}),
    ],
))


# nearest: auth-hair-metal-arena-promo (16 mm concert coverage), band-demo-vhs-1992;
# differs: balcony zoom through haze, stage lights blooming the tube, arena room on a crushed AGC.
register_preset(Preset(
    id="concert-bootleg-camcorder-1985",
    name="Concert Bootleg Camcorder",
    family="vhs",
    era="1985",
    desc="An arena bootleg shot from the balcony on a shoulder camcorder: the long lens hunting focus through cigarette haze, stage lights blooming the tube white, and an electret microphone crushed flat by the automatic level and the room.",
    tagline="Balcony telephoto haze, stage bloom, AGC",
    tags=("80s", "vhs", "camcorder", "concert"),
    keywords=("bootleg", "eighties", "balcony", "stage-lights", "bloom", "agc",
              "arena", "tape-trade", "live"),
    proc_height=520,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.14, "lift": 0.03, "knee": 0.66}),
        ("balance", {"warmth": 0.07, "high_tint": "yellow", "high_amt": 0.14}),
        ("saturation", {"amount": 1.12, "vibrance": 0.12}),
        ("exposure_auto", {"target": 0.38, "lag": 1.0, "overshoot": 0.4,
                           "max_boost": 5.0, "agc_gain_noise": 0.55, "wb_amount": 0.2,
                           "iris_step": 0.3}),
        ("optics", {"soft_focus": 0.26, "focus_drift": 0.25, "hunt_rate": 3.0,
                    "veiling_flare": 0.45, "bloom_mids": 0.35}),
        ("ntsc", {"strength": 0.6, "luma_bw": 3.0, "chroma_bw": 0.6, "phase_noise": 3.0,
                  "rainbow": 0.3, "dot_crawl": 0.3, "chroma_agc": 0.25}),
        ("vhs", {"mode": "sp", "generation": 2, "luma_bw": 2.6, "chroma_bw": 0.35,
                 "chroma_delay": 2.0, "sharpen": 0.15, "luma_noise": 0.4,
                 "chroma_noise": 0.45, "head_switch": 0.75, "dropouts": 3.0,
                 "time_base_error": 0.32, "flagging": 0.22, "head_beat": 0.15}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.12, "bloom": 0.58, "beam_bloom": 0.5,
                 "glass_glow": 0.25}),
        ("framing", {"aspect": "source", "mode": "box"}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "electret_1985", "amount": 0.9,
                              "overload": 0.9, "handling": 0.2, "self_noise_db": -50.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_distortion", {"type": "soft", "drive": 2.5, "tone": -0.1}),
        ("a_agc", {"target_db": -12.0, "max_gain_db": 10.0,
                   "attack_ms": 10.0, "release_ms": 600.0, "amount": 1.0}),
        ("a_video_tape_audio", {"format": "vhs_linear", "tracking": 0.25,
                                "dropout_rate": 5.0, "noise_db": -45.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.8}),
        ("a_room", {"mode": "chamber", "size": 3.0, "decay_s": 1.8,
                    "predelay_ms": 30.0, "damp": 0.4, "mix": 0.3}),
    ],
    variants=[
        Variant("soundboard-patch", "Soundboard Patch",
                "A friend on the crew ran a cable, so the picture stays terrible and the mix does not.",
                audio={"a_historical_mic.enabled": False, "a_distortion.drive": 1.2,
                       "a_room.mix": 0.08}),
        Variant("tenth-generation-trade", "Tenth-Generation Trade",
                "Traded by post until the stage is a rumor and the dropouts run in packs.",
                video={"vhs.generation": 5, "vhs.luma_noise": 0.55,
                       "vhs.chroma_noise": 0.55, "vhs.dropouts": 12.0},
                audio={"a_video_tape_audio.noise_db": -39.0}),
    ],
))
