"""Transmission-family presets, second wave: distribution paths and what they cost.

Not a program and not a network: the carrier itself. A scrambled premium channel,
a leaky cable drop, three flavours of digital cliff, a slow-scan converter on the
Moon, a videophone, a radiofax and a camcorder pointed at a cinema screen.
"""

from ..engine.presets import Preset, Variant, register_preset

# nearest: jammed-broadcast-1984; differs: sync suppression is periodic and steady,
# a wide bar breathing through the picture with a bright buzz, not intermittent jamming.
register_preset(Preset(
    id="scrambled-cable-1986",
    name="Scrambled Premium Channel",
    family="transmission",
    era="1986",
    desc="The channel you did not pay for: the sync pulse suppressed on a fixed cycle so a broad dark band walks down the picture, the set never quite locks, and the audio arrives as a bright buzz with a voice somewhere inside it.",
    tagline="Sync-suppressed roll, bars, buzzing audio",
    tags=("80s", "ntsc", "television", "interference", "set-top"),
    keywords=("scrambled", "cable", "premium", "eighties", "descrambler",
              "sync-suppression", "videocipher", "bars", "tearing", "pay-tv",
              "late-night"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.5}),
        ("tone", {"contrast": 1.06, "lift": 0.04, "knee": 0.82, "pivot": 0.45}),
        ("saturation", {"amount": 1.0, "vibrance": 0.05}),
        ("ntsc", {"strength": 0.8, "luma_bw": 3.2, "chroma_bw": 0.7, "phase_noise": 5.0,
                  "sync_jitter": 0.6, "rainbow": 0.3, "dot_crawl": 0.3}),
        ("jam_bars", {"amount": 0.7, "bar_size": 0.55, "roll_speed": 0.16, "tear": 0.18}),
        ("herringbone", {"amount": 0.4, "pattern": "rolling_hum", "wavelength": 9.0,
                         "drift": 0.45}),
        ("signal_rf", {"snow": 0.05, "sparkle": 2.0, "ghost_n": 1, "ghost_px": 10.0,
                       "ghost_alpha": 0.1, "hum_bar": 0.35, "hum_speed": 0.08}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.35, "scan_strength": 0.12, "curvature": 0.06,
                 "vignette_crt": 0.24}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 200.0, "high_hz": 4000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_distortion", {"type": "soft", "drive": 2.0, "tone": 0.2}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -40.0, "hum_db": -48.0, "comp": 0.5}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.7}),
    ],
    variants=[
        Variant("half-descrambled", "Almost Watchable",
                "Somebody's cousin sold you a box that half works: the bar thins out and you can follow the plot if you sit close.",
                video={"jam_bars.amount": 0.32, "jam_bars.tear": 0.08,
                       "herringbone.amount": 0.16, "signal_rf.hum_bar": 0.15,
                       "ntsc.sync_jitter": 0.3, "ntsc.phase_noise": 3.0},
                audio={"a_tv_sound.buzz_db": -55.0, "a_distortion.drive": 1.4,
                       "a_bandlimit.high_hz": 5500.0}),
        Variant("clean-descrambler", "Legitimate Subscriber",
                "The box downstairs is authorized: the sync comes back, the buzz drops out and it is just cable again.",
                video={"jam_bars.enabled": False, "herringbone.enabled": False,
                       "ntsc.sync_jitter": 0.08, "ntsc.phase_noise": 1.6,
                       "signal_rf.hum_bar": 0.05},
                audio={"a_distortion.enabled": False, "a_tv_sound.buzz_db": -62.0,
                       "a_bandlimit.high_hz": 7000.0}),
    ],
))

# nearest: pirate-uhf-1987; differs: a cable plant leaking into itself, so crossmodulated
# ghosts and a herringbone beat arrive on a strong signal with almost no snow.
register_preset(Preset(
    id="analog-cable-leak-1985",
    name="Analog Cable Leak",
    family="transmission",
    era="1985",
    desc="A tired coax drop and a channel-3 modulator: the picture is strong but doubled, a fine herringbone weave drifts across it from the channel next door, and 60 Hz hum sits under the sound.",
    tagline="Crossmod echo, herringbone, channel-3 mush",
    tags=("80s", "ntsc", "television", "interference", "rf"),
    keywords=("cable", "analog", "eighties", "leak", "ingress", "herringbone", "ghosting",
              "channel-3", "coax", "crossmodulation", "retro"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.45}),
        ("tone", {"contrast": 1.02, "lift": 0.03, "knee": 0.84, "pivot": 0.45}),
        ("saturation", {"amount": 1.0, "vibrance": 0.05}),
        ("ntsc", {"strength": 0.8, "luma_bw": 3.2, "chroma_bw": 0.8, "phase_noise": 2.0,
                  "rainbow": 0.3, "dot_crawl": 0.35}),
        ("signal_rf", {"snow": 0.05, "sparkle": 2.0, "ghost_n": 2, "ghost_px": 26.0,
                       "ghost_alpha": 0.24}),
        ("herringbone", {"amount": 0.5, "pattern": "herringbone", "wavelength": 6.5,
                         "drift": 1.0}),
        ("interlace", {"combing": 0.5, "twitter": 0.2}),
        ("crt", {"bloom": 0.35, "misconvergence": 0.5, "scan_strength": 0.1,
                 "curvature": 0.05, "vignette_crt": 0.22}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_tv_sound", {"hz": "60", "buzz_db": -52.0, "hum_db": -54.0, "comp": 0.45}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.7}),
        ("a_hum", {"hz": "60", "level_db": -56.0, "buzz": 0.3}),
    ],
    variants=[
        Variant("good-drop", "New Drop",
                "The installer has just been: one soft ghost, a whisper of weave and everything else where it should be.",
                video={"signal_rf.ghost_n": 1, "signal_rf.ghost_alpha": 0.07,
                       "herringbone.amount": 0.15, "ntsc.phase_noise": 1.2},
                audio={"a_hum.level_db": -66.0, "a_tv_sound.buzz_db": -60.0}),
        Variant("bad-splitter", "Four-Way Splitter",
                "Three televisions, a cable modem and a splitter from the hardware store: everything arrives three times.",
                video={"signal_rf.ghost_n": 3, "signal_rf.ghost_alpha": 0.36,
                       "signal_rf.snow": 0.1, "herringbone.amount": 0.68,
                       "ntsc.phase_noise": 3.0},
                audio={"a_hum.level_db": -46.0, "a_tv_sound.buzz_db": -46.0}),
    ],
))

# nearest: datamosh; differs: not a stylized corruption but a set-top box losing MPEG-2
# packets, so the picture tiles into macroblocks and freezes while the clock runs on.
register_preset(Preset(
    id="digital-cable-tiling-2002",
    name="Digital Cable Tiling",
    family="transmission",
    era="2002",
    desc="A digital tier squeezed too hard and a drop that is a little wet: whole macroblock rows slide sideways, the picture holds still for a beat and snaps forward, and the audio goes out for half a second at a time.",
    tagline="MPEG-2 macroblock tiling, freeze, audio cut",
    tags=("00s", "cable", "television", "codec", "interference"),
    keywords=("digital-cable", "tiling", "macroblocks", "aughts", "mpeg2", "freeze",
              "pixelation", "set-top", "dropout", "signal-loss", "glitch"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.02, "lift": 0.01, "knee": 0.88, "pivot": 0.45}),
        ("saturation", {"amount": 1.0}),
        ("codec_era", {"codec": "mpeg2video", "kbps": 2600, "gop": 15,
                       "field_mode": "interlaced_tff", "denoise_pre": 0.15}),
        ("codec_glitch", {"codec": "mpeg2video", "amount": 0.35, "drop_p": 0.09,
                          "freeze_p": 0.22, "slice_shift": 0.2, "kbps": 3500,
                          "gop": 15, "keyframes": True}),
        ("interlace", {"combing": 0.35, "twitter": 0.15}),
        ("crt", {"bloom": 0.2, "scan_strength": 0.08}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.005}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 14000.0}),
        ("a_codec_aac", {"kbps": 96, "mono": False}),
        ("a_digital_glitch", {"stutter_rate": 2.0, "mute_rate": 6.0, "crackle_rate": 2.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
    ],
    variants=[
        Variant("mild-rain", "Passing Shower",
                "A block here, a hiccup there, and nobody gets up to look at the box.",
                video={"codec_glitch.amount": 0.1, "codec_glitch.drop_p": 0.02,
                       "codec_glitch.freeze_p": 0.1, "codec_glitch.slice_shift": 0.05},
                audio={"a_digital_glitch.mute_rate": 2.0,
                       "a_digital_glitch.crackle_rate": 1.0}),
        Variant("heavy-storm", "Line Fault",
                "Whatever is wrong upstream is getting worse: the picture spends more time frozen than moving.",
                video={"codec_glitch.amount": 0.45, "codec_glitch.drop_p": 0.14,
                       "codec_glitch.freeze_p": 0.45, "codec_glitch.slice_shift": 0.3},
                audio={"a_digital_glitch.mute_rate": 15.0,
                       "a_digital_glitch.stutter_rate": 5.0}),
    ],
))

# nearest: digital-cable-tiling-2002; differs: a smaller dish bitrate with MPEG audio and
# rain fade, so the failures come in long freezes rather than steady tiling.
register_preset(Preset(
    id="digital-satellite-rain-fade-1998",
    name="Digital Satellite Rain Fade",
    family="transmission",
    era="1998",
    desc="An eighteen-inch dish and a rain cell over the neighbourhood: the encoder was already thin at 2 Mbit, and every heavy burst takes the transport stream out for a second and a half.",
    tagline="Blocky MPEG-2 dish, rain-fade freezes",
    tags=("90s", "television", "codec", "interference", "dbs"),
    keywords=("satellite", "dish", "digital", "nineties", "rain-fade", "mpeg2", "freeze",
              "directv-era", "blocks", "searching-for-signal", "glitch"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.04, "lift": 0.015, "knee": 0.86, "pivot": 0.45}),
        ("saturation", {"amount": 0.98}),
        ("codec_era", {"codec": "mpeg2video", "kbps": 2200, "gop": 15,
                       "field_mode": "interlaced_tff", "denoise_pre": 0.2}),
        ("codec_glitch", {"codec": "mpeg2video", "amount": 0.38, "drop_p": 0.12,
                          "freeze_p": 0.3, "slice_shift": 0.18, "kbps": 3000,
                          "gop": 15, "keyframes": True}),
        ("interlace", {"combing": 0.35, "twitter": 0.15}),
        ("crt", {"bloom": 0.25, "misconvergence": 0.3, "scan_strength": 0.1,
                 "vignette_crt": 0.16}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.005}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 12000.0}),
        ("a_codec_mp3", {"kbps": "128", "mono": False}),
        ("a_digital_glitch", {"stutter_rate": 1.5, "mute_rate": 5.0, "crackle_rate": 1.5}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
    ],
    variants=[
        Variant("clear-sky", "Clear Sky",
                "A cold dry night and a full transponder: the dish behaves and the blocks stay small.",
                video={"codec_era.kbps": 3200, "codec_glitch.amount": 0.08,
                       "codec_glitch.drop_p": 0.02, "codec_glitch.freeze_p": 0.05,
                       "codec_glitch.slice_shift": 0.0},
                audio={"a_digital_glitch.mute_rate": 1.0,
                       "a_digital_glitch.stutter_rate": 0.5}),
        Variant("downpour", "Searching for Signal",
                "The storm sits on top of the house and the receiver starts counting down to nothing.",
                video={"codec_glitch.amount": 0.5, "codec_glitch.drop_p": 0.18,
                       "codec_glitch.freeze_p": 0.55, "codec_glitch.slice_shift": 0.3},
                audio={"a_digital_glitch.mute_rate": 20.0,
                       "a_digital_glitch.stutter_rate": 6.0}),
    ],
))

# nearest: digital-satellite-rain-fade-1998; differs: 2009 over-the-air ATSC on an early
# flat panel, 16:9, where the failure is a long freeze and silence rather than blocks.
register_preset(Preset(
    id="atsc-digital-cliff-2009",
    name="Digital-TV Cliff",
    family="transmission",
    era="2009",
    desc="A converter box on a bent rabbit-ear after the analog shutoff: above threshold it is fine, below it the picture stops dead, tears into slices and comes back with the sound missing.",
    tagline="ATSC freeze-pixelate, converter-box mush",
    tags=("00s", "television", "lcd", "codec", "interference"),
    keywords=("atsc", "digital-cliff", "converter-box", "aughts", "dtv-transition",
              "freeze", "pixelate", "antenna", "ota", "dropout", "glitch"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.03, "lift": 0.01, "knee": 0.88, "pivot": 0.45}),
        ("saturation", {"amount": 1.0}),
        ("codec_era", {"codec": "mpeg2video", "kbps": 3000, "gop": 30,
                       "field_mode": "interlaced_tff"}),
        ("codec_glitch", {"codec": "mpeg2video", "amount": 0.26, "drop_p": 0.05,
                          "freeze_p": 0.45, "slice_shift": 0.32, "kbps": 4000,
                          "gop": 30, "keyframes": True}),
        ("interlace", {"combing": 0.3, "twitter": 0.12}),
        ("lcd_screen", {"grid": 0.06, "scale": 3, "response_smear": 0.2,
                        "backlight_bleed": 0.1, "viewing_angle": 0.08}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.004}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 40.0, "high_hz": 15000.0}),
        ("a_codec_aac", {"kbps": 128, "mono": False}),
        ("a_digital_glitch", {"stutter_rate": 0.0, "mute_rate": 8.0, "crackle_rate": 0.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("strong-signal", "Above Threshold",
                "The antenna found the tower: clean, boring, exactly what the transition promised.",
                video={"codec_glitch.amount": 0.04, "codec_glitch.drop_p": 0.01,
                       "codec_glitch.freeze_p": 0.06, "codec_glitch.slice_shift": 0.0},
                audio={"a_digital_glitch.mute_rate": 1.0}),
        Variant("fringe", "Fringe Reception",
                "Forty miles out with the antenna in the attic: it works when nobody walks past it.",
                video={"codec_glitch.amount": 0.35, "codec_glitch.drop_p": 0.16,
                       "codec_glitch.freeze_p": 0.7, "codec_glitch.slice_shift": 0.35},
                audio={"a_digital_glitch.mute_rate": 22.0,
                       "a_digital_glitch.stutter_rate": 4.0}),
    ],
))

# nearest: auth-mission-control-television-feed-1969; differs: the scan converter itself,
# 320 lines of long-persistence smear rather than an orthicon studio feed.
register_preset(Preset(
    id="slow-scan-lunar-1969",
    name="Slow-Scan Lunar Feed",
    family="transmission",
    era="1969",
    desc="A 320-line slow-scan camera pointed at a monitor and re-photographed for the networks: washed-out grays, long phosphor trails behind every movement and a headset voice through a 3 kHz link.",
    tagline="320-line SSTV smear, scan-converter ghosts",
    tags=("60s", "television", "bw", "spaceflight", "long-persistence"),
    keywords=("apollo", "moon", "sstv", "slow-scan", "sixties", "nasa", "lunar",
              "scan-converter", "ghosting", "historic"),
    proc_height=320,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.1}),
        ("tone", {"contrast": 0.9, "lift": 0.1, "knee": 0.65, "pivot": 0.44}),
        ("optics", {"soft_focus": 0.3, "corner_softness": 0.15}),
        ("phosphor_decay", {"decay": 0.9, "mode": "p22"}),
        ("ntsc", {"enabled": False, "strength": 0.6, "luma_bw": 2.6, "chroma_bw": 0.4,
                  "phase_noise": 2.0, "rainbow": 0.05, "dot_crawl": 0.08}),
        ("signal_rf", {"snow": 0.08, "sparkle": 2.0, "ghost_n": 1, "ghost_px": 12.0,
                       "ghost_alpha": 0.2}),
        ("crt", {"bloom": 0.55, "beam_bloom": 0.4, "glass_glow": 0.2, "curvature": 0.05,
                 "scan_strength": 0.1, "vignette_crt": 0.35}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "broadcast_dynamic_1955", "amount": 0.6,
                              "overload": 0.3, "self_noise_db": -52.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bandlimit", {"low_hz": 300.0, "high_hz": 3200.0}),
        ("a_distortion", {"type": "soft", "drive": 1.6, "tone": 0.15}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.75}),
        ("a_hum", {"hz": "60", "level_db": -56.0, "buzz": 0.2}),
    ],
    variants=[
        Variant("direct-sstv-tape", "Direct Recording",
                "The tape made at the tracking station before the networks got near it: the smear is real, the snow is not.",
                video={"signal_rf.snow": 0.0, "signal_rf.ghost_alpha": 0.0,
                       "crt.bloom": 0.45, "tone.contrast": 1.0},
                audio={"a_distortion.drive": 1.2, "a_hum.level_db": -66.0}),
        Variant("network-rebroadcast", "Network Rebroadcast",
                "What six hundred million people actually saw: a scan conversion of a scan conversion, off a rooftop antenna.",
                video={"ntsc.enabled": True, "signal_rf.snow": 0.12,
                       "phosphor_decay.decay": 0.75, "optics.soft_focus": 0.35},
                audio={"a_bandlimit.high_hz": 2800.0, "a_hum.level_db": -48.0}),
    ],
))

# nearest: closed-circuit-1970; differs: a near-square 250-line videophone screen with a
# phone-band voice, not a ceiling-mounted vidicon on a hall monitor.
register_preset(Preset(
    id="picturephone-1970",
    name="Picturephone",
    family="transmission",
    era="1970",
    desc="Two hundred and fifty lines of black-and-white on a nearly square tube, focus soft to the corners, phosphor smearing behind every gesture, and the other person arriving through a 3 kHz telephone pair.",
    tagline="250-line tube, telephone voice, tiny screen",
    tags=("70s", "crt", "monochrome", "square", "tube-camera"),
    keywords=("picturephone", "videophone", "seventies", "bell", "video-call", "bw",
              "250-line", "telephone", "lab", "early-video-call", "corporate"),
    proc_height=250,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "silver", "tint_amt": 0.12}),
        ("tone", {"contrast": 1.1, "lift": 0.05, "knee": 0.85, "pivot": 0.45}),
        ("optics", {"soft_focus": 0.25, "corner_softness": 0.15}),
        ("phosphor_decay", {"decay": 0.5, "mode": "p22"}),
        ("signal_rf", {"enabled": False, "snow": 0.06, "sparkle": 2.0, "ghost_n": 1,
                       "ghost_px": 8.0, "ghost_alpha": 0.12}),
        ("crt", {"bloom": 0.5, "curvature": 0.06, "glass_glow": 0.15,
                 "scan_strength": 0.25, "vignette_crt": 0.35}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_mono", {"amount": 1.0}),
        ("a_telephone", {"era": "rotary_1955", "line_noise_db": -52.0,
                         "exchange_noise": 0.3, "sidetone_click": True}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.5}),
    ],
    variants=[
        Variant("good-line", "Across the Building",
                "Two floors apart on the same exchange: as sharp as this thing was ever going to be.",
                video={"optics.soft_focus": 0.15, "crt.bloom": 0.42,
                       "phosphor_decay.decay": 0.4},
                audio={"a_telephone.line_noise_db": -60.0,
                       "a_telephone.exchange_noise": 0.1}),
        Variant("long-distance", "Long Distance",
                "Chicago to New York at forty dollars for three minutes, and it shows on both ends.",
                video={"optics.soft_focus": 0.35, "signal_rf.enabled": True,
                       "tone.contrast": 1.02, "tone.lift": 0.09},
                audio={"a_telephone.line_noise_db": -44.0,
                       "a_telephone.exchange_noise": 0.6}),
    ],
))

# nearest: teletext-1979; differs: the eight-colour block palette as the whole picture on
# a terminal, with a dial-up modem band on the sound, not captions over a program.
register_preset(Preset(
    id="videotex-terminal-1982",
    name="Videotex Terminal",
    family="transmission",
    era="1982",
    desc="A dedicated terminal on a phone line: everything quantized to the eight saturated teletext colours and a coarse block grid, drawn on a small curved tube with the modem band still audible under it.",
    tagline="Teletext blocks, modem tone, CRT glow",
    tags=("80s", "crt", "dither", "text", "dial-up"),
    keywords=("videotex", "prestel", "minitel", "teletext", "eighties", "terminal",
              "blocks", "modem", "8-color", "text-service"),
    upscale="sharp",
    video=[
        ("mono", {"enabled": False, "amount": 1.0, "response": "modern",
                  "tint": "amber_crt", "tint_amt": 0.6}),
        ("tone", {"contrast": 1.08, "lift": 0.02, "knee": 0.9, "pivot": 0.45}),
        ("pixel_era", {"res_h": 240, "palette": "teletext", "dither": "bayer2",
                       "contrast_snap": 0.5, "pixel_aspect": 1.3}),
        ("phosphor_decay", {"decay": 0.4, "mode": "p22"}),
        ("crt", {"scan_strength": 0.3, "bloom": 0.35, "curvature": 0.05,
                 "glass_glow": 0.15, "vignette_crt": 0.3}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.006}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 300.0, "high_hz": 3400.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_bitcrush", {"bits": 8, "sr_hz": 8000.0, "dither": False, "mix": 1.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.6}),
        ("a_hum", {"hz": "60", "level_db": -58.0, "buzz": 0.25}),
    ],
    variants=[
        Variant("minitel-mono", "Minitel Terminal",
                "The free terminal the phone company left in the hall: one amber gun and no colour at all.",
                video={"pixel_era.palette": "none", "mono.enabled": True,
                       "phosphor_decay.mode": "amber_mono", "crt.scan_strength": 0.24}),
        Variant("ceefax-bright", "Bright Page",
                "A page set for the shop window: the colours snapped hard and the tube run too bright.",
                video={"pixel_era.contrast_snap": 0.75, "crt.scan_strength": 0.18,
                       "crt.bloom": 0.45}),
    ],
))

# nearest: microfilm-morgue-1958; differs: a radiofax line scan with HF noise streaking
# whole columns, on damp paper, with no reader glare or frame border.
register_preset(Preset(
    id="weather-fax-1975",
    name="Weather Facsimile",
    family="transmission",
    era="1975",
    desc="A satellite picture painted one line at a time onto damp paper by a drum recorder listening to shortwave: flat grays, vertical scan streaks, and every burst of static punched straight through the cloud deck.",
    tagline="APT line-scan gray, streaks, HF hiss",
    tags=("70s", "fax", "printout", "monochrome", "shortwave"),
    keywords=("weather-fax", "apt", "satellite-image", "seventies", "facsimile",
              "hf-radio", "line-scan", "gray", "meteorology", "noaa"),
    proc_height=240,
    upscale="soft",
    video=[
        ("mono", {"amount": 1.0, "response": "panchromatic", "tint": "neutral", "tint_amt": 0.0}),
        ("tone", {"contrast": 0.85, "lift": 0.12, "knee": 0.7, "pivot": 0.45}),
        ("optics", {"soft_focus": 0.25}),
        ("telecine_scan", {"pin_stability": "pin_registered", "hop_px": 0.3,
                           "scanner_stripe": 0.8}),
        ("signal_rf", {"snow": 0.15, "sparkle": 3.0, "ghost_n": 0, "ghost_alpha": 0.0,
                       "impulse_noise": 4.0}),
        ("plate", {"pack": "paper_textures", "opacity": 0.18, "blend": "multiply",
                   "cycle": "hold", "scale": 1.2, "mono": True}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.004}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 300.0, "high_hz": 2800.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_shortwave", {"hi_hz": 2800.0, "fade": 0.3, "het_db": -46.0, "sferics": 0.5,
                         "static_db": -40.0, "utility_qrm": 0.2}),
        ("a_speaker", {"device": "portable_radio_1975", "strength": 0.8}),
    ],
    variants=[
        Variant("good-copy", "Clean Copy",
                "The morning pass with the band open: the fronts are legible and the paper stayed dry.",
                video={"signal_rf.snow": 0.05, "signal_rf.impulse_noise": 1.0,
                       "telecine_scan.scanner_stripe": 0.4},
                audio={"a_shortwave.static_db": -50.0, "a_shortwave.fade": 0.15}),
        Variant("storm-copy", "Storm Copy",
                "Thunder somewhere between here and the satellite, and every strike puts a black bar through Kansas.",
                video={"signal_rf.snow": 0.3, "signal_rf.impulse_noise": 10.0,
                       "tone.contrast": 0.75, "tone.lift": 0.16},
                audio={"a_shortwave.static_db": -32.0, "a_shortwave.fade": 0.6,
                       "a_shortwave.sferics": 0.8}),
    ],
))

# nearest: bootleg-vcd-mall-1998; differs: a 2005 DivX rip with camcorder AGC pumping and
# a full auditorium on the mic, instead of MPEG-1 blocks off a hot screen centre.
register_preset(Preset(
    id="cinema-cam-bootleg-2005",
    name="Cinema Cam Bootleg",
    family="transmission",
    era="2005",
    desc="A camcorder wedged on a knee three rows back: the screen keystoned and hot in the middle, auto-gain breathing at every cut, an audience laughing over the dialogue, all squeezed into a 700 kbit DivX.",
    tagline="Keystoned screen, AGC pump, DivX, hall echo",
    tags=("00s", "camcorder", "cinema", "piracy", "mpeg4"),
    keywords=("cam", "bootleg", "telesync", "pirated", "aughts", "camcorder-in-theater",
              "divx", "keystone", "audience", "torrent", "blockbuster"),
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.03, "knee": 0.78, "pivot": 0.44}),
        ("balance", {"warmth": 0.06}),
        ("saturation", {"amount": 0.95, "vibrance": 0.05}),
        ("projection", {"shutter_flicker": 0.15, "keystone": 0.06, "ambient_lift": 0.08,
                        "screen_gain_falloff": 0.3}),
        ("screen", {"surface": "matte_white", "hotspot": 0.3, "keystone_v": 0.03,
                    "room_spill": 0.2, "shake_event": 1.0}),
        ("optics", {"distortion": 0.03, "corner_softness": 0.15, "soft_focus": 0.06}),
        ("exposure_auto", {"target": 0.4, "lag": 0.9, "overshoot": 0.3, "max_boost": 3.0,
                           "agc_gain_noise": 0.4, "wb_amount": 0.25}),
        ("chroma_dv", {"ratio": "4:2:0", "edge_sharpen": 0.3, "dct_blocks": 0.2}),
        ("codec_era", {"codec": "mpeg4", "kbps": 700, "gop": 250, "res": "480p"}),
        ("framing", {"aspect": "source", "mode": "box", "edge_soft": 0.005}),
    ],
    audio=[
        ("a_historical_mic", {"profile": "camcorder_1994", "amount": 0.8, "handling": 0.2,
                              "overload": 0.35, "self_noise_db": -48.0}),
        ("a_agc", {"target_db": -14.0, "max_gain_db": 12.0, "amount": 0.7}),
        ("a_room", {"mode": "room", "size": 3.0, "decay_s": 1.6, "mix": 0.35,
                    "damp": 0.4, "predelay_ms": 30.0}),
        ("a_codec_mp3", {"kbps": "96", "mono": True}),
        ("a_speaker", {"device": "laptop_2006", "strength": 0.5}),
    ],
    variants=[
        Variant("telesync-line-audio", "Telesync",
                "Same terrible picture, but the sound came off the assistive-listening jack, so at least you can hear it.",
                audio={"a_historical_mic.enabled": False, "a_room.mix": 0.05,
                       "a_agc.amount": 0.3, "a_codec_mp3.kbps": "128",
                       "a_codec_mp3.mono": False}),
        Variant("dvd-screener-transfer", "Screener Rip",
                "Not a cam at all: somebody's awards disc, ripped straight and uploaded under the same filename.",
                video={"projection.enabled": False, "screen.enabled": False,
                       "exposure_auto.enabled": False, "optics.distortion": 0.0,
                       "optics.corner_softness": 0.05, "codec_era.kbps": 1200},
                audio={"a_historical_mic.enabled": False, "a_room.mix": 0.04,
                       "a_agc.amount": 0.2, "a_codec_mp3.kbps": "128",
                       "a_codec_mp3.mono": False}),
    ],
))
