"""Transmission-family presets: signals in trouble between the tower and the set."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="dx-skip-1959",
    name="Sporadic-E Skip",
    family="transmission",
    era="1959",
    desc="A thousand-mile freak of the ionosphere: the picture heaves in and out of the snow, venetian bars swelling with every fade, two stations wrestling over one channel.",
    tags=("50s", "dx", "rf", "bw"),
    proc_height=450,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.25}),
        ("tone", {"contrast": 1.18, "lift": 0.07, "knee": 0.74}),
        ("ntsc", {"strength": 0.4, "rainbow": 0.08, "dot_crawl": 0.08, "phase_noise": 1.0}),
        ("rf_dx", {"fade_depth": 0.75, "fade_rate": 0.1, "noise_floor": 0.75, "co_channel": 0.55,
                   "co_delay_s": 2.0, "venetian": 0.55}),
        ("signal_rf", {"snow": 0.15, "ghost_alpha": 0.0, "impulse_noise": 1.0}),
        ("interlace", {"combing": 0.5, "twitter": 0.35}),
        ("crt", {"scan_strength": 0.3, "bloom": 0.5, "curvature": 0.22, "vignette_crt": 0.45,
                 "glass_glow": 0.2}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.12}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 180.0, "high_hz": 4500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_shortwave", {"hi_hz": 4200.0, "fade": 0.7, "het_db": -48.0, "sferics": 0.3,
                         "static_db": -40.0}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.8}),
        ("a_hum", {"hz": 60, "level_db": -42.0}),
    ],
    variants=[
        Variant("logbook-peak", "Logbook Peak", "The thirty seconds worth photographing the screen for.",
                video={"rf_dx.fade_depth": 0.45, "rf_dx.noise_floor": 0.5, "rf_dx.co_channel": 0.3},
                audio={"a_shortwave.fade": 0.45, "a_shortwave.static_db": -46.0}),
        Variant("band-closing", "Band Closing", "The skip folds up while you fumble for the camera.",
                video={"rf_dx.fade_depth": 0.9, "rf_dx.noise_floor": 0.85, "rf_dx.venetian": 0.7},
                audio={"a_shortwave.fade": 0.9, "a_shortwave.static_db": -34.0}),
    ],
))

register_preset(Preset(
    id="jammed-broadcast-1984",
    name="Jammed Channel",
    family="transmission",
    era="1984",
    desc="Somebody doesn't want you watching: dark bars roll through the picture and tear the sync where they pass, a heterodyne snarl parked on the audio like a wasp.",
    tags=("80s", "jamming", "interference"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_80s", "strength": 0.6}),
        ("tone", {"contrast": 1.06, "lift": 0.03}),
        ("ntsc", {"strength": 0.9, "phase_noise": 2.4, "rainbow": 0.3, "dot_crawl": 0.3}),
        ("jam_bars", {"amount": 0.5, "bar_size": 0.4, "roll_speed": 0.45, "tear": 0.5}),
        ("herringbone", {"amount": 0.3, "pattern": "diagonal_bars", "wavelength": 7.0,
                         "drift": 1.2}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.12, "curvature": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_am_radio", {"hi_hz": 5000.0, "static_db": -44.0, "whistle_db": -36.0, "fade": 0.2,
                        "adjacent_channel": 0.5, "pump": 0.4}),
        ("a_hum", {"hz": 60, "buzz": 0.7, "level_db": -38.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.5}),
    ],
    variants=[
        Variant("nuisance", "Mere Nuisance", "The program mostly wins.",
                video={"jam_bars.amount": 0.25, "jam_bars.tear": 0.25, "herringbone.amount": 0.15},
                audio={"a_am_radio.whistle_db": -46.0, "a_hum.level_db": -44.0}),
        Variant("denial", "Full Denial", "The jammer wins. You watch anyway, out of spite.",
                video={"jam_bars.amount": 0.85, "jam_bars.tear": 0.8, "jam_bars.roll_speed": 0.8,
                       "herringbone.amount": 0.45},
                audio={"a_am_radio.whistle_db": -30.0, "a_hum.level_db": -32.0}),
    ],
))

register_preset(Preset(
    id="pirate-uhf-1987",
    name="Pirate UHF",
    family="transmission",
    era="1987",
    desc="Forty watts from a tower-block roof: a second-generation tape through an off-spec exciter — bent sync, soft snow, a voice riding clipped and proud over the hum.",
    tags=("80s", "pirate", "uhf", "outlaw"),
    proc_height=500,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.045, "knee": 0.8}),
        ("stock", {"profile": "tube_80s", "strength": 0.55}),
        ("ntsc", {"strength": 0.95, "phase_noise": 3.2, "sync_jitter": 0.45, "rainbow": 0.3,
                  "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "generation": 2, "luma_noise": 0.45, "chroma_noise": 0.45,
                 "head_switch": 0.6, "time_base_error": 0.5, "flagging": 0.4, "dropouts": 1.0,
                 "sharpen": 0.55}),
        ("signal_rf", {"snow": 0.35, "sparkle": 2.0, "ghost_px": 12.0, "ghost_alpha": 0.15,
                       "hum_bar": 0.25, "weak_signal": 0.3}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.32, "scan_strength": 0.12, "curvature": 0.1}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 7.0, "flutter_depth": 5.0}),
        ("a_distortion", {"type": "soft", "drive": 2.2}),
        ("a_agc", {"amount": 0.8}),
        ("a_tape_hiss", {"level_db": -38.0}),
        ("a_hum", {"hz": 60, "buzz": 0.5, "level_db": -40.0}),
    ],
    variants=[
        Variant("good-night", "Antenna Luck", "Tonight the wind points your way.",
                video={"signal_rf.snow": 0.15, "signal_rf.weak_signal": 0.1,
                       "ntsc.sync_jitter": 0.25},
                audio={"a_hum.level_db": -46.0}),
        Variant("raid-scare", "Transmitter Trouble", "Either the PA stage is dying or someone's at the door.",
                video={"signal_rf.weak_signal": 0.6, "signal_rf.snow": 0.6,
                       "ntsc.sync_jitter": 0.7, "vhs.tracking_error": 0.3},
                audio={"a_distortion.drive": 3.5, "a_hum.level_db": -34.0}),
    ],
))

register_preset(Preset(
    id="microwave-remote-1978",
    name="Microwave Remote",
    family="transmission",
    era="1978",
    desc="Live from the parking lot via the mast on the truck: a decent picture that shatters into strips for a heartbeat whenever the hop flinches, the reporter squeezed through comms iron.",
    tags=("70s", "news", "remote", "microwave"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.8}),
        ("tone", {"contrast": 1.07, "lift": 0.03}),
        ("ntsc", {"strength": 0.85, "phase_noise": 2.0, "rainbow": 0.28, "dot_crawl": 0.28}),
        ("signal_rf", {"snow": 0.1, "sparkle": 2.5, "ghost_alpha": 0.0, "impulse_noise": 0.3}),
        ("microwave_hit", {"rate": 2.0, "strength": 0.85}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.1}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.07}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 200.0, "high_hz": 5000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 6.0, "threshold_db": -26.0, "attack_ms": 2.0, "makeup_db": 4.0}),
        ("a_distortion", {"type": "soft", "drive": 1.6}),
        ("a_hum", {"hz": 60, "level_db": -48.0}),
    ],
    variants=[
        Variant("storm-cell", "Storm Between Towers", "The hop flinches every few seconds.",
                video={"microwave_hit.rate": 8.0, "signal_rf.snow": 0.2,
                       "signal_rf.impulse_noise": 1.0},
                audio={"a_distortion.drive": 2.2}),
        Variant("locked-in", "Clean Hop", "Engineering got the dish aimed before air.",
                video={"microwave_hit.rate": 0.3, "signal_rf.snow": 0.05}),
    ],
))

register_preset(Preset(
    id="storm-antenna-1966",
    name="Thunderstorm Reception",
    family="transmission",
    era="1966",
    desc="The movie versus the weather: every strike lashes a line of sparks across the screen, the color AGC breathes with the sagging signal, static crashes rolling through the speaker.",
    tags=("60s", "storm", "rf", "color"),
    proc_height=500,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.8}),
        ("tone", {"contrast": 1.08, "lift": 0.05, "knee": 0.78}),
        ("saturation", {"amount": 0.95}),
        ("ntsc", {"strength": 0.95, "phase_noise": 2.6, "chroma_agc": 0.6, "diff_phase": 2.0,
                  "rainbow": 0.3, "dot_crawl": 0.3}),
        ("rf_dx", {"fade_depth": 0.35, "fade_rate": 0.18, "noise_floor": 0.45, "co_channel": 0.0,
                   "venetian": 0.15}),
        ("signal_rf", {"snow": 0.3, "ghost_px": 12.0, "ghost_alpha": 0.15, "hum_bar": 0.2,
                       "impulse_noise": 8.0}),
        ("interlace", {"combing": 0.5, "twitter": 0.3}),
        ("crt", {"scan_strength": 0.2, "bloom": 0.45, "curvature": 0.15, "vignette_crt": 0.35}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.09}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -44.0}),
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_am_radio", {"hi_hz": 6000.0, "static_db": -34.0, "fade": 0.5, "pump": 0.5,
                        "whistle_db": -60.0}),
        ("a_speaker", {"device": "tv_console_1972", "strength": 0.6}),
        ("a_hum", {"hz": 60, "level_db": -44.0}),
    ],
    variants=[
        Variant("distant-front", "Storm Still Coming", "Flickers on the horizon, crackles in the sound.",
                video={"signal_rf.impulse_noise": 2.5, "rf_dx.fade_depth": 0.2,
                       "signal_rf.snow": 0.18},
                audio={"a_am_radio.static_db": -42.0, "a_am_radio.fade": 0.3}),
        Variant("overhead", "Directly Overhead", "Between strikes you can almost see the picture.",
                video={"signal_rf.impulse_noise": 20.0, "rf_dx.fade_depth": 0.55,
                       "signal_rf.snow": 0.5, "ntsc.chroma_agc": 0.8},
                audio={"a_am_radio.static_db": -28.0, "a_am_radio.fade": 0.7}),
    ],
))
