"""VHS-family presets: consumer tape in every state of grace and decay."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="vhs-1985-sp",
    name="VHS Standard Play",
    family="vhs",
    era="1985",
    desc="A well-kept SP recording on a good deck: soft but stable, gentle chroma smear, faint tape noise. The baseline VHS truth.",
    tags=("vhs", "clean", "80s"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.02, "knee": 0.86}),
        ("stock", {"profile": "tube_80s", "strength": 0.7}),
        ("ntsc", {"strength": 0.8, "dot_crawl": 0.25, "rainbow": 0.2, "phase_noise": 1.6}),
        ("vhs", {"mode": "sp", "luma_noise": 0.35, "chroma_noise": 0.35, "head_switch": 0.5,
                 "time_base_error": 0.3, "flagging": 0.2, "dropouts": 0.15, "sharpen": 0.5}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.25, "scan_strength": 0.0}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 11000.0}),
        ("a_wow_flutter", {"wow_depth": 4.0, "flutter_depth": 3.0}),
        ("a_tape_sat", {"drive": 1.8}),
        ("a_tape_hiss", {"level_db": -48.0}),
    ],
    variants=[
        Variant("fresh", "Fresh Tape", "First playback of a new recording — minimal damage.",
                video={"vhs.dropouts": 0.05, "vhs.time_base_error": 0.2, "vhs.luma_noise": 0.25},
                audio={"a_tape_hiss.level_db": -52.0}),
        Variant("hifi", "Hi-Fi Deck", "Late-80s HiFi audio path: wider, quieter sound.",
                audio={"a_bandlimit.high_hz": 16000.0, "a_tape_hiss.level_db": -56.0,
                       "a_wow_flutter.wow_depth": 2.0}),
        Variant("worn", "Well-Loved", "Hundreds of plays: more dropouts, noise and wobble.",
                video={"vhs.dropouts": 1.2, "vhs.luma_noise": 0.55, "vhs.tracking_error": 0.15,
                       "vhs.time_base_error": 0.5},
                audio={"a_tape_hiss.level_db": -42.0, "a_wow_flutter.wow_depth": 8.0}),
    ],
))

register_preset(Preset(
    id="vhs-ep-longplay",
    name="VHS Extended Play",
    family="vhs",
    era="1987",
    desc="Six hours on a T-120: half the tape speed, twice the misery. Muddy luma, boiling chroma noise, constant low-level instability.",
    tags=("vhs", "degraded", "ep"),
    proc_height=480,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.04, "lift": 0.035, "knee": 0.82}),
        ("stock", {"profile": "tube_80s", "strength": 0.6}),
        ("ntsc", {"strength": 0.9, "dot_crawl": 0.3, "rainbow": 0.35, "phase_noise": 2.8}),
        ("vhs", {"mode": "ep", "luma_noise": 0.3, "chroma_noise": 0.28, "head_switch": 0.7,
                 "time_base_error": 0.55, "flagging": 0.35, "dropouts": 0.8, "sharpen": 0.65}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 8000.0}),
        ("a_wow_flutter", {"wow_depth": 9.0, "flutter_depth": 6.0}),
        ("a_tape_sat", {"drive": 2.2}),
        ("a_tape_hiss", {"level_db": -40.0}),
        ("a_tape_dropouts", {"rate": 3.0, "azimuth": 0.35}),
    ],
    variants=[
        Variant("slp", "SLP Nightmare", "The 8-hour mode nobody admits to using.",
                video={"vhs.luma_noise": 0.38, "vhs.chroma_noise": 0.36, "vhs.tracking_error": 0.3},
                audio={"a_tape_hiss.level_db": -36.0}),
    ],
))

register_preset(Preset(
    id="vhs-rental-1992",
    name="Rental Tape",
    family="vhs",
    era="1992",
    desc="A video-store workhorse: tracking storms, crease dropouts, a transport that takes a second to lock. Be kind, rewind.",
    tags=("vhs", "damaged", "rental"),
    proc_height=520,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.03}),
        ("stock", {"profile": "tube_80s", "strength": 0.65}),
        ("ntsc", {"strength": 0.85, "dot_crawl": 0.3, "rainbow": 0.3, "phase_noise": 2.4}),
        ("vhs", {"mode": "sp", "luma_noise": 0.5, "chroma_noise": 0.5, "head_switch": 0.65,
                 "time_base_error": 0.5, "flagging": 0.4, "dropouts": 2.2, "dropout_burst": 0.5,
                 "tracking_error": 0.25, "sharpen": 0.6}),
        ("vcr_transport", {"start_glitch": True, "start_glitch_s": 1.2, "random_glitch_rate": 1.2}),
        ("plate", {"pack": "tape_creases", "opacity": 0.3, "blend": "screen", "cycle": "shuffle_fast",
                   "gate": 0.12, "jitter": 40.0}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.28}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 10000.0}),
        ("a_wow_flutter", {"wow_depth": 7.0, "flutter_depth": 5.0}),
        ("a_tape_sat", {"drive": 2.0}),
        ("a_tape_hiss", {"level_db": -44.0}),
        ("a_tape_dropouts", {"rate": 2.0, "azimuth": 0.3}),
    ],
    variants=[
        Variant("chewed", "Chewed Tape", "The deck ate it once. It shows.",
                video={"vhs.tracking_error": 0.55, "vhs.dropouts": 4.0, "vcr_transport.random_glitch_rate": 3.0,
                       "plate.gate": 0.3},
                audio={"a_tape_dropouts.rate": 6.0, "a_wow_flutter.wow_depth": 14.0}),
        Variant("late-fee", "Ex-Rental", "Retired shelf copy — tired but watchable.",
                video={"vhs.tracking_error": 0.12, "vhs.dropouts": 1.2, "vcr_transport.random_glitch_rate": 0.5}),
    ],
))

register_preset(Preset(
    id="vhs-camcorder-1989",
    name="Shoulder Camcorder",
    family="vhs",
    era="1989",
    desc="Full-size VHS camcorder with the orange date stamp: auto-iris pumping, autofocus hunts, birthday-party ambience.",
    tags=("vhs", "camcorder", "home-video", "timestamp"),
    proc_height=560,
    upscale="soft",
    video=[
        ("exposure_auto", {}),
        ("optics", {"focus_drift": 0.3, "hunt_rate": 0.8, "corner_softness": 0.25}),
        ("tone", {"contrast": 1.05, "lift": 0.02, "knee": 0.8}),
        ("stock", {"profile": "tube_80s", "strength": 0.6}),
        ("ntsc", {"strength": 0.8, "phase_noise": 2.0, "rainbow": 0.2}),
        ("vhs", {"mode": "sp", "luma_noise": 0.45, "chroma_noise": 0.5, "head_switch": 0.55,
                 "time_base_error": 0.35, "flagging": 0.25, "dropouts": 0.4, "sharpen": 0.55}),
        ("timestamp", {"style": "camcorder_orange", "corner": "br", "date_format": "mon_d_yyyy",
                       "start": "1989-07-22 16:42:10", "glow": 0.5}),
        ("interlace", {"combing": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9500.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.6}),
        ("a_wow_flutter", {"wow_depth": 5.0, "flutter_depth": 4.0}),
        ("a_tape_hiss", {"level_db": -42.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.25}),
    ],
    variants=[
        Variant("indoors", "Birthday Party", "Tungsten light, AGC noise floor, echoing living room.",
                video={"vhs.luma_noise": 0.6},
                audio={"a_agc.amount": 0.8}),
        Variant("no-stamp", "No Timestamp", "Date display switched off.",
                video={"timestamp.opacity": 0.0}),
    ],
))

register_preset(Preset(
    id="vhs-camcorder-1996",
    name="Palmcorder",
    family="vhs",
    era="1996",
    desc="Compact VHS-C/Video8 era: tighter image, cleaner color, white date stamp, still unmistakably tape.",
    tags=("vhs", "camcorder", "90s", "timestamp"),
    proc_height=600,
    upscale="soft",
    video=[
        ("exposure_auto", {}),
        ("optics", {"focus_drift": 0.15, "hunt_rate": 0.4}),
        ("tone", {"contrast": 1.06, "knee": 0.84}),
        ("ntsc", {"strength": 0.6, "phase_noise": 1.2}),
        ("vhs", {"mode": "sp", "luma_bw": 3.4, "luma_noise": 0.3, "chroma_noise": 0.35,
                 "head_switch": 0.4, "time_base_error": 0.25, "dropouts": 0.2, "sharpen": 0.6}),
        ("timestamp", {"style": "vcr_white", "corner": "br", "date_format": "dd-mm-yyyy",
                       "start": "1996-08-04 11:03:44"}),
        ("interlace", {"combing": 0.45}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 12000.0}),
        ("a_agc", {"amount": 0.45}),
        ("a_wow_flutter", {"wow_depth": 3.0, "flutter_depth": 2.5}),
        ("a_tape_hiss", {"level_db": -48.0}),
    ],
))

register_preset(Preset(
    id="vhs-dub-generation",
    name="Dubbed Copy",
    family="vhs",
    era="1990",
    desc="A copy of a copy of a copy: every generation smears chroma further, stacks noise, and bends the top of frame a little more.",
    tags=("vhs", "generation-loss", "bootleg"),
    proc_height=520,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.08, "lift": 0.045, "knee": 0.8}),
        ("stock", {"profile": "tube_80s", "strength": 0.55}),
        ("ntsc", {"strength": 0.9, "phase_noise": 3.2, "rainbow": 0.35, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "generation": 3, "luma_noise": 0.45, "chroma_noise": 0.45,
                 "head_switch": 0.6, "time_base_error": 0.6, "flagging": 0.5, "dropouts": 1.0,
                 "sharpen": 0.7}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8500.0}),
        ("a_wow_flutter", {"wow_depth": 8.0, "flutter_depth": 6.0}),
        ("a_tape_sat", {"drive": 2.6}),
        ("a_tape_hiss", {"level_db": -38.0}),
        ("a_tape_dropouts", {"rate": 1.5, "azimuth": 0.45}),
    ],
    variants=[
        Variant("gen5", "Fifth Generation", "Traded through five hands. Barely hanging on.",
                video={"vhs.generation": 5, "vhs.chroma_noise": 0.85, "vhs.tracking_error": 0.2},
                audio={"a_tape_hiss.level_db": -33.0, "a_wow_flutter.wow_depth": 12.0}),
    ],
))

register_preset(Preset(
    id="vhs-taped-off-air-1987",
    name="Taped Off Air",
    family="vhs",
    era="1987",
    desc="A broadcast caught on tape: antenna ghosting and snow under the VHS wash, channel readout in the corner. Saturday morning, preserved.",
    tags=("vhs", "broadcast", "rf", "nostalgia"),
    proc_height=540,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.03}),
        ("stock", {"profile": "tube_80s", "strength": 0.7}),
        ("signal_rf", {"snow": 0.25, "ghost_px": 14.0, "ghost_alpha": 0.18, "hum_bar": 0.15}),
        ("ntsc", {"strength": 0.9, "dot_crawl": 0.35, "rainbow": 0.35, "phase_noise": 2.4}),
        ("vhs", {"mode": "sp", "luma_noise": 0.45, "chroma_noise": 0.5, "head_switch": 0.6,
                 "time_base_error": 0.4, "flagging": 0.3, "dropouts": 0.5}),
        ("osd", {"show_ch": True, "channel": "CH 04", "style": "green", "size": 3,
                 "show_play": False, "show_sp": False, "show_counter": False}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3, "scan_strength": 0.12}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -44.0}),
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 10000.0}),
        ("a_wow_flutter", {"wow_depth": 5.0, "flutter_depth": 4.0}),
        ("a_tape_hiss", {"level_db": -44.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
    ],
    variants=[
        Variant("uhf", "UHF Fringe", "Channel 62 from two towns over: heavy snow, drifting ghosts.",
                video={"signal_rf.snow": 0.6, "signal_rf.ghost_alpha": 0.3, "signal_rf.weak_signal": 0.5,
                       "osd.channel": "CH 62"},
                audio={"a_tv_sound.buzz_db": -38.0}),
        Variant("cable", "Cable Box", "Clean-ish cable feed — no snow, just the wash.",
                video={"signal_rf.snow": 0.03, "signal_rf.ghost_alpha": 0.05, "osd.channel": "CH 23"}),
        Variant("no-osd", "No Readout", "Channel display off.",
                video={"osd.show_ch": False}),
    ],
))

register_preset(Preset(
    id="vhs-tracking-nightmare",
    name="Bad Tracking",
    family="vhs",
    era="1991",
    desc="The tape that never locks: rolling noise bands, shredded lines, a transport fighting for its life. Adjust TRACKING. It won't help.",
    tags=("vhs", "damaged", "glitch"),
    proc_height=500,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.04}),
        ("ntsc", {"strength": 0.9, "phase_noise": 3.6}),
        ("vhs", {"mode": "sp", "luma_noise": 0.6, "chroma_noise": 0.6, "head_switch": 0.8,
                 "time_base_error": 0.7, "flagging": 0.6, "dropouts": 2.0,
                 "tracking_error": 0.6}),
        ("vcr_transport", {"start_glitch": True, "start_glitch_s": 2.0, "random_glitch_rate": 4.0}),
        ("osd", {"show_play": True, "style": "white", "size": 3,
                 "show_sp": False, "show_counter": False}),
        ("interlace", {"combing": 0.6}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9000.0}),
        ("a_wow_flutter", {"wow_depth": 16.0, "flutter_depth": 10.0}),
        ("a_tape_dropouts", {"rate": 8.0, "azimuth": 0.6}),
        ("a_tape_hiss", {"level_db": -38.0}),
    ],
))

register_preset(Preset(
    id="vhs-tape-start",
    name="Tape Start",
    family="vhs",
    era="1988",
    desc="The first seconds after PLAY: rainbow junk, a vertical roll, then the picture staggers in. For intros and reveals.",
    tags=("vhs", "transition", "glitch"),
    proc_height=540,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05}),
        ("ntsc", {"strength": 0.85, "phase_noise": 2.4}),
        ("vhs", {"mode": "sp", "luma_noise": 0.45, "chroma_noise": 0.5, "head_switch": 0.6,
                 "time_base_error": 0.4, "dropouts": 0.4}),
        ("tape_junk", {"at_start_s": 1.6, "style": "rainbow_smear"}),
        ("vcr_transport", {"start_glitch": True, "start_glitch_s": 2.2}),
        ("osd", {"show_play": True, "style": "white", "size": 3}),
        ("interlace", {"combing": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 10000.0}),
        ("a_wow_flutter", {"wow_depth": 6.0, "flutter_depth": 5.0, "start_wobble": True}),
        ("a_tape_hiss", {"level_db": -42.0}),
    ],
    variants=[
        Variant("blue", "Blue Screen Lead-in", "VCRs that mute to blue instead of static.",
                video={"tape_junk.style": "blue_screen"}),
    ],
))

register_preset(Preset(
    id="betamax-1978",
    name="Betamax",
    family="vhs",
    era="1978",
    desc="The better format that lost: slightly crisper luma than VHS, earlier-era color electronics, warm and a touch unstable.",
    tags=("betamax", "70s", "tape"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.025}),
        ("stock", {"profile": "tube_70s", "strength": 0.8}),
        ("ntsc", {"strength": 0.95, "phase_noise": 3.2, "rainbow": 0.35, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "luma_bw": 3.2, "chroma_bw": 0.4, "luma_noise": 0.4,
                 "chroma_noise": 0.55, "head_switch": 0.5, "time_base_error": 0.45,
                 "flagging": 0.35, "dropouts": 0.5, "sharpen": 0.4}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 9000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 6.0, "flutter_depth": 5.0}),
        ("a_tape_sat", {"drive": 2.0}),
        ("a_tape_hiss", {"level_db": -42.0}),
    ],
))

register_preset(Preset(
    id="umatic-news-1982",
    name="U-matic Field Tape",
    family="vhs",
    era="1982",
    desc="Broadcast ¾-inch tape from a news van: professional bandwidth, still analog to the bone, with the ENG look of a thousand local stories.",
    tags=("umatic", "broadcast", "news"),
    proc_height=600,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.08, "lift": 0.02}),
        ("stock", {"profile": "tube_70s", "strength": 0.7}),
        ("ntsc", {"strength": 0.8, "phase_noise": 1.6, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "luma_bw": 4.0, "chroma_bw": 0.6, "luma_noise": 0.3,
                 "chroma_noise": 0.35, "head_switch": 0.35, "time_base_error": 0.25,
                 "dropouts": 0.3, "sharpen": 0.55}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.22}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 12000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_tape_hiss", {"level_db": -46.0}),
    ],
))
