"""VHS-family presets, second wave: rival tape formats, pro decks and trade copies."""

from ..engine.presets import Preset, Variant, register_preset

register_preset(Preset(
    id="pal-vhs-1988",
    name="PAL VHS",
    family="vhs",
    era="1988",
    desc="The European tape: 50 fields of Hanover-bar calm — hue that never twists, color softly averaged line to line, and a mains hum a note lower than you remember.",
    tagline="Stable hue, averaged color, 50 Hz hum",
    tags=("vhs", "pal", "80s"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.05, "lift": 0.025, "knee": 0.85}),
        ("stock", {"profile": "tube_80s", "strength": 0.65}),
        ("ntsc", {"system": "pal", "strength": 0.85, "luma_bw": 5.0, "chroma_bw": 1.1,
                  "rainbow": 0.2, "dot_crawl": 0.25}),
        ("vhs", {"mode": "sp", "luma_noise": 0.35, "chroma_noise": 0.35, "head_switch": 0.5,
                 "time_base_error": 0.3, "flagging": 0.2, "dropouts": 0.3, "sharpen": 0.45}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.28}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 11000.0}),
        ("a_wow_flutter", {"wow_depth": 4.0, "flutter_depth": 3.5}),
        ("a_tape_sat", {"drive": 1.8}),
        ("a_tape_hiss", {"level_db": -46.0}),
        ("a_hum", {"hz": 50, "level_db": -52.0}),
    ],
    variants=[
        Variant("lp", "PAL Long Play", "Four hours on an E-240: softer still, noisier, prouder.",
                video={"vhs.mode": "lp", "vhs.luma_noise": 0.28, "vhs.chroma_noise": 0.26,
                       "vhs.dropouts": 0.8},
                audio={"a_tape_hiss.level_db": -42.0, "a_wow_flutter.wow_depth": 7.0}),
        Variant("worn", "Lending-Library Copy", "Passed around the cul-de-sac for a decade.",
                video={"vhs.dropouts": 1.5, "vhs.tracking_error": 0.2, "vhs.time_base_error": 0.5},
                audio={"a_tape_hiss.level_db": -40.0, "a_wow_flutter.wow_depth": 9.0}),
    ],
))

register_preset(Preset(
    id="svhs-1992",
    name="S-VHS",
    family="vhs",
    era="1992",
    desc="The prosumer flex: 400 lines of luma down an S-video cable, color still color-under mush, FM sparkle ticking on the hardest edges.",
    tagline="400 lines of luma, color-under mush",
    tags=("svhs", "90s", "prosumer"),
    proc_height=620,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.015, "knee": 0.86}),
        ("ntsc", {"strength": 0.35, "phase_noise": 0.8, "rainbow": 0.1, "dot_crawl": 0.1,
                  "comb_mode": "comb_2d_adaptive"}),
        ("vhs", {"mode": "sp", "luma_bw": 5.0, "chroma_bw": 0.5, "luma_noise": 0.22,
                 "chroma_noise": 0.3, "head_switch": 0.4, "time_base_error": 0.2,
                 "flagging": 0.1, "dropouts": 0.25, "sharpen": 0.55, "fm_sparkle": 0.25}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.2}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 40.0, "high_hz": 15000.0}),
        ("a_wow_flutter", {"wow_depth": 2.5, "flutter_depth": 2.0}),
        ("a_tape_sat", {"drive": 1.5}),
        ("a_tape_hiss", {"level_db": -54.0}),
    ],
    variants=[
        Variant("composite-out", "Composite Cable", "Hooked up with the yellow plug anyway.",
                video={"ntsc.strength": 0.85, "ntsc.dot_crawl": 0.3, "ntsc.rainbow": 0.3}),
        Variant("et-mode", "S-VHS-ET", "Squeezing S-VHS onto a standard tape: sparklier, twitchier.",
                video={"vhs.fm_sparkle": 0.5, "vhs.luma_noise": 0.32, "vhs.dropouts": 0.8}),
    ],
))

register_preset(Preset(
    id="video8-holiday-1990",
    name="Video8 Holiday",
    family="vhs",
    era="1990",
    desc="A palm-size Handycam at the shore: tighter luma than VHS, a hair of azimuth shimmer on the detail, AFM sound that almost keeps up with the gulls.",
    tagline="Azimuth shimmer, AFM sound, gray date",
    tags=("video8", "camcorder", "90s", "home-video"),
    proc_height=560,
    upscale="soft",
    video=[
        ("exposure_auto", {"lag": 0.7, "overshoot": 0.25, "wb_amount": 0.3}),
        ("optics", {"corner_softness": 0.2, "focus_drift": 0.15, "hunt_rate": 0.5}),
        ("tone", {"contrast": 1.06, "knee": 0.84}),
        ("ntsc", {"strength": 0.7, "phase_noise": 1.4, "rainbow": 0.2}),
        ("vhs", {"mode": "sp", "luma_bw": 3.6, "luma_noise": 0.3, "chroma_noise": 0.35,
                 "head_switch": 0.35, "time_base_error": 0.25, "flagging": 0.15,
                 "dropouts": 0.5, "sharpen": 0.5, "azimuth_error": 0.15}),
        ("timestamp", {"style": "lcd_gray", "corner": "br", "date_format": "mon_d_yyyy",
                       "start": "1990-08-12 10:17:23", "glow": 0.3}),
        ("interlace", {"combing": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 13000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.55}),
        ("a_wow_flutter", {"wow_depth": 3.0, "flutter_depth": 2.5}),
        ("a_tape_hiss", {"level_db": -50.0}),
    ],
    variants=[
        Variant("no-stamp", "No Date", "Display switched off before the flight.",
                video={"timestamp.opacity": 0.0}),
        Variant("glovebox", "Glovebox Tape", "Two summers in a hot car: shimmer becomes smear.",
                video={"vhs.azimuth_error": 0.45, "vhs.dropouts": 2.0, "vhs.luma_noise": 0.45},
                audio={"a_tape_hiss.level_db": -42.0, "a_wow_flutter.wow_depth": 7.0}),
    ],
))

register_preset(Preset(
    id="wedding-master-1991",
    name="Wedding Master",
    family="vhs",
    era="1991",
    desc="The videographer's S-VHS master: Pro-Mist dove-white gowns shouldering softly into tape white-clip, and the wireless lav dropping out during the vows.",
    tagline="Pro-Mist gowns clipping, lav dropouts",
    tags=("svhs", "wedding", "90s", "pro-am"),
    proc_height=600,
    upscale="soft",
    video=[
        ("balance", {"warmth": 0.12, "high_tint": "cream", "high_amt": 0.25}),
        ("tone", {"contrast": 1.04, "lift": 0.02, "knee": 0.8}),
        ("optics", {"diffusion": 0.35, "soft_focus": 0.08}),
        ("ntsc", {"strength": 0.45, "phase_noise": 1.0, "rainbow": 0.12, "dot_crawl": 0.12}),
        ("vhs", {"mode": "sp", "luma_bw": 4.6, "chroma_bw": 0.5, "luma_noise": 0.22,
                 "chroma_noise": 0.28, "head_switch": 0.35, "time_base_error": 0.2,
                 "flagging": 0.1, "dropouts": 0.3, "sharpen": 0.4, "white_clip": 0.92}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.35, "bloom_radius": 14.0}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 70.0, "high_hz": 12000.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_tape_dropouts", {"rate": 2.0, "depth_db": 22.0}),
        ("a_tape_hiss", {"level_db": -50.0}),
        ("a_room", {"size": 1.3, "decay_s": 0.9, "mix": 0.16, "damp": 0.6}),
    ],
    variants=[
        Variant("reception", "The Reception", "Hall echo, hot PA, the lav under a jacket.",
                video={"vhs.luma_noise": 0.3},
                audio={"a_room.mix": 0.28, "a_room.decay_s": 1.2, "a_compressor.ratio": 5.0,
                       "a_tape_dropouts.rate": 4.0}),
        Variant("grandma-dub", "Copy for Grandma", "Dubbed to standard VHS on the kitchen VCR.",
                video={"vhs.generation": 2, "vhs.luma_bw": 3.0, "vhs.luma_noise": 0.4,
                       "vhs.chroma_noise": 0.45, "ntsc.strength": 0.8},
                audio={"a_tape_hiss.level_db": -42.0}),
    ],
))

register_preset(Preset(
    id="skate-hi8-1996",
    name="Skate Hi8",
    family="vhs",
    era="1996",
    desc="Fisheye at ankle height: barrel-bent curbs, auto-iris slamming between sun and shade, and a dubbed-hot soundtrack compressed until it stops apologizing.",
    tagline="Fisheye barrel, iris slam, crushed mix",
    tags=("hi8", "90s", "skate", "camcorder"),
    proc_height=560,
    upscale="soft",
    video=[
        ("optics", {"distortion": 0.22, "corner_softness": 0.3, "chromatic_aberration": 1.0}),
        ("exposure_auto", {"lag": 0.45, "overshoot": 0.5, "agc_gain_noise": 0.6, "iris_step": 0.4}),
        ("tone", {"contrast": 1.1, "knee": 0.82}),
        ("ntsc", {"strength": 0.6, "phase_noise": 1.4}),
        ("vhs", {"mode": "sp", "luma_bw": 3.8, "luma_noise": 0.4, "chroma_noise": 0.4,
                 "head_switch": 0.45, "time_base_error": 0.3, "flagging": 0.15,
                 "dropouts": 0.8, "sharpen": 0.6, "azimuth_error": 0.1}),
        ("interlace", {"combing": 0.55}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 12000.0}),
        ("a_tape_sat", {"drive": 3.0}),
        ("a_compressor", {"ratio": 8.0, "threshold_db": -22.0, "attack_ms": 2.0, "makeup_db": 4.0}),
        ("a_speaker", {"device": "boombox_1985", "strength": 0.35}),
        ("a_tape_hiss", {"level_db": -44.0}),
    ],
    variants=[
        Variant("curb-bite", "Curb Bite", "The camera has hit the ground more than once.",
                video={"vhs.skew_tear": 0.35, "vhs.dropouts": 2.5, "vhs.tracking_error": 0.2},
                audio={"a_tape_hiss.level_db": -40.0}),
        Variant("dusk-session", "Dusk Session", "Last tries under sodium lights: gain noise city.",
                video={"exposure_auto.max_boost": 6.0, "vhs.luma_noise": 0.55,
                       "tone.exposure": -0.3}),
    ],
))

register_preset(Preset(
    id="camcorder-slp-1999",
    name="VHS-C at SLP",
    family="vhs",
    era="1999",
    desc="The last tape in the bag on the slowest speed: mud-luma, skew tears off the top, chroma sitting two lines low — recorded on one deck, played on its enemy.",
    tagline="Mud luma, skew tears, chroma sitting low",
    tags=("vhs-c", "90s", "ep", "degraded"),
    proc_height=480,
    upscale="soft",
    video=[
        ("exposure_auto", {"lag": 0.8, "agc_gain_noise": 0.5}),
        ("tone", {"contrast": 1.03, "lift": 0.04, "knee": 0.8}),
        ("ntsc", {"strength": 0.8, "phase_noise": 2.4, "rainbow": 0.3}),
        ("vhs", {"mode": "ep", "luma_noise": 0.28, "chroma_noise": 0.24, "head_switch": 0.7,
                 "time_base_error": 0.5, "flagging": 0.35, "dropouts": 1.2, "sharpen": 0.6,
                 "interchange": 0.5, "skew_tear": 0.3}),
        ("timestamp", {"style": "lcd_gray", "corner": "br", "date_format": "dd-mm-yyyy",
                       "start": "1999-12-31 21:44:07"}),
        ("interlace", {"combing": 0.5}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.6}),
        ("a_wow_flutter", {"wow_depth": 9.0, "flutter_depth": 7.0, "cogging": 0.3}),
        ("a_tape_hiss", {"level_db": -40.0}),
        ("a_bed", {"bed": "vcr_transport", "level_db": -40.0, "duck": 0.4}),
    ],
    variants=[
        Variant("eaten", "Nearly Eaten", "The loading mechanism had opinions.",
                video={"vhs.skew_tear": 0.7, "vhs.tracking_error": 0.4, "vhs.dropouts": 4.0},
                audio={"a_wow_flutter.wow_depth": 16.0, "a_tape_hiss.level_db": -36.0}),
    ],
))

register_preset(Preset(
    id="laserdisc-1985",
    name="LaserDisc",
    family="vhs",
    era="1985",
    desc="Composite on its best behavior: no tape noise anywhere, just subcarrier dots crawling the edges of saturated color and a faint rainbow on fine detail. The videophile's paradox.",
    tagline="Crawling dots, zero tape noise",
    tags=("laserdisc", "80s", "clean", "composite"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.07, "lift": 0.01, "knee": 0.88}),
        ("saturation", {"amount": 1.06}),
        ("ntsc", {"strength": 0.95, "luma_bw": 4.4, "chroma_bw": 1.2, "phase_noise": 0.4,
                  "rainbow": 0.3, "dot_crawl": 0.5, "comb_mode": "comb_1line", "fringing": 0.6}),
        ("signal_rf", {"snow": 0.02, "ghost_alpha": 0.0, "impulse_noise": 0.0}),
        ("interlace", {"combing": 0.5, "twitter": 0.3}),
        ("crt", {"bloom": 0.22, "scan_strength": 0.08, "misconvergence": 0.4}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 30.0, "high_hz": 16000.0}),
        ("a_tape_hiss", {"level_db": -58.0, "type": "reel_15ips"}),
        ("a_compressor", {"ratio": 1.8}),
        ("a_cd_skip", {"rate": 0.0}),
    ],
    variants=[
        Variant("rot", "Laser Rot", "The pressing plant's glue betrays you: colored speckle storms.",
                video={"signal_rf.snow": 0.1, "signal_rf.impulse_noise": 5.0,
                       "ntsc.phase_noise": 1.2},
                audio={"a_cd_skip.rate": 3.0, "a_tape_hiss.level_db": -50.0}),
        Variant("reference", "Reference Pressing", "First play of a mint disc on a calibrated rig.",
                video={"ntsc.phase_noise": 0.2, "signal_rf.snow": 0.01, "crt.misconvergence": 0.2},
                audio={"a_tape_hiss.level_db": -64.0}),
    ],
))

register_preset(Preset(
    id="ced-videodisc-1983",
    name="CED VideoDisc",
    family="vhs",
    era="1983",
    desc="RCA's needle-in-a-caddy gamble: a steady composite picture until the stylus rides a worn groove — streaks, a stutter back, and the picture clears its throat.",
    tagline="Stylus streaks, stutter back a beat",
    tags=("ced", "80s", "videodisc"),
    proc_height=520,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.06, "lift": 0.02}),
        ("stock", {"profile": "tube_80s", "strength": 0.6}),
        ("ntsc", {"strength": 0.9, "phase_noise": 1.6, "rainbow": 0.3, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "luma_bw": 3.0, "chroma_bw": 0.5, "luma_noise": 0.3,
                 "chroma_noise": 0.3, "head_switch": 0.0, "flagging": 0.0, "jitter_v": 0.1,
                 "time_base_error": 0.25, "dropouts": 3.0, "dropout_burst": 0.5, "sharpen": 0.4}),
        ("vcr_transport", {"random_glitch_rate": 2.5}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.28}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 14000.0}),
        ("a_needle", {"skip_rate": 1.5}),
        ("a_tape_hiss", {"level_db": -50.0}),
        ("a_hum", {"hz": 60, "level_db": -54.0}),
    ],
    variants=[
        Variant("fifty-plays", "Fifty Plays In", "The groove is a suggestion now.",
                video={"vcr_transport.random_glitch_rate": 6.0, "vhs.dropouts": 8.0,
                       "vhs.luma_noise": 0.45},
                audio={"a_needle.skip_rate": 5.0, "a_tape_hiss.level_db": -44.0}),
    ],
))

register_preset(Preset(
    id="pixelvision-1989",
    name="PXL2000",
    family="vhs",
    era="1989",
    desc="Fisher-Price's audio-cassette camcorder: ninety lines of smeared charcoal-and-chalk, motion trailing like wet ink, the sound living on the same cassette as the picture.",
    tagline="90-line charcoal pixels",
    tags=("pixelvision", "80s", "bw", "toy", "lofi"),
    upscale="soft",
    video=[
        ("mono", {"response": "modern", "tint": "neutral", "tint_amt": 0.0}),
        ("tone", {"contrast": 1.3, "lift": 0.08, "knee": 0.72, "gamma": 0.95, "exposure": 0.2}),
        ("cadence", {"pattern": "twos"}),
        ("phosphor_decay", {"decay": 0.45, "mode": "p22"}),
        ("pixel_era", {"res_h": 90, "palette": "none", "dither": "none", "contrast_snap": 0.15,
                       "pixel_aspect": 1.1}),
        ("vhs", {"mode": "sp", "luma_bw": 1.8, "chroma_bw": 0.3, "luma_noise": 0.32,
                 "chroma_noise": 0.0, "head_switch": 0.0, "flagging": 0.0, "jitter_v": 0.15,
                 "time_base_error": 0.2, "dropouts": 0.8, "sharpen": 0.15}),
        ("framing", {"aspect": "4:3", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 250.0, "high_hz": 3800.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.8}),
        ("a_wow_flutter", {"wow_depth": 12.0, "flutter_depth": 9.0, "scrape": 0.4}),
        ("a_tape_sat", {"drive": 3.5}),
        ("a_tape_hiss", {"level_db": -34.0, "type": "dictaphone"}),
    ],
    variants=[
        Variant("art-school", "Art-School Transfer", "Projected at a gallery: softer, moodier.",
                video={"tone.contrast": 1.2, "phosphor_decay.decay": 0.55, "vhs.luma_noise": 0.25}),
        Variant("dying-batteries", "Dying Batteries", "Four AAs from the remote: the transport sags.",
                video={"vhs.time_base_error": 0.5, "vhs.dropouts": 3.0, "vhs.luma_noise": 0.45},
                audio={"a_wow_flutter.wow_depth": 22.0, "a_wow_flutter.start_wobble": True}),
    ],
))

register_preset(Preset(
    id="betacam-eng-1989",
    name="Betacam ENG",
    family="vhs",
    era="1989",
    desc="The news crew's component workhorse: crisp, controlled, colors staying in their lanes — broadcast discipline a full head above consumer tape.",
    tagline="Crisp component color, staying in lane",
    tags=("betacam", "80s", "broadcast", "news"),
    proc_height=620,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.08, "lift": 0.015, "knee": 0.85}),
        ("ntsc", {"strength": 0.3, "phase_noise": 0.8, "rainbow": 0.08, "dot_crawl": 0.1}),
        ("vhs", {"mode": "sp", "luma_bw": 4.8, "chroma_bw": 0.8, "luma_noise": 0.15,
                 "chroma_noise": 0.18, "head_switch": 0.0, "flagging": 0.0, "jitter_v": 0.05,
                 "time_base_error": 0.1, "dropouts": 0.15, "sharpen": 0.6}),
        ("interlace", {"combing": 0.55}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 14000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_agc", {"amount": 0.3}),
        ("a_tape_hiss", {"level_db": -52.0}),
    ],
    variants=[
        Variant("field-worn", "Field-Worn Cassette", "Recycled stock from the tape closet.",
                video={"vhs.dropouts": 1.2, "vhs.luma_noise": 0.28, "vhs.tracking_error": 0.08},
                audio={"a_tape_hiss.level_db": -46.0}),
    ],
))

register_preset(Preset(
    id="tape-swap-4th-gen-1994",
    name="Fansub Fourth Gen",
    family="vhs",
    era="1994",
    desc="Mail-traded anime four VCRs deep: chroma bleeding past its lines, the top of frame flagging like a pennant, hiss like weather — and you watched every episode anyway.",
    tagline="Chroma past the lines, flagging, hiss",
    tags=("vhs", "generation-loss", "fansub", "90s"),
    proc_height=500,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.09, "lift": 0.05, "knee": 0.78}),
        ("stock", {"profile": "tube_80s", "strength": 0.5}),
        ("ntsc", {"strength": 0.9, "phase_noise": 3.5, "rainbow": 0.35, "dot_crawl": 0.3}),
        ("vhs", {"mode": "sp", "generation": 4, "luma_noise": 0.55, "chroma_noise": 0.55,
                 "head_switch": 0.65, "time_base_error": 0.6, "flagging": 0.5,
                 "dropouts": 1.5, "sharpen": 0.7, "interchange": 0.5, "tracking_error": 0.2}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 8000.0}),
        ("a_wow_flutter", {"wow_depth": 10.0, "flutter_depth": 7.0}),
        ("a_tape_sat", {"drive": 2.8}),
        ("a_tape_dropouts", {"rate": 3.0, "azimuth": 0.5}),
        ("a_tape_hiss", {"level_db": -36.0}),
        ("a_bed", {"bed": "vcr_transport", "level_db": -42.0, "duck": 0.4}),
    ],
    variants=[
        Variant("second-gen", "Second Gen", "Straight from the club's master: almost respectable.",
                video={"vhs.generation": 2, "vhs.luma_noise": 0.4, "vhs.chroma_noise": 0.4,
                       "vhs.interchange": 0.2, "vhs.tracking_error": 0.05},
                audio={"a_tape_hiss.level_db": -44.0, "a_tape_dropouts.rate": 1.0}),
        Variant("sixth-gen", "The Copy of the Copy", "Traded past the point of legibility.",
                video={"vhs.generation": 5, "vhs.luma_noise": 0.65, "vhs.chroma_noise": 0.6,
                       "vhs.tracking_error": 0.4, "ntsc.phase_noise": 4.5},
                audio={"a_tape_hiss.level_db": -32.0, "a_wow_flutter.wow_depth": 15.0}),
    ],
))

register_preset(Preset(
    id="late-night-timer-rec-1987",
    name="Timer Recording",
    family="vhs",
    era="1987",
    desc="The VCR woke at 2 AM to tape it for you, half a tracking notch off: EP fog, a hum bar strolling up the picture, the show caught but never quite held.",
    tagline="EP fog with a hum bar strolling up",
    tags=("vhs", "ep", "off-air", "80s"),
    proc_height=480,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.04, "lift": 0.04, "knee": 0.8}),
        ("stock", {"profile": "tube_80s", "strength": 0.6}),
        ("signal_rf", {"snow": 0.18, "ghost_px": 12.0, "ghost_alpha": 0.14, "hum_bar": 0.3,
                       "hum_speed": 0.08}),
        ("ntsc", {"strength": 0.9, "phase_noise": 2.6, "rainbow": 0.3, "dot_crawl": 0.3}),
        ("vhs", {"mode": "ep", "luma_noise": 0.3, "chroma_noise": 0.26, "head_switch": 0.7,
                 "time_base_error": 0.5, "flagging": 0.35, "dropouts": 1.0,
                 "tracking_error": 0.35, "sharpen": 0.6}),
        ("interlace", {"combing": 0.5}),
        ("crt", {"bloom": 0.3}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -42.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 7500.0}),
        ("a_wow_flutter", {"wow_depth": 8.0, "flutter_depth": 6.0}),
        ("a_tape_hiss", {"level_db": -40.0}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.4}),
        ("a_bed", {"bed": "vcr_transport", "level_db": -42.0, "duck": 0.5}),
    ],
    variants=[
        Variant("three-am", "The 3 AM Movie", "Fringe reception and a tape on its ninth reuse.",
                video={"signal_rf.snow": 0.35, "signal_rf.weak_signal": 0.3,
                       "vhs.tracking_error": 0.5, "vhs.dropouts": 2.5},
                audio={"a_tape_hiss.level_db": -36.0, "a_tv_sound.buzz_db": -38.0}),
    ],
))
