"""Genre & world-cinema presets: era looks led by stock, grade and print character."""

from ..engine.presets import Preset, Variant, register_preset


def _film_audio(hi=7000.0, cell=-50.0, rolloff="feature_1940s", ratio=3.5):
    return [
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": hi}),
        ("a_mono", {"amount": 1.0}),
        ("a_optical_track", {"cell_noise": cell, "academy_rolloff": rolloff}),
        ("a_compressor", {"ratio": ratio}),
    ]


register_preset(Preset(
    id="giallo-1972",
    name="Giallo Thriller",
    family="world",
    era="1972",
    desc="Italian thriller Technicolor: venomous saturated primaries, hard shadows, a print that seems lit by gel and dread.",
    tagline="Venomous primaries, hard teal shadows",
    tags=("italy", "70s", "genre"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "technicolor3", "strength": 0.75}),
        ("tone", {"contrast": 1.22, "lift": 0.02, "knee": 0.8, "pivot": 0.4}),
        ("saturation", {"amount": 1.22, "vibrance": 0.2}),
        ("balance", {"shadow_tint": "teal", "shadow_amt": 0.25}),
        ("grain", {"amount": 0.42, "size": 2.0, "chroma_grain": 0.18}),
        ("halation", {"strength": 0.35, "tint": "red"}),
        ("gate_weave", {"amount": 1.0}),
        ("dust", {"density": 0.4}),
        ("vignette", {"amount": 0.42, "softness": 0.6}),
    ],
    audio=_film_audio(hi=8000.0, ratio=4.0),
))

register_preset(Preset(
    id="soviet-color-1975",
    name="Soviet Color Film",
    family="world",
    era="1975",
    desc="Svema/ORWO stock behind the curtain: muted cyan-leaning color, gentle contrast, an austere and beautiful drabness.",
    tagline="Muted cyan-leaning drab, green shadows",
    tags=("ussr", "70s", "orwo"),
    video=[
        ("stock", {"profile": "orwo_east", "strength": 1.0}),
        ("tone", {"contrast": 1.06, "lift": 0.05, "knee": 0.82}),
        ("saturation", {"amount": 0.88}),
        ("balance", {"warmth": -0.08, "shadow_tint": "green", "shadow_amt": 0.2}),
        ("grain", {"amount": 0.5, "size": 2.4, "chroma_grain": 0.2, "stock": "doc_16"}),
        ("halation", {"strength": 0.22, "tint": "orange"}),
        ("gate_weave", {"amount": 1.3}),
        ("flicker", {"amount": 0.14}),
        ("dust", {"density": 0.6, "hairs": 0.3}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=_film_audio(hi=6500.0, cell=-46.0, rolloff="classroom_16mm"),
))

register_preset(Preset(
    id="bollywood-1969",
    name="Bombay Technicolor",
    family="world",
    era="1969",
    desc="Eastmancolor spectacle with a decade of tropical storage: blazing saturation up top, magenta creeping into the shadows.",
    tagline="Blazing saturation, magenta shadows",
    tags=("india", "60s", "musical"),
    video=[
        ("stock", {"profile": "technicolor3", "strength": 0.7}),
        ("tone", {"contrast": 1.14, "lift": 0.04, "knee": 0.78}),
        ("saturation", {"amount": 1.18}),
        ("fade", {"amount": 0.3, "profile": "eastman_pink", "bloom_whites": 0.35}),
        ("grain", {"amount": 0.48, "size": 2.2, "chroma_grain": 0.2}),
        ("halation", {"strength": 0.32, "tint": "orange"}),
        ("gate_weave", {"amount": 1.4}),
        ("flicker", {"amount": 0.16}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("scratches", {"count": 3, "transient_rate": 1.0}),
        ("vignette", {"amount": 0.35}),
    ],
    audio=_film_audio(hi=6000.0, cell=-44.0, rolloff="classroom_16mm", ratio=4.5),
))

register_preset(Preset(
    id="hk-action-1988",
    name="Hong Kong Action Print",
    family="world",
    era="1988",
    desc="A hard-run 35mm action print: hot contrast, slightly lifted blacks, dye fade licking the edges - pure midnight-screening energy.",
    tagline="Pushed contrast, lifted blacks, splices",
    tags=("hongkong", "80s", "action"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_70s", "strength": 0.7}),
        ("tone", {"contrast": 1.2, "lift": 0.05, "knee": 0.76, "pivot": 0.42}),
        ("saturation", {"amount": 1.1}),
        ("fade", {"amount": 0.22, "profile": "cyan_loss"}),
        ("grain", {"amount": 0.45, "size": 2.1, "chroma_grain": 0.2, "stock": "push_process"}),
        ("halation", {"strength": 0.3, "tint": "red_orange"}),
        ("gate_weave", {"amount": 1.2, "splice_bump": 1.5}),
        ("dust", {"density": 0.8, "hairs": 0.4}),
        ("scratches", {"count": 4, "transient_rate": 1.5}),
        ("frame_damage", {"splice_skip_rate": 1.5}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=_film_audio(hi=8000.0, cell=-46.0, ratio=4.0),
))

register_preset(Preset(
    id="mexico-golden-1948",
    name="Época de Oro",
    family="world",
    era="1948",
    desc="Golden-age Mexican cinema: silvery panchromatic glamour, deep romantic blacks, halation like moonlight on tequila.",
    tagline="Silvery glamour, moonlight halation",
    tags=("mexico", "40s", "bw"),
    upscale="sharp",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.25}),
        ("tone", {"contrast": 1.24, "lift": 0.02, "knee": 0.8}),
        ("grain", {"amount": 0.42, "size": 1.9, "chroma_grain": 0.0, "stock": "fine_35"}),
        ("halation", {"strength": 0.45, "tint": "neutral", "threshold": 0.74}),
        ("gate_weave", {"amount": 1.1}),
        ("flicker", {"amount": 0.12}),
        ("dust", {"density": 0.5}),
        ("vignette", {"amount": 0.4, "softness": 0.65}),
    ],
    audio=_film_audio(hi=6800.0, ratio=4.0),
))

register_preset(Preset(
    id="nouvelle-vague-1962",
    name="Nouvelle Vague",
    family="world",
    era="1962",
    desc="Handheld Paris on fast B&W stock: pushed grain, natural light contrast, jump-cut nervous energy in the gate.",
    tagline="Pushed grain, daylight contrast, weave",
    tags=("france", "60s", "bw"),
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.16, "lift": 0.04, "knee": 0.82}),
        ("grain", {"amount": 0.55, "size": 2.3, "chroma_grain": 0.0, "stock": "push_process"}),
        ("halation", {"strength": 0.25, "tint": "neutral"}),
        ("gate_weave", {"amount": 1.8}),
        ("flicker", {"amount": 0.12}),
        ("dust", {"density": 0.45}),
        ("vignette", {"amount": 0.25}),
    ],
    audio=_film_audio(hi=7500.0, cell=-52.0),
))

register_preset(Preset(
    id="tokyo-spectacle-1962",
    name="Tokyo Spectacle Print",
    family="world",
    era="1962",
    desc="Tokyo-studio Eastmancolor: cyan sky, emerald sets and crimson costumes printed through soft optical mattes, then worn into a magenta-leaning television survivor.",
    tagline="Cyan sky, crimson dye, soft mattes",
    tags=("japan", "60s", "eastmancolor", "genre", "tokusatsu"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "eastman_60s", "strength": 0.95}),
        ("tone", {"contrast": 1.23, "lift": 0.015, "knee": 0.76, "pivot": 0.42}),
        ("balance", {"warmth": 0.14, "tint": 0.05, "shadow_tint": "blue", "shadow_amt": 0.3,
                     "high_tint": "yellow", "high_amt": 0.18}),
        ("saturation", {"amount": 1.16, "vibrance": 0.22}),
        ("optics", {"soft_focus": 0.16, "diffusion": 0.12, "corner_softness": 0.14,
                    "focus_drift": 0.12, "veiling_flare": 0.18}),
        ("optical_composite", {"softness": 0.2, "matte_line": 0.28, "registration": 0.35,
                               "layer_haze": 0.12, "density_breath": 0.3}),
        ("grain", {"amount": 0.4, "size": 1.9, "chroma_grain": 0.2, "stock": "fine_35",
                   "layers": "print_from_neg", "mottle": 0.15}),
        ("halation", {"strength": 0.38, "tint": "red_orange", "threshold": 0.7}),
        ("print_char", {"contrast_buildup": 1, "dmax_breath": 0.35, "acutance": 0.25}),
        ("fade", {"amount": 0.12, "profile": "eastman_pink", "bloom_whites": 0.18}),
        ("gate_weave", {"amount": 1.1, "splice_bump": 1.0}),
        ("flicker", {"amount": 0.14, "color_flicker": 0.12, "spatial": 0.2}),
        ("dust", {"density": 0.55, "hairs": 0.3}),
        ("scratches", {"count": 2, "transient_rate": 0.8}),
        ("frame_damage", {"splice_skip_rate": 0.8}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.25}),
        ("ntsc", {"strength": 0.28, "luma_bw": 4.8, "chroma_bw": 1.0,
                  "phase_noise": 1.2, "rainbow": 0.12, "dot_crawl": 0.1,
                  "chroma_agc": 0.1}),
        ("vignette", {"amount": 0.28, "softness": 0.68, "roundness": 0.65}),
        ("framing", {"aspect": "2.35", "mode": "box"}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 90.0, "high_hz": 7200.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_room", {"size": 1.4, "decay_s": 0.85, "mix": 0.16, "mode": "chamber"}),
        ("a_optical_track", {"low_hz": 100.0, "high_hz": 6500.0, "academy_rolloff": "none",
                             "cell_noise": -42.0, "flutter": 0.65, "drive": 1.8}),
        ("a_compressor", {"threshold_db": -22.0, "ratio": 5.0, "attack_ms": 5.0,
                          "release_ms": 180.0}),
    ],
    variants=[
        Variant("miniature-stage", "Miniature Stage", "The composite-heavy effects reel: softer model depth, brighter matte seams and heavier print breathing.",
                video={"optical_composite.softness": 0.42, "optical_composite.matte_line": 0.65,
                       "optical_composite.registration": 0.85, "optical_composite.layer_haze": 0.24,
                       "optics.focus_drift": 0.24, "grain.amount": 0.45}),
        Variant("swordplay-stage", "Swordplay Stage", "Cleaner mattes, amber tungsten and a slightly roomier optical mono track for the studio duel.",
                video={"balance.warmth": 0.24, "saturation.amount": 1.08,
                       "optical_composite.matte_line": 0.12, "optical_composite.registration": 0.12,
                       "ntsc.strength": 0.12},
                audio={"a_room.mix": 0.2}),
        Variant("television-transfer", "Television Transfer", "The 4:3 station element: softer bandwidth, stronger hue drift and another decade in the can.",
                video={"framing.aspect": "4:3", "ntsc.strength": 0.6, "ntsc.phase_noise": 2.4,
                       "ntsc.chroma_agc": 0.25, "cadence.field_blend": 0.45, "fade.amount": 0.22,
                       "dust.density": 0.75, "gate_weave.amount": 1.4},
                audio={"a_optical_track.cell_noise": -39.0, "a_optical_track.high_hz": 5600.0}),
    ],
))

register_preset(Preset(
    id="propaganda-1943",
    name="War Bond Reel",
    family="world",
    era="1943",
    desc="Why-we-fight urgency: contrasty dupe stock, heavy optical soundtrack, a print that toured every church basement in the county.",
    tagline="Contrasty dupe, heavy optical track",
    tags=("40s", "bw", "wartime"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic", "tint": "silver", "tint_amt": 0.2}),
        ("tone", {"contrast": 1.3, "lift": 0.05, "knee": 0.74}),
        ("grain", {"amount": 0.6, "size": 2.1, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("gate_weave", {"amount": 1.7, "splice_bump": 2.0}),
        ("flicker", {"amount": 0.25, "character": "projector"}),
        ("dust", {"density": 0.9, "size": 1.3, "hairs": 0.5}),
        ("scratches", {"count": 4, "transient_rate": 1.5}),
        ("frame_damage", {"splice_skip_rate": 2.0, "blotch_rate": 0.8}),
        ("cadence", {"pattern": "pulldown_judder", "field_blend": 0.3}),
        ("vignette", {"amount": 0.35}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=_film_audio(hi=5000.0, cell=-40.0, rolloff="newsreel_1930s", ratio=5.0),
))

register_preset(Preset(
    id="travelogue-1958",
    name="Kodachrome Travelogue",
    family="world",
    era="1958",
    desc="See the world in 16mm Kodachrome: postcard saturation, lecture-hall projector cadence, the narrator's optimism baked into the dyes.",
    tagline="Postcard saturation, projector cadence",
    tags=("50s", "16mm", "kodachrome"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 0.95}),
        ("tone", {"contrast": 1.12, "lift": 0.03, "knee": 0.8}),
        ("balance", {"warmth": 0.15}),
        ("grain", {"amount": 0.4, "size": 2.1, "chroma_grain": 0.18, "stock": "doc_16"}),
        ("halation", {"strength": 0.28, "tint": "orange"}),
        ("gate_weave", {"amount": 1.4}),
        ("flicker", {"amount": 0.18, "character": "projector"}),
        ("dust", {"density": 0.6, "hairs": 0.35}),
        ("vignette", {"amount": 0.35}),
        ("projection", {"shutter_flicker": 0.25, "ambient_lift": 0.2}),
    ],
    audio=_film_audio(hi=6500.0, cell=-48.0, rolloff="classroom_16mm"),
))

register_preset(Preset(
    id="student-film-1971",
    name="Student Film",
    family="world",
    era="1971",
    desc="B&W 16mm reversal shot on a borrowed Bolex: uneven exposure, honest grain, more ambition than lighting.",
    tagline="Uneven exposure, coarse reversal grain",
    tags=("70s", "16mm", "bw"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.1, "lift": 0.05, "knee": 0.8}),
        ("exposure_auto", {}),
        ("grain", {"amount": 0.58, "size": 2.1, "chroma_grain": 0.0, "stock": "doc_16"}),
        ("gate_weave", {"amount": 2.0, "splice_bump": 2.5}),
        ("flicker", {"amount": 0.22}),
        ("dust", {"density": 0.8, "hairs": 0.5}),
        ("scratches", {"count": 2, "transient_rate": 1.0}),
        ("frame_damage", {"splice_skip_rate": 2.5}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 120.0, "high_hz": 6000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_wow_flutter", {"wow_depth": 8.0, "flutter_depth": 6.0}),
        ("a_tape_hiss", {"level_db": -40.0, "type": "reel_375ips"}),
        ("a_agc", {"amount": 0.6}),
    ],
))

register_preset(Preset(
    id="serial-western-1938",
    name="Saturday Serial",
    family="world",
    era="1938",
    desc="Chapter Seven: PERIL AT RED ROCK - cheap fast stock, blazing skies, a print worn gray by every kid in town.",
    tagline="Blazing skies, print worn gray",
    tags=("30s", "bw", "serial"),
    proc_height=640,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic"}),
        ("tone", {"contrast": 1.26, "lift": 0.07, "knee": 0.72}),
        ("grain", {"amount": 0.58, "size": 2.1, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("halation", {"strength": 0.3, "tint": "neutral"}),
        ("gate_weave", {"amount": 1.9, "splice_bump": 2.0}),
        ("flicker", {"amount": 0.28, "character": "projector"}),
        ("dust", {"density": 1.0, "size": 1.4, "hairs": 0.6}),
        ("scratches", {"count": 5, "transient_rate": 2.0}),
        ("frame_damage", {"splice_skip_rate": 3.0, "slip_rate": 0.8}),
        ("vignette", {"amount": 0.4}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=_film_audio(hi=5200.0, cell=-40.0, rolloff="newsreel_1930s", ratio=5.0),
))

register_preset(Preset(
    id="soap-opera-1982",
    name="Daytime Drama",
    family="world",
    era="1982",
    desc="The soap-opera effect itself: gauzy diffusion over crisp studio video, flowers in soft focus, feelings in sharp relief.",
    tagline="Gauzy diffusion over crisp video",
    tags=("80s", "video", "studio"),
    proc_height=560,
    upscale="soft",
    video=[
        ("tone", {"contrast": 1.04, "lift": 0.02, "knee": 0.82}),
        ("balance", {"warmth": 0.15, "high_tint": "pink", "high_amt": 0.2}),
        ("optics", {"diffusion": 0.45, "soft_focus": 0.15}),
        ("saturation", {"amount": 1.08}),
        ("phosphor_decay", {"decay": 0.15}),
        ("ntsc", {"strength": 0.7, "phase_noise": 1.6, "dot_crawl": 0.2}),
        ("interlace", {"combing": 0.55, "twitter": 0.3}),
        ("crt", {"bloom": 0.4}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 80.0, "high_hz": 10000.0}),
        ("a_compressor", {"ratio": 3.0}),
        ("a_room", {"size": 0.8, "decay_s": 0.45, "mix": 0.15}),
        ("a_tape_hiss", {"level_db": -48.0}),
    ],
))

register_preset(Preset(
    id="game-show-1978",
    name="Game Show Floor",
    family="world",
    era="1978",
    desc="Chroma cranked to prize-wall levels: glowing orange flesh, buzzing saturated set colors, studio video with comet trails on the lights.",
    tagline="Orange flesh, buzzing set, comet trails",
    tags=("70s", "video", "studio"),
    proc_height=540,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.9}),
        ("tone", {"contrast": 1.08, "lift": 0.04, "knee": 0.76}),
        ("saturation", {"amount": 1.25}),
        ("phosphor_decay", {"decay": 0.28}),
        ("ntsc", {"strength": 0.95, "phase_noise": 3.2, "rainbow": 0.4, "dot_crawl": 0.35}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.45, "scan_strength": 0.12, "misconvergence": 0.5}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.07}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -42.0}),
        ("a_bandlimit", {"low_hz": 100.0, "high_hz": 8000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.6}),
        ("a_speaker", {"device": "tv_mono_1985", "strength": 0.45}),
    ],
    variants=[
        Variant("source-clean", "Source-Clean Transfer",
                "Preserves the period carrier and color response while disabling momentary source loss or masking.",
                video={"framing.corner_radius": 0.0}),
    ],
))

register_preset(Preset(
    id="wedding-16mm-1954",
    name="Wedding Reel",
    family="world",
    era="1954",
    desc="The big day on rented 16mm: blushing Kodachrome, nervous framing, the reel the family threads up every anniversary.",
    tagline="Blushing Kodachrome, light leaks",
    tags=("50s", "16mm", "home-movie"),
    proc_height=600,
    upscale="soft",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 0.9}),
        ("tone", {"contrast": 1.1, "lift": 0.04}),
        ("balance", {"warmth": 0.2}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("optics", {"corner_softness": 0.3, "focus_drift": 0.2}),
        ("grain", {"amount": 0.45, "size": 1.97, "chroma_grain": 0.18, "stock": "doc_16"}),
        ("halation", {"strength": 0.3, "tint": "orange"}),
        ("gate_weave", {"amount": 1.8, "splice_bump": 1.5}),
        ("flicker", {"amount": 0.24, "character": "projector"}),
        ("dust", {"density": 0.8, "hairs": 0.5}),
        ("light_leak", {"constant": 0.1, "frequency": 0.5}),
        ("vignette", {"amount": 0.45, "softness": 0.6}),
        ("projection", {"shutter_flicker": 0.3, "ambient_lift": 0.25}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -26.0}),
        ("a_hum", {"hz": 60, "level_db": -52.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain treated original audio under the projector.",
                audio={"a_gain.db": -8.0}),
    ],
))

register_preset(Preset(
    id="training-film-1966",
    name="Corporate Training Film",
    family="world",
    era="1966",
    desc="SAFETY BEGINS WITH YOU: flat even lighting on Ektachrome, cheerful narration bandwidth, a print the projector has memorized.",
    tagline="Flat Ektachrome, mild pink, projector",
    tags=("60s", "16mm", "industrial"),
    proc_height=640,
    upscale="soft",
    video=[
        ("stock", {"profile": "ektachrome", "strength": 0.9}),
        ("tone", {"contrast": 1.06, "lift": 0.05, "knee": 0.82}),
        ("grain", {"amount": 0.42, "size": 2.1, "chroma_grain": 0.18, "stock": "doc_16"}),
        ("fade", {"amount": 0.25, "profile": "eastman_pink"}),
        ("gate_weave", {"amount": 1.3}),
        ("flicker", {"amount": 0.16, "character": "projector"}),
        ("dust", {"density": 0.7, "hairs": 0.4}),
        ("scratches", {"count": 3}),
        ("vignette", {"amount": 0.3}),
        ("projection", {"shutter_flicker": 0.25, "ambient_lift": 0.25}),
    ],
    audio=_film_audio(hi=5800.0, cell=-45.0, rolloff="classroom_16mm", ratio=4.0),
))

register_preset(Preset(
    id="music-promo-1967",
    name="Music Promo Film",
    family="world",
    era="1967",
    desc="A band miming in a field for the cameras: sun-flared 35mm, popping color, optical printer zooms baked into the negative's soul.",
    tagline="Popping color, sun flares, leaks",
    tags=("60s", "music", "film"),
    upscale="sharp",
    video=[
        ("stock", {"profile": "kodachrome", "strength": 0.8}),
        ("tone", {"contrast": 1.12, "lift": 0.02}),
        ("saturation", {"amount": 1.15, "vibrance": 0.2}),
        ("optics", {"chromatic_aberration": 1.2}),
        ("grain", {"amount": 0.4, "size": 2.0, "chroma_grain": 0.18}),
        ("halation", {"strength": 0.35, "tint": "warm_white"}),
        ("gate_weave", {"amount": 1.1}),
        ("light_leak", {"constant": 0.1, "frequency": 1.0}),
        ("dust", {"density": 0.4}),
        ("vignette", {"amount": 0.28}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 60.0, "high_hz": 10000.0}),
        ("a_tape_sat", {"drive": 2.2, "bump_db": 3.0}),
        ("a_compressor", {"ratio": 4.0}),
        ("a_tape_hiss", {"level_db": -46.0, "type": "reel_15ips"}),
    ],
))

register_preset(Preset(
    id="bleach-bypass-1998",
    name="Bleach Bypass",
    family="world",
    era="1998",
    desc="Silver retained in the print: crushed desaturated shadows, chrome highlights, the end-of-the-millennium war-movie nerve.",
    tagline="Chrome highlights, crushed gray shadows",
    tags=("90s", "process", "genre"),
    upscale="sharp",
    video=[
        ("fade", {"amount": 0.35, "profile": "bleach", "bloom_whites": 0.1}),
        ("tone", {"contrast": 1.28, "lift": 0.0, "knee": 0.78, "pivot": 0.45}),
        ("saturation", {"amount": 0.7}),
        ("stock", {"profile": "vision_90s", "strength": 0.8}),
        ("grain", {"amount": 0.4, "size": 1.8, "chroma_grain": 0.15, "stock": "fine_35"}),
        ("halation", {"strength": 0.25, "tint": "neutral"}),
        ("gate_weave", {"amount": 0.7}),
        ("vignette", {"amount": 0.3}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 50.0, "high_hz": 14000.0}),
        ("a_compressor", {"ratio": 2.5}),
    ],
))

register_preset(Preset(
    id="cross-process-1996",
    name="Cross-Processed",
    family="world",
    era="1996",
    desc="Slide film through the wrong chemicals: cyan skies gone acid, green shadows, blown magenta skin - the music-video look that ate the 90s.",
    tagline="Acid cyan, green shadows, blown magenta",
    tags=("90s", "process", "music-video"),
    upscale="sharp",
    video=[
        ("tone", {"contrast": 1.3, "lift": 0.03, "knee": 0.75, "pivot": 0.4}),
        ("balance", {"tint": -0.25, "shadow_tint": "green", "shadow_amt": 0.5, "high_tint": "yellow", "high_amt": 0.35}),
        ("saturation", {"amount": 1.3}),
        ("stock", {"profile": "ektachrome", "strength": 0.8}),
        ("grain", {"amount": 0.45, "size": 2.0, "chroma_grain": 0.2}),
        ("halation", {"strength": 0.3, "tint": "warm_white"}),
        ("vignette", {"amount": 0.35, "softness": 0.55}),
    ],
    audio=[
        ("a_bandlimit", {"low_hz": 45.0, "high_hz": 15000.0}),
        ("a_compressor", {"ratio": 3.0}),
    ],
))

register_preset(Preset(
    id="silent-comedy-1925",
    name="Silent Two-Reeler",
    family="world",
    era="1925",
    desc="Custard-pie physics at sixteen frames a second: crisp orthochromatic sunshine, brisk undercranked motion, a live-wire print.",
    tagline="Crisp ortho sun, brisk undercrank",
    tags=("20s", "bw", "silent", "comedy"),
    proc_height=600,
    upscale="soft",
    video=[
        ("mono", {"response": "orthochromatic"}),
        ("tone", {"contrast": 1.22, "lift": 0.05, "knee": 0.76}),
        ("cadence", {"pattern": "silent_irregular"}),
        ("grain", {"amount": 0.55, "size": 1.97, "chroma_grain": 0.0, "stock": "print_dupe"}),
        ("flicker", {"amount": 0.4, "character": "hand_cranked", "spatial": 0.35}),
        ("gate_weave", {"amount": 2.3, "splice_bump": 2.0}),
        ("dust", {"density": 1.0, "size": 1.3, "hairs": 0.6}),
        ("scratches", {"count": 4, "transient_rate": 1.5}),
        ("frame_damage", {"splice_skip_rate": 2.5}),
        ("vignette", {"amount": 0.45, "softness": 0.6}),
        ("framing", {"aspect": "4:3"}),
    ],
    audio=[
        ("a_gain", {"db": -60.0}),
        ("a_projector", {"machine": "proj_16mm", "level_db": -27.0}),
        ("a_hum", {"hz": 60, "level_db": -54.0}),
    ],
    variants=[
        Variant("keep-sound", "Keep Sound", "Retain the (treated) original audio.",
                audio={"a_gain.db": -6.0}),
    ],
))

register_preset(Preset(
    id="telethon-1976",
    name="Late-Night Telethon",
    family="world",
    era="1976",
    desc="Hour nineteen of the broadcast: tired studio cameras, smeary phosphor trails, the tote board glowing through video noise.",
    tagline="Smeary phosphor trails, video noise",
    tags=("70s", "video", "broadcast"),
    proc_height=520,
    upscale="soft",
    video=[
        ("stock", {"profile": "tube_70s", "strength": 0.85}),
        ("tone", {"contrast": 1.05, "lift": 0.05, "knee": 0.76}),
        ("phosphor_decay", {"decay": 0.32}),
        ("ntsc", {"strength": 0.95, "phase_noise": 3.6, "rainbow": 0.4, "dot_crawl": 0.35}),
        ("vhs", {"mode": "sp", "luma_noise": 0.4, "chroma_noise": 0.4, "head_switch": 0.5,
                 "time_base_error": 0.35}),
        ("interlace", {"combing": 0.55}),
        ("crt", {"bloom": 0.4, "scan_strength": 0.12}),
        ("framing", {"aspect": "4:3", "corner_radius": 0.08}),
    ],
    audio=[
        ("a_tv_sound", {"buzz_db": -40.0}),
        ("a_bandlimit", {"low_hz": 110.0, "high_hz": 7000.0}),
        ("a_mono", {"amount": 1.0}),
        ("a_agc", {"amount": 0.7}),
        ("a_speaker", {"device": "tv_mono_1965", "strength": 0.55}),
    ],
))

register_preset(Preset(
    id="drama-kitchen-sink-1961",
    name="Kitchen Sink Drama",
    family="world",
    era="1961",
    desc="British new-wave realism: damp gray B&W, coal-smoke midtones, rain promised in every highlight.",
    tagline="Damp gray mids, coal-smoke contrast",
    tags=("uk", "60s", "bw"),
    video=[
        ("mono", {"response": "panchromatic"}),
        ("tone", {"contrast": 1.12, "lift": 0.06, "knee": 0.8, "gamma": 0.98}),
        ("grain", {"amount": 0.48, "size": 2.2, "chroma_grain": 0.0, "stock": "doc_16"}),
        ("halation", {"strength": 0.2, "tint": "neutral"}),
        ("gate_weave", {"amount": 1.2}),
        ("flicker", {"amount": 0.1}),
        ("dust", {"density": 0.5}),
        ("vignette", {"amount": 0.32}),
    ],
    audio=_film_audio(hi=6800.0, cell=-50.0),
))
