#!/usr/bin/env python
"""Generate docs/catalog.md - the full preset & parameter reference - from the registry."""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from aesthetician.engine.graph import get_effect
from aesthetician.engine.presets import all_presets

OUT = os.path.join(ROOT, "docs", "catalog.md")


def chain_keys(chain):
    counts: dict[str, int] = {}
    for eid, params in chain:
        counts[eid] = counts.get(eid, 0) + 1
        yield (eid if counts[eid] == 1 else f"{eid}#{counts[eid]}"), eid, params


def main() -> None:
    presets = sorted(all_presets().values(), key=lambda p: (p.family, p.id))
    lines = [
        "# Aesthetician - Preset Catalog",
        "",
        "Generated by `scripts/gen_catalog.py`. Override any parameter with",
        "`--set effect.param=value` (audio effects start with `a_`).",
        "",
    ]
    fam = None
    for p in presets:
        if p.family != fam:
            fam = p.family
            lines += [f"## {fam.upper()}", ""]
        lines += [f"### `{p.id}` - {p.name} ({p.era})", "", p.desc, ""]
        if p.variants:
            lines.append("**Variants:** " + ", ".join(f"`{v.id}` ({v.name} - {v.desc})" for v in p.variants))
            lines.append("")
        for label, chain in (("Picture", p.video), ("Sound", p.audio)):
            if not chain:
                continue
            lines.append(f"**{label}:**")
            for key, eid, params in chain_keys(chain):
                cls = get_effect(eid)
                shown = ", ".join(f"`{key}.{k}={v}`" for k, v in params.items()) or "(defaults)"
                lines.append(f"- **{cls.label}** - {shown}")
            lines.append("")
        knobs = 0
        for _, eid, _ in chain_keys(p.video + p.audio):
            knobs += len(get_effect(eid).PARAMS)
        lines.append(f"*{knobs} adjustable parameters in this preset.*")
        lines.append("")
    n_var = sum(len(p.variants) for p in presets)
    lines.insert(4, f"**{len(presets)} presets · {n_var} variants.**")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({len(presets)} presets)")


if __name__ == "__main__":
    main()
