#!/usr/bin/env python
"""Record when each preset first entered the library, from git history.

Writes aesthetician/presets/_introduced.py: preset id -> (date, version), where
the date is the author date of the first commit whose tree declares that id
(`id="..."` in a presets module) and the version is the earliest release tag
that contains the commit. A preset in the working tree that no commit knows
yet gets today's date and the version "unreleased". The app sorts on this;
the CLI prints it. Re-run after adding presets:

    .venv/bin/python scripts/gen_introduced.py

The file is generated, committed, and cheap to regenerate; it exists because
the packaged app has no git history to ask.
"""

from __future__ import annotations

import datetime as dt
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUT = os.path.join(ROOT, "aesthetician", "presets", "_introduced.py")
ID_RE = re.compile(r'^\s*(?:id=)?"([a-z0-9][a-z0-9\-]+)"', re.M)


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout


def _ids_in(text: str) -> set[str]:
    # The literal id="..." keyword and the positional first argument of the
    # source-preserving `_preset("id", ...)` helper both count.
    ids: set[str] = set(re.findall(r'^\s*id="([a-z0-9\-]+)"', text, re.M))
    ids |= set(re.findall(r'register_preset\(_preset\(\s*\n?\s*"([a-z0-9\-]+)"', text))
    return ids


def version_key(tag: str) -> tuple[int, ...]:
    return tuple(int(x) for x in re.findall(r"\d+", tag)[:3]) or (10**6,)


def main() -> int:
    from aesthetician.engine.presets import PRESET_ALIASES, all_presets

    wanted = set(all_presets())
    # A renamed preset is as old as the name it had before.
    alias_of = {new: old for old, new in PRESET_ALIASES.items()}
    wanted |= set(alias_of.values())
    # Walk history oldest-first; the first commit whose presets modules contain
    # an id is when it was introduced.
    commits = git("log", "--reverse", "--format=%H %aI", "--", "aesthetician/presets").strip().splitlines()
    tags_cache: dict[str, str] = {}

    def first_tag(sha: str) -> str:
        if sha in tags_cache:
            return tags_cache[sha]
        tags = [t for t in git("tag", "--contains", sha).split() if re.match(r"^v\d", t)]
        tags.sort(key=version_key)
        tags_cache[sha] = tags[0].lstrip("v") if tags else "unreleased"
        return tags_cache[sha]

    introduced: dict[str, tuple[str, str]] = {}
    seen: set[str] = set()
    for line in commits:
        sha, date = line.split(" ", 1)
        files = git("ls-tree", "-r", "--name-only", sha, "--", "aesthetician/presets").split()
        ids: set[str] = set()
        for f in files:
            if not f.endswith(".py") or os.path.basename(f).startswith("_"):
                continue
            ids |= _ids_in(git("show", f"{sha}:{f}"))
        new = (ids & wanted) - seen
        if not new:
            continue
        seen |= new
        day = date[:10]
        ver = first_tag(sha)
        for pid in new:
            introduced[pid] = (day, ver)
        if seen >= wanted:
            break

    for new, old in alias_of.items():
        if old in introduced and (new not in introduced or introduced[old][0] < introduced[new][0]):
            introduced[new] = introduced[old]
            seen.add(new)
    for old in alias_of.values():
        introduced.pop(old, None)
    wanted -= set(alias_of.values())
    today = dt.date.today().isoformat()
    for pid in sorted(wanted - seen):
        introduced[pid] = (today, "unreleased")

    lines = [
        '"""When each preset entered the library: id -> (date, first release).',
        "",
        "Generated by scripts/gen_introduced.py from git history; do not edit by hand.",
        'A preset that has not been released yet reads "unreleased" until the next run',
        "after its release tag exists.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "INTRODUCED: dict[str, tuple[str, str]] = {",
    ]
    for pid in sorted(introduced):
        day, ver = introduced[pid]
        lines.append(f'    "{pid}": ("{day}", "{ver}"),')
    lines.append("}")
    lines.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    released = sum(1 for v in introduced.values() if v[1] != "unreleased")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(introduced)} presets, {released} with a release tag")
    return 0


if __name__ == "__main__":
    sys.exit(main())
